import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json","cache-control":"no-store"}});
const clamp=(v:number,min=0,max=1)=>Math.max(min,Math.min(max,v)),sigmoid=(x:number)=>1/(1+Math.exp(-x));
async function sha256(v:string){const data=new TextEncoder().encode(v),hash=await crypto.subtle.digest("SHA-256",data);return Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,"0")).join("")}
function parseVector(v:unknown,n:number){if(typeof v!=="string")return[];return v.replace(/^\[/,"").replace(/\]$/,"").split(",").map(Number).filter(Number.isFinite).slice(0,n)}
function defaults(){return{hidden:[{w:[1.25,.15,.10,.10,.05,0,0,0,1,.10,0,.05],b:-.75},{w:[.15,1.05,1.15,.05,0,.65,.55,.10,.20,0,.05,0],b:-1.15},{w:[.45,.25,.25,.75,.55,0,0,.25,.25,.40,.55,0],b:-1.20},{w:[.60,.55,.45,0,0,.10,.10,.75,.45,.15,0,.25],b:-1.25},{w:[.75,.35,.35,.05,0,.10,.10,.10,.20,.70,.25,.10],b:-1.05},{w:[.50,.20,.30,.10,0,.10,.10,.15,.65,.10,.15,.20],b:-1.10},{w:[.30,.55,.40,.05,0,.10,.10,.10,.25,.20,0,.65],b:-1.00},{w:[.80,.35,.35,.10,0,.10,.10,.20,.50,.25,.10,.20],b:-1.20}],out:[.20,.16,.12,.11,.13,.10,.08,.10],bias:-.05}}
function validNetwork(v:unknown){if(!v||typeof v!=="object")return null;const r=v as Record<string,unknown>,h=Array.isArray(r.hidden)?r.hidden:[],o=Array.isArray(r.out)?r.out.map(Number):[];if(h.length!==8||o.length!==8)return null;const hidden=h.map(x=>{const q=x&&typeof x==="object"?x as Record<string,unknown>:{},w=Array.isArray(q.w)?q.w.map(Number):[];return{w:w.length===12?w:Array(12).fill(0),b:Number(q.b??0)}});return{hidden,out:o,bias:Number(r.bias??0)}}
function forward(net:ReturnType<typeof defaults>,x:number[]){const h=net.hidden.map(n=>Math.tanh(n.b+n.w.reduce((s,w,i)=>s+w*(x[i]??0),0))),z=net.bias+net.out.reduce((s,w,i)=>s+w*h[i],0);return{h,y:sigmoid(z)}}
Deno.serve(async(req:Request)=>{
  if(req.method!=="POST")return json({error:"Method not allowed"},405);
  const base=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!base||!key)return json({error:"Runtime credentials missing"},500);
  const secret=req.headers.get("x-match-secret")||"",sr=await fetch(`${base}/rest/v1/app_secrets?name=eq.ingest_api&select=sha256`,{headers:{apikey:key,Authorization:`Bearer ${key}`}}),srows=await sr.json().catch(()=>[]) as Array<{sha256?:string}>;if(!secret||!srows[0]?.sha256||await sha256(secret)!==srows[0].sha256)return json({error:"Unauthorized"},401);
  const ex=await fetch(`${base}/rest/v1/match_training_examples?select=pair_features,reward&order=last_outcome_at.desc&limit=5000`,{headers:{apikey:key,Authorization:`Bearer ${key}`}});if(!ex.ok)return json({error:"Training data unavailable",detail:await ex.text()},502);const rows=await ex.json() as Array<{pair_features?:string;reward?:number}>;const data=rows.map(r=>({x:parseVector(r.pair_features,12),y:clamp(Number(r.reward??0)/1.5)})).filter(r=>r.x.length===12);if(data.length<500)return json({trained:false,reason:"insufficient_samples",samples:data.length,minSamples:500});
  const mr=await fetch(`${base}/rest/v1/matching_model_versions?model_version=eq.semantic-neural-v1&select=weights&limit=1`,{headers:{apikey:key,Authorization:`Bearer ${key}`}}),mrows=await mr.json().catch(()=>[]) as Array<{weights?:Record<string,unknown>}>;const currentWeights=mrows[0]?.weights??{},net=validNetwork(currentWeights.network)??defaults();
  const split=Math.max(400,Math.floor(data.length*.82)),train=data.slice(0,split),valid=data.slice(split),lr=.018,l2=.00035,epochs=Math.min(22,10+Math.floor(Math.log10(data.length)*3));
  for(let epoch=0;epoch<epochs;epoch++)for(const row of train){const {h,y}=forward(net,row.x),err=y-row.y,oldOut=[...net.out];for(let j=0;j<8;j++){net.out[j]-=lr*(err*h[j]+l2*net.out[j]);const delta=(1-h[j]*h[j])*err*oldOut[j];for(let i=0;i<12;i++)net.hidden[j].w[i]-=lr*(delta*row.x[i]+l2*net.hidden[j].w[i]);net.hidden[j].b-=lr*delta;}net.bias-=lr*err;}
  const evalSet=valid.length?valid:train.slice(-Math.min(100,train.length));let mse=0,mae=0;for(const row of evalSet){const p=forward(net,row.x).y,d=p-row.y;mse+=d*d;mae+=Math.abs(d)}mse/=Math.max(1,evalSet.length);mae/=Math.max(1,evalSet.length);const score=clamp(1-mse),weights={...currentWeights,network:net,min_samples_for_learned_weight:500};
  const patch=await fetch(`${base}/rest/v1/matching_model_versions?model_version=eq.semantic-neural-v1`,{method:"PATCH",headers:{apikey:key,Authorization:`Bearer ${key}`,"content-type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({weights,sample_count:data.length,validation_score:score,trained_at:new Date().toISOString(),active:true})});if(!patch.ok)return json({error:"Model update failed",detail:await patch.text()},502);
  return json({trained:true,samples:data.length,epochs,validationScore:score,mae});
});
