function stringOrNull(value:unknown){return typeof value==="string"&&value.trim()?value.trim():null}
function asBoolean(value:unknown){if(typeof value==="boolean")return value;if(typeof value==="number")return value>0;if(typeof value==="string")return["1","true","yes","in stock","available"].includes(value.trim().toLowerCase());return false}
function asNumber(value:unknown){if(typeof value==="number"&&Number.isFinite(value))return value;if(typeof value==="string"){const parsed=Number(value.replace(/[^0-9.,-]/g,"").replace(",","."));return Number.isFinite(parsed)?parsed:null}return null}
function safeHttpUrl(value:unknown){const raw=stringOrNull(value);if(!raw)return null;try{const u=new URL(raw);return u.protocol==="https:"||u.protocol==="http:"?u.toString():null}catch{return null}}

export function normalizeLinkwiseProduct(input:unknown){
 if(!input||typeof input!=="object"||Array.isArray(input))return null; const item=input as Record<string,unknown>; const productId=item.product_id; const name=stringOrNull(item.product_name); if((typeof productId!=="string"&&typeof productId!=="number")||!name)return null;
 const description=stringOrNull(item.description); const category=stringOrNull(item.category); const haystack=`${category??""} ${name} ${description??""}`.toLowerCase(); const keywords=["travel","luggage","suitcase","cabin","backpack","adapter","organizer","beach","camp","βαλίτ","ταξιδ","σακίδ"]; const availability=stringOrNull(item.availability);
 return {sourceProductId:String(productId),modelName:stringOrNull(item.model_name),name,description,sourceCategory:category,brand:stringOrNull(item.brand_name),trackingUrl:safeHttpUrl(item.tracking_url),imageUrl:safeHttpUrl(item.image_url)??safeHttpUrl(item.thumb_url),inStock:asBoolean(item.in_stock)||(availability?.toLowerCase().includes("available")??false),availability,validFrom:stringOrNull(item.valid_from),validTo:stringOrNull(item.valid_to),onSale:asBoolean(item.on_sale),currency:stringOrNull(item.currency),price:asNumber(item.price),fullPrice:asNumber(item.full_price),discount:asNumber(item.discount),demandProxy:asNumber(item.times_bought),size:stringOrNull(item.size),colour:stringOrNull(item.colour),variations:item.variations??null,travelRelevant:keywords.some(k=>haystack.includes(k)),observedAt:new Date().toISOString()};
}
