import { NextResponse } from "next/server";
import { loadV8StayOffers } from "@/lib/data/destination-v8";
import { loadLocalityStayOffersV24 } from "@/lib/data/locality-stays-v24";
import { loadV8SessionConstraintsV22,recordV8DestinationSelection } from "@/lib/data/match-learning-v8";
import { semanticMapFromVectorV23 } from "@/lib/decision/fuzzy-semantic-v23";
import { STAY_CONSTRAINT_KINDS_V16 } from "@/lib/decision/stay-constraints-v16";
import { stayOfferCriterionDeltaV23 } from "@/lib/decision/stay-offer-score";
import { V23_SEMANTIC_DIMENSIONS,type StayConstraintKind,type StayConstraintSpec,type V23FuzzyIntentContract,type V23SemanticDimension,type V8StayResponse } from "@/lib/decision/v8-types";

export const runtime="nodejs";export const dynamic="force-dynamic";
const iso=/^\d{4}-\d{2}-\d{2}$/;const cookie=/(?:^|;\s*)travel_match_session=([0-9a-f-]{36})(?:;|$)/i;
function readStayRequirements(value:unknown):StayConstraintSpec|undefined{if(!value||typeof value!=="object"||Array.isArray(value))return undefined;const row=value as Record<string,unknown>,read=(key:string)=>Array.isArray(row[key])?row[key].filter((item):item is StayConstraintKind=>typeof item==="string"&&STAY_CONSTRAINT_KINDS_V16.includes(item as StayConstraintKind)):[];const hard=[...new Set(read("hard"))],soft=[...new Set(read("soft").filter(kind=>!hard.includes(kind)))];return{hard,soft,confidence:"HIGH",source:"deterministic",needsSemanticAssist:false}}
function readSemanticV23(value:unknown):V23FuzzyIntentContract|undefined{if(!value||typeof value!=="object"||Array.isArray(value))return undefined;const row=value as Record<string,unknown>,pv=Array.isArray(row.positiveVector)?row.positiveVector.map(Number).filter(Number.isFinite).slice(0,24):[],nv=Array.isArray(row.negativeVector)?row.negativeVector.map(Number).filter(Number.isFinite).slice(0,24):[];if(pv.length!==24||nv.length!==24)return undefined;const priorities=Array.isArray(row.priorities)?row.priorities.filter((x):x is V23SemanticDimension=>typeof x==="string"&&(V23_SEMANTIC_DIMENSIONS as readonly string[]).includes(x)).slice(0,5):[],q=row.qualifiers&&typeof row.qualifiers==="object"&&!Array.isArray(row.qualifiers)?row.qualifiers as Record<string,unknown>:{},readQ=(k:string)=>Math.max(0,Math.min(1,Number(q[k])||0));return{positive:semanticMapFromVectorV23(pv),negative:semanticMapFromVectorV23(nv),priorities,qualifiers:{avoidCrowds:readQ("avoidCrowds"),easyAccess:readQ("easyAccess"),slowRhythm:readQ("slowRhythm"),walkable:readQ("walkable"),localCharacter:readQ("localCharacter")},confidence:Math.max(0,Math.min(1,Number(row.confidence)||.6)),source:"structured",positiveVector:pv,negativeVector:nv};}
export async function GET(request:Request){const u=new URL(request.url),slug=(u.searchParams.get("slug")??u.searchParams.get("destination_id")??"").trim(),localityId=(u.searchParams.get("locality_id")??"").trim(),localityLabel=(u.searchParams.get("locality_label")??"").trim(),start=(u.searchParams.get("start_date")??"").trim(),end=(u.searchParams.get("end_date")??"").trim();if(!slug&&!localityId)return NextResponse.json({message:"Χρειάζομαι περιοχή για να συνεχίσω."},{status:400});if(!iso.test(start)||!iso.test(end)||Date.parse(end)<=Date.parse(start))return NextResponse.json({message:"Χρειάζομαι έγκυρες ημερομηνίες για να ελέγξω τη διαμονή."},{status:400});const session=request.headers.get("cookie")?.match(cookie)?.[1]??null;try{const loader=localityId?loadLocalityStayOffersV24(localityId,start,end,30):loadV8StayOffers(slug,start,end,30),[offers,constraints]=await Promise.all([loader,session?loadV8SessionConstraintsV22(session):Promise.resolve(null),session&&slug?recordV8DestinationSelection(session,slug):Promise.resolve(false)]),stayRequirements=readStayRequirements(constraints?.stayRequirements),semanticV23=readSemanticV23(constraints?.semanticV23),scored=offers.map(offer=>({...offer,semanticScore:stayOfferCriterionDeltaV23(offer,stayRequirements,semanticV23)})),result:V8StayResponse={version:9,slug:slug||`locality-${localityId}`,localityId:localityId||undefined,localityLabel:localityLabel||undefined,startDate:start,endDate:end,offers:scored,availabilityMeaning:"full-trip-validity-confirm-before-booking"};return NextResponse.json(result,{headers:{"cache-control":"no-store","x-travel-stay-ranking":localityId?"v24-exact-locality":"v23-fuzzy"}})}catch{return NextResponse.json({message:"Δεν υπάρχει αυτή τη στιγμή επιλογή διαμονής που να μπορώ να επιβεβαιώσω για ολόκληρο το ταξίδι σου. Η επιλογή σου έχει κρατηθεί."},{status:503})}}
