import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type JsonRecord=Record<string,unknown>;
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json","cache-control":"no-store","x-content-type-options":"nosniff"}});
const base=()=>Deno.env.get("SUPABASE_URL")??"";
const service=()=>Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
async function sha256(value:string){const data=new TextEncoder().encode(value);const hash=await crypto.subtle.digest("SHA-256",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("")}
let cachedSecretHash="",cachedSecretAt=0;
async function authorized(req:Request){const provided=req.headers.get("x-ingest-secret")??"";if(!provided)return false;const now=Date.now();if(!cachedSecretHash||now-cachedSecretAt>300_000){const r=await fetch(`${base()}/rest/v1/app_secrets?name=eq.ingest_api&select=sha256&limit=1`,{headers:{apikey:service(),Authorization:`Bearer ${service()}`}});cachedSecretHash=r.ok?String((await r.json())?.[0]?.sha256??""):"";cachedSecretAt=now}return Boolean(cachedSecretHash)&&await sha256(provided)===cachedSecretHash}
function auth(extra:Record<string,string>={}){const key=service();return{apikey:key,Authorization:`Bearer ${key}`,"content-type":"application/json",...extra}}
async function proxy(path:string,init:RequestInit={}){const r=await fetch(`${base()}/rest/v1/${path}`,{...init,headers:auth((init.headers??{}) as Record<string,string>)});const text=await r.text();let body:unknown=text;try{body=text?JSON.parse(text):null}catch{}return{ok:r.ok,status:r.status,body}}
async function rpc(name:string,payload:JsonRecord){return proxy(`rpc/${name}`,{method:"POST",body:JSON.stringify(payload)})}
const str=(v:unknown,max=3000)=>typeof v==="string"?v.trim().slice(0,max):"";
const int=(v:unknown,def:number,min:number,max:number)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):def};
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

Deno.serve(async(req:Request)=>{
 if(req.method!=="POST")return json({error:"Method not allowed"},405);if(!base()||!service())return json({error:"Supabase runtime credentials missing"},500);if(!(await authorized(req)))return json({error:"Unauthorized"},401);const len=Number(req.headers.get("content-length")??0);if(len>250_000)return json({error:"Payload too large"},413);
 const body=await req.json().catch(()=>null) as JsonRecord|null,action=str(body?.action,80),p=(body?.payload&&typeof body.payload==="object"&&!Array.isArray(body.payload)?body.payload:{}) as JsonRecord;if(!action)return json({error:"Action required"},400);let result:{ok:boolean;status:number;body:unknown};
 switch(action){
  case "agent_profiles":result=await proxy("travel_agent_profiles_v70?active=eq.true&select=agent_id,title,mission,system_prompt,allowed_tools,evidence_policy,prompt_version&order=agent_id");break;
  case "candidate_universe":result=await rpc("get_agentic_candidate_universe_v70",{p_limit:int(p.limit,220,1,574),p_locale:p.locale==="en"?"en":"el"});break;
  case "destination_bundle":result=await rpc("get_agentic_destination_bundle_v70",{p_node_keys:Array.isArray(p.nodeKeys)?p.nodeKeys.map(x=>str(x,180)).filter(Boolean).slice(0,40):[],p_locale:p.locale==="en"?"en":"el",p_stay_limit:int(p.stayLimit,6,1,12),p_entity_limit:int(p.entityLimit,80,10,120)});break;
  case "create_session":result=await proxy("travel_funnel_sessions_v70",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({profile_key:str(p.profileKey,80)||null,auth_user_id:uuid.test(str(p.authUserId,80))?str(p.authUserId,80):null,locale:p.locale==="en"?"en":"el",current_context:p.initialContext&&typeof p.initialContext==="object"&&!Array.isArray(p.initialContext)?p.initialContext:{}})});break;
  case "load_session":{const id=str(p.sessionId,80);if(!uuid.test(id))return json({error:"Invalid session"},400);result=await proxy(`travel_funnel_sessions_v70?id=eq.${encodeURIComponent(id)}&select=*&limit=1`);break}
  case "load_turns":{const id=str(p.sessionId,80);if(!uuid.test(id))return json({error:"Invalid session"},400);result=await proxy(`travel_funnel_turns_v70?session_id=eq.${encodeURIComponent(id)}&select=*&order=id.asc&limit=${int(p.limit,24,1,60)}`);break}
  case "append_turn":{const id=str(p.sessionId,80);if(!uuid.test(id))return json({error:"Invalid session"},400);const role=["user","assistant","system_event"].includes(str(p.role,30))?str(p.role,30):"system_event";result=await proxy("travel_funnel_turns_v70",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({session_id:id,role,content:str(p.content,6000),stage:str(p.stage,80)||"discovering",structured_extract:p.structuredExtract&&typeof p.structuredExtract==="object"&&!Array.isArray(p.structuredExtract)?p.structuredExtract:{},evidence_refs:Array.isArray(p.evidenceRefs)?p.evidenceRefs.slice(0,300):[]})});break}
  case "update_session":{const id=str(p.sessionId,80);if(!uuid.test(id))return json({error:"Invalid session"},400);const patch=p.patch&&typeof p.patch==="object"&&!Array.isArray(p.patch)?p.patch:{};result=await proxy(`travel_funnel_sessions_v70?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});break}
  case "load_discovery_snapshot":{const locale=p.locale==="en"?"en":"el",hash=str(p.contextHash,120)||"default-greece",now=encodeURIComponent(new Date().toISOString());result=await proxy(`travel_discovery_snapshots_v70?locale=eq.${locale}&context_hash=eq.${encodeURIComponent(hash)}&expires_at=gt.${now}&select=*&order=generated_at.desc&limit=1`);break}
  case "save_discovery_snapshot":{const now=new Date(),expires=new Date(now.getTime()+int(p.ttlHours,18,1,48)*3600000),locale=p.locale==="en"?"en":"el",hash=str(p.contextHash,120)||"default-greece";result=await proxy("travel_discovery_snapshots_v70?on_conflict=snapshot_date,locale,context_hash",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({snapshot_date:now.toISOString().slice(0,10),locale,context_hash:hash,context:p.context&&typeof p.context==="object"&&!Array.isArray(p.context)?p.context:{},picks:Array.isArray(p.picks)?p.picks.slice(0,80):[],evidence_state:p.evidenceState&&typeof p.evidenceState==="object"&&!Array.isArray(p.evidenceState)?p.evidenceState:{},model_label:str(p.modelLabel,120)||null,generated_at:now.toISOString(),expires_at:expires.toISOString()})});break}
  case "guest_memory":result=await rpc("get_traveler_context_v45",{p_profile_key:str(p.profileKey,80)});break;
  case "stay_inventory":result=await rpc("get_agentic_stay_inventory_v70",{p_destination_slug:str(p.destinationSlug,160),p_limit:int(p.limit,80,1,200)});break;
  case "stay_offer":result=await proxy(`stay_offers?source_product_id=eq.${encodeURIComponent(str(p.sourceProductId,180))}&select=source_product_id,place_id,property_name,location_label,description,tracking_url,image_url,in_stock,availability,valid_from,valid_to,currency,price,full_price,observed_at&limit=1`);break;
  case "create_tracking_action":{const code=str(p.code,40);if(!/^[a-z0-9]{12,40}$/i.test(code))return json({error:"Invalid tracking code"},400);result=await proxy("travel_tracking_actions_v70",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({code,journey_id:uuid.test(str(p.journeyId,80))?str(p.journeyId,80):null,session_id:uuid.test(str(p.sessionId,80))?str(p.sessionId,80):null,action_type:["stay","activity","transport","restaurant","other"].includes(str(p.actionType,30))?str(p.actionType,30):"other",subject_key:str(p.subjectKey,180)||null,tracking_url:str(p.trackingUrl,4000),metadata:p.metadata&&typeof p.metadata==="object"&&!Array.isArray(p.metadata)?p.metadata:{}})});break}
  case "resolve_tracking_action":result=await proxy(`travel_tracking_actions_v70?code=eq.${encodeURIComponent(str(p.code,40))}&select=id,code,tracking_url,click_count,expires_at&limit=1`);break;
  case "mark_tracking_click":{const id=str(p.id,80);if(!uuid.test(id))return json({error:"Invalid tracking id"},400);result=await proxy(`travel_tracking_actions_v70?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({click_count:int(p.count,0,0,2_000_000_000)+1,last_clicked_at:new Date().toISOString()})});break}
  case "create_journey":result=await proxy("travel_journeys_v70",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(p.row&&typeof p.row==="object"&&!Array.isArray(p.row)?p.row:{})});break;
  case "load_journey_by_slug":result=await proxy(`travel_journeys_v70?journey_slug=eq.${encodeURIComponent(str(p.slug,180))}&select=*&limit=1`);break;
  case "load_journey_by_id":{const id=str(p.id,80);if(!uuid.test(id))return json({error:"Invalid journey id"},400);result=await proxy(`travel_journeys_v70?id=eq.${encodeURIComponent(id)}&select=*&limit=1`);break}
  case "update_journey":{const id=str(p.id,80);if(!uuid.test(id))return json({error:"Invalid journey id"},400);const patch=p.patch&&typeof p.patch==="object"&&!Array.isArray(p.patch)?p.patch:{};result=await proxy(`travel_journeys_v70?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});break}
  default:return json({error:"Unsupported action"},400)
 }
 return json(result.body,result.ok?200:result.status||502);
});
