import { runTravelGuru } from "@/lib/ai/travel-guru";
import { loadAffiliateUniverse } from "@/lib/data/affiliate-universe";
import { enrichCandidatesWithWeather, weatherGate } from "@/lib/data/weather";
import { rankAffiliateCandidates, seasonGate } from "@/lib/decision/affiliate-engine";
import { parseTripRequest } from "@/lib/validation/trip";

export const runtime="nodejs"; export const dynamic="force-dynamic"; type EventPayload=Record<string,unknown>;
export async function POST(request:Request){const body=await request.json().catch(()=>null),parsed=parseTripRequest(body);if(!parsed.success)return Response.json({error:"Invalid trip request",details:parsed.errors},{status:400});const encoder=new TextEncoder();const stream=new ReadableStream<Uint8Array>({async start(controller){const emit=(type:string,payload:EventPayload={})=>controller.enqueue(encoder.encode(`${JSON.stringify({type,at:new Date().toISOString(),...payload})}\n`));try{emit("source:start",{source:"linkwise-json-only",startDate:parsed.data.startDate,endDate:parsed.data.endDate});const universe=await loadAffiliateUniverse(parsed.data,150);emit("source:ready",{candidateCount:universe.length,exactDateRange:true,fiveStarRich:universe.filter(c=>c.fiveStarOfferCount>=5).length});if(universe.length<5){emit("error",{message:"Not enough tracked destinations overlap the selected dates"});controller.close();return}
emit("rank:start",{filters:{distancePreference:parsed.data.distancePreference,pace:parsed.data.pace,hotelStyle:parsed.data.hotelStyle,avoid:parsed.data.avoid}});const preRanked=rankAffiliateCandidates(parsed.data,universe,40);emit("rank:ready",{shortlistCount:preRanked.length});
emit("weather:start",{candidates:Math.min(36,preRanked.length),dates:[parsed.data.startDate,parsed.data.endDate]});const first=await enrichCandidatesWithWeather(parsed.data,preRanked.slice(0,24).map(x=>x.candidate),24);let enriched=first,gated=weatherGate(parsed.data,enriched);if(gated.length<7&&preRanked.length>24){const extra=await enrichCandidatesWithWeather(parsed.data,preRanked.slice(24,36).map(x=>x.candidate),12);enriched=[...first,...extra];gated=weatherGate(parsed.data,enriched)}emit("weather:ready",{weatherChecked:enriched.length,weatherScreenedCount:gated.length,preview:[...gated].sort((a,b)=>(b.weather?.score??0)-(a.weather?.score??0)).slice(0,6).map(c=>({destination:c.locationLabel,weather:c.weather?.score,source:c.weather?.source,maxC:c.weather?.temperatureMaxC,rain:c.weather?.precipitationMmDay}))});if(gated.length<5){emit("error",{message:"Not enough destinations passed weather screening"});controller.close();return}
const ranked=rankAffiliateCandidates(parsed.data,gated,18),seasonReady=seasonGate(ranked);emit("season:ready",{before:ranked.length,after:seasonReady.length,rejected:ranked.filter(x=>x.breakdown.seasonality<50).slice(0,8).map(x=>({destination:x.candidate.locationLabel,seasonality:x.breakdown.seasonality,weather:x.breakdown.weather}))});if(seasonReady.length<5){emit("error",{message:"Not enough destinations passed seasonality screening"});controller.close();return}emit("decision:ready",{shortlistCount:seasonReady.length,preview:seasonReady.slice(0,8).map(x=>({destination:x.candidate.locationLabel,score:Math.round(x.score),weather:x.breakdown.weather,seasonality:x.breakdown.seasonality,offers:x.candidate.activeOfferCount}))});
emit("guru:start",{model:process.env.DEEPSEEK_API_KEY?(process.env.DEEPSEEK_MODEL??"deepseek-v4-pro"):"deterministic-fallback",candidateCount:Math.min(12,seasonReady.length)});const guru=await runTravelGuru(parsed.data,seasonReady);if(guru.recommendations.length!==5){emit("error",{message:"Travel Guru could not produce five valid weather/season-screened choices"});controller.close();return}emit("guru:ready",{mode:guru.mode,distinctDestinations:guru.recommendations.length});emit("final",{result:{request:parsed.data,generatedAt:new Date().toISOString(),mode:guru.mode,source:"linkwise-json-only",candidateCount:universe.length,weatherScreenedCount:seasonReady.length,affiliateOnly:true,recommendations:guru.recommendations}})}catch(error){emit("error",{message:error instanceof Error?error.message:"Travel decision pipeline unavailable"})}finally{controller.close()}}});return new Response(stream,{headers:{"content-type":"application/x-ndjson; charset=utf-8","cache-control":"no-store, no-transform","x-content-type-options":"nosniff"}})}
