import { readFile } from "node:fs/promises";
import path from "node:path";
import fontkit from "@pdf-lib/fontkit";
import { PDFDocument,PDFFont,PDFImage,PDFName,PDFPage,PDFString,rgb } from "pdf-lib";
import QRCode from "qrcode";
import { loadV8DestinationCatalog,loadV8StayOfferById,loadV8StayOffers } from "@/lib/data/destination-v8";
import { assessStayWindowV25 } from "@/lib/data/provider-availability-v25";
import { getLocalIntelligenceV38 } from "@/lib/data/local-intelligence-v38";
import { getDailyTripWeatherV25 } from "@/lib/data/trip-weather-v25";
import { estimateBeyondHotelBudgetV25 } from "@/lib/decision/trip-budget-v25";
import { researchDestination } from "@/lib/ai/destination-research";
import { buildEscapeBookIntelligenceV61,type EscapeBookPickV61 } from "@/lib/ai/escape-book-intelligence-v61";
import { parseTripRequest,type TripRequest } from "@/lib/validation/trip";

export const runtime="nodejs";
export const dynamic="force-dynamic";
export const maxDuration=60;
const iso=/^\d{4}-\d{2}-\d{2}$/,slugPattern=/^[a-z0-9-]{2,80}$/i,safeId=/^[a-zA-Z0-9:_-]{1,180}$/;
const A4:[number,number]=[595.28,841.89],DAY=86_400_000;
const c={night:rgb(.025,.067,.057),deep:rgb(.045,.102,.086),panel:rgb(.075,.145,.122),gold:rgb(.875,.735,.486),cyan:rgb(.55,.89,.86),paper:rgb(.967,.948,.902),white:rgb(.99,.985,.96),ink:rgb(.075,.11,.095),muted:rgb(.34,.39,.36),line:rgb(.8,.78,.7)};
const say=(lang:"el"|"en",el:string,en:string)=>lang==="el"?el:en;
function wrap(text:string,font:PDFFont,size:number,width:number){const words=text.replace(/\s+/g," ").trim().split(" ").filter(Boolean),out:string[]=[];let line="";for(const word of words){const next=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(next,size)<=width)line=next;else{if(line)out.push(line);line=word}}if(line)out.push(line);return out}
function block(page:PDFPage,text:string,font:PDFFont,size:number,x:number,y:number,width:number,color=c.ink,lineHeight=size*1.42,maxLines=30){const lines=wrap(text,font,size,width).slice(0,maxLines);lines.forEach((line,i)=>page.drawText(line,{x,y:y-i*lineHeight,size,font,color}));return y-lines.length*lineHeight}
function base(page:PDFPage,kicker:string,title:string,regular:PDFFont,bold:PDFFont){page.drawRectangle({x:0,y:0,width:A4[0],height:A4[1],color:c.paper});page.drawRectangle({x:0,y:690,width:A4[0],height:151,color:c.night});page.drawText(kicker.toUpperCase(),{x:42,y:797,size:7.5,font:bold,color:c.cyan});wrap(title,bold,29,500).slice(0,2).forEach((line,i)=>page.drawText(line,{x:42,y:758-i*34,size:29,font:bold,color:c.white}));page.drawLine({start:{x:42,y:116},end:{x:553,y:116},thickness:.65,color:c.line});page.drawText("AI ESCAPE STUDIO · 360° SOURCED DOSSIER",{x:42,y:89,size:6.5,font:bold,color:c.muted})}
function footer(page:PDFPage,no:number,total:number,regular:PDFFont){page.drawText(`${no}/${total}`,{x:520,y:88,size:6.5,font:regular,color:c.muted})}
function priceLabel(price:number|null|undefined,currency:string|null|undefined,lang:"el"|"en"){return price!=null&&price>0?`${price.toLocaleString(lang==="el"?"el-GR":"en-GB",{maximumFractionDigits:2})} ${currency||"EUR"}`:say(lang,"Τιμή στον πάροχο","Price at provider")}
function isSummer(start:string,end:string){for(let t=Date.parse(`${start}T00:00:00Z`),last=Date.parse(`${end}T00:00:00Z`);t<=last;t+=DAY){const m=new Date(t).getUTCMonth()+1;if(m>=6&&m<=9)return true}return false}
function decodeTrip(token:string|null){if(!token)return null;try{const raw=JSON.parse(Buffer.from(token,"base64url").toString("utf8"));const parsed=parseTripRequest(raw);return parsed.success?parsed.data:null}catch{return null}}
function fallbackTrip(start:string,end:string,lang:"el"|"en"):TripRequest{return{origin:"Athens",startDate:start,endDate:end,month:"flexible",nights:Math.max(1,Math.round((Date.parse(`${end}T00:00:00Z`)-Date.parse(`${start}T00:00:00Z`))/DAY)),budget:900,moods:["relax"],travelerType:"couple",language:lang,distancePreference:"any",pace:"balanced",hotelStyle:"any",avoid:"none",entryMode:"idea",groupSize:2,desiredEnergy:"balanced",socialPreference:"balanced",noveltyPreference:"balanced",mustHave:"none",dateFlexibility:"few-days",transportMode:"any",stayLocationPreference:"balanced"}}
async function photo(pdf:PDFDocument,url?:string|null):Promise<PDFImage|null>{if(!url)return null;try{const response=await fetch(url,{headers:{"user-agent":"TravelAI/38 EscapeBook"},signal:AbortSignal.timeout(6500)});if(!response.ok)return null;const bytes=new Uint8Array(await response.arrayBuffer()),type=(response.headers.get("content-type")??"").toLowerCase();if(type.includes("png"))return await pdf.embedPng(bytes);return await pdf.embedJpg(bytes)}catch{return null}}
function drawPhoto(page:PDFPage,image:PDFImage|null,x:number,y:number,w:number,h:number){if(!image){page.drawRectangle({x,y,width:w,height:h,color:rgb(.88,.93,.90)});page.drawRectangle({x:x+8,y:y+8,width:w-16,height:h-16,borderColor:rgb(.72,.82,.77),borderWidth:.7});return}const scale=Math.max(w/image.width,h/image.height),iw=image.width*scale,ih=image.height*scale;page.drawImage(image,{x:x+(w-iw)/2,y:y+(h-ih)/2,width:iw,height:ih})}
function addUriLink(pdf:PDFDocument,page:PDFPage,url:string,x:number,y:number,w:number,h:number){const annotation=pdf.context.register(pdf.context.obj({Type:"Annot",Subtype:"Link",Rect:[x,y,x+w,y+h],Border:[0,0,0],A:{Type:"Action",S:"URI",URI:PDFString.of(url)}}));page.node.set(PDFName.of("Annots"),pdf.context.obj([annotation]))}
function placeCard(page:PDFPage,place:EscapeBookPickV61,index:number,image:PDFImage|null,regular:PDFFont,bold:PDFFont,x:number,y:number,w:number,h:number,lang:"el"|"en"){page.drawRectangle({x,y,width:w,height:h,color:c.white,borderColor:c.line,borderWidth:.5});drawPhoto(page,image,x,y+h-86,w,86);page.drawText(`${String(index+1).padStart(2,"0")} · ${place.source.toUpperCase()}`,{x:x+12,y:y+h-104,size:6.1,font:bold,color:c.muted});wrap(place.name,bold,11.5,w-24).slice(0,2).forEach((line,i)=>page.drawText(line,{x:x+12,y:y+h-124-i*14,size:11.5,font:bold,color:c.ink}));let metaY=y+h-154;if(place.rating!=null){page.drawText(`★ ${place.rating.toFixed(1)}${place.ratingCount?` · ${place.ratingCount.toLocaleString()} ${say(lang,"κριτικές","reviews")}`:""}`,{x:x+12,y:metaY,size:7,font:bold,color:c.gold});metaY-=12}if(place.distanceKm!=null){page.drawText(place.distanceKm<1?`${Math.max(1,Math.round(place.distanceKm*1000))} m ${say(lang,"από το stay","from stay")}`:`${place.distanceKm.toFixed(place.distanceKm<10?1:0)} km ${say(lang,"από το stay","from stay")}`,{x:x+12,y:metaY,size:6.5,font:bold,color:c.cyan});metaY-=11}metaY=block(page,place.why,regular,6.7,x+12,metaY,w-24,c.ink,9.2,3)-4;block(page,place.practical,regular,6.1,x+12,metaY,w-24,c.muted,8.5,2);page.drawText(place.trust.slice(0,58),{x:x+12,y:y+10,size:5.8,font:bold,color:c.muted})}
async function aerialMedia(requestUrl:string,destination:string){try{const url=new URL("/api/escape/media",requestUrl);url.searchParams.set("destination",destination);url.searchParams.set("mode","aerial");const response=await fetch(url,{cache:"no-store",signal:AbortSignal.timeout(8500)});if(!response.ok)return[] as Array<{imageUrl:string;sourceUrl:string;title:string;license:string;attribution:string}>;const payload=await response.json() as {items?:Array<{imageUrl:string;sourceUrl:string;title:string;license:string;attribution:string}>};return(payload.items??[]).slice(0,4)}catch{return[]}}

export async function GET(request:Request){
 const url=new URL(request.url),slug=(url.searchParams.get("slug")??"").toLowerCase(),start=url.searchParams.get("start")??"",end=url.searchParams.get("end")??"",offerId=url.searchParams.get("offer")??"",tripToken=url.searchParams.get("trip"),requestedLang=url.searchParams.get("lang")==="en"?"en":"el";
 if(!slugPattern.test(slug)||!iso.test(start)||!iso.test(end)||Date.parse(end)<=Date.parse(start)||!safeId.test(offerId))return Response.json({error:"Invalid guide request"},{status:400});
 const[catalog,offers,directOffer]=await Promise.all([loadV8DestinationCatalog(),loadV8StayOffers(slug,start,end,60),loadV8StayOfferById(offerId)]).catch(()=>[[],[],null] as const),destination=catalog.find(x=>x.slug===slug),feedOffer=offers.find(x=>x.sourceProductId===offerId&&x.trackingUrl.startsWith("https://go.linkwi.se/")&&x.trackingUrl.includes("/CD104/")&&(!x.validFrom||Date.parse(x.validFrom)<=Date.parse(`${start}T23:59:59Z`))&&Boolean(x.validTo)&&Date.parse(x.validTo as string)>=Date.parse(`${end}T00:00:00Z`)),offer=feedOffer??(directOffer?.sourceProductId===offerId&&directOffer.trackingUrl.startsWith("https://go.linkwi.se/")&&directOffer.trackingUrl.includes("/CD104/")?directOffer:null);
 if(!destination||!offer)return Response.json({error:"Stay could not be resolved for this guide"},{status:404});
 const tokenTrip=decodeTrip(tripToken),lang=(tokenTrip?.language==="en"?"en":requestedLang) as "el"|"en",trip=tokenTrip??fallbackTrip(start,end,lang),destinationName=lang==="en"?destination.nameEn:destination.nameEl,summer=isSummer(start,end);
 const[weather,local,research,aerial,availabilityResult]=await Promise.all([getDailyTripWeatherV25(trip,destination.latitude,destination.longitude),getLocalIntelligenceV38({destinationSlug:slug,destinationName,hotelName:offer.propertyName,latitude:destination.latitude,longitude:destination.longitude,isSummer:summer,language:lang}),researchDestination({destination:destinationName,latitude:destination.latitude,longitude:destination.longitude,language:lang,travelerType:trip.travelerType,moods:trip.moods,nights:trip.nights}),aerialMedia(request.url,destinationName),assessStayWindowV25({slug,startDate:start,endDate:end,offerId:offer.sourceProductId,propertyName:offer.propertyName,groupSize:Math.max(1,trip.groupSize??1),probeProvider:true})]),availability=availabilityResult.truth,budget=estimateBeyondHotelBudgetV25(trip,destination.costTier);
 const dossier=await buildEscapeBookIntelligenceV61({local,research,trip,destination:destinationName,stayName:offer.propertyName});
 if(url.searchParams.get("format")==="json")return Response.json({
  version:"V61",designEngine:"canva-master",canvaMasterDesignId:"DAHVrzXLWDo",generatedAt:new Date().toISOString(),
  trip:{destination:destinationName,start,end,travelerType:trip.travelerType,moods:trip.moods,budget:trip.budget,origin:trip.origin},
  stay:{id:offer.sourceProductId,name:offer.propertyName,price:offer.price,currency:offer.currency,imageUrl:offer.imageUrl??offer.thumbUrl,trackingUrl:offer.trackingUrl},
  weather:weather.days,budgetBeyondStay:budget,dossier,availability,
  disclosure:{local:local.sourceDisclosure,availability:availability.reason,affiliate:"Affiliate tracking URL is preserved exactly; final price, room and live availability are confirmed by the provider."}
 },{headers:{"cache-control":"no-store","x-travel-guide":"v61-canva-data"}});
 const pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);const[regularBytes,boldBytes]=await Promise.all([readFile(path.join(process.cwd(),"public/fonts/DejaVuSans.ttf")),readFile(path.join(process.cwd(),"public/fonts/DejaVuSans-Bold.ttf"))]),regular=await pdf.embedFont(regularBytes,{subset:true}),bold=await pdf.embedFont(boldBytes,{subset:true});
 const placeRows=[...dossier.dontMiss,...dossier.restaurants,...dossier.nightlife,...dossier.nearby],uniqueImageUrls=[...new Set(placeRows.map(x=>x.imageUrl).filter((x):x is string=>Boolean(x)))].slice(0,14),[coverImage,...embeddedPlaces]=await Promise.all([photo(pdf,aerial[0]?.imageUrl??local.attractions[0]?.imageUrl??offer.imageUrl??offer.thumbUrl),...uniqueImageUrls.map(x=>photo(pdf,x))]),imageMap=new Map<string,PDFImage>();uniqueImageUrls.forEach((url,index)=>{const img=embeddedPlaces[index];if(img)imageMap.set(url,img)});
 const qrData=await QRCode.toDataURL(offer.trackingUrl,{errorCorrectionLevel:"H",margin:2,width:460,color:{dark:"#071713",light:"#FFFDF8"}}),qr=await pdf.embedPng(Buffer.from(qrData.split(",")[1],"base64")),total=7,dateFmt=new Intl.DateTimeFormat(lang==="el"?"el-GR":"en-GB",{day:"numeric",month:"long",year:"numeric"}),dateLabel=`${dateFmt.format(new Date(`${start}T12:00:00Z`))} → ${dateFmt.format(new Date(`${end}T12:00:00Z`))}`;

 const cover=pdf.addPage(A4);cover.drawRectangle({x:0,y:0,width:A4[0],height:A4[1],color:c.night});drawPhoto(cover,coverImage,0,300,A4[0],542);cover.drawRectangle({x:0,y:0,width:A4[0],height:A4[1],color:c.night,opacity:.32});cover.drawRectangle({x:0,y:0,width:A4[0],height:390,color:c.night,opacity:.92});cover.drawText("YOUR ESCAPE BOOK · V61",{x:42,y:786,size:8,font:bold,color:c.cyan});wrap(destinationName,bold,51,500).slice(0,2).forEach((line,i)=>cover.drawText(line,{x:42,y:360-i*58,size:51,font:bold,color:c.white}));cover.drawText(dateLabel,{x:44,y:235,size:11,font:regular,color:c.gold});block(cover,research.overview??say(lang,"Μια απόδραση χτισμένη από πραγματικό inventory, καιρό, local signals και πηγές — όχι από generic λίστες.","An escape built from real inventory, weather, local signals and sources — not generic lists."),regular,12,44,202,495,c.white,18,5);cover.drawText(`${offer.propertyName} · ${priceLabel(offer.price,offer.currency,lang)}`,{x:44,y:104,size:9,font:bold,color:c.cyan});cover.drawText(aerial[0]?`${say(lang,"Φωτογραφία προορισμού","Destination image")}: ${aerial[0].attribution} · ${aerial[0].license}`:say(lang,"Εικόνα από τεκμηριωμένη πηγή","Image from sourced content"),{x:44,y:56,size:5.8,font:regular,color:rgb(.72,.75,.7)});footer(cover,1,total,regular);

 const fit=pdf.addPage(A4);base(fit,"01 · WHY HERE · WHY NOW",say(lang,`Γιατί ${destinationName}`,`Why ${destinationName}`),regular,bold);let y=642;y=block(fit,research.overview??say(lang,"Η πρόταση πέρασε από season, route, inventory και local reality checks.","The choice passed season, route, inventory and local reality checks."),regular,13,44,y,500,c.ink,20,6)-24;fit.drawText(say(lang,"ΚΑΙΡΟΣ ΣΤΙΣ ΗΜΕΡΟΜΗΝΙΕΣ ΣΟΥ","WEATHER FOR YOUR DATES"),{x:44,y,size:7,font:bold,color:c.muted});const weatherY=y-22;weather.days.slice(0,5).forEach((day,i)=>{const x=44+i*102;fit.drawRectangle({x,y:weatherY-65,width:94,height:66,color:c.white,borderColor:c.line,borderWidth:.4});fit.drawText(day.date.slice(5),{x:x+10,y:weatherY-18,size:7,font:bold,color:c.muted});fit.drawText(`${day.temperatureMinC==null?"?":Math.round(day.temperatureMinC)}–${day.temperatureMaxC==null?"?":Math.round(day.temperatureMaxC)}°`,{x:x+10,y:weatherY-41,size:14,font:bold,color:c.ink});fit.drawText(day.source.toUpperCase(),{x:x+10,y:weatherY-56,size:5.2,font:regular,color:c.gold})});fit.drawRectangle({x:44,y:260,width:507,height:210,color:c.deep});fit.drawText("ESCAPE DNA",{x:62,y:442,size:7,font:bold,color:c.cyan});block(fit,trip.moods.map(x=>x.toUpperCase()).join(" · "),bold,19,62,410,455,c.white,25,4);block(fit,say(lang,`Ρυθμός: ${trip.pace}. Ενέργεια: ${trip.desiredEnergy}. Παρέα: ${trip.travelerType}.`,`Pace: ${trip.pace}. Energy: ${trip.desiredEnergy}. Travellers: ${trip.travelerType}.`),regular,9,62,342,455,rgb(.78,.84,.8),14,5);const ds=local.destinationSignal;if(ds?.aiScore!=null&&ds.sampleSize>=3)fit.drawText(`AI GUEST SIGNAL ${ds.aiScore}/100 · n=${ds.sampleSize}`,{x:62,y:287,size:7.5,font:bold,color:c.gold});footer(fit,2,total,regular);

 const sights=pdf.addPage(A4);base(sights,"02 · DON'T MISS",say(lang,"Ό,τι αξίζει χώρο στο ταξίδι","What deserves space in the trip"),regular,bold);const attractionRows=dossier.dontMiss.slice(0,4);if(attractionRows.length)attractionRows.forEach((p,i)=>placeCard(sights,p,i,imageMap.get(p.imageUrl??"")??null,regular,bold,44+(i%2)*256,382-Math.floor(i/2)*252,244,230,lang));else block(sights,say(lang,"Δεν επέστρεψε αρκετή τεκμηρίωση για ranked αξιοθέατα. Δεν συμπληρώνουμε λίστα με εικασίες.","Not enough evidence returned for ranked attractions. We do not fill the list with guesses."),regular,13,48,610,495,c.ink,20,6);if(research.attractions.length){sights.drawText("GROUNDED RESEARCH NOTES",{x:44,y:177,size:7,font:bold,color:c.muted});let ry=157;for(const item of research.attractions.slice(0,3)){ry=block(sights,`${item.name}: ${item.whyItFits??item.summary}`,regular,8,44,ry,500,c.ink,12,2)-8}}footer(sights,3,total,regular);

 const food=pdf.addPage(A4);base(food,"03 · FOOD · DRINKS · LOCAL LIFE",say(lang,"Πού αξίζει να φας και να βγεις","Where it is worth eating and going out"),regular,bold);const restaurantRows=dossier.restaurants.slice(0,4),nightRows=dossier.nightlife.slice(0,2);food.drawText(say(lang,"RESTAURANTS · πραγματικό provider rating όπου υπάρχει","RESTAURANTS · real provider ratings where available"),{x:44,y:650,size:7,font:bold,color:c.muted});restaurantRows.forEach((p,i)=>placeCard(food,p,i,imageMap.get(p.imageUrl??"")??null,regular,bold,44+(i%2)*256,385-Math.floor(i/2)*230,244,210,lang));food.drawText(say(lang,"ΠΟΤΟ / ΒΡΑΔΥ","DRINKS / NIGHTLIFE"),{x:44,y:145,size:7,font:bold,color:c.muted});nightRows.slice(0,2).forEach((p,i)=>{food.drawText(`${p.name}${p.rating!=null?` · ★ ${p.rating.toFixed(1)}`:""} · ${p.source}`,{x:44+i*256,y:126,size:7.2,font:bold,color:c.ink});block(food,p.why,regular,6.2,44+i*256,112,236,c.muted,8,2)});footer(food,4,total,regular);

 const nearby=pdf.addPage(A4);base(nearby,"04 · NEARBY FROM YOUR STAY",say(lang,"Χαμηλής τριβής επιλογές γύρω από τη βάση σου","Low-friction picks around your stay"),regular,bold);nearby.drawText(say(lang,"SPATIAL INTELLIGENCE · ranked by distance + evidence + fit","SPATIAL INTELLIGENCE · ranked by distance + evidence + fit"),{x:44,y:650,size:7,font:bold,color:c.muted});const nearbyRows=dossier.nearby.slice(0,5);let ny=618;for(const [i,p] of nearbyRows.entries()){nearby.drawRectangle({x:44,y:ny-82,width:507,height:72,color:i===0?rgb(.92,.96,.93):c.white,borderColor:c.line,borderWidth:.45});nearby.drawText(String(i+1).padStart(2,"0"),{x:58,y:ny-28,size:14,font:bold,color:c.gold});wrap(p.name,bold,11,240).slice(0,2).forEach((line,j)=>nearby.drawText(line,{x:92,y:ny-22-j*13,size:11,font:bold,color:c.ink}));const d=p.distanceKm==null?say(lang,"απόσταση μη διαθέσιμη","distance unavailable"):p.distanceKm<1?Math.round(p.distanceKm*1000)+" m":p.distanceKm.toFixed(p.distanceKm<10?1:0)+" km";nearby.drawText(d+" · "+p.source,{x:350,y:ny-22,size:6.5,font:bold,color:c.cyan});block(nearby,p.why,regular,6.5,92,ny-52,440,c.muted,8.5,2);ny-=92}block(nearby,say(lang,"Οι αποστάσεις εμφανίζονται μόνο όταν ο provider επέστρεψε συντεταγμένες. Η AI δεν εφευρίσκει χρόνο διαδρομής ή opening hours.","Distances appear only when provider coordinates exist. AI does not invent travel times or opening hours."),regular,7,44,145,500,c.muted,10,4);footer(nearby,5,total,regular);

 const practical=pdf.addPage(A4);base(practical,"05 · KNOW BEFORE YOU GO",say(lang,"Χρήματα, τριβές και πηγές","Money, friction and sources"),regular,bold);practical.drawText(say(lang,"ΕΚΤΙΜΗΣΗ ΕΚΤΟΣ ΔΙΑΜΟΝΗΣ","BEYOND-STAY ESTIMATE"),{x:44,y:644,size:7,font:bold,color:c.muted});practical.drawText(`€${budget.totalLow}–€${budget.totalHigh}`,{x:44,y:596,size:34,font:bold,color:c.ink});block(practical,budget.note,regular,9,44,572,500,c.muted,14,4);let py=505;for(const note of research.practicalNotes.slice(0,7)){practical.drawCircle({x:50,y:py+3,size:3,color:c.gold});py=block(practical,note,regular,9,64,py,470,c.ink,14,3)-10}practical.drawRectangle({x:44,y:145,width:507,height:128,color:c.white,borderColor:c.line,borderWidth:.5});practical.drawText("360° DISCLOSURE",{x:60,y:247,size:7,font:bold,color:c.cyan});block(practical,local.sourceDisclosure,regular,7.5,60,226,475,c.muted,11,4);block(practical,availability.reason,regular,6.5,60,181,475,c.ink,9,3);practical.drawText(`${say(lang,"Πηγές","Providers")}: ${dossier.sourceLedger.join(" + ")||"Open data"}`,{x:60,y:154,size:6.5,font:bold,color:c.ink});block(practical,dossier.learning.note,regular,6.2,60,151,470,c.muted,8.5,2);footer(practical,6,total,regular);

 const ready=pdf.addPage(A4);ready.drawRectangle({x:0,y:0,width:A4[0],height:A4[1],color:c.night});ready.drawText("READY WHEN YOU ARE",{x:44,y:783,size:8,font:bold,color:c.cyan});block(ready,say(lang,"Το Escape Book τελειώνει εδώ. Η εμπορική ενέργεια ξεκινά μόνο αν το επιλέξεις εσύ.","The Escape Book ends here. The commercial action starts only if you choose it."),bold,25,44,718,500,c.white,32,4);ready.drawImage(qr,{x:44,y:385,width:188,height:188});ready.drawText(availability.feedWindowCovered?say(lang,"ΣΚΑΝΑΡΕ ΓΙΑ ΤΗΝ ΤΡΕΧΟΥΣΑ ΠΡΟΣΦΟΡΑ","SCAN FOR THE CURRENT PROVIDER OFFER"):say(lang,"ΣΚΑΝΑΡΕ ΓΙΑ ΕΠΙΒΕΒΑΙΩΣΗ ΗΜΕΡΟΜΗΝΙΩΝ","SCAN TO VERIFY YOUR DATES"),{x:265,y:536,size:7,font:bold,color:c.gold});block(ready,offer.propertyName,bold,18,265,505,280,c.white,22,3);block(ready,priceLabel(offer.price,offer.currency,lang),bold,10,265,432,270,c.cyan,14,2);block(ready,say(lang,"Affiliate disclosure: ο σύνδεσμος είναι affiliate. Αν ολοκληρώσεις αγορά, ενδέχεται να λάβουμε προμήθεια χωρίς επιπλέον κόστος για εσένα.","Affiliate disclosure: this is an affiliate link. If you purchase, we may earn a commission at no extra cost to you."),regular,8,265,397,270,rgb(.74,.8,.76),12,6);ready.drawRectangle({x:44,y:205,width:507,height:54,color:c.gold});ready.drawText(availability.feedWindowCovered?say(lang,"ΑΝΟΙΞΕ ΤΗΝ ΠΡΟΣΦΟΡΑ ΣΤΟΝ ΠΑΡΟΧΟ ↗","OPEN THE PROVIDER OFFER ↗"):say(lang,"ΕΠΙΒΕΒΑΙΩΣΕ ΗΜΕΡΟΜΗΝΙΕΣ ΣΤΟΝ ΠΑΡΟΧΟ ↗","VERIFY DATES WITH PROVIDER ↗"),{x:69,y:225,size:10,font:bold,color:c.night});addUriLink(pdf,ready,offer.trackingUrl,44,205,507,54);block(ready,offer.trackingUrl,regular,5.2,44,165,507,rgb(.55,.62,.58),8,3);ready.drawText(say(lang,"Ακριβές tracking URL · δεν τροποποιήθηκε","Exact tracking URL · unchanged"),{x:44,y:124,size:6.5,font:bold,color:c.cyan});footer(ready,7,total,regular);

 const bytes=await pdf.save();return new Response(Buffer.from(bytes),{status:200,headers:{"content-type":"application/pdf","content-disposition":`attachment; filename="escape-book-${slug}.pdf"`,"cache-control":"private, no-store","x-escape-book":"v38"}})
}
