import { PrintTravelGuideV25 } from "@/components/print-travel-guide-v25";
import { buildTripBuilderV25 } from "@/lib/trip-builder/build-v25";
import type { TripadvisorPlaceV25 } from "@/lib/trip-builder/types-v25";
import { parseTripRequest } from "@/lib/validation/trip";
import styles from "./travel-guide-v25.module.css";

export const runtime="nodejs";export const dynamic="force-dynamic";
type Params={slug?:string;offer?:string;trip?:string};
const safeSlug=/^[a-z0-9-]{2,80}$/i,safeOffer=/^[a-zA-Z0-9:_-]{1,180}$/;
function decodeTrip(token:string){try{return JSON.parse(Buffer.from(token,"base64url").toString("utf8")) as unknown}catch{return null}}
function date(value:string,language:"el"|"en"){return new Intl.DateTimeFormat(language==="el"?"el-GR":"en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date(`${value}T12:00:00Z`))}
function rating(item:TripadvisorPlaceV25){return[item.ranking!=null?`#${item.ranking}`:null,item.rating!=null?`${item.rating.toFixed(1)}/5`:null,item.reviewCount!=null?`${Math.round(item.reviewCount)} reviews`:null].filter(Boolean).join(" · ")}
function Places({items}:{items:TripadvisorPlaceV25[]}){return <div className={styles.grid3}>{items.map(item=><article className={styles.card} key={`${item.kind}-${item.locationId}`}>{item.imageUrl?<img src={item.imageUrl} alt={item.name}/>:null}<small>{item.kind.toUpperCase()} · Tripadvisor</small><h3>{item.name}</h3>{rating(item)?<strong>{rating(item)}</strong>:null}{item.description?<p>{item.description.slice(0,300)}</p>:null}{item.address?<p><small>{item.address}</small></p>:null}{item.webUrl?<a href={item.webUrl} target="_blank" rel="noopener noreferrer">Tripadvisor ↗</a>:null}</article>)}</div>}

export default async function TravelGuidePage({searchParams}:{searchParams:Promise<Params>}){
 const q=await searchParams,slug=String(q.slug??"").toLowerCase(),offer=String(q.offer??""),raw=q.trip?decodeTrip(q.trip):null,parsed=parseTripRequest(raw);if(!safeSlug.test(slug)||!safeOffer.test(offer)||!parsed.success)return <main className={styles.page}><div className={styles.toolbar}>Invalid travel guide request.</div></main>;
 let plan;try{plan=await buildTripBuilderV25({trip:parsed.data,slug,offerId:offer})}catch{return <main className={styles.page}><div className={styles.toolbar}>This guide cannot be verified with the current stay/feed evidence. Return to the trip funnel and reselect the stay.</div></main>}
 const lang=plan.trip.language==="en"?"en":"el",name=lang==="el"?plan.destination.name:plan.destination.nameEn,ta=plan.tripadvisor,extra=plan.budgetBeyondHotel,truth=plan.availability.state.replaceAll("_"," "),web=plan.webResearch;
 return <main className={styles.page} data-canva-ready="true"><div className={styles.toolbar}><a href="/">← Travel Guru</a><PrintTravelGuideV25/></div><div className={styles.book}>
  <section className={`${styles.sheet} ${styles.cover}`}>{plan.stay?.imageUrl?<img className={styles.coverImage} src={plan.stay.imageUrl} alt={plan.stay.propertyName}/>:<div/>}<div><span className={styles.kicker}>PERSONAL TRAVEL GUIDE · V25 · CANVA-READY</span><h1>{name}</h1><h2>{date(plan.trip.startDate,lang)} → {date(plan.trip.endDate,lang)}</h2><p>{plan.trip.nights} night(s) · {plan.trip.groupSize} traveller(s) · {plan.stay?.propertyName}</p></div></section>

  <section className={styles.sheet}><div className={styles.heading}><div><span className={styles.kicker}>01 · STAY + AVAILABILITY TRUTH</span><h2>{plan.stay?.propertyName}</h2></div><span className={styles.badge}>{truth}</span></div><div className={styles.grid2}><div className={styles.card}>{plan.stay?.imageUrl?<img src={plan.stay.imageUrl} alt={plan.stay.propertyName}/>:null}<small>SELECTED STAY</small><h3>{plan.stay?.propertyName}</h3>{plan.stay?.price!=null?<p>Feed price signal: {plan.stay.currency??"EUR"} {plan.stay.price}</p>:null}<p>{plan.availability.reason}</p>{plan.stay?<a className={styles.cta} href={plan.stay.trackingUrl} target="_blank" rel="sponsored nofollow noopener">Final provider check ↗</a>:null}</div><div className={styles.card}><small>TRIPADVISOR HOTEL SIGNAL · {ta.sourceMonth}</small>{ta.hotel?.imageUrl?<img src={ta.hotel.imageUrl} alt={ta.hotel.name}/>:null}<h3>{ta.hotel?.name??"No live Tripadvisor hotel match"}</h3>{ta.hotel?<><div className={styles.metric}>{ta.hotel.rating!=null?`${ta.hotel.rating.toFixed(1)}/5`:"—"}</div><p>{rating(ta.hotel)}</p>{ta.hotel.webUrl?<a href={ta.hotel.webUrl} target="_blank" rel="noopener noreferrer">View on Tripadvisor ↗</a>:null}</>:<p>{ta.note}</p>}</div></div><div className={styles.note}>Feed validity is not a booking. Only explicit stock/provider evidence is labelled confirmed; otherwise the final room and price must be checked on the provider page.</div><div className={styles.footer}>Tripadvisor content is rendered live and not stored. Popularity ranking, when shown, is cited as of {ta.sourceMonth}.</div></section>

  <section className={styles.sheet}><div className={styles.heading}><div><span className={styles.kicker}>02 · WEATHER DAY BY DAY</span><h2>{plan.weather.label}</h2></div><span className={styles.badge}>{plan.weather.score??"—"}/100</span></div><div className={styles.weather}>{plan.weather.days.map(day=><article className={styles.card} key={day.date}><small>{date(day.date,lang)}</small><div className={styles.metric}>{day.temperatureMinC==null?"?":Math.round(day.temperatureMinC)}–{day.temperatureMaxC==null?"?":Math.round(day.temperatureMaxC)}°C</div><p>{day.summary}</p>{day.precipitationProbability!=null?<small>Rain {day.precipitationProbability}%</small>:null}</article>)}</div><div className={styles.note}>{plan.weather.days.some(day=>day.source==="typical")?"Dates outside the reliable short-range forecast horizon are shown as typical seasonal conditions, not as a false daily forecast.":"Daily short-range forecast for the selected dates."}</div></section>

  <section className={styles.sheet}><div className={styles.heading}><div><span className={styles.kicker}>03 · WEB RESEARCH + PLACES + MUSEUMS</span><h2>What to see around {name}</h2></div></div>{web.overview?<p>{web.overview}</p>:null}{web.bullets.length?<div className={styles.grid2}>{web.bullets.map(item=><article className={styles.card} key={item.name}><small>GROUNDED WEB RESEARCH · {item.strength}</small><h3>{item.name}</h3><p>{item.summary}</p>{item.why?<p><strong>Why it fits:</strong> {item.why}</p>:null}</article>)}</div>:null}{ta.status==="live"&&[...ta.places,...ta.museums].length?<><h3>Tripadvisor places / museums</h3><Places items={[...ta.places,...ta.museums]}/></>:null}{!web.bullets.length&&![...ta.places,...ta.museums].length?<div className={styles.note}>Not enough verified evidence was returned, so the guide does not invent POIs.</div>:null}{web.sources.length?<div className={styles.attribution}>Web sources: {web.sources.map(source=>source.domain).join(" · ")}</div>:null}<div className={styles.attribution}>Tripadvisor · live Content API · {ta.sourceMonth}</div></section>

  <section className={styles.sheet}><div className={styles.heading}><div><span className={styles.kicker}>04 · FOOD + DRINKS + NIGHTLIFE</span><h2>Top-ranked choices for your evenings</h2></div></div><h3>Restaurants</h3>{ta.restaurants.length?<Places items={ta.restaurants}/>:<div className={styles.note}>No live restaurant ranking returned.</div>}<h3>Bars / nightlife</h3>{ta.nightlife.length?<Places items={ta.nightlife}/>:<div className={styles.note}>No live nightlife result returned.</div>}<div className={styles.attribution}>Tripadvisor popularity rankings, where available, as of {ta.sourceMonth}.</div></section>

  {plan.destination.isSummer?<section className={styles.sheet}><div className={styles.heading}><div><span className={styles.kicker}>05 · SUMMER BEACHES</span><h2>Beach options for these dates</h2></div></div>{ta.beaches.length?<Places items={ta.beaches}/>:<div className={styles.note}>No live Tripadvisor beach result was returned, so this guide does not invent a ranked beach list.</div>}<div className={styles.attribution}>Tripadvisor · {ta.sourceMonth}</div></section>:null}

  <section className={styles.sheet}><div className={styles.heading}><div><span className={styles.kicker}>{plan.destination.isSummer?"06":"05"} · BUDGET BEYOND HOTEL</span><h2>Money to reserve for life outside the room</h2></div><span className={styles.badge}>EUR · GROUP TOTAL</span></div><div className={styles.grid2}><div className={styles.card}><small>FOOD</small><div className={styles.metric}>€{extra.foodLow}–€{extra.foodHigh}</div></div><div className={styles.card}><small>DRINKS / NIGHTLIFE</small><div className={styles.metric}>€{extra.drinksNightlifeLow}–€{extra.drinksNightlifeHigh}</div></div><div className={styles.card}><small>MUSEUMS / ACTIVITIES</small><div className={styles.metric}>€{extra.attractionsLow}–€{extra.attractionsHigh}</div></div><div className={styles.card}><small>LOCAL TRANSPORT</small><div className={styles.metric}>€{extra.localTransportLow}–€{extra.localTransportHigh}</div></div><div className={`${styles.card} ${styles.total}`}><small>TOTAL EXCLUDING HOTEL + INTERCITY TRANSPORT</small><div className={styles.metric}>€{extra.totalLow}–€{extra.totalHigh}</div></div></div><p className={styles.note}>{extra.note}</p></section>

  <section className={styles.sheet}><div className={styles.heading}><div><span className={styles.kicker}>{plan.destination.isSummer?"07":"06"} · FLEXIBLE DATE BACKUP</span><h2>Same weekday pattern only</h2></div></div><div className={styles.list}>{plan.flexibleWindows.map(window=><div className={styles.row} key={window.startDate}><strong>{date(window.startDate,lang)} → {date(window.endDate,lang)}</strong><span>{window.weatherLabel}</span><small>{window.availability.state.replaceAll("_"," ")}</small></div>)}</div><div className={styles.canva}><strong>Canva-ready content structure</strong><p>Reusable sections: cover, hotel, daily weather, grounded web POIs, Tripadvisor restaurants/nightlife, summer beaches, non-hotel budget and same-weekday alternatives. Live Tripadvisor fields remain no-store.</p><p>Template status: {plan.guide.canvaTemplateStatus}.</p></div><div className={styles.footer}>Generated {new Date(plan.generatedAt).toLocaleString("en-GB",{timeZone:"Europe/Athens"})} · Travel Guru V25</div></section>
 </div></main>
}
