"use client";

import { useEffect,useMemo,useRef,useState } from "react";
import { TripadvisorProofV25 } from "@/components/tripadvisor-proof-v25";
import type { TripBuilderPlanV25,TripadvisorPlaceV25 } from "@/lib/trip-builder/types-v25";
import type { TripRequest } from "@/lib/validation/trip";
import type { V8StayOffer,V8StayResponse } from "@/lib/decision/v8-types";
import styles from "./post-stay-trip-builder-v25.module.css";

type Context={trip:TripRequest|null;slug:string|null;offers:V8StayOffer[];startDate:string|null;endDate:string|null};
type Selection={trip:TripRequest;slug:string;offer:V8StayOffer};
type TravelWindow=Window&{__travelV25Context?:Context;__travelV25FetchWrapped?:boolean};
const EVENT="travel:v25-stay-selected",DAY=86_400_000;
const addDays=(iso:string,days:number)=>new Date(Date.parse(`${iso}T00:00:00Z`)+days*DAY).toISOString().slice(0,10);
const pretty=(iso:string,lang:"el"|"en")=>new Intl.DateTimeFormat(lang==="el"?"el-GR":"en-GB",{weekday:"short",day:"numeric",month:"short"}).format(new Date(`${iso}T12:00:00Z`));
const say=(lang:"el"|"en",el:string,en:string)=>lang==="el"?el:en;
function truthLabel(state:TripBuilderPlanV25["availability"]["state"],lang:"el"|"en"){const map:Record<typeof state,[string,string]>={CONFIRMED_ACTIVE:["Το feed δηλώνει ενεργό","Feed marks active"],VALID_WINDOW_STOCK_UNKNOWN:["Οι ημερομηνίες καλύπτονται · stock άγνωστο","Dates covered · stock unknown"],EXPLICITLY_UNAVAILABLE:["Μη διαθέσιμο","Unavailable"],NOT_IN_FEED:["Δεν υπάρχει στο feed για αυτές τις ημερομηνίες","Not in feed for these dates"],PROVIDER_PAGE_REACHED:["Οι ημερομηνίες πέρασαν στη σελίδα παρόχου · τελική επιβεβαίωση εκεί","Dates passed to provider · confirm there"],PROVIDER_UNAVAILABLE:["Ο πάροχος επέστρεψε μη διαθεσιμότητα","Provider returned unavailable"],PROVIDER_PROBE_UNAVAILABLE:["Δεν έγινε ασφαλής live έλεγχος παρόχου","Provider live check unavailable"]};return map[state][lang==="el"?0:1]}
function PlaceCard({item,lang}:{item:TripadvisorPlaceV25;lang:"el"|"en"}){return <article className={styles.card}>{item.imageUrl?<img className={styles.photo} src={item.imageUrl} alt={item.name}/>:null}<small>{item.kind.toUpperCase()}</small><h4>{item.name}</h4><TripadvisorProofV25 item={item}/>{item.description?<p>{item.description.slice(0,260)}</p>:null}{item.address?<p><small>{item.address}</small></p>:null}{item.webUrl?<a href={item.webUrl} target="_blank" rel="noopener noreferrer">{say(lang,"Δες στο Tripadvisor ↗","View on Tripadvisor ↗")}</a>:null}</article>}
function updateOneNightPicker(){const inputs=[...document.querySelectorAll<HTMLInputElement>('input[type="date"]')];if(inputs.length<2)return;const start=inputs[0],end=inputs[1];if(!start.value)return;const desired=addDays(start.value,1);if(end.min!==desired)end.min=desired}
function readSelection(ctx:Context):Selection|null{if(!ctx.trip||!ctx.slug||!ctx.offers.length)return null;const title=document.getElementById("final-step-title")?.textContent?.trim()??"",offer=ctx.offers.find(row=>title.includes(row.propertyName));if(!offer)return null;const startDate=ctx.startDate??ctx.trip.startDate,endDate=ctx.endDate??ctx.trip.endDate,nights=Math.max(1,Math.round((Date.parse(`${endDate}T00:00:00Z`)-Date.parse(`${startDate}T00:00:00Z`))/DAY));return{trip:{...ctx.trip,startDate,endDate,nights},slug:ctx.slug,offer}}

export function PostStayTripBuilderV25(){
 const[plan,setPlan]=useState<TripBuilderPlanV25|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[step,setStep]=useState(1),lastKey=useRef("");const lang:"el"|"en"=plan?.trip.language==="en"?"en":"el";
 useEffect(()=>{const w=window as TravelWindow,ctx=w.__travelV25Context??{trip:null,slug:null,offers:[],startDate:null,endDate:null};w.__travelV25Context=ctx;const originalFetch=window.fetch.bind(window);if(!w.__travelV25FetchWrapped){w.__travelV25FetchWrapped=true;window.fetch=async(input:RequestInfo|URL,init?:RequestInit)=>{const url=typeof input==="string"?input:input instanceof URL?input.toString():input.url,method=(init?.method??(input instanceof Request?input.method:"GET")).toUpperCase();if(url.includes("/api/recommend/stream")&&method==="POST"&&typeof init?.body==="string"){try{ctx.trip=JSON.parse(init.body) as TripRequest}catch{}}const response=await originalFetch(input,init);if(url.includes("/api/destination-detail")&&response.ok){try{const parsed=new URL(url,window.location.origin),payload=await response.clone().json() as V8StayResponse;ctx.slug=payload.slug;ctx.offers=payload.offers??[];ctx.startDate=parsed.searchParams.get("start_date")??payload.startDate;ctx.endDate=parsed.searchParams.get("end_date")??payload.endDate}catch{}}return response}}
 let previous="";const observer=new MutationObserver(()=>{updateOneNightPicker();const selection=readSelection(ctx);if(!selection)return;const key=`${selection.slug}:${selection.offer.sourceProductId}:${selection.trip.startDate}:${selection.trip.endDate}`;if(key===previous)return;previous=key;window.dispatchEvent(new CustomEvent<Selection>(EVENT,{detail:selection}))});observer.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:["min","value"]});updateOneNightPicker();return()=>observer.disconnect()},[]);
 useEffect(()=>{const handle=(event:Event)=>{const selection=(event as CustomEvent<Selection>).detail;if(!selection)return;const key=`${selection.slug}:${selection.offer.sourceProductId}:${selection.trip.startDate}:${selection.trip.endDate}`;if(lastKey.current===key)return;lastKey.current=key;setLoading(true);setError(null);setPlan(null);setStep(1);void fetch("/api/trip-builder",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip:selection.trip,slug:selection.slug,offerId:selection.offer.sourceProductId})}).then(async response=>{if(!response.ok)throw new Error("Trip Builder unavailable");return await response.json() as TripBuilderPlanV25}).then(value=>{setPlan(value);window.setTimeout(()=>document.getElementById("trip-builder-v25")?.scrollIntoView({behavior:"smooth",block:"start"}),120)}).catch(()=>setError("Trip Builder could not verify this stay safely.")).finally(()=>setLoading(false))};window.addEventListener(EVENT,handle);return()=>window.removeEventListener(EVENT,handle)},[]);
 const extra=plan?.budgetBeyondHotel,ta=plan?.tripadvisor,hasTa=ta?.status==="live",allExplore=useMemo(()=>[...(ta?.places??[]),...(ta?.museums??[])],[ta]);
 if(!loading&&!plan&&!error)return <div className={styles.hidden} aria-hidden="true"/>;if(loading&&!plan)return <section id="trip-builder-v25" className={styles.loading}><strong>TRIP BUILDER V25</strong><p>Weather · availability · web research · Tripadvisor · beaches · guide</p></section>;if(error&&!plan)return <section id="trip-builder-v25" className={styles.shell}><div className={styles.empty}>{error}</div></section>;if(!plan)return null;
 return <section id="trip-builder-v25" className={styles.shell}>
  <div className={styles.head}><div><span className={styles.eyebrow}>POST-STAY TRIP BUILDER · V25</span><h2>{say(lang,"Διάλεξες βάση. Τώρα χτίζουμε το πραγματικό ταξίδι.","You chose the base. Now we build the real trip.")}</h2><p>{say(lang,"Οι αρχικές ημερομηνίες μένουν default. Κάθε εναλλακτική κρατά ακριβώς το ίδιο weekday pattern και ελέγχεται ξανά για καιρό και stay truth.","Your original dates stay the default. Every alternative keeps the exact weekday pattern and is rechecked for weather and stay truth.")}</p></div><div className={styles.meta}><strong>{plan.stay?.propertyName}</strong><span>{pretty(plan.trip.startDate,lang)} → {pretty(plan.trip.endDate,lang)} · {plan.trip.nights} {say(lang,"νύχτα/ες","night(s)")}</span><span>{truthLabel(plan.availability.state,lang)}</span></div></div>
  <div className={styles.steps}>{[[1,"Weather & dates"],[2,say(lang,"Τι να δεις","Explore")],[3,say(lang,"Φαγητό & ζωή","Food & life")],[4,say(lang,"Guide & budget","Guide & budget")]].map(([n,label])=><button key={String(n)} className={step===n?styles.active:""} onClick={()=>setStep(Number(n))}>{n}. {label}</button>)}</div>
  {step===1?<div className={styles.panel}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>{say(lang,"ΒΗΜΑ 1 · ΚΑΙΡΟΣ + ΗΜΕΡΟΜΗΝΙΕΣ","STEP 1 · WEATHER + DATES")}</span><h3>{plan.weather.label}</h3></div><span className={styles.truth}>{truthLabel(plan.availability.state,lang)}</span></div><div className={styles.weatherGrid}>{plan.weather.days.map(day=><article key={day.date} className={styles.weatherDay}><small>{pretty(day.date,lang)}</small><div className={styles.temp}>{day.temperatureMinC==null?"?":Math.round(day.temperatureMinC)}–{day.temperatureMaxC==null?"?":Math.round(day.temperatureMaxC)}°C</div><p>{day.summary}</p>{day.precipitationProbability!=null?<small>{say(lang,"Πιθανότητα βροχής","Rain probability")}: {day.precipitationProbability}%</small>:null}</article>)}</div><div className={styles.flex}><h4>{say(lang,"Εναλλακτικές ίδιων ημερών εβδομάδας","Same-weekday alternatives")}</h4>{plan.flexibleWindows.length?plan.flexibleWindows.map(window=><div className={styles.window} key={window.startDate}><strong>{pretty(window.startDate,lang)} → {pretty(window.endDate,lang)}</strong><small>{window.shiftDays>0?`+${window.shiftDays}`:window.shiftDays} {say(lang,"ημέρες","days")}</small><small>{window.weatherLabel}</small><small>{truthLabel(window.availability.state,lang)} · {window.alternativeStayCount} {say(lang,"άλλα stays","other stays")}</small></div>):<div className={styles.empty}>{say(lang,"Δεν βρέθηκαν ασφαλείς εναλλακτικές.","No safe alternatives found.")}</div>}</div></div>:null}
  {step===2?<div className={styles.panel}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>{say(lang,"ΒΗΜΑ 2 · INTERNET RESEARCH + ΓΥΡΩ ΣΟΥ","STEP 2 · INTERNET RESEARCH + AROUND YOU")}</span><h3>{say(lang,"Τι αξίζει να δεις — με bullets, πηγές και εικόνες όπου υπάρχουν","What is worth seeing — with bullets, sources and imagery where available")}</h3></div></div>{plan.webResearch.overview?<p>{plan.webResearch.overview}</p>:null}{plan.webResearch.bullets.length?<div className={styles.cards}>{plan.webResearch.bullets.map(item=><article className={styles.card} key={item.name}><small>WEB RESEARCH · {item.strength}</small><h4>{item.name}</h4><p>{item.summary}</p>{item.why?<p><strong>{say(lang,"Γιατί ταιριάζει:","Why it fits:")}</strong> {item.why}</p>:null}</article>)}</div>:null}{hasTa&&allExplore.length?<><h4>{say(lang,"Tripadvisor places / museums με εικόνες","Tripadvisor places / museums with imagery")}</h4><div className={styles.cards}>{allExplore.map(item=><PlaceCard key={`${item.kind}-${item.locationId}`} item={item} lang={lang}/>)}</div></>:null}{!plan.webResearch.bullets.length&&!allExplore.length?<div className={styles.empty}>{say(lang,"Δεν υπάρχει αρκετό verified research για να γεμίσω το βήμα με εικασίες.","There is not enough verified research; the app will not fill this step with guesses.")}</div>:null}<p className={styles.source}>{plan.webResearch.sources.map(source=>source.domain).join(" · ")}{plan.webResearch.sources.length?" · ":""}{ta?.note}</p></div>:null}
  {step===3?<div className={styles.panel}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>{say(lang,"ΒΗΜΑ 3 · ΦΑΓΗΤΟ + ΠΟΤΟ + ΒΡΑΔΥ","STEP 3 · FOOD + DRINKS + NIGHTLIFE")}</span><h3>{say(lang,"Tripadvisor-ranked επιλογές για να φας, να πιεις και να βγεις","Tripadvisor-ranked food, drinks and nightlife")}</h3></div></div>{hasTa?<><h4>{say(lang,"Εστιατόρια","Restaurants")}</h4><div className={styles.cards}>{ta?.restaurants.map(item=><PlaceCard key={`r-${item.locationId}`} item={item} lang={lang}/>)}</div><h4>{say(lang,"Bars / nightlife","Bars / nightlife")}</h4><div className={styles.cards}>{ta?.nightlife.map(item=><PlaceCard key={`n-${item.locationId}`} item={item} lang={lang}/>)}</div>{plan.destination.isSummer?<><h4>{say(lang,"Παραλίες για τις καλοκαιρινές ημερομηνίες","Beaches for your summer dates")}</h4><div className={styles.cards}>{ta?.beaches.map(item=><PlaceCard key={`b-${item.locationId}`} item={item} lang={lang}/>)}</div></>:null}</>:<div className={styles.empty}>{ta?.note}</div>}<p className={styles.source}>{say(lang,"Tripadvisor content φορτώνεται live και δεν αποθηκεύεται. Ranking μόνο όταν επιστρέφεται από το API.","Tripadvisor content is loaded live and is not stored. Ranking appears only when returned by the API.")}</p></div>:null}
  {step===4&&extra?<div className={styles.panel}><div className={styles.guide}><div className={styles.guidePreview}>{plan.stay?.imageUrl?<img className={styles.photo} src={plan.stay.imageUrl} alt={plan.stay.propertyName}/>:null}<span>PERSONAL TRAVEL GUIDE · CANVA-READY</span><h3>{lang==="el"?plan.destination.name:plan.destination.nameEn}</h3><p>{pretty(plan.trip.startDate,lang)} → {pretty(plan.trip.endDate,lang)} · {plan.stay?.propertyName}</p></div><div><span className={styles.eyebrow}>{say(lang,"ΒΗΜΑ 4 · ΠΡΑΓΜΑΤΙΚΟ ΠΛΑΝΟ","STEP 4 · THE REAL PLAN")}</span><h3>{say(lang,"Budget πέρα από το ξενοδοχείο","Budget beyond the hotel")}</h3><div className={styles.budgetGrid}><div className={styles.budgetCard}><small>{say(lang,"Φαγητό","Food")}</small><strong>€{extra.foodLow}–€{extra.foodHigh}</strong></div><div className={styles.budgetCard}><small>{say(lang,"Ποτό / nightlife","Drinks / nightlife")}</small><strong>€{extra.drinksNightlifeLow}–€{extra.drinksNightlifeHigh}</strong></div><div className={styles.budgetCard}><small>{say(lang,"Μουσεία / εμπειρίες","Museums / activities")}</small><strong>€{extra.attractionsLow}–€{extra.attractionsHigh}</strong></div><div className={styles.budgetCard}><small>{say(lang,"Τοπικές μετακινήσεις","Local transport")}</small><strong>€{extra.localTransportLow}–€{extra.localTransportHigh}</strong></div><div className={`${styles.budgetCard} ${styles.budgetTotal}`}><small>{say(lang,"Σύνολο πέρα από hotel","Total beyond hotel")}</small><strong>€{extra.totalLow}–€{extra.totalHigh}</strong></div></div><p className={styles.source}>{extra.note}</p><a className={styles.cta} href={plan.guide.path} target="_blank">{say(lang,"Άνοιξε το προσωπικό Travel Guide →","Open your personal Travel Guide →")}</a></div></div></div>:null}
  <div className={styles.controls}><button className={styles.secondary} disabled={step===1} onClick={()=>setStep(v=>Math.max(1,v-1))}>{say(lang,"Πίσω","Back")}</button><button className={styles.primary} disabled={step===4} onClick={()=>setStep(v=>Math.min(4,v+1))}>{say(lang,"Συνέχισε","Continue")}</button></div>
 </section>
}
