"use client";

import { useMemo,useRef,useState } from "react";
import type { TripRequest,Month } from "@/lib/validation/trip";
import type { V8Recommendation,V8RecommendationResponse,V8StayOffer,V8StayResponse } from "@/lib/decision/v8-types";

type Lang="el"|"en";type StreamEvent={type:string;progress?:number;message?:string;result?:V8RecommendationResponse;catalogSize?:number;summary?:string;checked?:number;corrected?:boolean};
const say=(l:Lang,el:string,en:string)=>l==="el"?el:en;
const addDays=(iso:string,n:number)=>new Date(Date.parse(`${iso}T00:00:00Z`)+n*86400000).toISOString().slice(0,10);
const nights=(a:string,b:string)=>Math.max(2,Math.round((Date.parse(`${b}T00:00:00Z`)-Date.parse(`${a}T00:00:00Z`))/86400000));
const month=(iso:string):Month=>Number(iso.slice(5,7))===9?"september":Number(iso.slice(5,7))===10?"october":Number(iso.slice(5,7))===11?"november":"flexible";
const defaultTrip:TripRequest={origin:"Athens",startDate:"2026-10-16",endDate:"2026-10-19",month:"october",nights:3,budget:500,moods:["romantic","food"],travelerType:"couple",language:"el",distancePreference:"easy-hop",pace:"balanced",hotelStyle:"boutique",avoid:"long-travel"};
const moods=[
 {v:"relax",i:"◌",el:"Ηρεμία",en:"Switch off"},{v:"romantic",i:"♡",el:"Ρομαντικό",en:"Romantic"},{v:"food",i:"✦",el:"Καλό φαγητό",en:"Great food"},{v:"culture",i:"◇",el:"Πολιτισμός",en:"Culture"},
 {v:"city",i:"▦",el:"Πόλη",en:"City"},{v:"nature",i:"⌁",el:"Φύση",en:"Nature"},{v:"adventure",i:"↗",el:"Περιπέτεια",en:"Adventure"},{v:"warmth",i:"☀",el:"Ζέστη / θάλασσα",en:"Warm / sea"}
] as const;
const stageLabels:Record<string,[string,string]>={
 "understand:start":["Καταλαβαίνω τι ταξίδι χρειάζεσαι","Understanding the trip you need"],"understand:ready":["Το intent profile είναι έτοιμο","Intent profile ready"],"catalog:start":["Ανοίγω το Destination Knowledge Graph","Opening the Destination Knowledge Graph"],"catalog:ready":["Συγκρίνω Ελλάδα και εξωτερικό","Comparing Greece and abroad"],"shortlist:ready":["Κρατάω μόνο τα πραγματικά δυνατά matches","Keeping only strong destination matches"],"weather:start":["Ελέγχω εποχή και καιρό στους finalists","Checking season and weather for finalists"],"weather:ready":["Season + weather check έτοιμο","Season + weather check ready"],"verify:start":["Τελικός consistency check μόνο αν χρειάζεται","Final consistency check only if needed"],"verify:ready":["Οι 5 επιλογές κλείδωσαν","Your five choices are locked"]
};

export function TravelDecisionExperience(){
 const[lang,setLang]=useState<Lang>("el"),[trip,setTrip]=useState<TripRequest>(defaultTrip),[loading,setLoading]=useState(false),[events,setEvents]=useState<StreamEvent[]>([]),[error,setError]=useState<string|null>(null),[result,setResult]=useState<V8RecommendationResponse|null>(null),[selected,setSelected]=useState<V8Recommendation|null>(null),[stayData,setStayData]=useState<V8StayResponse|null>(null),[stayLoading,setStayLoading]=useState(false);const running=useRef(false),controller=useRef<AbortController|null>(null);
 const activeStage=events[events.length-1];
 const stayOffers=useMemo(()=>{const rows=[...(stayData?.offers??[])];const style=trip.hotelStyle;return rows.sort((a,b)=>{const sa=offerScore(a,style),sb=offerScore(b,style);return sb-sa}).slice(0,9)},[stayData,trip.hotelStyle]);
 function patch<K extends keyof TripRequest>(k:K,v:TripRequest[K]){setTrip(t=>({...t,[k]:v}))}
 function dates(start:string,end:string){let e=end;if(!e||Date.parse(e)<=Date.parse(start))e=addDays(start,3);setTrip(t=>({...t,startDate:start,endDate:e,nights:nights(start,e),month:month(start)}))}
 function toggleMood(v:TripRequest["moods"][number]){setTrip(t=>{const has=t.moods.includes(v),next=has?t.moods.filter(x=>x!==v):[...t.moods,v].slice(-3);return next.length?{...t,moods:next}:t})}
 function label(type:string){return stageLabels[type]?.[lang==="el"?0:1]??type}
 async function run(){if(running.current)return;running.current=true;setLoading(true);setError(null);setResult(null);setSelected(null);setStayData(null);setEvents([]);const c=new AbortController();controller.current=c;let final=false;
  try{const r=await fetch("/api/recommend/stream",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...trip,language:lang}),signal:c.signal});if(!r.ok||!r.body)throw new Error(say(lang,"Δεν ξεκίνησε το matching.","Matching could not start."));const reader=r.body.getReader(),decoder=new TextDecoder();let buf="";while(true){const{done,value}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const lines=buf.split("\n");buf=lines.pop()??"";for(const line of lines){if(!line.trim())continue;const ev=JSON.parse(line) as StreamEvent;if(ev.type==="error")throw new Error(ev.message||"Matching error");if(ev.type==="final"&&ev.result){final=true;setResult(ev.result);setTrip(ev.result.request);await reader.cancel();break}setEvents(prev=>[...prev.filter(x=>x.type!==ev.type),ev].slice(-6));}if(final)break}if(!final)throw new Error(say(lang,"Η ανάλυση έκλεισε χωρίς αποτέλεσμα.","The analysis ended without a result."));}
  catch(e){if((e as Error)?.name!=="AbortError")setError(e instanceof Error?e.message:"Error")}finally{running.current=false;controller.current=null;setLoading(false)}
 }
 async function choose(r:V8Recommendation){setSelected(r);setStayData(null);setStayLoading(true);setTimeout(()=>document.getElementById("destination-detail")?.scrollIntoView({behavior:"smooth",block:"start"}),50);try{const u=new URL("/api/destination-detail",window.location.origin);u.searchParams.set("slug",r.slug);u.searchParams.set("start_date",trip.startDate);u.searchParams.set("end_date",trip.endDate);const res=await fetch(u);if(res.ok)setStayData(await res.json() as V8StayResponse)}finally{setStayLoading(false)}}
 return <div className="v8-site">
  <header className="v8-nav"><a href="#top" className="v8-brand">TRAVEL <em>GURU</em><small>Destination-first AI</small></a><div className="v8-nav-proof">{say(lang,"Ο προορισμός πρώτα. Τα offers μετά.","Destination first. Offers second.")}</div><div className="v8-lang"><button className={lang==="el"?"on":""} onClick={()=>setLang("el")}>EL</button><button className={lang==="en"?"on":""} onClick={()=>setLang("en")}>EN</button></div></header>
  <main id="top">
   <section className="v8-hero"><div className="v8-hero-copy"><span className="v8-kicker">✦ Travel Decision Intelligence</span><h1>{say(lang,"Όχι “πού έχει ξενοδοχεία”.","Not “where hotels exist.”")}<br/><em>{say(lang,"Πού αξίζει να πας.","Where you should go.")}</em></h1><p>{say(lang,"Οι απαντήσεις σου γίνονται semantic intent. Μετά συγκρίνονται με ανεξάρτητη γνώση προορισμών, εποχή, effort, διάρκεια, budget band και weather. Τα affiliate stays μπαίνουν μόνο αφού διαλέξεις τόπο.","Your answers become semantic intent, then match against independent destination knowledge, season, effort, duration, budget band and weather. Affiliate stays appear only after you choose a place.")}</p><div className="v8-proof"><span>42 canonical destinations</span><span>21 Greece + 21 abroad</span><span>0% hotel supply in destination score</span></div></div><div className="v8-photo-stack"><div style={{backgroundImage:"url('/api/destination-photo?name=Rome&lang=en')"}}/><div style={{backgroundImage:"url('/api/destination-photo?name=Chania&lang=en')"}}/><div style={{backgroundImage:"url('/api/destination-photo?name=Budapest&lang=en')"}}/><b>5<br/><small>{say(lang,"διαφορετικά matches","different matches")}</small></b></div></section>

   <section className="v8-planner"><div className="v8-planner-head"><div><span className="v8-kicker">01 — {say(lang,"Πες μου τα βασικά","Tell me the basics")}</span><h2>{say(lang,"Ένα λεπτό. Καμία ατελείωτη φόρμα.","One minute. No endless form.")}</h2></div><span>{trip.nights} {say(lang,"νύχτες","nights")} · €{trip.budget}</span></div>
    <div className="v8-form-grid">
     <Field title={say(lang,"Από πού;","From where?")}><div className="v8-pills"><Pill on={trip.origin==="Athens"} onClick={()=>patch("origin","Athens")}>Athens</Pill><Pill on={trip.origin==="Thessaloniki"} onClick={()=>patch("origin","Thessaloniki")}>Thessaloniki</Pill></div></Field>
     <Field title={say(lang,"Πότε;","When?")}><div className="v8-dates"><input type="date" min="2026-08-08" value={trip.startDate} onChange={e=>dates(e.target.value,trip.endDate)}/><span>→</span><input type="date" min={addDays(trip.startDate,2)} value={trip.endDate} onChange={e=>dates(trip.startDate,e.target.value)}/></div></Field>
     <Field title={say(lang,"Με ποιον;","With whom?")}><div className="v8-pills">{([['solo','Solo'],['couple',say(lang,'Ζευγάρι','Couple')],['family',say(lang,'Οικογένεια','Family')],['friends',say(lang,'Παρέα','Friends')]] as const).map(([v,t])=><Pill key={v} on={trip.travelerType===v} onClick={()=>patch("travelerType",v)}>{t}</Pill>)}</div></Field>
     <Field title={say(lang,"Συνολικό budget signal","Total budget signal")}><div className="v8-pills">{[300,450,600,800,1200].map(v=><Pill key={v} on={trip.budget===v} onClick={()=>patch("budget",v)}>€{v}</Pill>)}</div></Field>
    </div>
    <div className="v8-divider"/>
    <div className="v8-question"><span className="v8-kicker">02 — {say(lang,"Τι θέλεις να σου δώσει αυτό το ταξίδι;","What should this trip give you?")}</span><p>{say(lang,"Διάλεξε έως 3.","Choose up to 3.")}</p><div className="v8-moods">{moods.map(m=><button key={m.v} className={trip.moods.includes(m.v)?"on":""} onClick={()=>toggleMood(m.v)}><i>{m.i}</i><span>{lang==="el"?m.el:m.en}</span></button>)}</div></div>
    <div className="v8-form-grid v8-secondary">
     <Field title={say(lang,"Πόση μετακίνηση;","How much travel effort?")}><div className="v8-pills">{([['nearby',say(lang,'Κοντά','Nearby')],['easy-hop',say(lang,'Εύκολο hop','Easy hop')],['any',say(lang,'Όπου αξίζει','Wherever fits')],['island',say(lang,'Νησιωτικό','Island feel')]] as const).map(([v,t])=><Pill key={v} on={trip.distancePreference===v} onClick={()=>patch("distancePreference",v)}>{t}</Pill>)}</div></Field>
     <Field title={say(lang,"Τι να αποφύγω;","What should I avoid?")}><div className="v8-pills">{([['long-travel',say(lang,'Ταλαιπωρία','Long travel')],['high-cost',say(lang,'Υψηλό κόστος','High cost')],['crowds',say(lang,'Πολύ κόσμο','Crowds')],['none',say(lang,'Τίποτα','Nothing')]] as const).map(([v,t])=><Pill key={v} on={trip.avoid===v} onClick={()=>patch("avoid",v)}>{t}</Pill>)}</div></Field>
     <Field title={say(lang,"Stay style — δεν αλλάζει τον προορισμό","Stay style — does not choose destination")}><div className="v8-pills">{([['boutique','Boutique'],['luxury','5★ / luxury'],['value',say(lang,'Value','Value')],['resort','Resort'],['any',say(lang,'Οτιδήποτε','Any')]] as const).map(([v,t])=><Pill key={v} on={trip.hotelStyle===v} onClick={()=>patch("hotelStyle",v)}>{t}</Pill>)}</div></Field>
     <Field title={say(lang,"Πες το με δικά σου λόγια — προαιρετικό","Say it in your own words — optional")}><textarea value={trip.tripText??""} maxLength={320} placeholder={say(lang,"π.χ. θέλω ήσυχα, καλό φαγητό, όχι τουριστίλα και να μη λιώσω στη μετακίνηση","e.g. quiet, great food, not too touristy, and easy to reach")} onChange={e=>patch("tripText",e.target.value)}/></Field>
    </div>
    <button className="v8-run" disabled={loading} onClick={()=>void run()}><span>{loading?say(lang,"Ψάχνω τα σωστά 5…","Finding the right five…"):say(lang,"Βρες μου τα σωστά 5","Find my right five")}</span><b>{loading?"◉":"→"}</b></button>{error&&<div className="v8-error">{error}</div>}
   </section>

   {loading&&<section className="v8-processing"><div className="v8-orbit"><span/><span/><span/><b>AI</b></div><div><span className="v8-kicker">{say(lang,"Δουλεύει τώρα","Working now")}</span><h2>{activeStage?label(activeStage.type):say(lang,"Καταλαβαίνω το ταξίδι…","Understanding your trip…")}</h2><div className="v8-stage-list">{events.filter(e=>e.type!=="final").slice(-5).map((e,i)=><div key={e.type}><span>{i===events.filter(x=>x.type!=="final").slice(-5).length-1?"◉":"✓"}</span>{label(e.type)}</div>)}</div><p>{say(lang,"Δεν υπάρχει fake 100%. Το αποτέλεσμα εμφανίζεται μόνο όταν υπάρχει final response.","No fake 100%. Results appear only after a real final response.")}</p></div></section>}

   {result&&<section className="v8-results"><div className="v8-results-head"><div><span className="v8-kicker">03 — {say(lang,"Τα 5 matches σου","Your 5 matches")}</span><h2>{say(lang,"Πέντε διαφορετικές απαντήσεις. Όχι πέντε παραλλαγές του ίδιου.","Five different answers. Not five versions of the same place.")}</h2></div><div className="v8-result-meta"><span>{result.catalogSize} destinations checked</span><span>{result.mode==="deepseek-intent"?"DeepSeek intent parser":"structured intent"}</span><span>{result.verifierUsed?"OpenAI verifier used":"verifier skipped"}</span></div></div><div className="v8-card-grid">{result.recommendations.map((r,i)=><ResultCard key={r.slug} r={r} i={i} lang={lang} onClick={()=>void choose(r)}/>)}</div></section>}

   {selected&&<section id="destination-detail" className="v8-detail"><div className="v8-detail-hero"><div className="v8-detail-photo" style={{backgroundImage:`linear-gradient(90deg,rgba(14,28,22,.1),rgba(14,28,22,.48)),url('/api/destination-photo?name=${encodeURIComponent(selected.destinationEn)}&lang=en')`}}/><div className="v8-detail-copy"><span className="v8-kicker">{selected.role}</span><h2>{selected.destination}</h2><p>{selected.why}</p><div className="v8-detail-facts"><span>{selected.breakdown.intent}% intent</span><span>{selected.breakdown.season}% season</span><span>{selected.breakdown.effort}% effort</span><span>{selected.budgetLabel}</span></div></div></div><div className="v8-stay-head"><div><span className="v8-kicker">{say(lang,"STAYS — μετά την επιλογή προορισμού","STAYS — after destination choice")}</span><h3>{say(lang,"Τώρα κοιτάμε τα ξενοδοχεία.","Now we look at stays.")}</h3></div><p>{say(lang,"Τα offers εδώ είναι γεωγραφικά συνδεδεμένα με τον προορισμό. Η ισχύς του feed επικαλύπτει τις ημερομηνίες σου· η πραγματική διαθεσιμότητα δωματίου επιβεβαιώνεται στον merchant.","These offers are geographically linked to the destination. Feed validity overlaps your dates; actual room availability is confirmed by the merchant.")}</p></div>{stayLoading?<div className="v8-stay-loading">◉ {say(lang,"Ελέγχω το current feed…","Checking current feed…")}</div>:stayOffers.length?<div className="v8-stays">{stayOffers.map(o=><StayCard key={o.sourceProductId} offer={o} lang={lang}/>)}</div>:<div className="v8-no-stays"><b>{say(lang,"Δεν βρήκα verified stay offer στο τρέχον feed.","No verified stay offer in the current feed.")}</b><p>{say(lang,"Ο προορισμός παραμένει σωστό match — δεν τον υποβαθμίζουμε επειδή λείπει affiliate inventory.","The destination remains a valid match — missing affiliate inventory does not lower its rank.")}</p></div>}</section>}
  </main><footer className="v8-footer">Travel Guru V8 · Destination knowledge → feasibility → weather → 5 matches → stays</footer>
 </div>
}

function Field({title,children}:{title:string;children:React.ReactNode}){return <div className="v8-field"><label>{title}</label>{children}</div>}
function Pill({on,onClick,children}:{on:boolean;onClick:()=>void;children:React.ReactNode}){return <button type="button" className={on?"on":""} onClick={onClick}>{children}</button>}
function ResultCard({r,i,lang,onClick}:{r:V8Recommendation;i:number;lang:Lang;onClick:()=>void}){return <article className={`v8-result-card ${i===0?"featured":""}`}><div className="v8-result-photo" style={{backgroundImage:`linear-gradient(180deg,rgba(13,27,21,.02),rgba(13,27,21,.68)),url('/api/destination-photo?name=${encodeURIComponent(r.destinationEn)}&lang=en')`}}><div><span>#{i+1}</span><b>{r.role}</b></div><section><small>{r.country}</small><h3>{r.destination}</h3></section></div><div className="v8-result-body"><div className="v8-score"><strong>{r.score}</strong><span>match score</span><em>{r.confidence}</em></div><p>{r.why}</p><div className="v8-bars"><Bar label="intent" v={r.breakdown.intent}/><Bar label="season" v={r.breakdown.season}/><Bar label="effort" v={r.breakdown.effort}/><Bar label="budget" v={r.breakdown.budget}/><Bar label="weather" v={r.breakdown.weather}/></div><div className="v8-card-notes"><span>⌁ {r.effortLabel}</span><span>€ {r.budgetLabel}</span>{r.weather?.temperatureMeanC!=null&&<span>☀ {Math.round(r.weather.temperatureMeanC)}° avg</span>}</div><button onClick={onClick}>{say(lang,"Άνοιξε το match","Open this match")} <b>→</b></button></div></article>}
function Bar({label,v}:{label:string;v:number}){return <div><span>{label}</span><i><b style={{width:`${Math.max(0,Math.min(100,v))}%`}}/></i><strong>{v}</strong></div>}
function offerScore(o:V8StayOffer,style:TripRequest["hotelStyle"]){let s=100-(o.distanceKm??20);if(style==="luxury")s+=(o.starLevel??0)*12;if(style==="value"&&o.price!=null)s+=Math.max(0,80-o.price)/3;if(style==="boutique"&&/boutique|design/i.test(`${o.propertyName} ${o.description??""}`))s+=25;if(style==="resort"&&/resort|spa|all inclusive/i.test(`${o.propertyName} ${o.description??""}`))s+=25;s+=Math.min(15,(o.discount??0)/2);return s}
function StayCard({offer,lang}:{offer:V8StayOffer;lang:Lang}){const image=offer.imageUrl||offer.thumbUrl;return <article className="v8-stay"><div className="v8-stay-photo" style={image?{backgroundImage:`url(${image})`}:undefined}><span>{offer.distanceKm!=null?`${offer.distanceKm.toFixed(1)} km`:"stay"}</span></div><div><small>{offer.city||offer.category||"stay"}</small><h4>{offer.propertyName}</h4><p>{offer.description?.slice(0,120)}</p><div className="v8-stay-facts">{offer.price!=null&&<span>{offer.currency||"€"} {Math.round(offer.price)} <small>feed price</small></span>}{offer.discount!=null&&offer.discount>0&&<span>-{Math.round(offer.discount)}%</span>}{offer.starLevel&&<span>{offer.starLevel}★</span>}</div><a href={offer.trackingUrl} target="_blank" rel="sponsored nofollow">{say(lang,"Έλεγξε στον merchant","Check with merchant")} ↗</a></div></article>}
