"use client";

import { useEffect, useMemo, useState, type CSSProperties, type ReactNode } from "react";
import type { AffiliateDestinationDetailResponse, AffiliateOffer, DestinationInsightsResponse, GuruRecommendation, GuruRecommendationResponse, WeatherEvidence } from "@/lib/decision/types";
import type { Month, TripRequest } from "@/lib/validation/trip";

type Lang="el"|"en"; type View="home"|"thinking"|"choices"|"destination"; type GuideSection="dates"|"distance"|"mood"|"stay"|"people"|"style"|null;
type Featured={destinationId:string;locationLabel:string;imageUrl:string};
type StreamEvent={type:string;candidateCount?:number;weatherChecked?:number;weatherScreenedCount?:number;shortlistCount?:number;mode?:string;preview?:Array<{destination:string;score?:number;weather?:number;seasonality?:number;maxC?:number|null;rain?:number|null}>;result?:GuruRecommendationResponse;message?:string};

const defaultRequest:TripRequest={origin:"Athens",startDate:"2026-10-16",endDate:"2026-10-19",month:"october",nights:3,budget:500,moods:["romantic","food"],travelerType:"couple",language:"el",distancePreference:"easy-hop",pace:"balanced",hotelStyle:"luxury",avoid:"long-travel"};
const moodOptions=[{value:"relax",el:"Να αδειάσει το μυαλό",en:"Switch off",icon:"◌"},{value:"romantic",el:"Να ξανασυνδεθούμε",en:"Reconnect",icon:"♡"},{value:"food",el:"Να φάω πραγματικά καλά",en:"Eat really well",icon:"✦"},{value:"culture",el:"Να νιώσω τον τόπο",en:"Feel the place",icon:"◇"},{value:"nature",el:"Να βγω έξω",en:"Get outside",icon:"⌁"},{value:"adventure",el:"Να ξεφύγω από τα συνηθισμένα",en:"Break routine",icon:"↗"},{value:"warmth",el:"Ήλιο & θάλασσα",en:"Sun & sea",icon:"☀"},{value:"city",el:"Πόλη & ενέργεια",en:"City energy",icon:"▦"}] as const;
const distanceOptions=[{value:"nearby",el:"Κοντά μου",en:"Nearby",noteEl:"λίγη μετακίνηση",noteEn:"minimal travel"},{value:"easy-hop",el:"Εύκολη απόδραση",en:"Easy hop",noteEl:"να μη με κουράσει",noteEn:"keep it easy"},{value:"island",el:"Νησιωτική αίσθηση",en:"Island feel",noteEl:"θάλασσα πρώτα",noteEn:"sea first"},{value:"any",el:"Έκπληξέ με",en:"Surprise me",noteEl:"όπου αξίζει",noteEn:"where it fits"}] as const;
const hotelOptions=[{value:"luxury",el:"5★ / luxury",en:"5★ / luxury"},{value:"boutique",el:"Boutique",en:"Boutique"},{value:"resort",el:"Resort",en:"Resort"},{value:"value",el:"Καλύτερη αξία",en:"Best value"},{value:"any",el:"Χωρίς προτίμηση",en:"No preference"}] as const;
const avoidOptions=[{value:"long-travel",el:"πολλή ταλαιπωρία",en:"too much travel"},{value:"high-cost",el:"να ξεφύγει το κόστος",en:"cost getting away"},{value:"crowds",el:"πολύ κόσμο",en:"too crowded"},{value:"none",el:"τίποτα συγκεκριμένο",en:"nothing specific"}] as const;
const travelerOptions=[{value:"solo",el:"μόνος/η",en:"solo"},{value:"couple",el:"ζευγάρι",en:"couple"},{value:"family",el:"οικογένεια",en:"family"},{value:"friends",el:"παρέα",en:"friends"}] as const;
const say=(lang:Lang,el:string,en:string)=>lang==="el"?el:en;
const isoToday=()=>new Date().toISOString().slice(0,10);
const addDays=(iso:string,days:number)=>new Date(Date.parse(`${iso}T00:00:00Z`)+days*86400000).toISOString().slice(0,10);
const nightsBetween=(a:string,b:string)=>Math.max(0,Math.round((Date.parse(`${b}T00:00:00Z`)-Date.parse(`${a}T00:00:00Z`))/86400000));
const monthFromDate=(iso:string):Month=>{const m=Number(iso.slice(5,7));return m===9?"september":m===10?"october":m===11?"november":"flexible"};
const moodLabel=(m:TripRequest["moods"],lang:Lang)=>m.map(x=>{const o=moodOptions.find(v=>v.value===x);return o?(lang==="el"?o.el:o.en):x}).join(" + ");
const dateLabel=(v:string|null|undefined,lang:Lang,year=false)=>{if(!v)return"—";const d=new Date(`${v.slice(0,10)}T00:00:00Z`);if(Number.isNaN(d.getTime()))return v;return new Intl.DateTimeFormat(lang==="el"?"el-GR":"en-GB",{day:"numeric",month:"short",...(year?{year:"numeric" as const}:{})}).format(d)};
const rangeLabel=(r:TripRequest,lang:Lang)=>`${dateLabel(r.startDate,lang)} → ${dateLabel(r.endDate,lang,true)} · ${r.nights} ${say(lang,"νύχτες","nights")}`;
const priceLabel=(o:AffiliateOffer,lang:Lang)=>o.price==null?say(lang,"Δεν δόθηκε τιμή","Price not supplied"):o.currency?`${o.currency} ${Math.round(o.price)}`:`${say(lang,"τιμή feed","feed price")} ${Math.round(o.price)}`;
const confidenceLabel=(v:GuruRecommendation["confidence"],lang:Lang)=>v==="HIGH"?say(lang,"Υψηλή","High"):v==="MEDIUM"?say(lang,"Μεσαία","Medium"):say(lang,"Χαμηλή","Low");
const roleLabel=(role:string,lang:Lang)=>{const m:Record<string,[string,string]>={"GURU PICK":["ΚΟΡΥΦΑΙΑ ΕΠΙΛΟΓΗ","GURU PICK"],"WEATHER FIT":["ΚΑΛΥΤΕΡΟΣ ΚΑΙΡΟΣ","WEATHER FIT"],"LUXURY DEPTH":["ΒΑΘΟΣ 5★","LUXURY DEPTH"],"BEST VALUE":["ΚΑΛΥΤΕΡΗ ΑΞΙΑ","BEST VALUE"],"EASY ESCAPE":["ΕΥΚΟΛΗ ΑΠΟΔΡΑΣΗ","EASY ESCAPE"],"SMART ALTERNATIVE":["ΕΞΥΠΝΗ ΕΝΑΛΛΑΚΤΙΚΗ","SMART ALTERNATIVE"],"WILDCARD":["WILDCARD","WILDCARD"]};return m[role]?.[lang==="el"?0:1]??role};
function Metric({label,value}:{label:string;value:number}){return <div className="v5-metric"><span>{label}</span><i><b style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></i><strong>{value}</strong></div>}
function WeatherMini({weather,lang}:{weather?:WeatherEvidence|null;lang:Lang}){if(!weather)return <div className="weather-mini muted">{say(lang,"Weather pending","Weather pending")}</div>;const sun=Math.round(Math.min(100,Math.max(0,(weather.sunSignal??3)*14)));return <div className={`weather-mini ${weather.score>=72?"good":weather.score<50?"risk":"ok"}`}><div className="weather-mini-head"><span>☀ {weather.score}/100</span><small>{weather.typical?say(lang,"Τυπικό κλίμα","Typical climate"):say(lang,"Πρόγνωση","Forecast")}</small></div><div className="weather-temp"><b>{weather.temperatureMaxC!=null?`${Math.round(weather.temperatureMaxC)}°`:"—"}</b><span>{weather.temperatureMinC!=null?`${Math.round(weather.temperatureMinC)}° min`:""}</span><em>{weather.precipitationMmDay!=null?`☂ ${weather.precipitationMmDay} mm/d`:""}</em></div><div className="weather-sun"><i><b style={{width:`${sun}%`}}/></i><span>sun</span></div></div>}

export function TravelDecisionExperience(){
  const[lang,setLang]=useState<Lang>("el"),[draft,setDraft]=useState<TripRequest>(defaultRequest),[view,setView]=useState<View>("home"),[open,setOpen]=useState<GuideSection>(null),[featured,setFeatured]=useState<Featured[]>([]),[result,setResult]=useState<GuruRecommendationResponse|null>(null),[selected,setSelected]=useState<GuruRecommendation|null>(null),[detail,setDetail]=useState<AffiliateDestinationDetailResponse|null>(null),[insights,setInsights]=useState<DestinationInsightsResponse|null>(null),[thinking,setThinking]=useState<StreamEvent[]>([]),[thinkingError,setThinkingError]=useState<string|null>(null),[selectedOffer,setSelectedOffer]=useState<AffiliateOffer|null>(null),[offerUnlocked,setOfferUnlocked]=useState(false),[now,setNow]=useState(()=>Date.now());
  useEffect(()=>{fetch("/api/featured").then(r=>r.ok?r.json():{destinations:[]}).then((d:{destinations?:Featured[]})=>setFeatured(d.destinations??[])).catch(()=>setFeatured([]))},[]);
  useEffect(()=>{setDraft(d=>({...d,language:lang}))},[lang]);
  useEffect(()=>{if(view!=="destination")return;const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id)},[view]);
  const premiumDisplay=useMemo(()=>detail?[...detail.premiumOffers,...detail.premiumFill.filter(x=>!detail.premiumOffers.some(p=>p.sourceProductId===x.sourceProductId))].slice(0,5):[],[detail]);
  const premiumIds=useMemo(()=>new Set(premiumDisplay.map(x=>x.sourceProductId)),[premiumDisplay]);
  const alternativeDisplay=useMemo(()=>detail?detail.alternatives.filter(x=>!premiumIds.has(x.sourceProductId)).slice(0,5):[],[detail,premiumIds]);
  const allShownOffers=useMemo(()=>[...premiumDisplay,...alternativeDisplay],[premiumDisplay,alternativeDisplay]);
  const nearestExpiry=useMemo(()=>{const xs=allShownOffers.map(x=>x.validTo?new Date(x.validTo).getTime():NaN).filter(x=>Number.isFinite(x)&&x>now);return xs.length?Math.min(...xs):null},[allShownOffers,now]);
  const countdown=useMemo(()=>{if(!nearestExpiry)return null;let s=Math.max(0,Math.floor((nearestExpiry-now)/1000));const days=Math.floor(s/86400);s%=86400;const hours=Math.floor(s/3600);s%=3600;const minutes=Math.floor(s/60),seconds=s%60;return{days,hours,minutes,seconds}},[nearestExpiry,now]);
  const topThinking=thinking[thinking.length-1],thinkingProgress=Math.min(100,Math.max(10,thinking.length*14)),comparisons=result?.recommendations??[];
  const hero=(i:number)=>featured[i]?.imageUrl?{backgroundImage:`linear-gradient(180deg,rgba(1,18,40,.08),rgba(1,18,40,.58)),url(${featured[i].imageUrl})`}:undefined;

  function update<K extends keyof TripRequest>(key:K,value:TripRequest[K]){setDraft(d=>({...d,[key]:value}));}
  function updateDates(start:string,end:string){let s=start,e=end;if(!s)return;if(!e||Date.parse(e)<=Date.parse(s))e=addDays(s,Math.max(2,draft.nights));let nights=nightsBetween(s,e);if(nights<2){e=addDays(s,2);nights=2}if(nights>14){e=addDays(s,14);nights=14}setDraft(d=>({...d,startDate:s,endDate:e,nights,month:monthFromDate(s)}));}
  function toggleMood(value:TripRequest["moods"][number]){const active=draft.moods.includes(value),next=active?draft.moods.filter(x=>x!==value):[...draft.moods,value].slice(-3);if(next.length)setDraft({...draft,moods:next});}
  function stageLabel(type:string){const labels:Record<string,[string,string]>={"source:start":["Ελέγχω ποια tracked offers καλύπτουν ακριβώς τις ημερομηνίες","Checking tracked offers for the exact dates"],"source:ready":["Κλείδωσα τους πραγματικά διαθέσιμους προορισμούς","Eligible destinations locked"],"rank:start":["Εφαρμόζω απόσταση, budget και travel intent","Applying distance, budget and travel intent"],"rank:ready":["Έφτιαξα το πρώτο shortlist","Initial shortlist ready"],"weather:start":["Ελέγχω καιρό και εποχικότητα πριν επιλέξω","Checking weather and seasonality before choosing"],"weather:ready":["Αφαίρεσα επιλογές με αδύναμο weather fit","Weak-weather choices filtered"],"decision:ready":["Συνδύασα seasonality, period supply και προσωπικό fit","Seasonality, period supply and personal fit combined"],"guru:start":["Το DeepSeek συγκρίνει μόνο το καθαρό shortlist","DeepSeek compares only the clean shortlist"],"guru:ready":["Οι 5 τελικές επιλογές κλείδωσαν","Five final choices locked"]};return labels[type]?.[lang==="el"?0:1]??type;}
  async function askGuru(){setThinking([]);setThinkingError(null);setSelected(null);setDetail(null);setInsights(null);setSelectedOffer(null);setView("thinking");try{const response=await fetch("/api/recommend/stream",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,language:lang})});if(!response.ok||!response.body)throw new Error(say(lang,"Δεν ξεκίνησε η ανάλυση.","Could not start analysis."));const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()??"";for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line) as StreamEvent;setThinking(p=>[...p,event].slice(-10));if(event.type==="error")throw new Error(event.message||"Analysis stopped");if(event.type==="final"&&event.result){setResult(event.result);setDraft(event.result.request);setView("choices")}}}}catch(e){setThinkingError(e instanceof Error?e.message:"Error");setView("home")}}
  async function chooseDestination(trip:GuruRecommendation){setSelected(trip);setDetail(null);setInsights(null);setSelectedOffer(null);setOfferUnlocked(false);setView("destination");window.scrollTo({top:0,behavior:"smooth"});const detailUrl=`/api/destination-detail?destination_id=${encodeURIComponent(trip.destinationId)}&start_date=${encodeURIComponent(draft.startDate)}&end_date=${encodeURIComponent(draft.endDate)}`;const insightParams=new URLSearchParams({destination:trip.destination,lang,traveler:draft.travelerType,moods:draft.moods.join(","),nights:String(draft.nights)});if(trip.latitude!=null)insightParams.set("lat",String(trip.latitude));if(trip.longitude!=null)insightParams.set("lon",String(trip.longitude));const[d,i]=await Promise.all([fetch(detailUrl).then(r=>r.ok?r.json():null).catch(()=>null),fetch(`/api/destination-insights?${insightParams}`).then(r=>r.ok?r.json():null).catch(()=>null)]);setDetail(d as AffiliateDestinationDetailResponse|null);setInsights(i as DestinationInsightsResponse|null)}
  function reviewOffer(offer:AffiliateOffer){setSelectedOffer(offer);setOfferUnlocked(false);setTimeout(()=>document.getElementById("offer-review")?.scrollIntoView({behavior:"smooth",block:"center"}),50)}

  if(view==="destination"&&selected){const researchReady=insights?.source==="openai-web-research";return <div className="v5-app v5-destination-page"><header className="v5-nav"><button className="v5-back" onClick={()=>setView("choices")}>← {say(lang,"πίσω στις 5 επιλογές","back to 5 choices")}</button><a className="v5-logo" href="#">✦ <b>Travel Guru</b></a><nav><span>{rangeLabel(draft,lang)}</span></nav><div className="v5-lang"><button className={lang==="el"?"active":""} onClick={()=>setLang("el")}>EL</button><button className={lang==="en"?"active":""} onClick={()=>setLang("en")}>EN</button></div></header><main>
      <section className="destination-hero" style={selected.imageUrl?{backgroundImage:`linear-gradient(90deg,rgba(3,17,40,.9),rgba(3,17,40,.48)),url(${selected.imageUrl})`}:undefined}><div className="destination-story"><span className="v5-kicker">{say(lang,"Weather-screened AI choice","Weather-screened AI choice")}</span><h1>{selected.destination}</h1><p>{selected.whyThisPlace}</p><div className="destination-chips"><span>◎ {selected.distanceKm!=null?`≈ ${selected.distanceKm} km`:"—"}</span><span>★ {selected.fiveStarOfferCount} 5★</span><span>⌁ {selected.activeOfferCount} {say(lang,"offers στις ημερομηνίες","offers on dates")}</span></div><div className="why-card"><b>{say(lang,"Γιατί τώρα;","Why now?")}</b><p>{selected.whyNow}</p></div></div><div className="destination-weather-card"><WeatherMini weather={selected.weather} lang={lang}/><p>{selected.weather?.summary}</p><small>{selected.weather?.typical?say(lang,"Κλιματολογική ένδειξη — όχι μακρινή πρόγνωση.","Climate signal — not a long-range forecast."):say(lang,"Πρόγνωση μέσα σε αξιόπιστο horizon.","Forecast inside a reliable horizon.")}</small></div><aside className="live-eval"><div className="live-title"><span className="live-dot"/>AI {say(lang,"ranking","ranking")}</div><Metric label="weather" value={selected.breakdown.weather}/><Metric label={say(lang,"εποχικότητα","seasonality")} value={selected.breakdown.seasonality}/><Metric label="intent" value={selected.breakdown.intent}/><Metric label="effort" value={selected.breakdown.effort}/><Metric label="value" value={selected.breakdown.value}/></aside><aside className="compare-card"><b>{say(lang,"Σε σχέση με τις άλλες 4","Against your other 4")}</b>{comparisons.map((x,i)=><button key={x.destinationId} className={x.destinationId===selected.destinationId?"active":""} onClick={()=>void chooseDestination(x)}><span>{i+1}. {x.destination}</span><b>{x.score}% · ☀{x.weather?.score??"—"}</b></button>)}</aside></section>
      <section className="destination-body"><div className="offers-column"><div className="urgency-bar"><div><span>{say(lang,"Μόνο πραγματική λήξη feed","Verified feed expiry only")}</span><b>{countdown?say(lang,"Η κοντινότερη προσφορά λήγει σε:","Nearest offer expires in:"):say(lang,"Χωρίς επιβεβαιωμένη κοντινή λήξη","No verified near-term expiry")}</b></div>{countdown&&<div className="countdown"><span><b>{String(countdown.days).padStart(2,"0")}</b><small>D</small></span><i>:</i><span><b>{String(countdown.hours).padStart(2,"0")}</b><small>H</small></span><i>:</i><span><b>{String(countdown.minutes).padStart(2,"0")}</b><small>M</small></span></div>}</div><OfferSection title={say(lang,"5★ πρώτα — υψηλότερη feed τιμή προς χαμηλότερη","5★ first — higher feed price to lower")} offers={premiumDisplay} startRank={1} lang={lang} onReview={reviewOffer}/><OfferSection title={say(lang,"5 καλύτερες εναλλακτικές","5 strongest alternatives")} offers={alternativeDisplay} startRank={6} lang={lang} onReview={reviewOffer}/>{selectedOffer&&<section id="offer-review" className="offer-review-panel"><div className="offer-review-main"><div className="offer-review-image" style={(selectedOffer.imageUrl||selectedOffer.thumbUrl)?{backgroundImage:`url(${selectedOffer.imageUrl||selectedOffer.thumbUrl})`}:undefined}/><div><span className="v5-kicker">{say(lang,"Τελικός έλεγχος πριν το affiliate click","Final review before affiliate click")}</span><h3>{selectedOffer.propertyName}</h3><p>{selectedOffer.description}</p><div className="review-facts"><span>{priceLabel(selectedOffer,lang)}</span><span>{selectedOffer.starLevel?`${selectedOffer.starLevel}★`:"—"}</span><span>{dateLabel(selectedOffer.validTo,lang,true)}</span></div>{!offerUnlocked?<button className="unlock-button" onClick={()=>setOfferUnlocked(true)}>{say(lang,"Έλεγξα — ξεκλείδωσε το link","Reviewed — unlock link")}</button>:<div className="final-link"><div><b>{say(lang,"Τελικό βήμα","Final step")}</b><small>Linkwise tracking URL</small></div><a href={selectedOffer.trackingUrl} target="_blank" rel="sponsored nofollow">{say(lang,"Άνοιγμα προσφοράς","Open offer")} ↗</a></div>}</div></div></section>}</div><aside className="discovery-column"><div className="why-ai-panel"><span>✦ {say(lang,"Decision evidence","Decision evidence")}</span><ul><li>☀ {selected.breakdown.weather}% weather</li><li>◫ {selected.breakdown.seasonality}% seasonality</li><li>⌁ {selected.activeOfferCount} {say(lang,"offers στις ημερομηνίες","date-overlap offers")}</li><li>♡ {selected.breakdown.intent}% intent</li></ul></div>{researchReady&&insights?.overview&&<div className="research-overview"><div className="panel-title"><b>{say(lang,"Τοπική έρευνα","Local research")}</b></div><p>{insights.overview}</p></div>}</aside></section>
    </main></div>}

  return <div className="v5-app"><header className="v5-nav"><a className="v5-logo" href="#top">✦ <b>Travel Guru</b></a><nav><a href="#guide">{say(lang,"Βρες μου ταξίδι","Find my trip")}</a><span>{say(lang,"Weather-first decision AI","Weather-first decision AI")}</span></nav><div className="v5-lang"><button className={lang==="el"?"active":""} onClick={()=>setLang("el")}>EL</button><button className={lang==="en"?"active":""} onClick={()=>setLang("en")}>EN</button></div></header><main id="top"><section className="v5-hero"><div className="hero-bg hero-bg-main" style={hero(0)}/><div className="hero-bg hero-bg-side a" style={hero(1)}/><div className="hero-bg hero-bg-side b" style={hero(2)}/><div className="hero-overlay"><div className="hero-copy-v5"><span className="hero-badge">✦ {say(lang,"AI που πρώτα ελέγχει αν αξίζει να πας τότε","AI that first checks whether it is worth going then")}</span><h1>{say(lang,"Δώσε ημερομηνίες.","Give me dates.")}<br/><em>{say(lang,"Θα βρω πού αξίζει να πας.","I’ll find where it makes sense to go.")}</em></h1><p>{say(lang,"Δεν ξεκινώ από ξενοδοχεία. Ξεκινώ από τις ημερομηνίες σου, τον καιρό, την εποχικότητα και το πόσο εύκολο θέλεις να είναι το ταξίδι — και μετά ψάχνω μόνο μέσα στο affiliate inventory.","I do not start from hotels. I start from your dates, weather, seasonality and desired effort — then search only inside the affiliate inventory.")}</p><div className="proof-row"><span>✓ exact dates</span><span>✓ weather gate</span><span>✓ seasonality</span><span>✓ DeepSeek final judgement</span></div></div></div></section>
    <section className="guide-shell" id="guide"><div className="guide-card"><div className="guide-head"><div><span>✦ {say(lang,"Πότε μπορείς πραγματικά να φύγεις;","When can you actually leave?")}</span><p>{say(lang,"Το ημερολόγιο αλλάζει όλο το ranking.","The calendar changes the whole ranking.")}</p></div><em>{rangeLabel(draft,lang)}</em></div>
      <GuideRow icon="▦" question={say(lang,"Από πού και ποιες ακριβώς ημερομηνίες;","From where, and what exact dates?")} value={`${draft.origin} · ${rangeLabel(draft,lang)}`} active={open==="dates"} onClick={()=>setOpen(open==="dates"?null:"dates")}><div className="calendar-editor"><label>{say(lang,"Αναχώρηση","Departure")}<input type="date" min={isoToday()} value={draft.startDate} onChange={e=>updateDates(e.target.value,draft.endDate)}/></label><label>{say(lang,"Επιστροφή","Return")}<input type="date" min={addDays(draft.startDate,2)} max={addDays(draft.startDate,14)} value={draft.endDate} onChange={e=>updateDates(draft.startDate,e.target.value)}/></label><label>{say(lang,"Αφετηρία","Origin")}<input value={draft.origin} onChange={e=>update("origin",e.target.value)}/></label></div></GuideRow>
      <GuideRow icon="◎" question={say(lang,"Πόσο μακριά θέλεις να νιώθει;","How far should it feel?")} value={(distanceOptions.find(x=>x.value===draft.distancePreference)?.[lang==="el"?"el":"en"] as string)||""} active={open==="distance"} onClick={()=>setOpen(open==="distance"?null:"distance")}><div className="option-grid four">{distanceOptions.map(x=><button key={x.value} className={draft.distancePreference===x.value?"active":""} onClick={()=>update("distancePreference",x.value)}><b>{lang==="el"?x.el:x.en}</b><small>{lang==="el"?x.noteEl:x.noteEn}</small></button>)}</div></GuideRow>
      <GuideRow icon="☺" question={say(lang,"Τι θέλεις να σου λύσει αυτό το ταξίδι;","What should this trip solve for you?")} value={moodLabel(draft.moods,lang)} active={open==="mood"} onClick={()=>setOpen(open==="mood"?null:"mood")}><div className="option-grid four moods">{moodOptions.map(x=><button key={x.value} className={draft.moods.includes(x.value)?"active":""} onClick={()=>toggleMood(x.value)}><i>{x.icon}</i><b>{lang==="el"?x.el:x.en}</b></button>)}</div></GuideRow>
      <GuideRow icon="€" question={say(lang,"Πόσο άνετα θέλεις να κινηθείς;","How comfortable should the budget feel?")} value={`${draft.budget} ${say(lang,"budget signal","budget signal")}`} active={open==="stay"} onClick={()=>setOpen(open==="stay"?null:"stay")}><div className="chip-row">{[250,350,500,700,1000,1500].map(n=><button key={n} className={draft.budget===n?"active":""} onClick={()=>update("budget",n)}>{n}</button>)}</div></GuideRow>
      <GuideRow icon="♙" question={say(lang,"Με ποιον ταξιδεύεις;","Who are you travelling with?")} value={(travelerOptions.find(x=>x.value===draft.travelerType)?.[lang==="el"?"el":"en"] as string)||""} active={open==="people"} onClick={()=>setOpen(open==="people"?null:"people")}><div className="chip-row large">{travelerOptions.map(x=><button key={x.value} className={draft.travelerType===x.value?"active":""} onClick={()=>update("travelerType",x.value)}>{lang==="el"?x.el:x.en}</button>)}</div></GuideRow>
      <GuideRow icon="♥" question={say(lang,"Τι hotel vibe θες και τι να αποφύγω;","Hotel vibe and what should I avoid?")} value={`${hotelOptions.find(x=>x.value===draft.hotelStyle)?.[lang==="el"?"el":"en"]} · ${avoidOptions.find(x=>x.value===draft.avoid)?.[lang==="el"?"el":"en"]}`} active={open==="style"} onClick={()=>setOpen(open==="style"?null:"style")}><div className="guide-controls"><div className="chip-row">{hotelOptions.map(x=><button key={x.value} className={draft.hotelStyle===x.value?"active":""} onClick={()=>update("hotelStyle",x.value)}>{lang==="el"?x.el:x.en}</button>)}</div><div className="chip-row">{avoidOptions.map(x=><button key={x.value} className={draft.avoid===x.value?"active":""} onClick={()=>update("avoid",x.value)}>{lang==="el"?x.el:x.en}</button>)}</div></div></GuideRow>
      <button className="guide-cta" onClick={()=>void askGuru()}><span>{say(lang,"Έλεγξε καιρό και βρες τις 5 καλύτερες","Check weather & find my best 5")}</span><b>✦</b></button></div>
      <aside className="thinking-card"><div className="thinking-title"><span className="live-dot"/><b>AI {view==="thinking"?say(lang,"δουλεύει","working"):say(lang,"έτοιμο","ready")}</b><em>{view==="thinking"?"Live":"Standby"}</em></div><p>{view==="thinking"&&topThinking?stageLabel(topThinking.type):say(lang,"Inventory → exact dates → weather → seasonality → DeepSeek.","Inventory → exact dates → weather → seasonality → DeepSeek.")}</p><div className="thinking-progress"><i><b style={{width:`${view==="thinking"?thinkingProgress:12}%`}}/></i></div>{thinking.filter(x=>x.type!=="final").slice(-7).map((e,i)=><div className="thinking-stage" key={`${e.type}-${i}`}><span>{i===thinking.length-1?"◉":"✓"}</span><p>{stageLabel(e.type)}</p></div>)}{thinkingError&&<div className="thinking-error">{thinkingError}</div>}</aside></section>
      {view==="choices"&&result&&<section className="choice-section" id="choices"><div className="choice-heading"><div><span className="v5-kicker">{say(lang,"Οι 5 επιλογές που πέρασαν το weather gate","5 choices that passed the weather gate")}</span><h2>{say(lang,"Καλύτερα για αυτές τις ημερομηνίες — όχι γενικά.","Better for these dates — not in general.")}</h2></div><div><b>{result.weatherScreenedCount??5}</b><span>{say(lang,"weather-screened candidates","weather-screened candidates")}</span></div></div><div className="choice-grid">{result.recommendations.map((trip,i)=><DestinationChoice key={trip.destinationId} trip={trip} index={i} lang={lang} onChoose={()=>void chooseDestination(trip)}/>)}</div></section>}
    </main><footer className="v5-footer"><span>Travel Guru · Weather-first affiliate decision OS</span><span>{say(lang,"Exact dates → weather → seasonality → fit → DeepSeek → 5 choices","Exact dates → weather → seasonality → fit → DeepSeek → 5 choices")}</span></footer></div>
}

function GuideRow({icon,question,value,active,onClick,children}:{icon:string;question:string;value:string;active:boolean;onClick:()=>void;children:ReactNode}){return <div className={`guide-row ${active?"open":""}`}><button className="guide-row-main" onClick={onClick}><i>{icon}</i><span><small>{question}</small><b>{value}</b></span><em>{active?"−":"+"}</em></button><div className="guide-row-extra">{children}</div></div>}
function DestinationChoice({trip,index,lang,onChoose}:{trip:GuruRecommendation;index:number;lang:Lang;onChoose:()=>void}){return <article className={`choice-card ${index===0?"featured":""}`}><div className="choice-photo" style={trip.imageUrl?{backgroundImage:`linear-gradient(180deg,rgba(3,17,40,.02),rgba(3,17,40,.8)),url(${trip.imageUrl})`}:undefined}><div><span>#{index+1}</span><em>{roleLabel(trip.role,lang)}</em></div><section><small>{trip.country}</small><h3>{trip.destination}</h3></section></div><div className="choice-body"><div className="choice-score"><strong>{trip.score}%</strong><span>AI match</span><em>{confidenceLabel(trip.confidence,lang)}</em></div><WeatherMini weather={trip.weather} lang={lang}/><p>{trip.whyThisPlace}</p><div className="choice-bars"><Metric label="weather" value={trip.breakdown.weather}/><Metric label={say(lang,"season","season")} value={trip.breakdown.seasonality}/><Metric label="intent" value={trip.breakdown.intent}/><Metric label="effort" value={trip.breakdown.effort}/></div><div className="choice-stats"><span><b>{trip.activeOfferCount}</b>{say(lang,"offers τώρα","date offers")}</span><span><b>{trip.fiveStarOfferCount}</b>5★</span><span><b>{trip.distanceKm!=null?Math.round(trip.distanceKm):"—"}</b>km</span></div><button className="choose-button" onClick={onChoose}>{say(lang,"Δες γιατί αξίζει τώρα","See why it works now")} <span>→</span></button></div></article>}
function OfferSection({title,offers,startRank,lang,onReview}:{title:string;offers:AffiliateOffer[];startRank:number;lang:Lang;onReview:(o:AffiliateOffer)=>void}){return <><div className="offer-section-head"><div><span>✦ {title}</span></div><em>{offers.length} offers</em></div><div className="hotel-grid">{offers.map((o,i)=><HotelCard key={o.sourceProductId} offer={o} rank={startRank+i} lang={lang} onReview={()=>onReview(o)}/>)}</div></>}
function HotelCard({offer,rank,lang,onReview}:{offer:AffiliateOffer;rank:number;lang:Lang;onReview:()=>void}){const image=offer.imageUrl||offer.thumbUrl;return <article className="hotel-card"><div className="hotel-photo" style={image?{backgroundImage:`linear-gradient(180deg,rgba(3,17,40,.02),rgba(3,17,40,.4)),url(${image})`}:undefined}><b>{rank}</b><span>{offer.starLevel?`${offer.starLevel}★`:"stay"}</span></div><div className="hotel-copy"><small>{offer.category||"stay"}</small><h3>{offer.propertyName}</h3><div className="hotel-price"><b>{priceLabel(offer,lang)}</b>{offer.discount&&offer.discount>0?<em>-{Math.round(offer.discount)}%</em>:null}</div><p>{offer.description?.slice(0,100)}</p><div className="hotel-valid"><span>{dateLabel(offer.validTo,lang)}</span><span>live feed</span></div><button onClick={onReview}>{say(lang,"Δες λεπτομέρειες","View details")}</button></div></article>}
