"use client";

import { useMemo,useRef,useState } from "react";
import type { TripRequest,Month } from "@/lib/validation/trip";
import type { V8Recommendation,V8RecommendationResponse,V8StayOffer,V8StayResponse } from "@/lib/decision/v8-types";
import type { DestinationInsightsResponse } from "@/lib/decision/types";
import type { ContinuityEnvelope } from "@/lib/continuity";
import type { SmartDateWindow } from "@/lib/decision/date-windows-v9";

type Lang="el"|"en";type StreamEvent={type:string;progress?:number;message?:string;result?:V8RecommendationResponse;continuity?:ContinuityEnvelope;catalogSize?:number;summary?:string;checked?:number;corrected?:boolean;agreement?:string};
const say=(l:Lang,el:string,en:string)=>l==="el"?el:en;
const addDays=(iso:string,n:number)=>new Date(Date.parse(`${iso}T00:00:00Z`)+n*86400000).toISOString().slice(0,10);
const nights=(a:string,b:string)=>Math.max(2,Math.round((Date.parse(`${b}T00:00:00Z`)-Date.parse(`${a}T00:00:00Z`))/86400000));
const humanDate=(iso:string,lang:Lang)=>new Intl.DateTimeFormat(lang==="el"?"el-GR":"en-GB",{day:"numeric",month:"short"}).format(new Date(`${iso}T12:00:00Z`));
const month=(iso:string):Month=>Number(iso.slice(5,7))===9?"september":Number(iso.slice(5,7))===10?"october":Number(iso.slice(5,7))===11?"november":"flexible";
const defaultTrip:TripRequest={origin:"Athens",startDate:"2026-10-16",endDate:"2026-10-19",month:"october",nights:3,budget:500,moods:["romantic","food"],travelerType:"couple",language:"el",distancePreference:"easy-hop",pace:"balanced",hotelStyle:"boutique",avoid:"long-travel"};
const moods=[
 {v:"relax",i:"◌",el:"Ηρεμία",en:"Switch off"},{v:"romantic",i:"♡",el:"Ρομαντικό",en:"Romantic"},{v:"food",i:"✦",el:"Καλό φαγητό",en:"Great food"},{v:"culture",i:"◇",el:"Πολιτισμός",en:"Culture"},
 {v:"city",i:"▦",el:"Πόλη",en:"City"},{v:"nature",i:"⌁",el:"Φύση",en:"Nature"},{v:"adventure",i:"↗",el:"Περιπέτεια",en:"Adventure"},{v:"warmth",i:"☀",el:"Ζέστη / θάλασσα",en:"Warm / sea"}
] as const;
const stageLabels:Record<string,[string,string]>={
 "understand:start":["Καταλαβαίνω τι χρειάζεσαι από αυτό το ταξίδι","Understanding what you need from this trip"],"understand:ready":["Το προσωπικό σου ταξιδιωτικό brief είναι έτοιμο","Your personal travel brief is ready"],"catalog:start":["Ανοίγω τον χάρτη των πιθανών επιλογών","Opening the map of possible choices"],"catalog:ready":["Συγκρίνω Ελλάδα και εξωτερικό","Comparing Greece and abroad"],"shortlist:ready":["Κρατάω μόνο τις επιλογές που αξίζουν πραγματικά","Keeping only choices that genuinely fit"],"weather:start":["Ελέγχω εποχή και καιρό στις δυνατές επιλογές","Checking season and weather for the strongest options"],"weather:ready":["Ο έλεγχος της περιόδου ολοκληρώθηκε","The timing check is complete"],"verify:start":["Ο δύσκολος ελεγκτής ψάχνει αδύναμα σημεία","The skeptical editor is looking for weak points"],"verify:ready":["Οι αδύναμες επιλογές αποκλείστηκαν","Weak choices have been removed"],"council:start":["Δύο ανεξάρτητες φωνές καταλήγουν στην απόφαση","Two independent voices are reaching a decision"],"council:ready":["Το συμβούλιο κατέληξε","The council has reached its verdict"]
};

export function TravelDecisionExperience(){
 const[lang,setLang]=useState<Lang>("el"),[trip,setTrip]=useState<TripRequest>(defaultTrip),[loading,setLoading]=useState(false),[events,setEvents]=useState<StreamEvent[]>([]),[error,setError]=useState<string|null>(null),[result,setResult]=useState<V8RecommendationResponse|null>(null),[selected,setSelected]=useState<V8Recommendation|null>(null),[stayData,setStayData]=useState<V8StayResponse|null>(null),[insights,setInsights]=useState<DestinationInsightsResponse|null>(null),[stayLoading,setStayLoading]=useState(false);const running=useRef(false),controller=useRef<AbortController|null>(null);
 const activeStage=events[events.length-1];
 const stayOffers=useMemo(()=>{const rows=[...(stayData?.offers??[])];const style=trip.hotelStyle;return rows.sort((a,b)=>{const sa=offerScore(a,style),sb=offerScore(b,style);return sb-sa}).slice(0,3)},[stayData,trip.hotelStyle]);
 function patch<K extends keyof TripRequest>(k:K,v:TripRequest[K]){setTrip(t=>({...t,[k]:v}))}
 function dates(start:string,end:string){let e=end;if(!e||Date.parse(e)<=Date.parse(start))e=addDays(start,3);setTrip(t=>({...t,startDate:start,endDate:e,nights:nights(start,e),month:month(start)}))}
 function toggleMood(v:TripRequest["moods"][number]){setTrip(t=>{const has=t.moods.includes(v),next=has?t.moods.filter(x=>x!==v):[...t.moods,v].slice(-3);return next.length?{...t,moods:next}:t})}
 function label(type:string){return stageLabels[type]?.[lang==="el"?0:1]??type}
 async function run(){if(running.current)return;running.current=true;setLoading(true);setError(null);setResult(null);setSelected(null);setStayData(null);setInsights(null);setEvents([]);const c=new AbortController();controller.current=c;let final=false;
  try{const r=await fetch("/api/recommend/stream",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...trip,language:lang}),signal:c.signal});if(!r.ok||!r.body)throw new Error();const reader=r.body.getReader(),decoder=new TextDecoder();let buf="";while(true){const{done,value}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const lines=buf.split("\n");buf=lines.pop()??"";for(const line of lines){if(!line.trim())continue;const ev=JSON.parse(line) as StreamEvent;if(ev.type==="continuity"){setError(ev.continuity?.message[lang]||ev.message||say(lang,"Οι επιλογές σου έχουν κρατηθεί. Δοκίμασε ξανά σε λίγο.","Your choices are saved. Try again in a moment."));await reader.cancel();break}if(ev.type==="final"&&ev.result){final=true;setResult(ev.result);setTrip(ev.result.request);await reader.cancel();break}setEvents(prev=>[...prev.filter(x=>x.type!==ev.type),ev].slice(-6));}if(final)break}if(!final&&!c.signal.aborted)throw new Error();}
  catch(e){if((e as Error)?.name!=="AbortError")setError(say(lang,"Δεν μπόρεσα ακόμη να επιβεβαιώσω με ασφάλεια όλες τις λεπτομέρειες. Οι επιλογές σου έχουν κρατηθεί· δοκίμασε ξανά σε λίγο.","I couldn't safely verify every detail yet. Your choices are saved—try again in a moment."))}finally{running.current=false;controller.current=null;setLoading(false)}
 }
 async function loadDestination(r:V8Recommendation,startDate:string,endDate:string,includeInsights:boolean){setStayLoading(true);try{const staysUrl=new URL("/api/destination-detail",window.location.origin);staysUrl.searchParams.set("slug",r.slug);staysUrl.searchParams.set("start_date",startDate);staysUrl.searchParams.set("end_date",endDate);const tasks:Promise<Response>[]=[fetch(staysUrl)];if(includeInsights){const insightUrl=new URL("/api/destination-insights",window.location.origin);insightUrl.searchParams.set("destination",r.destination);insightUrl.searchParams.set("lat",String(r.latitude));insightUrl.searchParams.set("lon",String(r.longitude));insightUrl.searchParams.set("lang",lang);insightUrl.searchParams.set("traveler",trip.travelerType);insightUrl.searchParams.set("moods",trip.moods.join(","));insightUrl.searchParams.set("nights",String(nights(startDate,endDate)));tasks.push(fetch(insightUrl))}const responses=await Promise.allSettled(tasks);const stayRes=responses[0];if(stayRes.status==="fulfilled"&&stayRes.value.ok)setStayData(await stayRes.value.json() as V8StayResponse);if(includeInsights){const insightRes=responses[1];if(insightRes?.status==="fulfilled"&&insightRes.value.ok)setInsights(await insightRes.value.json() as DestinationInsightsResponse)}}finally{setStayLoading(false)}}
 async function choose(r:V8Recommendation){setSelected(r);setStayData(null);setInsights(null);setTimeout(()=>document.getElementById("destination-detail")?.scrollIntoView({behavior:"smooth",block:"start"}),50);await loadDestination(r,trip.startDate,trip.endDate,true)}
 function selectWindow(window:SmartDateWindow){dates(window.startDate,window.endDate);if(selected)void loadDestination(selected,window.startDate,window.endDate,false)}
 return <div className="v8-site">
  <header className="v8-nav"><a href="#top" className="v8-brand">TRAVEL <em>GURU</em><small>Your travel decision team</small></a><div className="v8-nav-proof">{say(lang,"Πρώτα η σωστή απόφαση. Μετά οι λεπτομέρειες.","The right decision first. Details second.")}</div><div className="v8-lang"><button className={lang==="el"?"on":""} onClick={()=>setLang("el")}>EL</button><button className={lang==="en"?"on":""} onClick={()=>setLang("en")}>EN</button></div></header>
  <main id="top">
   <section className="v8-hero"><div className="v8-hero-copy"><span className="v8-kicker">✦ Your personal travel council</span><h1>{say(lang,"Δεν ψάχνεις άλλες λίστες.","You don't need another list.")}<br/><em>{say(lang,"Χρειάζεσαι τη σωστή απόφαση.","You need the right decision.")}</em></h1><p>{say(lang,"Μια μικρή ομάδα ταξιδιωτικών συμβούλων καταλαβαίνει τον σκοπό σου, αποκλείει ό,τι δεν στέκει για τις ημερομηνίες και το budget σου και υπερασπίζεται μόνο τις επιλογές που αξίζουν.","A small team of travel advisers understands your purpose, removes what doesn't fit your dates and budget, and defends only the choices worth taking.")}</p><div className="v8-proof"><span>{say(lang,"Διαφορετικές οπτικές","Independent perspectives")}</span><span>{say(lang,"Έλεγχος περιόδου","Timing checked")}</span><span>{say(lang,"Καμία κρυφή προώθηση","No hidden influence")}</span></div></div><div className="v8-photo-stack"><div style={{backgroundImage:"url('/api/destination-photo?name=Rome&lang=en')"}}/><div style={{backgroundImage:"url('/api/destination-photo?name=Chania&lang=en')"}}/><div style={{backgroundImage:"url('/api/destination-photo?name=Budapest&lang=en')"}}/><b>5<br/><small>{say(lang,"διαφορετικά ταξίδια","different journeys")}</small></b></div></section>

   <section className="v8-planner"><div className="v8-planner-head"><div><span className="v8-kicker">01 — {say(lang,"Πες μου τα βασικά","Tell me the basics")}</span><h2>{say(lang,"Ένα λεπτό. Καμία ατελείωτη φόρμα.","One minute. No endless form.")}</h2></div><span>{trip.nights} {say(lang,"νύχτες","nights")} · €{trip.budget}</span></div>
    <div className="v8-form-grid">
     <Field title={say(lang,"Από πού;","From where?")}><div className="v8-pills"><Pill on={trip.origin==="Athens"} onClick={()=>patch("origin","Athens")}>Athens</Pill><Pill on={trip.origin==="Thessaloniki"} onClick={()=>patch("origin","Thessaloniki")}>Thessaloniki</Pill></div></Field>
     <Field title={say(lang,"Πότε;","When?")}><div className="v8-dates"><input type="date" min="2026-08-08" value={trip.startDate} onChange={e=>dates(e.target.value,trip.endDate)}/><span>→</span><input type="date" min={addDays(trip.startDate,2)} value={trip.endDate} onChange={e=>dates(trip.startDate,e.target.value)}/></div></Field>
     <Field title={say(lang,"Με ποιον;","With whom?")}><div className="v8-pills">{([['solo','Solo'],['couple',say(lang,'Ζευγάρι','Couple')],['family',say(lang,'Οικογένεια','Family')],['friends',say(lang,'Παρέα','Friends')]] as const).map(([v,t])=><Pill key={v} on={trip.travelerType===v} onClick={()=>patch("travelerType",v)}>{t}</Pill>)}</div></Field>
     <Field title={say(lang,"Συνολικό budget signal","Total budget signal")}><div className="v8-pills">{[300,450,600,800,1200].map(v=><Pill key={v} on={trip.budget===v} onClick={()=>patch("budget",v)}>€{v}</Pill>)}</div></Field>
    </div>
    <div className="v8-divider"/>
    <div className="v8-question"><span className="v8-kicker">02 — {say(lang,"Τι θέλεις να σου δώσει αυτό το ταξίδι;","What should this trip give you?")}</span><p>{say(lang,"Διάλεξε έως 3.","Choose up to 3.")}</p><div className="v8-moods">{moods.map(m=><button key={m.v} className={trip.moods.includes(m.v)?"on":""} onClick={()=>toggleMood(m.v)}><i>{m.i}</i><span>{lang==="el"?m.el:m.en}</span></button>)}</div></div>
    <div className="v8-form-grid v8-secondary">
     <Field title={say(lang,"Πόση μετακίνηση;","How much travel effort?")}><div className="v8-pills">{([['nearby',say(lang,'Κοντά','Nearby')],['easy-hop',say(lang,'Εύκολο hop','Easy hop')],['any',say(lang,'Όπου αξίζει','Wherever fits')],['island',say(lang,'Νησιωτικό','Island feel')]] as const).map(([v,t])=><Pill key={v} on={trip.distancePreference===v} onClick={()=>patch("distancePreference",v)}>{t}</Pill>)}</div></Field>
     <Field title={say(lang,"Τι να αποφύγω;","What should I avoid?")}><div className="v8-pills">{([['long-travel',say(lang,'Ταλαιπωρία','Long travel')],['high-cost',say(lang,'Υψηλό κόστος','High cost')],['crowds',say(lang,'Πολύ κόσμο','Crowds')],['none',say(lang,'Τίποτα','Nothing')]] as const).map(([v,t])=><Pill key={v} on={trip.avoid===v} onClick={()=>patch("avoid",v)}>{t}</Pill>)}</div></Field>
     <Field title={say(lang,"Stay style — δεν αλλάζει τον προορισμό","Stay style — does not choose destination")}><div className="v8-pills">{([['boutique','Boutique'],['luxury','5★ / luxury'],['value',say(lang,'Value','Value')],['resort','Resort'],['any',say(lang,'Οτιδήποτε','Any')]] as const).map(([v,t])=><Pill key={v} on={trip.hotelStyle===v} onClick={()=>patch("hotelStyle",v)}>{t}</Pill>)}</div></Field>
     <Field title={say(lang,"Πες το με δικά σου λόγια — προαιρετικό","Say it in your own words — optional")}><textarea value={trip.tripText??""} maxLength={320} placeholder={say(lang,"π.χ. θέλω ήσυχα, καλό φαγητό, όχι τουριστίλα και να μη λιώσω στη μετακίνηση","e.g. quiet, great food, not too touristy, and easy to reach")} onChange={e=>patch("tripText",e.target.value)}/></Field>
    </div>
    <button className="v8-run" disabled={loading} onClick={()=>void run()}><span>{loading?say(lang,"Ψάχνω τα σωστά 5…","Finding the right five…"):say(lang,"Βρες μου τα σωστά 5","Find my right five")}</span><b>{loading?"◉":"→"}</b></button>{error&&<div className="v8-error">{error}</div>}
   </section>

   {loading&&<section className="v8-processing"><div className="v8-orbit"><span/><span/><span/><b>✦</b></div><div><span className="v8-kicker">{say(lang,"Το συμβούλιό σου δουλεύει","Your council is working")}</span><h2>{activeStage?label(activeStage.type):say(lang,"Καταλαβαίνω το ταξίδι…","Understanding your trip…")}</h2><div className="v8-stage-list">{events.filter(e=>e.type!=="final").slice(-5).map((e,i)=><div key={e.type}><span>{i===events.filter(x=>x.type!=="final").slice(-5).length-1?"◉":"✓"}</span>{label(e.type)}</div>)}</div><p>{say(lang,"Κάθε επιλογή πρέπει να επιβιώσει από τον έλεγχο σκοπού, εποχής, μετακίνησης και κόστους.","Every option must survive purpose, timing, travel-effort and cost checks.")}</p></div></section>}

   {result&&<section className="v8-results"><div className="v8-results-head"><div><span className="v8-kicker">03 — {say(lang,"Οι 5 αποφάσεις που άντεξαν","The five choices that survived")}</span><h2>{say(lang,"Πέντε διαφορετικοί τρόποι να πετύχει αυτό το ταξίδι.","Five different ways this trip can work.")}</h2></div><div className="v8-result-meta"><span>{say(lang,"Εποχή ελεγμένη","Timing checked")}</span><span>{say(lang,"Διαφορετικοί χαρακτήρες","Different personalities")}</span><span>{result.council?.agreement==="STRONG"?say(lang,"Ισχυρή συμφωνία","Strong agreement"):say(lang,"Ισορροπημένη απόφαση","Balanced verdict")}</span></div></div><div className="v8-card-grid">{result.recommendations.map((r,i)=><ResultCard key={r.slug} r={r} i={i} lang={lang} onClick={()=>void choose(r)}/>)}</div></section>}

   {selected&&<section id="destination-detail" className="v8-detail">
    <div className="v8-detail-hero"><div className="v8-detail-photo" style={{backgroundImage:`linear-gradient(90deg,rgba(14,28,22,.08),rgba(14,28,22,.58)),url('/api/destination-photo?name=${encodeURIComponent(selected.destinationEn)}&lang=en')`}}/><div className="v8-detail-copy"><span className="v8-kicker">{say(lang,"Η μεγάλη αποκάλυψη","The reveal")}</span><h2>{selected.destination}</h2><p>{insights?.overview||selected.why}</p><div className="v8-detail-facts"><span>{selected.effortLabel}</span><span>{selected.budgetLabel}</span><span>{selected.confidence==="HIGH"?say(lang,"Ισχυρή βεβαιότητα","Strong confidence"):say(lang,"Καλή βεβαιότητα","Good confidence")}</span>{selected.weather?.temperatureMeanC!=null&&<span>{Math.round(selected.weather.temperatureMeanC)}° {say(lang,"τυπικά","typical")}</span>}</div></div></div>

    {result?.council&&<div className="v9-council"><div className="v9-section-head"><span className="v8-kicker">04 — {say(lang,"Η απόφαση του συμβουλίου","The council verdict")}</span><h3>{say(lang,"Δύο ανεξάρτητες φωνές. Μία καθαρή επιλογή.","Two independent voices. One clear choice.")}</h3></div><div className="v9-voices">{result.council.voices.map(voice=><article key={voice.role}><span>{lang==="el"?voice.titleEl:voice.titleEn}</span><p>{voice.verdict}</p><b>{voice.pickSlug===selected.slug?"✓ ":""}{voice.confidence==="HIGH"?say(lang,"Ισχυρή θέση","Strong view"):say(lang,"Μετρημένη θέση","Measured view")}</b></article>)}</div></div>}

    <div className="v9-dates"><div className="v9-section-head"><span className="v8-kicker">05 — {say(lang,"Πότε αξίζει περισσότερο","When it works best")}</span><h3>{say(lang,"Τρία παράθυρα, με καθαρό συμβιβασμό.","Three windows, each with a clear trade-off.")}</h3></div><div className="v9-date-grid">{(selected.dateWindows??[]).map((window,index)=><button type="button" key={window.id} className={trip.startDate===window.startDate&&trip.endDate===window.endDate?"on":""} onClick={()=>selectWindow(window)}><span>{index===0?say(lang,"Προτεινόμενο","Recommended"):say(lang,"Εναλλακτική","Alternative")}</span><strong>{humanDate(window.startDate,lang)} → {humanDate(window.endDate,lang)}</strong><b>{lang==="el"?window.titleEl:window.titleEn}</b><p>{lang==="el"?window.tradeoffEl:window.tradeoffEn}</p></button>)}</div></div>

    <div className="v9-story"><div className="v9-section-head"><span className="v8-kicker">06 — {say(lang,"Το ταξίδι σε 90 δευτερόλεπτα","Your trip in 90 seconds")}</span><h3>{say(lang,"Να πώς θα το νιώσεις.","This is how it could feel.")}</h3></div>{insights?.attractions.length||insights?.restaurants.length?<div className="v9-story-grid"><StoryBeat number="01" title={say(lang,"Φτάνεις και κατεβάζεις ρυθμό","Arrive and change pace")} text={insights?.practicalNotes[0]||selected.effortLabel}/><StoryBeat number="02" title={insights?.attractions[0]?.name||say(lang,"Η signature στιγμή","The signature moment")} text={insights?.attractions[0]?.whyItFits||insights?.attractions[0]?.summary||selected.seasonNote}/><StoryBeat number="03" title={insights?.restaurants[0]?.name||say(lang,"Η γεύση του τόπου","A taste of the place")} text={insights?.restaurants[0]?.whyItFits||insights?.restaurants[0]?.summary||say(lang,"Χρόνος για τοπική ζωή και φαγητό χωρίς βιασύνη.","Time for local life and food without rushing.")}/></div>:<div className="v9-research-pending">{stayLoading?say(lang,"Χτίζω την προσωπική ιστορία του ταξιδιού σου…","Building your personal trip story…"):say(lang,"Σου δείχνω μόνο όσα μπόρεσα να επιβεβαιώσω. Η βασική επιλογή παραμένει ασφαλής.","I am showing only what I could verify. The core choice remains safe.")}</div>}</div>

    <div className="v8-stay-head"><div><span className="v8-kicker">07 — {say(lang,"Πού θα μείνεις","Where to stay")}</span><h3>{say(lang,"Μία κύρια επιλογή και δύο εναλλακτικές.","One main choice and two alternatives.")}</h3></div><p>{say(lang,"Οι παρακάτω επιλογές ταιριάζουν στην περιοχή και στις ημερομηνίες σου. Η τελική τιμή και το διαθέσιμο δωμάτιο επιβεβαιώνονται πριν προχωρήσεις.","These choices fit your area and dates. Final price and room availability are confirmed before you continue.")}</p></div>{stayLoading?<div className="v8-stay-loading">◉ {say(lang,"Επιβεβαιώνω τις καλύτερες επιλογές…","Confirming the best options…")}</div>:stayOffers.length?<div className="v8-stays">{stayOffers.map((o,i)=><StayCard key={o.sourceProductId} offer={o} lang={lang} primary={i===0}/>)}</div>:<div className="v8-no-stays"><b>{say(lang,"Δεν υπάρχει ακόμη επιλογή διαμονής που να μπορώ να σου δείξω με βεβαιότητα.","There isn't a stay option I can show with confidence yet.")}</b><p>{say(lang,"Η επιλογή προορισμού παραμένει έγκυρη. Μπορείς να κρατήσεις το σχέδιο και να επανέλθεις.","The destination decision remains valid. You can keep the plan and return later.")}</p></div>}
   </section>}
  </main><footer className="v8-footer">Travel Guru · Understand → challenge → decide → experience → stay</footer>
 </div>
}

function Field({title,children}:{title:string;children:React.ReactNode}){return <div className="v8-field"><label>{title}</label>{children}</div>}
function Pill({on,onClick,children}:{on:boolean;onClick:()=>void;children:React.ReactNode}){return <button type="button" className={on?"on":""} onClick={onClick}>{children}</button>}
function ResultCard({r,i,lang,onClick}:{r:V8Recommendation;i:number;lang:Lang;onClick:()=>void}){const character=i===0?say(lang,"Η επιλογή του συμβουλίου","The council choice"):r.role==="EASIEST"?say(lang,"Η πιο εύκολη","The easiest"):r.role==="SMART VALUE"?say(lang,"Η έξυπνη αξία","The smart-value choice"):r.role==="ROMANTIC"?say(lang,"Η ρομαντική","The romantic one"):say(lang,"Η διαφορετική οπτική","The different perspective");return <article className={`v8-result-card ${i===0?"featured":""}`}><div className="v8-result-photo" style={{backgroundImage:`linear-gradient(180deg,rgba(13,27,21,.02),rgba(13,27,21,.68)),url('/api/destination-photo?name=${encodeURIComponent(r.destinationEn)}&lang=en')`}}><div><span>#{i+1}</span><b>{character}</b></div><section><small>{r.country}</small><h3>{r.destination}</h3></section></div><div className="v8-result-body"><div className="v9-confidence"><span>{r.confidence==="HIGH"?say(lang,"Ισχυρή βεβαιότητα","Strong confidence"):say(lang,"Καλή βεβαιότητα","Good confidence")}</span><i>{say(lang,"Πέρασε όλους τους ελέγχους","Passed every check")}</i></div><p>{r.why}</p><div className="v8-card-notes"><span>⌁ {r.effortLabel}</span><span>€ {r.budgetLabel}</span>{r.weather?.temperatureMeanC!=null&&<span>☀ {Math.round(r.weather.temperatureMeanC)}° {say(lang,"τυπικά","typical")}</span>}</div><button onClick={onClick}>{say(lang,"Δείξε μου γιατί","Show me why")} <b>→</b></button></div></article>}
function StoryBeat({number,title,text}:{number:string;title:string;text:string}){return <article><span>{number}</span><h4>{title}</h4><p>{text}</p></article>}
function offerScore(o:V8StayOffer,style:TripRequest["hotelStyle"]){let s=100-(o.distanceKm??20);if(style==="luxury")s+=(o.starLevel??0)*12;if(style==="value"&&o.price!=null)s+=Math.max(0,80-o.price)/3;if(style==="boutique"&&/boutique|design/i.test(`${o.propertyName} ${o.description??""}`))s+=25;if(style==="resort"&&/resort|spa|all inclusive/i.test(`${o.propertyName} ${o.description??""}`))s+=25;s+=Math.min(15,(o.discount??0)/2);return s}
function StayCard({offer,lang,primary}:{offer:V8StayOffer;lang:Lang;primary:boolean}){const image=offer.imageUrl||offer.thumbUrl;return <article className={`v8-stay ${primary?"primary":""}`}><div className="v8-stay-photo" style={image?{backgroundImage:`url(${image})`}:undefined}><span>{primary?say(lang,"Κύρια επιλογή","Main choice"):offer.distanceKm!=null?`${offer.distanceKm.toFixed(1)} km`:say(lang,"Εναλλακτική","Alternative")}</span></div><div><small>{offer.city||say(lang,"Προτεινόμενη περιοχή","Recommended area")}</small><h4>{offer.propertyName}</h4><p>{offer.description?.slice(0,120)}</p><div className="v8-stay-facts">{offer.price!=null&&offer.currency&&<span>{offer.currency} {Math.round(offer.price)} <small>{say(lang,"ενδεικτική τιμή","indicative price")}</small></span>}{offer.starLevel&&<span>{offer.starLevel}★</span>}</div><a href={offer.trackingUrl} target="_blank" rel="sponsored nofollow noopener noreferrer">{say(lang,"Έλεγξε τιμή και διαθεσιμότητα","Check price and availability")} ↗</a></div></article>}
