import { V31PageFrame } from "@/components/v31-site-shell";

type Lang="el"|"en";
const say=(lang:Lang,el:string,en:string)=>lang==="el"?el:en;

export function V31NativeHome({lang="el"}:{lang?:Lang}){
 const prefix=lang==="en"?"/en":"",destinations=lang==="en"?"/en/destinations":"/proorismoi";
 const apps=[
  {n:"01",title:say(lang,"AI Σύμβουλος","AI Planner"),text:say(lang,"Δώσε πόλη, ημερομηνίες, budget και τρόπο ταξιδιού. Πάρε audited shortlist.","Give a city, dates, budget and travel style. Get an audited shortlist."),href:`${prefix}/ai-planner`,tag:"DECIDE"},
  {n:"02",title:say(lang,"Χάρτης Διαμονών","Stay Map"),text:say(lang,"Δες πραγματικά καταλύματα και offers ως markers τιμής πάνω στον χάρτη.","See real stays and offers as price markers directly on the map."),href:`${prefix}/stays-map`,tag:"PRODUCT MAP"},
  {n:"03",title:say(lang,"AI Χάρτης Ελλάδας","AI Greece Map"),text:say(lang,"Σύγκρινε προορισμούς με season fit, πρόσβαση, supply και trusted evidence.","Compare destinations by season fit, access, supply and trusted evidence."),href:`${prefix}/ai-map`,tag:"RANK"},
  {n:"04",title:say(lang,"Προορισμοί","Destinations"),text:say(lang,"Μπες σε ξεχωριστές σελίδες προορισμών — όχι σε μία ατελείωτη homepage.","Open dedicated destination pages instead of one endless homepage."),href:destinations,tag:"EXPLORE"},
  {n:"05",title:say(lang,"Ανά εποχή","Seasonal"),text:say(lang,"Δες πού έχει νόημα να πας ανά μήνα και τύπο ταξιδιού.","See where it makes sense to go by month and trip type."),href:`${prefix}/seasonal`,tag:"WHEN"},
  {n:"06",title:say(lang,"Οδηγοί","Guides"),text:say(lang,"Πρακτικοί οδηγοί για αποφάσεις, μετακινήσεις, διαμονή και planning.","Practical guides for decisions, transport, stays and planning."),href:`${prefix}/guides`,tag:"LEARN"}
 ];
 return <V31PageFrame lang={lang}>
  <section className="v32-home-hero">
   <div className="wf-shell v32-home-hero__grid">
    <div><span className="wf-kicker">AI GREECE TRAVEL · CONTROL CENTER</span><h1>{say(lang,"Μία πλατφόρμα. Πολλές πραγματικές σελίδες.","One platform. Multiple real pages.")}</h1><p>{say(lang,"Σχεδίασε το ταξίδι, σύγκρινε προορισμούς και άνοιξε πραγματικά προϊόντα διαμονής επάνω στον χάρτη — χωρίς να ψάχνεις μέσα σε μία τεράστια landing page.","Plan the trip, compare destinations and open real accommodation products on the map — without hunting through one giant landing page.")}</p><div className="v32-home-actions"><a className="wf-btn wf-btn--primary" href={`${prefix}/ai-planner`}>{say(lang,"Ξεκίνα με AI →","Start with AI →")}</a><a className="wf-btn wf-btn--secondary" href={`${prefix}/stays-map`}>{say(lang,"Άνοιξε τον χάρτη προϊόντων","Open product map")}</a></div></div>
    <a className="v32-map-teaser" href={`${prefix}/stays-map`}><div className="v32-map-teaser__grid" aria-hidden="true"><span className="v32-pin p1">€89</span><span className="v32-pin p2">€124</span><span className="v32-pin p3">€176</span><span className="v32-pin p4">€98</span></div><div><span>LIVE STAY INVENTORY</span><strong>{say(lang,"Τα προϊόντα σου πάνω στον χάρτη →","Your products on the map →")}</strong><small>{say(lang,"Google Maps όταν υπάρχει key · OpenStreetMap fallback πάντα διαθέσιμο","Google Maps when configured · OpenStreetMap fallback always available")}</small></div></a>
   </div>
  </section>

  <section className="wf-section v32-app-section"><div className="wf-shell"><div className="v32-section-head"><div><span className="wf-kicker">CHOOSE A TOOL</span><h2 className="wf-h2">{say(lang,"Τι θέλεις να κάνεις τώρα;","What do you want to do now?")}</h2></div><p>{say(lang,"Κάθε λειτουργία έχει πλέον δικό της route, δική της οθόνη και σαφή δουλειά.","Every function now has its own route, screen and clear job.")}</p></div><div className="v32-app-grid">{apps.map(app=><a className="v32-app-card" href={app.href} key={app.n}><span className="v32-app-card__n">{app.n}</span><span className="wf-kicker">{app.tag}</span><h3>{app.title}</h3><p>{app.text}</p><b>{say(lang,"Άνοιγμα →","Open →")}</b></a>)}</div></div></section>

  <section className="wf-section wf-paper-section"><div className="wf-shell v32-two-maps"><div><span className="wf-kicker">TWO MAPS · TWO JOBS</span><h2 className="wf-h2">{say(lang,"Μην μπερδεύουμε προορισμούς με προϊόντα.","Do not mix destinations with products.")}</h2><p className="wf-lead">{say(lang,"Ο AI Χάρτης κατατάσσει πόλεις και νησιά. Ο Χάρτης Διαμονών δείχνει τα πραγματικά offers σου στο ακριβές σημείο τους.","The AI Map ranks cities and islands. The Stay Map plots your real offers at their actual locations.")}</p></div><div className="v32-map-choice"><a href={`${prefix}/ai-map`}><span>AI DESTINATION MAP</span><strong>{say(lang,"Ποιος προορισμός ταιριάζει;","Which destination fits?")}</strong><small>{say(lang,"AI score · season · access · evidence","AI score · season · access · evidence")}</small></a><a href={`${prefix}/stays-map`}><span>PRODUCT / STAY MAP</span><strong>{say(lang,"Πού είναι τα προϊόντα και πόσο κοστίζουν;","Where are the products and what do they cost?")}</strong><small>{say(lang,"Marker τιμής · offer · image · booking CTA","Price marker · offer · image · booking CTA")}</small></a></div></div></section>

  <section className="wf-section"><div className="wf-shell wf-trust"><div><span className="wf-kicker">AI THAT RESPECTS LOCATION</span><h2 className="wf-h2">{say(lang,"Πρώτα η σωστή πόλη. Μετά η καλύτερη επιλογή.","Right city first. Best option second.")}</h2><p className="wf-lead">{say(lang,"Αν δώσεις συγκεκριμένη πόλη ή νησί, το location scope παραμένει hard constraint πριν από ranking και recommendations.","When you give a specific city or island, location scope remains a hard constraint before ranking and recommendations.")}</p></div><div className="wf-trust__list"><div className="wf-trust__item"><strong>01 · Location truth</strong><p className="wf-body">{say(lang,"Δεν αλλάζει κρυφά πόλη επειδή ένα άλλο μέρος έχει υψηλότερο score.","It does not silently switch cities because another place scores higher.")}</p></div><div className="wf-trust__item"><strong>02 · Real inventory markers</strong><p className="wf-body">{say(lang,"Τα pins του Stay Map προέρχονται από προϊόντα με πραγματικές συντεταγμένες και tracking URLs.","Stay Map pins come from products with real coordinates and tracking URLs.")}</p></div><div className="wf-trust__item"><strong>03 · Fail-safe maps</strong><p className="wf-body">{say(lang,"Αν το Google Maps key δεν είναι διαθέσιμο, ο χάρτης συνεχίζει με OpenStreetMap αντί να σπάει.","If a Google Maps key is unavailable, the map continues with OpenStreetMap instead of breaking.")}</p></div></div></div></section>
 </V31PageFrame>
}
