import { V31PageFrame } from "@/components/v31-site-shell";

type Lang="el"|"en";
const say=(lang:Lang,el:string,en:string)=>lang==="el"?el:en;

export function V31NativeHome({lang="el"}:{lang?:Lang}){
 const prefix=lang==="en"?"/en":"",destinations=lang==="en"?"/en/destinations":"/proorismoi";
 const apps=[
  {n:"01",title:say(lang,"Βρες την απόδρασή σου","Find your escape"),text:say(lang,"Ξεκίνα από το πότε μπορείς να φύγεις και τι χρειάζεσαι να νιώσεις. Το AI χτίζει το Escape DNA και περιορίζει τις επιλογές.","Start with when you can leave and how you want the break to feel. AI builds your Escape DNA and narrows the world."),href:lang==="en"?"/en/ai-planner":"/escape",tag:"MISSION"},
  {n:"02",title:say(lang,"AI Σύμβουλος","AI Planner"),text:say(lang,"Δώσε πόλη, ημερομηνίες, budget και τρόπο ταξιδιού. Πάρε audited shortlist.","Give a city, dates, budget and travel style. Get an audited shortlist."),href:`${prefix}/ai-planner`,tag:"DECIDE"},
  {n:"03",title:say(lang,"Χάρτης Διαμονών","Stay Map"),text:say(lang,"Δες πραγματικά καταλύματα και offers ως markers τιμής πάνω στον χάρτη.","See real stays and offers as price markers directly on the map."),href:`${prefix}/stays-map`,tag:"PRODUCT MAP"},
  {n:"04",title:say(lang,"AI Χάρτης Ελλάδας","AI Greece Map"),text:say(lang,"Σύγκρινε προορισμούς με season fit, πρόσβαση, supply και trusted evidence.","Compare destinations by season fit, access, supply and trusted evidence."),href:`${prefix}/ai-map`,tag:"RANK"},
  {n:"05",title:say(lang,"Προορισμοί","Destinations"),text:say(lang,"Μπες σε ξεχωριστές σελίδες προορισμών — όχι σε μία ατελείωτη homepage.","Open dedicated destination pages instead of one endless homepage."),href:destinations,tag:"EXPLORE"},
  {n:"06",title:say(lang,"Ανά εποχή","Seasonal"),text:say(lang,"Δες πού έχει νόημα να πας ανά μήνα και τύπο ταξιδιού.","See where it makes sense to go by month and trip type."),href:`${prefix}/seasonal`,tag:"WHEN"}
 ];
 return <V31PageFrame lang={lang}>
  <section className="v32-home-hero">
   <div className="wf-shell v32-home-hero__grid">
    <div><span className="wf-kicker">AI HOLIDAY MISSION CONTROL</span><h1>{say(lang,"Χρειάζεσαι μια απόδραση. Δεν χρειάζεται να ξέρεις ακόμη πού.","You need a break. You do not need to know where yet.")}</h1><p>{say(lang,"Ξεκίνα από τον χρόνο που έχεις και από το πώς θέλεις να νιώσεις. Το AI συγκρίνει εποχή, budget, πρόσβαση και πραγματικές επιλογές και μετά χτίζει την απόδραση γύρω από εσένα.","Start with the time you have and how you want to feel. AI compares season, budget, access and real options, then builds the escape around you.")}</p><div className="v32-home-actions"><a className="wf-btn wf-btn--primary" href={lang==="en"?"/en/ai-planner":"/escape"}>{say(lang,"Βρες την απόδρασή μου →","Find my escape →")}</a><a className="wf-btn wf-btn--secondary" href={`${prefix}/ai-planner`}>{say(lang,"Έχω ήδη προορισμό","I already have a destination")}</a></div></div>
    <a className="v32-map-teaser" href={lang==="en"?"/en/ai-planner":"/escape"}><div className="v32-map-teaser__grid" aria-hidden="true"><span className="v32-pin p1">SUN</span><span className="v32-pin p2">QUIET</span><span className="v32-pin p3">FOOD</span><span className="v32-pin p4">VALUE</span></div><div><span>ESCAPE DNA</span><strong>{say(lang,"Πρώτα εσύ. Μετά ο προορισμός →","You first. Destination second →")}</strong><small>{say(lang,"Ημερομηνία · συναίσθημα · budget · friction · season","Dates · feeling · budget · friction · season")}</small></div></a>
   </div>
  </section>

  <section className="wf-section v32-app-section"><div className="wf-shell"><div className="v32-section-head"><div><span className="wf-kicker">CHOOSE A PATH</span><h2 className="wf-h2">{say(lang,"Από την ανάγκη στην απόφαση.","From need to decision.")}</h2></div><p>{say(lang,"Η νέα ροή ξεκινά χωρίς destination search. Τα υπάρχοντα εργαλεία παραμένουν διαθέσιμα όταν τα χρειάζεσαι.","The new journey starts without destination search. Existing tools remain available when you need them.")}</p></div><div className="v32-app-grid">{apps.map(app=><a className="v32-app-card" href={app.href} key={app.n}><span className="v32-app-card__n">{app.n}</span><span className="wf-kicker">{app.tag}</span><h3>{app.title}</h3><p>{app.text}</p><b>{say(lang,"Άνοιγμα →","Open →")}</b></a>)}</div></div></section>

  <section className="wf-section wf-paper-section"><div className="wf-shell v32-two-maps"><div><span className="wf-kicker">DECISION BEFORE COMMERCE</span><h2 className="wf-h2">{say(lang,"Δεν ξεκινάμε από ξενοδοχεία. Ξεκινάμε από το σωστό ταξίδι.","We do not start from hotels. We start from the right trip.")}</h2><p className="wf-lead">{say(lang,"Ο προορισμός επιλέγεται πρώτα από τις ανάγκες, την εποχή και το friction. Μόνο μετά εμφανίζονται πραγματικά offers και γίνεται 360° research.","The destination is chosen first from needs, season and friction. Only then do real offers and 360° research appear.")}</p></div><div className="v32-map-choice"><a href={lang==="en"?"/en/ai-planner":"/escape"}><span>MISSION FUNNEL</span><strong>{say(lang,"Τι απόδραση χρειάζομαι;","What escape do I need?")}</strong><small>{say(lang,"When · Escape DNA · 3 finalists","When · Escape DNA · 3 finalists")}</small></a><a href={`${prefix}/stays-map`}><span>PRODUCT / STAY MAP</span><strong>{say(lang,"Πού είναι τα προϊόντα και πόσο κοστίζουν;","Where are the products and what do they cost?")}</strong><small>{say(lang,"Μόνο μετά την απόφαση προορισμού","Only after destination choice")}</small></a></div></div></section>

  <section className="wf-section"><div className="wf-shell wf-trust"><div><span className="wf-kicker">AI THAT EARNS TRUST</span><h2 className="wf-h2">{say(lang,"Ζεστή καθοδήγηση. Καθαρά trade-offs. Χωρίς ψεύτικη πίεση.","Warm guidance. Clear trade-offs. No fake pressure.")}</h2><p className="wf-lead">{say(lang,"Το AI εξηγεί γιατί μια επιλογή ταιριάζει, τι θυσιάζεις και πότε αξίζει να αλλάξεις ημερομηνία ή προορισμό. Η πώληση έρχεται ως φυσική συνέχεια της λύσης.","AI explains why an option fits, what you trade off, and when changing dates or destination makes more sense. Commerce follows naturally from the solution.")}</p></div><div className="wf-trust__list"><div className="wf-trust__item"><strong>01 · Human need first</strong><p className="wf-body">{say(lang,"Πρώτα το συναίσθημα και ο χρόνος που έχεις, όχι merchant inventory.","Feeling and available time come before merchant inventory.")}</p></div><div className="wf-trust__item"><strong>02 · Three finalists</strong><p className="wf-body">{say(lang,"Winner, Smart Value και Wild Card αντί για ατελείωτο κατάλογο.","Winner, Smart Value and Wild Card instead of an endless catalogue.")}</p></div><div className="wf-trust__item"><strong>03 · Research after choice</strong><p className="wf-body">{say(lang,"Καιρός, φαγητό, μέρη και logistics ερευνώνται σε βάθος αφού επιλέξεις.","Weather, food, places and logistics are researched deeply after you choose.")}</p></div></div></div></section>
 </V31PageFrame>
}
