"use client";

import { FormEvent,useMemo,useState } from "react";
import type { V8StayOffer } from "@/lib/decision/v8-types";
import type { TripRequest } from "@/lib/validation/trip";
import type { TripBuilderPlanV25 } from "@/lib/trip-builder/types-v25";

type Props={slug:string;name:string;nameEn:string;trip:TripRequest;offers:V8StayOffer[];lang?:"el"|"en";missionId?:string|null};
const say=(lang:"el"|"en",el:string,en:string)=>lang==="el"?el:en;

export function V33EscapeBuilderClient({slug,name,nameEn,trip,offers,lang="el",missionId=null}:Props){
 const[selected,setSelected]=useState<V8StayOffer|null>(offers[0]??null),[plan,setPlan]=useState<TripBuilderPlanV25|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[email,setEmail]=useState(""),[mailState,setMailState]=useState<"idle"|"sending"|"sent"|"error">("idle");
 const destination=lang==="en"?nameEn:name,photo=selected?.imageUrl||selected?.thumbUrl||null,total=plan?.budgetBeyondHotel,guideUrl=plan?.guide.path||"",currentOffer=plan?.stay?.trackingUrl||selected?.trackingUrl||"",weatherSummary=useMemo(()=>plan?.weather.days.slice(0,5)??[],[plan]);

 async function persistCompleted(built:TripBuilderPlanV25){
  if(!missionId)return;
  const media=[built.stay?.imageUrl?{kind:"stay",url:built.stay.imageUrl}:null,...built.tripadvisor.places.map(x=>x.imageUrl?{kind:x.kind,url:x.imageUrl,name:x.name}:null),...built.tripadvisor.restaurants.map(x=>x.imageUrl?{kind:"restaurant",url:x.imageUrl,name:x.name}:null)].filter(Boolean).slice(0,20);
  await fetch("/api/escape/research/complete",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,destinationId:slug,weather:built.weather,places:built.webResearch.bullets,restaurants:built.tripadvisor.restaurants,practicalNotes:built.webResearch.practicalNotes,logistics:{availability:built.availability,flexibleWindows:built.flexibleWindows,budgetBeyondHotel:built.budgetBeyondHotel},sources:built.webResearch.sources,media,guidePath:built.guide.path,trackingUrl:built.stay?.trackingUrl??selected?.trackingUrl??null})}).catch(()=>null);
 }
 async function build(){
  if(!selected)return;setBusy(true);setError(null);setPlan(null);
  try{
   if(missionId)await fetch("/api/escape/select",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,destinationId:slug})}).catch(()=>null);
   const response=await fetch("/api/trip-builder",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip,slug,offerId:selected.sourceProductId})});if(!response.ok)throw new Error(`HTTP ${response.status}`);
   const built=await response.json() as TripBuilderPlanV25;setPlan(built);void persistCompleted(built);
  }catch(err){setError(err instanceof Error?err.message:say(lang,"Δεν μπόρεσα να επαληθεύσω το ταξίδι με ασφάλεια.","I could not verify the trip safely."))}finally{setBusy(false)}
 }
 async function sendEmail(event:FormEvent){event.preventDefault();if(!selected||!email)return;setMailState("sending");try{const response=await fetch("/api/guide/email",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,slug,start:trip.startDate,end:trip.endDate,offer:selected.sourceProductId,language:lang})});if(!response.ok)throw new Error();if(missionId)await fetch("/api/escape/email-state",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,email})}).catch(()=>null);setMailState("sent")}catch{setMailState("error")}}
 async function share(){const url=window.location.href,text=say(lang,`Τι λες για ${destination}; Δες την απόδραση που μας έφτιαξε ο AI travel expert.`,`What do you think about ${destination}? See the escape the AI travel expert built for us.`);if(navigator.share){await navigator.share({title:destination,text,url}).catch(()=>undefined)}else{await navigator.clipboard.writeText(url).catch(()=>undefined)}if(missionId)void fetch("/api/escape/event",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,eventName:"escape_shared",payload:{destinationId:slug}})}).catch(()=>null)}
 const track=(eventName:string,payload:Record<string,unknown>={})=>{if(missionId)void fetch("/api/escape/event",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,eventName,payload})}).catch(()=>null)};

 return <main className="escape-builder-v33">
  <section className="escape-builder-hero-v33" style={photo?{backgroundImage:`linear-gradient(90deg,rgba(4,12,20,.88),rgba(4,12,20,.35)),url('${photo}')`}:undefined}><a className="escape-back-v33" href={lang==="en"?"/en":"/"}>← {say(lang,"Νέα αναζήτηση","New search")}</a><div><span>YOUR ESCAPE · {trip.startDate} → {trip.endDate}</span><h1>{destination}</h1><p>{say(lang,"Εσύ διάλεξες τον προορισμό. Τώρα θα ελέγξουμε καιρό, πραγματικές επιλογές, τι αξίζει να δεις, φαγητό, μετακινήσεις και το budget γύρω από τη διαμονή — πριν σου πούμε να προχωρήσεις.","You chose the destination. Now we verify weather, real options, what is worth seeing, food, logistics and the budget around the stay — before asking you to proceed.")}</p></div></section>
  <section className="escape-builder-shell-v33">
   <div className="escape-builder-title-v33"><span>STEP 1</span><h2>{say(lang,"Διάλεξε τη βάση που θέλεις να ελέγξουμε.","Choose the base you want us to verify.")}</h2><p>{say(lang,"Δεν σε στέλνω ακόμη έξω από το site. Πρώτα χτίζω την πραγματική απόδραση γύρω από αυτή την επιλογή.","I am not sending you away yet. First I build the real escape around this option.")}</p></div>
   {offers.length?<div className="escape-offer-grid-v33">{offers.slice(0,6).map((offer,index)=><button type="button" key={offer.sourceProductId} className={selected?.sourceProductId===offer.sourceProductId?"is-active":""} onClick={()=>{setSelected(offer);setPlan(null)}}>{offer.imageUrl||offer.thumbUrl?<img src={offer.imageUrl||offer.thumbUrl||""} alt=""/>:null}<div><small>{index===0?say(lang,"Καλύτερο διαθέσιμο match","Best available match"):say(lang,"Εναλλακτική","Alternative")}</small><strong>{offer.propertyName}</strong><span>{offer.city||destination}</span>{offer.price!=null?<b>{offer.price.toLocaleString(lang==="el"?"el-GR":"en-GB")} {offer.currency||"EUR"}</b>:null}</div></button>)}</div>:<div className="escape-empty-v33">{say(lang,"Δεν υπάρχει ακόμη πλήρως έγκυρη διαμονή στο feed για όλο το διάστημα. Δεν θα κατασκευάσουμε ψεύτικη διαθεσιμότητα.","There is no fully valid stay in the feed for the whole period yet. We will not fabricate availability.")}</div>}
   <button className="escape-build-v33" type="button" onClick={build} disabled={!selected||busy}>{busy?say(lang,"Οι agents κάνουν 360° έλεγχο…","Agents are running the 360° check…"):say(lang,"Χτίσε την απόδρασή μου →","Build my escape →")}</button>{error?<div className="escape-error-v33">{error}</div>:null}
   {plan?<section className="escape-plan-v33"><div className="escape-builder-title-v33"><span>STEP 2 · 360° VERIFIED ESCAPE</span><h2>{say(lang,"Τώρα έχεις ταξίδι — όχι απλώς ένα δωμάτιο.","Now you have a trip — not just a room.")}</h2><p>{plan.webResearch.overview||say(lang,"Η πρόταση χτίστηκε μόνο από όσα μπορέσαμε να επαληθεύσουμε.","The proposal uses only what we could verify.")}</p></div>
    <div className="escape-plan-grid-v33"><article><span>WEATHER</span><h3>{plan.weather.label}</h3><div className="escape-weather-v33">{weatherSummary.map(day=><div key={day.date}><strong>{day.temperatureMinC==null?"?":Math.round(day.temperatureMinC)}–{day.temperatureMaxC==null?"?":Math.round(day.temperatureMaxC)}°</strong><small>{day.date.slice(5)}</small><p>{day.summary}</p></div>)}</div></article><article><span>{say(lang,"ΤΙ ΑΞΙΖΕΙ","WHAT IS WORTH IT")}</span><h3>{say(lang,"Μη χάσεις χρόνο στα λάθος πράγματα.","Do not waste time on the wrong things.")}</h3><ul>{plan.webResearch.bullets.slice(0,6).map(item=><li key={item.name}><strong>{item.name}</strong><p>{item.summary}</p></li>)}</ul></article></div>
    <div className="escape-plan-grid-v33"><article><span>FOOD & LOCAL LIFE</span><h3>{say(lang,"Επιλογές που έχουν λόγο να μπουν στο πρόγραμμα.","Places that deserve a place in the plan.")}</h3><div className="escape-place-list-v33">{plan.tripadvisor.restaurants.slice(0,5).map(item=><div key={item.locationId}>{item.imageUrl?<img src={item.imageUrl} alt=""/>:null}<div><strong>{item.name}</strong><small>{item.rating!=null?`${item.rating}/5 · `:""}{item.reviewCount!=null?`${item.reviewCount} reviews`:""}</small><p>{item.description}</p></div></div>)}{!plan.tripadvisor.restaurants.length?<p>{plan.tripadvisor.note}</p>:null}</div></article><article><span>{say(lang,"ΠΡΟΣΟΧΗ","WATCH OUT")}</span><h3>{say(lang,"Τι να ξέρεις πριν φύγεις.","What to know before you go.")}</h3><ul>{plan.webResearch.practicalNotes.slice(0,8).map((note,index)=><li key={index}><p>{note}</p></li>)}</ul>{total?<div className="escape-budget-v33"><strong>{say(lang,"Budget πέρα από τη διαμονή","Budget beyond the stay")}</strong><b>{total.totalLow}–{total.totalHigh} EUR</b><small>{total.note}</small></div>:null}</article></div>
    <section className="escape-final-card-v33"><div><span>{say(lang,"Η ΑΠΟΔΡΑΣΗ ΕΙΝΑΙ ΕΤΟΙΜΗ","YOUR ESCAPE IS READY")}</span><h2>{plan.stay?.propertyName}</h2><p>{say(lang,"Έλεγξες πρώτα το ταξίδι. Τώρα, αν σου κάνει, δες την τρέχουσα προσφορά στον πάροχο. Η τελική τιμή, δωμάτιο και διαθεσιμότητα επιβεβαιώνονται εκεί.","You checked the trip first. If it still feels right, view the current provider offer. Final price, room and availability are confirmed there.")}</p></div><div className="escape-actions-v33">{currentOffer?<a href={currentOffer} target="_blank" rel="sponsored nofollow noopener" onClick={()=>track("affiliate_offer_opened",{destinationId:slug,offerId:selected?.sourceProductId})}>{say(lang,"Δες την τρέχουσα προσφορά ↗","View current offer ↗")}</a>:null}{guideUrl?<a href={guideUrl} target="_blank" rel="noopener" onClick={()=>track("guide_downloaded",{destinationId:slug})}>{say(lang,"Κατέβασε το Escape Book PDF","Download Escape Book PDF")}</a>:null}<button type="button" onClick={share}>{say(lang,"Μοιράσου την πρόταση","Share this escape")}</button></div></section>
    <form className="escape-email-v33" onSubmit={sendEmail}><div><span>ESCAPE BOOK</span><h3>{say(lang,"Στείλε το προσωπικό travel dossier στο email σου.","Send the personal travel dossier to your email.")}</h3><p>{say(lang,"Με QR που οδηγεί στο ίδιο affiliate tracking URL. Δεν σε γράφουμε αυτόματα σε newsletter.","With a QR pointing to the same affiliate tracking URL. No automatic newsletter signup.")}</p></div><div><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><button disabled={mailState==="sending"}>{mailState==="sending"?say(lang,"Αποστολή…","Sending…"):say(lang,"Στείλε το Escape Book","Send Escape Book")}</button>{mailState==="sent"?<small>{say(lang,"Στάλθηκε.","Sent.")}</small>:mailState==="error"?<small>{say(lang,"Δεν στάλθηκε — χρησιμοποίησε το download.","Could not send — use the download instead.")}</small>:null}</div></form>
   </section>:null}
  </section>
 </main>
}
