"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import type { EscapeSolutionResponseV35,EscapeSolutionV35 } from "@/lib/decision/solution-ranking-v35";
import styles from "./v34-escape-funnel.module.css";

type Lang="el"|"en";
type Stage="feel"|"questions"|"dna"|"dates"|"reality"|"solve"|"results";
type QuestionId="companions"|"outcome"|"social"|"novelty"|"must_have"|"friction";
type Answer={questionId:QuestionId;value:string};
type Profile={travelerType:"solo"|"couple"|"family"|"friends";moods:Array<"relax"|"romantic"|"food"|"warmth"|"city"|"nature"|"adventure"|"culture">;pace:"slow"|"balanced"|"full";desiredEnergy:"restore"|"balanced"|"stimulating";socialPreference:"quiet"|"balanced"|"lively";noveltyPreference:"familiar"|"balanced"|"surprise";avoid:"long-travel"|"high-cost"|"crowds"|"none";mustHave:"sea"|"nature"|"culture"|"nightlife"|"none";dnaLabels:string[]};
type Discovery={summary:string;profile:Profile;answered:QuestionId[];nextQuestionId:QuestionId|null;confidence:number;complete:boolean};
type DateWindow={id:string;label:string;note:string;start:string;end:string;reason?:string;confidence?:"HIGH"|"MEDIUM"};
type StreamRow={type:string;progress?:number;message?:string};
type Media={imageUrl:string;sourceUrl:string;title:string;description?:string;license:string;attribution:string};
type VisualWorld={id:string;query:string;el:string;en:string;hintEl:string;hintEn:string;semanticEl:string;semanticEn:string};

const say=(lang:Lang,el:string,en:string)=>lang==="el"?el:en;
const DAY=86_400_000;
const iso=(d:Date)=>d.toISOString().slice(0,10);
const add=(d:Date,days:number)=>new Date(d.getTime()+days*DAY);
const groupSize=(type:Profile["travelerType"])=>type==="solo"?1:type==="couple"?2:4;
function nextWeekday(base:Date,weekday:number,weekOffset=0){const d=new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth(),base.getUTCDate()));const delta=(weekday-d.getUTCDay()+7)%7||7;return add(d,delta+weekOffset*7)}

const VISUAL_WORLDS:VisualWorld[]=[
 {id:"sea-light",query:"Mediterranean island aerial coast",el:"Θάλασσα & φως",en:"Sea & light",hintEl:"Ορίζοντας, νερό, αργός ρυθμός.",hintEn:"Horizon, water, slower rhythm.",semanticEl:"Με τραβάει η θάλασσα, το φως και ένας αργός μεσογειακός ρυθμός.",semanticEn:"I am drawn to sea, light and a slower Mediterranean rhythm."},
 {id:"city-night",query:"European old town aerial evening",el:"Πόλη & βράδυ",en:"City & evenings",hintEl:"Βόλτες, φαγητό, ενέργεια.",hintEn:"Walking, food, energy.",semanticEl:"Θέλω ατμοσφαιρική πόλη, βόλτες, καλό φαγητό και βραδινή ζωή.",semanticEn:"I want an atmospheric city, walks, great food and evening life."},
 {id:"green-reset",query:"Madeira aerial green mountains",el:"Πράσινο & reset",en:"Green & reset",hintEl:"Φύση, καθαρό μυαλό, ανάσα.",hintEn:"Nature, clear head, breathing room.",semanticEl:"Θέλω πράσινο, φύση και πραγματική αποφόρτιση μακριά από θόρυβο.",semanticEn:"I want greenery, nature and a proper reset away from noise."},
 {id:"mountain-cozy",query:"Alpine village aerial winter mountains",el:"Βουνό & θαλπωρή",en:"Mountains & warmth",hintEl:"Τοπίο, ησυχία, cozy ρυθμός.",hintEn:"Landscape, quiet, cosy rhythm.",semanticEl:"Με ελκύει βουνό, θαλπωρή, ωραίο τοπίο και ήρεμες μέρες.",semanticEn:"I am drawn to mountains, warmth, beautiful scenery and quiet days."},
 {id:"adventure",query:"dramatic island aerial cliffs Europe",el:"Περιπέτεια",en:"Adventure",hintEl:"Κίνηση, φύση, κάτι αξέχαστο.",hintEn:"Movement, nature, something memorable.",semanticEl:"Θέλω περιπέτεια, εντυπωσιακή φύση και ένα ταξίδι που θα θυμάμαι.",semanticEn:"I want adventure, dramatic nature and a trip I will remember."},
 {id:"surprise",query:"hidden European coast aerial village",el:"Έκπληξέ με",en:"Surprise me",hintEl:"Όχι το προφανές — το σωστό.",hintEn:"Not the obvious — the right one.",semanticEl:"Θέλω κάτι που δεν θα έψαχνα μόνος μου, αρκεί να ταιριάζει πραγματικά.",semanticEn:"I want something I would not search for myself, as long as it genuinely fits."}
];

const QUESTIONS:Record<QuestionId,{el:string;en:string;options:Array<{value:string;el:string;en:string;hintEl:string;hintEn:string}>}>={
 companions:{el:"Με ποιον φεύγεις;",en:"Who are you escaping with?",options:[{value:"solo",el:"Μόνος/η",en:"Solo",hintEl:"Ελευθερία χωρίς συμβιβασμούς.",hintEn:"Freedom without compromise."},{value:"couple",el:"Με τον άνθρωπό μου",en:"With my partner",hintEl:"Χρόνος για δύο.",hintEn:"Time for two."},{value:"family",el:"Με παιδιά",en:"With kids",hintEl:"Να λειτουργεί για όλους.",hintEn:"Make it work for everyone."},{value:"friends",el:"Με φίλους",en:"With friends",hintEl:"Κοινές στιγμές και ενέργεια.",hintEn:"Shared moments and energy."}]},
 outcome:{el:"Όταν γυρίσεις, πώς θέλεις να νιώθεις;",en:"How do you want to feel when you return?",options:[{value:"restore",el:"Πραγματικά ξεκούραστος",en:"Properly rested",hintEl:"Χαμηλοί ρυθμοί και ανάσα.",hintEn:"Low pace and breathing room."},{value:"balanced",el:"Γεμάτος ωραίες στιγμές",en:"Full of good memories",hintEl:"Άνεση και εμπειρίες σε ισορροπία.",hintEn:"Ease and experiences in balance."},{value:"stimulating",el:"Ζωντανός και ενθουσιασμένος",en:"Alive and energised",hintEl:"Κάτι που θα θυμάσαι.",hintEn:"Something memorable."}]},
 social:{el:"Τι ατμόσφαιρα θέλεις;",en:"What atmosphere fits you?",options:[{value:"quiet",el:"Ήσυχα",en:"Quiet",hintEl:"Λιγότερος κόσμος, περισσότερος χώρος.",hintEn:"Less crowd, more room."},{value:"balanced",el:"Λίγη ζωή, χωρίς χάος",en:"Some life, no chaos",hintEl:"Επιλογές αλλά και ησυχία.",hintEn:"Options without overload."},{value:"lively",el:"Θέλω ενέργεια",en:"I want energy",hintEl:"Βόλτες, bars, βραδινή ζωή.",hintEn:"Streets, bars, nights out."}]},
 novelty:{el:"Πόσο έξω από τα συνηθισμένα;",en:"How far from familiar?",options:[{value:"familiar",el:"Θέλω σιγουριά",en:"Keep it familiar",hintEl:"Εύκολο και προβλέψιμο.",hintEn:"Easy and predictable."},{value:"balanced",el:"Κάτι νέο, χωρίς ρίσκο",en:"New, not risky",hintEl:"Ανακάλυψη με ασφάλεια.",hintEn:"Discovery with confidence."},{value:"surprise",el:"Έκπληξέ με",en:"Surprise me",hintEl:"Βρες κάτι που δεν θα έψαχνα.",hintEn:"Find what I would not search for."}]},
 must_have:{el:"Τι πρέπει οπωσδήποτε να υπάρχει;",en:"What must be there?",options:[{value:"sea",el:"Θάλασσα / φως",en:"Sea / light",hintEl:"Ορίζοντας και νερό.",hintEn:"Horizon and water."},{value:"nature",el:"Φύση",en:"Nature",hintEl:"Πράσινο, βουνό, διαδρομές.",hintEn:"Green, mountains, trails."},{value:"culture",el:"Κουλτούρα / ιστορία",en:"Culture / history",hintEl:"Κάτι ουσιαστικό να ανακαλύψω.",hintEn:"Something meaningful to discover."},{value:"nightlife",el:"Βραδινή ζωή",en:"Nightlife",hintEl:"Η μέρα να μην τελειώνει νωρίς.",hintEn:"Let the day continue after dark."},{value:"none",el:"Κανένα must-have",en:"No must-have",hintEl:"Βρες την καλύτερη συνολική ισορροπία.",hintEn:"Find the best overall balance."}]},
 friction:{el:"Τι δεν θέλεις να πληρώσεις με χρόνο ή νεύρα;",en:"What should not cost you time or energy?",options:[{value:"long-travel",el:"Πολλή μετακίνηση",en:"Long travel",hintEl:"Να αρχίσει γρήγορα η απόδραση.",hintEn:"Let the escape start quickly."},{value:"crowds",el:"Υπερβολικό κόσμο",en:"Crowds",hintEl:"Όχι ουρές και τουριστική πίεση.",hintEn:"No queues and tourist overload."},{value:"high-cost",el:"Premium χωρίς λόγο",en:"Pointless premium",hintEl:"Αξία, όχι φθηνότερο πάση θυσία.",hintEn:"Value, not cheap at any cost."},{value:"none",el:"Δεν με περιορίζει κάτι",en:"Nothing specific",hintEl:"Κράτα μεγάλο χώρο επιλογών.",hintEn:"Keep the option space wide."}]}
};

function fallbackWindows(lang:Lang,duration:number):DateWindow[]{const now=new Date(),fri=nextWeekday(now,5),fri2=nextWeekday(now,5,2),sun=nextWeekday(now,0,1);return[
 {id:"easy",label:say(lang,"Εύκολη απόδραση","Easy escape"),note:say(lang,"Παρασκευή · λίγη άδεια","Friday · minimal leave"),start:iso(fri),end:iso(add(fri,duration)),reason:say(lang,"Χαμηλή οργανωτική τριβή.","Low planning friction."),confidence:"MEDIUM"},
 {id:"space",label:say(lang,"Περισσότερος χώρος","More room"),note:say(lang,"Λίγο αργότερα · περισσότερες επιλογές","A little later · more options"),start:iso(fri2),end:iso(add(fri2,duration)),reason:say(lang,"Μεγαλύτερο περιθώριο για δυνατό matching.","More room for stronger matching."),confidence:"MEDIUM"},
 {id:"quiet",label:say(lang,"Πιο ήσυχος ρυθμός","Quieter rhythm"),note:say(lang,"Κυριακή–μέσα εβδομάδας","Sunday into midweek"),start:iso(sun),end:iso(add(sun,duration)),reason:say(lang,"Λιγότερη πίεση από weekend patterns.","Less weekend-pattern pressure."),confidence:"MEDIUM"}
]}

export function V34EscapeFunnel({lang="el"}:{lang?:Lang}){
 const[stage,setStage]=useState<Stage>("feel"),[initialText,setInitialText]=useState(""),[activeWorld,setActiveWorld]=useState("sea-light"),[answers,setAnswers]=useState<Answer[]>([]),[discovery,setDiscovery]=useState<Discovery|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const[dateMode,setDateMode]=useState<"suggest"|"fixed"|"flexible">("suggest"),[duration,setDuration]=useState(3),[horizonDays,setHorizonDays]=useState(60),[dateWindows,setDateWindows]=useState<DateWindow[]>(()=>fallbackWindows(lang,3)),[windowId,setWindowId]=useState("easy"),[dateLoading,setDateLoading]=useState(false);
 const initialFallback=useMemo(()=>fallbackWindows(lang,3)[0],[lang]);
 const[fixedStart,setFixedStart]=useState(initialFallback.start),[fixedEnd,setFixedEnd]=useState(initialFallback.end),[origin,setOrigin]=useState(say(lang,"Αθήνα","Athens")),[budget,setBudget]=useState(1200),[rows,setRows]=useState<StreamRow[]>([]),[result,setResult]=useState<EscapeSolutionResponseV35|null>(null),[solutionIndex,setSolutionIndex]=useState(0),[missionId,setMissionId]=useState<string|null>(null);
 const[moodMedia,setMoodMedia]=useState<Record<string,Media>>({}),[solutionMedia,setSolutionMedia]=useState<Record<string,Media[]>>({});
 const selectedWindow=dateMode==="fixed"?{id:"fixed",label:say(lang,"Οι ημερομηνίες μου","My dates"),note:"",start:fixedStart,end:fixedEnd}:dateWindows.find(item=>item.id===windowId)??dateWindows[0];
 const q=discovery?.nextQuestionId?QUESTIONS[discovery.nextQuestionId]:null,solutions=result?.solutions??[],selectedSolution=solutions[solutionIndex]??null,activeWorldMedia=moodMedia[activeWorld];
 const step=stage==="feel"?1:stage==="questions"||stage==="dna"?2:stage==="dates"?3:stage==="reality"?4:5;

 useEffect(()=>{let cancelled=false;Promise.all(VISUAL_WORLDS.map(async world=>{try{const r=await fetch(`/api/escape/media?mode=aerial&destination=${encodeURIComponent(world.query)}`);const d=await r.json() as {items?:Media[]};return[world.id,d.items?.[0]??null] as const}catch{return[world.id,null] as const}})).then(entries=>{if(cancelled)return;const next:Record<string,Media>={};for(const[id,item]of entries)if(item)next[id]=item;setMoodMedia(next)});return()=>{cancelled=true}},[]);
 useEffect(()=>{if(stage!=="dates"||!discovery||dateMode==="fixed")return;let cancelled=false;setDateLoading(true);fetch("/api/escape/date-opportunities",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,initialText,duration,horizonDays:dateMode==="flexible"?horizonDays:60,profile:{travelerType:discovery.profile.travelerType,desiredEnergy:discovery.profile.desiredEnergy,socialPreference:discovery.profile.socialPreference,noveltyPreference:discovery.profile.noveltyPreference,avoid:discovery.profile.avoid,moods:discovery.profile.moods}})}).then(async r=>r.ok?await r.json():null).then((d:{windows?:DateWindow[]}|null)=>{if(cancelled)return;const windows=d?.windows?.length===3?d.windows:fallbackWindows(lang,duration);setDateWindows(windows);setWindowId(windows[0].id)}).catch(()=>{if(!cancelled){const windows=fallbackWindows(lang,duration);setDateWindows(windows);setWindowId(windows[0].id)}}).finally(()=>{if(!cancelled)setDateLoading(false)});return()=>{cancelled=true}},[stage,discovery,dateMode,duration,horizonDays,initialText,lang]);
 useEffect(()=>{if(!solutions.length)return;let cancelled=false;Promise.all(solutions.map(async solution=>{const destination=solution.recommendation.destinationEn||solution.recommendation.destination;try{const r=await fetch(`/api/escape/media?mode=aerial&destination=${encodeURIComponent(destination)}`);const d=await r.json() as {items?:Media[]};return[solution.recommendation.slug,d.items?.slice(0,4)??[]] as [string,Media[]]}catch{return[solution.recommendation.slug,[] as Media[]] as [string,Media[]]}})).then(entries=>{if(cancelled)return;const next:Record<string,Media[]>={};for(const[slug,items]of entries)next[slug]=items;setSolutionMedia(next)});return()=>{cancelled=true}},[result]);

 function chooseVisual(world:VisualWorld){setActiveWorld(world.id);const semantic=say(lang,world.semanticEl,world.semanticEn);setInitialText(current=>current.includes(semantic)?current:(current.trim()?`${current.trim()} ${semantic}`:semantic))}
 async function discover(nextAnswers=answers){setBusy(true);setError(null);try{const r=await fetch("/api/escape/discovery",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,initialText,answers:nextAnswers})});if(!r.ok)throw new Error();const d=await r.json() as Discovery;setDiscovery(d);setStage(d.complete?"dna":"questions")}catch{setError(say(lang,"Δεν κατάφερα να σε καταλάβω αρκετά. Δοκίμασε ξανά με λίγες περισσότερες λέξεις.","I could not understand enough yet. Try again with a little more detail."))}finally{setBusy(false)}}
 async function start(e:FormEvent){e.preventDefault();if(initialText.trim().length<3)return;await discover([])}
 async function answer(questionId:QuestionId,value:string){const next=[...answers.filter(a=>a.questionId!==questionId),{questionId,value}];setAnswers(next);await discover(next)}
 async function createMission(){if(!discovery||!selectedWindow)return null;try{const r=await fetch("/api/escape/mission",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,originText:origin,travelWindow:{label:selectedWindow.label,start:selectedWindow.start,end:selectedWindow.end},needText:initialText.slice(0,500),travelerType:discovery.profile.travelerType,groupSize:groupSize(discovery.profile.travelerType),budgetEur:budget,dna:discovery.profile.dnaLabels})});if(!r.ok)return null;const d=await r.json() as {missionId?:string};return d.missionId??null}catch{return null}}
 async function persistSolutions(id:string,finalResult:EscapeSolutionResponseV35){const finalists=finalResult.solutions.slice(0,10).map(item=>({slug:item.recommendation.slug,score:item.combinedScore,why:`${item.reasoning.destination} ${item.reasoning.stay}`,seasonNote:item.recommendation.seasonNote,budgetLabel:item.recommendation.budgetLabel,effortLabel:item.recommendation.effortLabel}));await fetch("/api/escape/matches",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId:id,finalists})}).catch(()=>null)}
 async function solve(){if(!discovery||!selectedWindow)return;setBusy(true);setError(null);setRows([]);setResult(null);setSolutionIndex(0);setStage("solve");const id=await createMission();setMissionId(id);const nights=Math.max(1,Math.round((Date.parse(`${selectedWindow.end}T00:00:00Z`)-Date.parse(`${selectedWindow.start}T00:00:00Z`))/DAY));const payload={origin,startDate:selectedWindow.start,endDate:selectedWindow.end,month:"flexible",nights,budget,moods:discovery.profile.moods.length?discovery.profile.moods:["relax"],travelerType:discovery.profile.travelerType,groupSize:groupSize(discovery.profile.travelerType),language:lang,distancePreference:"any",pace:discovery.profile.pace,hotelStyle:"any",avoid:discovery.profile.avoid,entryMode:"idea",desiredEnergy:discovery.profile.desiredEnergy,socialPreference:discovery.profile.socialPreference,noveltyPreference:discovery.profile.noveltyPreference,mustHave:discovery.profile.mustHave,dateFlexibility:dateMode==="fixed"?"fixed":"few-days",transportMode:"any",stayLocationPreference:"balanced",tripText:`${initialText}. ${discovery.summary}`.slice(0,500)};
  try{const response=await fetch("/api/escape/solve/stream",{method:"POST",headers:{"content-type":"application/json",accept:"application/x-ndjson"},body:JSON.stringify(payload)});if(!response.ok)throw new Error();const reader=response.body?.getReader();if(!reader)throw new Error();const decoder=new TextDecoder();let buffer="";const consume=(line:string)=>{if(!line.trim())return;const item=JSON.parse(line) as StreamRow&{result?:EscapeSolutionResponseV35};if(item.type==="final"&&item.result){setResult(item.result);setStage("results");if(id)void persistSolutions(id,item.result)}else if(item.type==="continuity"){setError(item.message??say(lang,"Δεν βρήκα ασφαλές αποτέλεσμα. Δοκίμασε πιο ανοιχτό budget ή ημερομηνίες.","I could not find a safe result. Try wider dates or budget."))}else setRows(current=>[...current,item])};while(true){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines)consume(line)}if(buffer.trim())consume(buffer)}catch{setError(say(lang,"Η ανάλυση δεν ολοκληρώθηκε. Κράτησα το προφίλ σου για να ξαναδοκιμάσεις.","The analysis did not complete. I kept your profile so you can retry."));setStage("reality")}finally{setBusy(false)}}
 function reset(){setStage("feel");setResult(null);setRows([]);setError(null);setSolutionIndex(0)}
 function tripHref(solution:EscapeSolutionV35){const rec=solution.recommendation;return `/escape/${encodeURIComponent(rec.slug)}?start=${selectedWindow?.start}&end=${selectedWindow?.end}&budget=${budget}&travelerType=${discovery?.profile.travelerType??"couple"}&mood=${discovery?.profile.moods[0]??"relax"}&origin=${encodeURIComponent(origin)}&lang=${lang}&offer=${encodeURIComponent(solution.stay.sourceProductId)}${missionId?`&mission=${missionId}`:""}`}
 function moveSolution(delta:number){if(!solutions.length)return;setSolutionIndex(current=>(current+delta+solutions.length)%solutions.length)}
 const selectedGallery=selectedSolution?solutionMedia[selectedSolution.recommendation.slug]??[]:[],selectedBackdrop=selectedGallery[0]?.imageUrl??selectedSolution?.stay.imageUrl??activeWorldMedia?.imageUrl??null;

 return <main className={styles.shell} data-mood={activeWorld} data-stage={stage}>
  {selectedBackdrop&&stage==="results"?<img key={`${selectedSolution?.recommendation.slug}-backdrop`} className={styles.globalBackdrop} src={selectedBackdrop} alt="" aria-hidden="true"/>:activeWorldMedia?<img key={`${activeWorld}-backdrop`} className={styles.globalBackdrop} src={activeWorldMedia.imageUrl} alt="" aria-hidden="true"/>:<div className={styles.globalFallback}/>}<div className={styles.globalShade}/><div className={styles.grain}/>
  <header className={styles.topbar}><button type="button" className={styles.brand} onClick={reset}>AI TRAVEL <b>ESCAPE</b></button><div className={styles.steps}>{[1,2,3,4,5].map(n=><span key={n} className={n===step?styles.stepActive:n<step?styles.stepDone:""}>{n}</span>)}</div><a className={styles.lang} href={lang==="en"?"/":"/en"}>{lang==="en"?"ΕΛ":"EN"}</a></header>

  {stage==="feel"&&<section className={styles.stage}><div className={styles.heroCopy}><span className={styles.eyebrow}>01 · FEEL FIRST</span><h1>{say(lang,"Πώς θέλεις να νιώθεις όταν φύγεις;","How do you want to feel when you leave?")}</h1><p>{say(lang,"Μην ψάξεις προορισμό. Δώσε μου το πρόβλημα, το mood ή απλώς διάλεξε μια εικόνα.","Do not search for a destination. Give me the problem, the mood, or simply choose an image.")}</p><form onSubmit={start} className={styles.prompt}><textarea value={initialText} onChange={e=>setInitialText(e.target.value)} placeholder={say(lang,"π.χ. Έχω κουραστεί, θέλω 4 μέρες με τη σύντροφό μου, ήσυχα αλλά με καλό φαγητό…","e.g. I am exhausted. Four days with my partner, calm but with great food…")} maxLength={700}/><button disabled={busy||initialText.trim().length<3}>{busy?"AI…":say(lang,"Ξεκίνα →","Start →")}</button></form></div><div className={styles.moodDeck}>{VISUAL_WORLDS.map(world=>{const media=moodMedia[world.id];return <button key={world.id} type="button" className={activeWorld===world.id?styles.moodActive:""} onClick={()=>chooseVisual(world)}>{media&&<img src={media.imageUrl} alt=""/>}<i/><strong>{say(lang,world.el,world.en)}</strong><small>{say(lang,world.hintEl,world.hintEn)}</small></button>})}</div></section>}

  {stage==="questions"&&q&&discovery&&<section className={styles.stage}><div className={styles.questionIntro}><span className={styles.eyebrow}>02 · UNDERSTAND YOU</span><p>{discovery.summary}</p><h2>{say(lang,q.el,q.en)}</h2></div><div className={styles.choiceGrid}>{q.options.map(option=><button key={option.value} disabled={busy} onClick={()=>answer(discovery.nextQuestionId!,option.value)}><b>{say(lang,option.el,option.en)}</b><span>{say(lang,option.hintEl,option.hintEn)}</span></button>)}</div></section>}

  {stage==="dna"&&discovery&&<section className={styles.stage}><div className={styles.centerCard}><span className={styles.eyebrow}>02 · ESCAPE DNA</span><h2>{say(lang,"Αυτό κατάλαβα για το ταξίδι που χρειάζεσαι.","This is the trip I think you need.")}</h2><blockquote>{discovery.summary}</blockquote><div className={styles.dna}>{discovery.profile.dnaLabels.map(label=><span key={label}>{label}</span>)}</div><div className={styles.actions}><button className={styles.primary} onClick={()=>setStage("dates")}>{say(lang,"Σωστά — πάμε στο πότε →","Correct — now when →")}</button><button className={styles.ghost} onClick={()=>setStage("feel")}>{say(lang,"Όχι ακριβώς","Not quite")}</button></div></div></section>}

  {stage==="dates"&&discovery&&<section className={styles.stage}><div className={styles.questionIntro}><span className={styles.eyebrow}>03 · TIME STRATEGY</span><h2>{say(lang,"Πότε έχει νόημα να φύγεις;","When does it make sense to go?")}</h2></div><div className={styles.dateModes}>{(["suggest","fixed","flexible"] as const).map(mode=><button key={mode} className={dateMode===mode?styles.selected:""} onClick={()=>setDateMode(mode)}><b>{mode==="suggest"?say(lang,"Βρες το για μένα","Find it for me"):mode==="fixed"?say(lang,"Ξέρω πότε","I know when"):say(lang,"Είμαι flexible","I am flexible")}</b><span>{mode==="suggest"?say(lang,"3 έξυπνα παράθυρα","3 smart windows"):mode==="fixed"?say(lang,"Συγκεκριμένες ημερομηνίες","Exact dates"):say(lang,"Μεγαλύτερος ορίζοντας","Wider horizon")}</span></button>)}</div>{dateMode==="fixed"?<div className={styles.fixedDates}><label>{say(lang,"Αναχώρηση","Departure")}<input type="date" value={fixedStart} min={iso(new Date())} onChange={e=>setFixedStart(e.target.value)}/></label><label>{say(lang,"Επιστροφή","Return")}<input type="date" value={fixedEnd} min={fixedStart} onChange={e=>setFixedEnd(e.target.value)}/></label></div>:<><div className={styles.pills}><span>{say(lang,"Νύχτες","Nights")}</span>{[2,3,4,5,7].map(n=><button key={n} className={duration===n?styles.pillActive:""} onClick={()=>setDuration(n)}>{n}</button>)}{dateMode==="flexible"&&[60,90,120].map(n=><button key={n} className={horizonDays===n?styles.pillActive:""} onClick={()=>setHorizonDays(n)}>{n}d</button>)}</div><div className={styles.windowGrid}>{dateLoading?<div className={styles.thinking}>{say(lang,"Ο Date Agent συγκρίνει travel rhythm και διαθέσιμο χρονικό χώρο…","The Date Agent is comparing travel rhythm and available time…")}</div>:dateWindows.map(window=><button key={window.id} className={windowId===window.id?styles.windowActive:""} onClick={()=>setWindowId(window.id)}><small>{window.label}</small><b>{window.start.slice(5)} → {window.end.slice(5)}</b><span>{window.note}</span><em>{window.reason}</em></button>)}</div></>}<button className={styles.floatingNext} disabled={dateLoading||!selectedWindow} onClick={()=>setStage("reality")}>{say(lang,"Συνέχεια →","Continue →")}</button></section>}

  {stage==="reality"&&discovery&&selectedWindow&&<section className={styles.stage}><div className={styles.centerCard}><span className={styles.eyebrow}>04 · REALITY CHECK</span><h2>{say(lang,"Δύο πράγματα πριν ψάξω πραγματικά.","Two things before I search for real.")}</h2><div className={styles.realityGrid}><label>{say(lang,"Αφετηρία","Starting from")}<input value={origin} onChange={e=>setOrigin(e.target.value)}/></label><div><span>{say(lang,"Άνετο συνολικό budget","Comfortable total budget")}</span><div className={styles.budgetGrid}>{[600,900,1200,1600,2200,3000].map(value=><button key={value} className={budget===value?styles.selected:""} onClick={()=>setBudget(value)}>€{value}</button>)}</div></div></div><div className={styles.solveBrief}><b>{discovery.summary}</b><span>{selectedWindow.start} → {selectedWindow.end} · {origin} · €{budget}</span></div><button className={styles.primary} disabled={busy||origin.trim().length<2} onClick={solve}>{say(lang,"Βρες τις 10 καλύτερες πραγματικές λύσεις →","Find my 10 best real solutions →")}</button></div></section>}

  {stage==="solve"&&<section className={styles.stage}><div className={styles.solveStage}><div className={styles.orbit}><i/><i/><i/><b>AI</b></div><span className={styles.eyebrow}>05 · DUAL-PASS AGENT</span><h2>{say(lang,"Πρώτα βρίσκω το σωστό ταξίδι. Μετά το αναγκάζω να περάσει από την πραγματικότητα.","First I find the right trip. Then I force it through reality.")}</h2><div className={styles.agentLines}>{rows.slice(-5).map((row,index)=><p key={`${row.type}-${index}`}><span>{row.progress??"·"}</span>{row.message??row.type}</p>)}</div><small>{say(lang,"Destination fit → πραγματικό stay inventory → δεύτερο rerank → αιτιολόγηση","Destination fit → real stay inventory → second rerank → explanation")}</small></div></section>}

  {stage==="results"&&selectedSolution&&selectedWindow&&<section className={`${styles.stage} ${styles.resultsStage}`}><button className={styles.arrowLeft} onClick={()=>moveSolution(-1)} aria-label="Previous">‹</button><button className={styles.arrowRight} onClick={()=>moveSolution(1)} aria-label="Next">›</button><div className={styles.solutionMain}><div className={styles.solutionStory}><span className={styles.eyebrow}>#{selectedSolution.rank} · {selectedSolution.combinedScore}% MATCH</span><h1>{lang==="en"?selectedSolution.recommendation.destinationEn:selectedSolution.recommendation.destination}</h1><p className={styles.bigWhy}>{selectedSolution.reasoning.destination}</p><div className={styles.scoreRow}><span>{say(lang,"Ταξίδι","Trip")} <b>{selectedSolution.destinationScore}</b></span><span>{say(lang,"Διαμονή","Stay")} <b>{selectedSolution.inventoryScore}</b></span><span>{say(lang,"Επιλογές","Inventory")} <b>{selectedSolution.inventoryDepth}%</b></span></div><div className={styles.reverseBox}><small>{say(lang,"ΑΝΤΙΣΤΡΟΦΗ ΣΚΕΨΗ","REVERSE CHECK")}</small><p>{selectedSolution.reasoning.reverse}</p></div></div><aside className={styles.stayCard}>{selectedSolution.stay.imageUrl&&<img src={selectedSolution.stay.imageUrl} alt=""/>}<div><small>{say(lang,"ΚΑΤΑΛΥΜΑ ΠΟΥ ΣΤΗΡΙΖΕΙ ΤΗΝ ΕΠΙΛΟΓΗ","STAY THAT SUPPORTS THIS CHOICE")}</small><h3>{selectedSolution.stay.propertyName}</h3>{selectedSolution.stay.city&&<span>{selectedSolution.stay.city}</span>}<p>{selectedSolution.reasoning.stay}</p><div className={styles.stayFacts}>{selectedSolution.stay.price!=null&&<b>{selectedSolution.stay.currency??"EUR"} {Math.round(selectedSolution.stay.price)} <small>{say(lang,"τιμή feed","feed price")}</small></b>}{selectedSolution.stay.discountPct!=null&&<em>-{Math.round(selectedSolution.stay.discountPct)}%</em>}</div><small className={styles.tradeoff}>{selectedSolution.reasoning.tradeoff}</small><div className={styles.ctas}><a className={styles.primaryLink} href={tripHref(selectedSolution)}>{say(lang,"Χτίσε όλο το ταξίδι","Build the full trip")}</a><a className={styles.affiliateLink} href={selectedSolution.stay.trackingUrl} target="_blank" rel="sponsored noreferrer">{say(lang,"Έλεγξε το κατάλυμα ↗","Check the stay ↗")}</a></div></div></aside></div><div className={styles.solutionRail}>{solutions.map((solution,index)=>{const thumb=solutionMedia[solution.recommendation.slug]?.[0]?.imageUrl??solution.stay.imageUrl;return <button key={`${solution.recommendation.slug}-${solution.stay.sourceProductId}`} className={index===solutionIndex?styles.solutionActive:""} onClick={()=>setSolutionIndex(index)}>{thumb&&<img src={thumb} alt=""/>}<i/><small>#{index+1}</small><b>{lang==="en"?solution.recommendation.destinationEn:solution.recommendation.destination}</b><span>{solution.stay.propertyName}</span></button>})}</div></section>}

  {stage==="results"&&result&&result.solutions.length===0&&<section className={styles.stage}><div className={styles.centerCard}><span className={styles.eyebrow}>NO SAFE MATCH</span><h2>{say(lang,"Δεν θα σου εφεύρω αποτέλεσμα.","I will not invent a result.")}</h2><p>{say(lang,"Βρήκα destination fit αλλά όχι αρκετό πραγματικό stay inventory για να το στηρίξω. Άνοιξε λίγο ημερομηνίες ή budget και ξανατρέχω.","I found destination fit but not enough real stay inventory to support it. Widen dates or budget and I will rerun it.")}</p><button className={styles.primary} onClick={()=>setStage("dates")}>{say(lang,"Άλλαξε ημερομηνίες","Change dates")}</button></div></section>}
  {error&&<div className={styles.error}>{error}<button onClick={()=>setError(null)}>×</button></div>}
 </main>
}
