"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import type { V8StayOffer } from "@/lib/decision/v8-types";
import type { TripRequest } from "@/lib/validation/trip";
import type { TripBuilderPlanV25 } from "@/lib/trip-builder/types-v25";
import styles from "./v34-escape-builder.module.css";

type Props={slug:string;name:string;nameEn:string;trip:TripRequest;offers:V8StayOffer[];lang?:"el"|"en";missionId?:string|null};
type Media={imageUrl:string;sourceUrl:string;title:string;license:string;attribution:string};
type Dossier={destination:{slug:string;name:string;nameEn:string;latitude:number;longitude:number;isSummer:boolean};weather:{label:string;score:number|null;days:Array<{date:string;temperatureMinC:number|null;temperatureMaxC:number|null;summary:string}>};places:{status:string;sourceMonth:string;places:Array<{locationId:string;name:string;description:string|null;imageUrl:string|null;rating:number|null;reviewCount:number|null}>;museums:Array<{locationId:string;name:string;description:string|null;imageUrl:string|null;rating:number|null}>;restaurants:Array<{locationId:string;name:string;description:string|null;imageUrl:string|null;rating:number|null;reviewCount:number|null}>;nightlife:Array<{locationId:string;name:string;description:string|null;imageUrl:string|null;rating:number|null}>;beaches:Array<{locationId:string;name:string;description:string|null;imageUrl:string|null;rating:number|null}>;note:string};research:{source:string;overview:string|null;attractions:Array<{name:string;summary?:string|null;whyItFits?:string|null}>;practicalNotes:string[];sources:Array<{title:string;url:string;domain:string}>};budgetBeyondHotel:{totalLow:number;totalHigh:number;note:string}};
const say=(lang:"el"|"en",el:string,en:string)=>lang==="el"?el:en;

export function V34EscapeBuilderClient({slug,name,nameEn,trip,offers,lang="el",missionId=null}:Props){
 const destination=lang==="en"?nameEn:name;const[selected,setSelected]=useState<V8StayOffer|null>(offers[0]??null),[dossier,setDossier]=useState<Dossier|null>(null),[plan,setPlan]=useState<TripBuilderPlanV25|null>(null),[stage,setStage]=useState<"reveal"|"research"|"dossier"|"stay"|"final">("reveal"),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[media,setMedia]=useState<Media|null>(null),[email,setEmail]=useState(""),[mailState,setMailState]=useState<"idle"|"sending"|"sent"|"error">("idle");
 const hero=media?.imageUrl||selected?.imageUrl||selected?.thumbUrl||null,currentOffer=plan?.stay?.trackingUrl||selected?.trackingUrl||"",guideUrl=plan?.guide.path||"",weatherDays=useMemo(()=>dossier?.weather.days.slice(0,5)??[],[dossier]);
 useEffect(()=>{let cancelled=false;fetch(`/api/escape/media?destination=${encodeURIComponent(nameEn||name)}`).then(r=>r.json()).then((d:{items?:Media[]})=>{if(!cancelled)setMedia(d.items?.[0]??null)}).catch(()=>undefined);return()=>{cancelled=true}},[name,nameEn]);
 const track=(eventName:string,payload:Record<string,unknown>={})=>{if(missionId)void fetch("/api/escape/event",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,eventName,payload})}).catch(()=>null)};

 async function research(){setBusy(true);setError(null);setStage("research");try{if(missionId)await fetch("/api/escape/select",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,destinationId:slug})}).catch(()=>null);const response=await fetch("/api/escape/research",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip,slug})});if(!response.ok)throw new Error("research");const data=await response.json() as Dossier;setDossier(data);setStage("dossier");track("destination_research_completed",{destinationId:slug})}catch{setError(say(lang,"Δεν ολοκληρώθηκε ακόμη ο 360° έλεγχος. Η επιλογή σου έχει κρατηθεί.","The 360° check is not complete yet. Your choice has been saved."));setStage("reveal")}finally{setBusy(false)}}
 async function buildFinal(){if(!selected)return;setBusy(true);setError(null);try{const response=await fetch("/api/trip-builder",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip,slug,offerId:selected.sourceProductId})});if(!response.ok)throw new Error("builder");const built=await response.json() as TripBuilderPlanV25;setPlan(built);setStage("final");if(missionId){const mediaRows=[built.stay?.imageUrl?{kind:"stay",url:built.stay.imageUrl}:null,...built.tripadvisor.places.map(x=>x.imageUrl?{kind:x.kind,url:x.imageUrl,name:x.name}:null)].filter(Boolean).slice(0,20);void fetch("/api/escape/research/complete",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,destinationId:slug,weather:built.weather,places:built.webResearch.bullets,restaurants:built.tripadvisor.restaurants,practicalNotes:built.webResearch.practicalNotes,logistics:{availability:built.availability,flexibleWindows:built.flexibleWindows,budgetBeyondHotel:built.budgetBeyondHotel},sources:built.webResearch.sources,media:mediaRows,guidePath:built.guide.path,trackingUrl:built.stay?.trackingUrl??selected.trackingUrl})}).catch(()=>null)}}catch{setError(say(lang,"Δεν μπόρεσα να επαληθεύσω αυτή τη διαμονή με ασφάλεια.","I could not verify this stay safely."))}finally{setBusy(false)}}
 async function share(){const url=window.location.href,text=say(lang,`Τι λες για ${destination}; Δες την απόδραση που μας έφτιαξε ο AI travel expert.`,`What do you think about ${destination}? See the escape our AI travel expert built.`);if(navigator.share)await navigator.share({title:destination,text,url}).catch(()=>undefined);else await navigator.clipboard.writeText(url).catch(()=>undefined);track("escape_shared",{destinationId:slug})}
 async function sendEmail(event:FormEvent){event.preventDefault();if(!selected||!email)return;setMailState("sending");try{const response=await fetch("/api/guide/email",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,slug,start:trip.startDate,end:trip.endDate,offer:selected.sourceProductId,language:lang})});if(!response.ok)throw new Error();if(missionId)await fetch("/api/escape/email-state",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,email})}).catch(()=>null);setMailState("sent")}catch{setMailState("error")}}

 const highlightImages=[...(dossier?.places.places??[]),...(dossier?.places.beaches??[]),...(dossier?.places.restaurants??[])].filter(x=>x.imageUrl).slice(0,4);
 return <main className={styles.shell}>
  <section className={styles.hero} style={hero?{backgroundImage:`linear-gradient(180deg,rgba(3,9,8,.16),rgba(3,9,8,.32) 45%,rgba(3,9,8,.92)),url('${hero}')`}:undefined}><div className={styles.heroMotion}/><a className={styles.back} href={lang==="en"?"/en":"/"}>← {say(lang,"Άλλαξε επιλογή","Change choice")}</a><div className={styles.heroContent}><span>YOUR ESCAPE · {trip.startDate} → {trip.endDate}</span><h1>{destination}</h1><p>{say(lang,"Δεν θα σου δείξω ξενοδοχεία ακόμη. Πρώτα θέλω να δεις αν αυτό το μέρος μπορεί πραγματικά να γίνει το ταξίδι που χρειάζεσαι.","I will not show you hotels yet. First I want to see whether this place can really become the trip you need.")}</p>{stage==="reveal"&&<button onClick={research} disabled={busy}>{say(lang,"Δείξε μου γιατί ταιριάζει →","Show me why it fits →")}</button>}{media&&<small className={styles.credit}>Photo: {media.attribution} · {media.license}</small>}</div></section>

  {stage==="research"&&<section className={styles.research}><div className={styles.pulse}/><span>360° DESTINATION RESEARCH</span><h2>{say(lang,"Ελέγχω το ταξίδι — όχι τη διαφήμιση.","Checking the trip — not the sales pitch.")}</h2><p>{say(lang,"Καιρός, μέρη, φαγητό, ρυθμός, πρακτικά, κρυφά κόστη και τι αξίζει πραγματικά στις δικές σου ημερομηνίες.","Weather, places, food, pace, practical friction, hidden costs and what is genuinely worth your time on your dates.")}</p></section>}

  {dossier&&(stage==="dossier"||stage==="stay"||stage==="final")&&<section className={styles.dossier}><div className={styles.intro}><span>WHY HERE · WHY NOW</span><h2>{dossier.research.overview||say(lang,"Αυτό είναι το πραγματικό σχήμα της απόδρασης.","This is the real shape of the escape.")}</h2></div><div className={styles.weatherStrip}>{weatherDays.map(day=><article key={day.date}><small>{day.date.slice(5)}</small><strong>{day.temperatureMinC==null?"?":Math.round(day.temperatureMinC)}–{day.temperatureMaxC==null?"?":Math.round(day.temperatureMaxC)}°</strong><p>{day.summary}</p></article>)}</div>
   <div className={styles.storyGrid}><article><span>{say(lang,"ΤΙ ΔΕΝ ΘΑ ΕΧΑΝΑ","WHAT I WOULD NOT MISS")}</span><h3>{say(lang,"Λίγα πράγματα, σωστά επιλεγμένα.","Fewer things, better chosen.")}</h3><ul>{dossier.research.attractions.slice(0,5).map((x,i)=><li key={`${x.name}-${i}`}><strong>{x.name}</strong><p>{x.whyItFits||x.summary}</p></li>)}</ul></article><article><span>LOCAL LIFE</span><h3>{say(lang,"Φαγητό και μέρη που αξίζουν χώρο στο ταξίδι.","Food and places that deserve space in the trip.")}</h3><div className={styles.placeList}>{dossier.places.restaurants.slice(0,4).map(x=><div key={x.locationId}>{x.imageUrl?<img src={x.imageUrl} alt=""/>:null}<div><strong>{x.name}</strong><small>{x.rating!=null?`${x.rating}/5`:""}{x.reviewCount?` · ${x.reviewCount} reviews`:""}</small><p>{x.description}</p></div></div>)}</div></article></div>
   {highlightImages.length>0&&<div className={styles.gallery}>{highlightImages.map((x,i)=><figure key={`${x.locationId}-${i}`}><img src={x.imageUrl||""} alt={x.name}/><figcaption>{x.name}</figcaption></figure>)}</div>}
   <div className={styles.storyGrid}><article><span>{say(lang,"ΝΑ ΞΕΡΕΙΣ ΠΡΙΝ ΦΥΓΕΙΣ","KNOW BEFORE YOU GO")}</span><h3>{say(lang,"Δεν θα κρύψω τα trade-offs.","I will not hide the trade-offs.")}</h3><ul>{dossier.research.practicalNotes.slice(0,7).map((note,i)=><li key={i}><p>{note}</p></li>)}</ul></article><article><span>{say(lang,"ΚΟΣΤΟΣ ΕΚΤΟΣ ΔΙΑΜΟΝΗΣ","BEYOND THE STAY")}</span><h3>€{dossier.budgetBeyondHotel.totalLow}–€{dossier.budgetBeyondHotel.totalHigh}</h3><p>{dossier.budgetBeyondHotel.note}</p><small>{say(lang,"Εκτίμηση, όχι προσφορά. Άγνωστα κόστη δεν μηδενίζονται.","Estimate, not an offer. Unknown costs are not treated as zero.")}</small></article></div>
   {stage==="dossier"&&<div className={styles.commit}><span>{say(lang,"ΑΝ ΑΥΤΟ ΣΟΥ ΜΙΛΑΕΙ...","IF THIS FEELS RIGHT...")}</span><h2>{say(lang,"Τώρα έχει νόημα να βρούμε πού θα μείνεις.","Now it makes sense to decide where to stay.")}</h2><button onClick={()=>setStage("stay")}>{say(lang,"Βρες τη σωστή βάση →","Find the right base →")}</button></div>}
  </section>}

  {stage==="stay"&&<section className={styles.stays}><span>STAY MATCH</span><h2>{say(lang,"Μία βάση που ταιριάζει στο ταξίδι — όχι ένα wall από offers.","A base that fits the trip — not a wall of offers.")}</h2>{offers.length?<div className={styles.stayGrid}>{offers.slice(0,3).map((offer,index)=><button key={offer.sourceProductId} className={selected?.sourceProductId===offer.sourceProductId?styles.activeStay:""} onClick={()=>setSelected(offer)}>{offer.imageUrl||offer.thumbUrl?<img src={offer.imageUrl||offer.thumbUrl||""} alt=""/>:null}<div><small>{index===0?say(lang,"Κύρια επιλογή","Primary match"):index===1?say(lang,"Καλύτερη αξία","Value alternative"):say(lang,"Εναλλακτική","Alternative")}</small><strong>{offer.propertyName}</strong><span>{offer.city||destination}</span>{offer.price!=null?<b>{offer.price.toLocaleString(lang==="el"?"el-GR":"en-GB")} {offer.currency||"EUR"}</b>:null}</div></button>)}</div>:<div className={styles.empty}>{say(lang,"Δεν υπάρχει αυτή τη στιγμή έγκυρη διαμονή για όλο το διάστημα. Το ταξίδι παραμένει αποθηκευμένο — δεν θα εμφανίσουμε ψεύτικη διαθεσιμότητα.","There is no fully valid stay for the whole period right now. The trip stays saved — we will not fabricate availability.")}</div>}<button className={styles.primary} disabled={!selected||busy} onClick={buildFinal}>{busy?say(lang,"Επιβεβαιώνω τη διαμονή...","Verifying the stay..."):say(lang,"Ολοκλήρωσε το Escape Book →","Complete the Escape Book →")}</button></section>}

  {stage==="final"&&plan&&<section className={styles.final}><span>{say(lang,"Η ΑΠΟΔΡΑΣΗ ΕΙΝΑΙ ΕΤΟΙΜΗ","YOUR ESCAPE IS READY")}</span><h2>{plan.stay?.propertyName}</h2><p>{say(lang,"Πρώτα αποφάσισες το ταξίδι. Τώρα μπορείς να ελέγξεις την τρέχουσα προσφορά στον πάροχο. Τελική τιμή, δωμάτιο και διαθεσιμότητα επιβεβαιώνονται εκεί.","You decided the trip first. Now you can check the current provider offer. Final price, room and availability are confirmed there.")}</p><div className={styles.actions}>{currentOffer&&<a href={currentOffer} target="_blank" rel="sponsored nofollow noopener" onClick={()=>track("affiliate_offer_opened",{destinationId:slug,offerId:selected?.sourceProductId})}>{say(lang,"Δες την τρέχουσα προσφορά ↗","View current offer ↗")}</a>}{guideUrl&&<a href={guideUrl} target="_blank" rel="noopener" onClick={()=>track("guide_downloaded",{destinationId:slug})}>{say(lang,"Escape Book PDF","Escape Book PDF")}</a>}<button onClick={share}>{say(lang,"Μοιράσου την απόδραση","Share the escape")}</button></div><form onSubmit={sendEmail} className={styles.email}><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><button disabled={mailState==="sending"}>{mailState==="sending"?say(lang,"Αποστολή...","Sending..."):say(lang,"Στείλε το Escape Book","Send Escape Book")}</button>{mailState==="sent"&&<small>{say(lang,"Στάλθηκε.","Sent.")}</small>}{mailState==="error"&&<small>{say(lang,"Δεν στάλθηκε — χρησιμοποίησε το PDF.","Could not send — use the PDF.")}</small>}</form></section>}
  {error&&<div className={styles.error}>{error}</div>}
 </main>
}
