"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { V8RecommendationResponse } from "@/lib/decision/v8-types";
import styles from "./v34-escape-funnel.module.css";

type Lang="el"|"en";
type QuestionId="companions"|"outcome"|"social"|"novelty"|"must_have"|"friction";
type Answer={questionId:QuestionId;value:string};
type Profile={travelerType:"solo"|"couple"|"family"|"friends";moods:Array<"relax"|"romantic"|"food"|"warmth"|"city"|"nature"|"adventure"|"culture">;pace:"slow"|"balanced"|"full";desiredEnergy:"restore"|"balanced"|"stimulating";socialPreference:"quiet"|"balanced"|"lively";noveltyPreference:"familiar"|"balanced"|"surprise";avoid:"long-travel"|"high-cost"|"crowds"|"none";mustHave:"sea"|"nature"|"culture"|"nightlife"|"none";dnaLabels:string[]};
type Discovery={summary:string;profile:Profile;answered:QuestionId[];nextQuestionId:QuestionId|null;confidence:number;complete:boolean};
type Window={id:string;label:string;note:string;start:string;end:string};
type StreamRow={type:string;progress:number;message?:string};
type Media={imageUrl:string;sourceUrl:string;title:string;license:string;attribution:string};

const say=(lang:Lang,el:string,en:string)=>lang==="el"?el:en;
const DAY=86_400_000;
const iso=(d:Date)=>d.toISOString().slice(0,10);
const add=(d:Date,days:number)=>new Date(d.getTime()+days*DAY);
function nextWeekday(base:Date,weekday:number){const d=new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth(),base.getUTCDate()));const delta=(weekday-d.getUTCDay()+7)%7||7;return add(d,delta)}
function groupSize(type:Profile["travelerType"]){return type==="solo"?1:type==="couple"?2:4}

const QUESTIONS:Record<QuestionId,{el:string;en:string;options:Array<{value:string;el:string;en:string;hintEl:string;hintEn:string}>}>={
 companions:{el:"Ποιος θα είναι μαζί σου;",en:"Who are you escaping with?",options:[{value:"solo",el:"Μόνος/η",en:"Solo",hintEl:"Χωρίς συμβιβασμούς.",hintEn:"No compromises."},{value:"couple",el:"Με τον άνθρωπό μου",en:"With my partner",hintEl:"Χρόνος για δύο.",hintEn:"Time for two."},{value:"family",el:"Με παιδιά",en:"With kids",hintEl:"Να περάσουμε όλοι καλά.",hintEn:"Make it work for everyone."},{value:"friends",el:"Με φίλους",en:"With friends",hintEl:"Κοινές στιγμές και ενέργεια.",hintEn:"Shared moments and energy."}]},
 outcome:{el:"Όταν επιστρέψεις, πώς θέλεις να νιώθεις;",en:"How do you want to feel when you come back?",options:[{value:"restore",el:"Ξεκούραστος πραγματικά",en:"Actually rested",hintEl:"Χαμηλοί ρυθμοί, ανάσα.",hintEn:"Slower pace, proper reset."},{value:"balanced",el:"Γεμάτος όμορφες στιγμές",en:"Full of good memories",hintEl:"Ισορροπία εμπειρίας και άνεσης.",hintEn:"A balance of experience and ease."},{value:"stimulating",el:"Ζωντανός και ενθουσιασμένος",en:"Alive and energized",hintEl:"Κάτι που θα θυμάμαι.",hintEn:"Something memorable."}]},
 social:{el:"Τι ατμόσφαιρα αντέχεις αυτή τη στιγμή;",en:"What kind of atmosphere fits you right now?",options:[{value:"quiet",el:"Ήσυχα",en:"Quiet",hintEl:"Λιγότερος κόσμος, περισσότερο χώρος.",hintEn:"Less crowd, more space."},{value:"balanced",el:"Λίγη ζωή, χωρίς χάος",en:"Some life, no chaos",hintEl:"Να έχω επιλογές αλλά και ησυχία.",hintEn:"Options without overload."},{value:"lively",el:"Θέλω ενέργεια",en:"I want energy",hintEl:"Βόλτες, bars, βραδινή ζωή.",hintEn:"Streets, bars, nights out."}]},
 novelty:{el:"Πόσο μακριά από το γνώριμο θέλεις να πας;",en:"How far from familiar do you want to go?",options:[{value:"familiar",el:"Θέλω σιγουριά",en:"Keep it familiar",hintEl:"Εύκολο και προβλέψιμο.",hintEn:"Easy and predictable."},{value:"balanced",el:"Κάτι νέο, αλλά όχι ρίσκο",en:"New, but not risky",hintEl:"Ανακάλυψη με ασφάλεια.",hintEn:"Discovery with confidence."},{value:"surprise",el:"Έκπληξέ με",en:"Surprise me",hintEl:"Δείξε μου κάτι που δεν θα έψαχνα.",hintEn:"Show me what I would not search for."}]},
 must_have:{el:"Αν ένα πράγμα έπρεπε να είναι τέλειο, ποιο;",en:"If one thing had to be perfect, what would it be?",options:[{value:"sea",el:"Θάλασσα / φως",en:"Sea / light",hintEl:"Να ανοίγει το μάτι.",hintEn:"Space, light, horizon."},{value:"nature",el:"Φύση",en:"Nature",hintEl:"Πράσινο, βουνό, διαδρομές.",hintEn:"Green, mountains, trails."},{value:"culture",el:"Ιστορία / κουλτούρα",en:"Culture / history",hintEl:"Να έχει κάτι να ανακαλύψω.",hintEn:"Something worth discovering."},{value:"nightlife",el:"Βραδινή ζωή",en:"Nightlife",hintEl:"Να μην τελειώνει νωρίς η μέρα.",hintEn:"Let the day continue after dark."},{value:"none",el:"Δεν έχω must-have",en:"No must-have",hintEl:"Βρες την καλύτερη συνολική ισορροπία.",hintEn:"Find the best overall balance."}]},
 friction:{el:"Τι δεν θέλεις να πληρώσεις με χρόνο ή νεύρα;",en:"What do you not want to pay for with time or energy?",options:[{value:"long-travel",el:"Πολλές ώρες μετακίνησης",en:"Long travel",hintEl:"Θέλω να αρχίσουν γρήγορα οι διακοπές.",hintEn:"I want the holiday to start fast."},{value:"crowds",el:"Πολύ κόσμο",en:"Crowds",hintEl:"Δεν θέλω να νιώθω ότι είμαι σε ουρά.",hintEn:"I do not want queue energy."},{value:"high-cost",el:"Να πληρώσω premium χωρίς λόγο",en:"Paying premium for no reason",hintEl:"Θέλω αξία, όχι φθηνότερο πάση θυσία.",hintEn:"Value, not cheap at any cost."},{value:"none",el:"Δεν με περιορίζει κάτι ιδιαίτερα",en:"Nothing specific",hintEl:"Έχουμε μεγαλύτερο χώρο επιλογών.",hintEn:"Keep the option space wide."}]}
};

function suggestedWindows(lang:Lang,duration=3):Window[]{const now=new Date(),fri=nextWeekday(now,5),fri2=add(fri,14),sun=nextWeekday(add(now,7),0);return[
 {id:"easy",label:say(lang,"Το εύκολο weekend","The easy weekend"),note:say(lang,"Παρασκευή αναχώρηση · λίγες ημέρες άδειας","Friday departure · minimal leave"),start:iso(fri),end:iso(add(fri,duration))},
 {id:"space",label:say(lang,"Το weekend με χώρο","The weekend with room"),note:say(lang,"Λίγο αργότερα · περισσότερες επιλογές","A little later · more options"),start:iso(fri2),end:iso(add(fri2,duration))},
 {id:"quiet",label:say(lang,"Η πιο ήσυχη εκδοχή","The quieter version"),note:say(lang,"Κυριακή–μέσα εβδομάδας · λιγότερη πίεση","Sunday–midweek · lower pressure"),start:iso(sun),end:iso(add(sun,duration))}
]}

export function V34EscapeFunnel({lang="el"}:{lang?:Lang}){
 const [initialText,setInitialText]=useState("");const [answers,setAnswers]=useState<Answer[]>([]);const [discovery,setDiscovery]=useState<Discovery|null>(null);const [stage,setStage]=useState<"listen"|"questions"|"dna"|"dates"|"constraints"|"research"|"results">("listen");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
 const [dateMode,setDateMode]=useState<"suggest"|"fixed"|"flexible">("suggest");const [duration,setDuration]=useState(3);const windows=useMemo(()=>suggestedWindows(lang,duration),[lang,duration]);const [windowId,setWindowId]=useState("easy");const [fixedStart,setFixedStart]=useState(windows[0].start);const [fixedEnd,setFixedEnd]=useState(windows[0].end);
 const [origin,setOrigin]=useState(say(lang,"Αθήνα","Athens"));const [budget,setBudget]=useState(900);const [result,setResult]=useState<V8RecommendationResponse|null>(null);const [rows,setRows]=useState<StreamRow[]>([]);const [missionId,setMissionId]=useState<string|null>(null);const [media,setMedia]=useState<Record<string,Media>>({});
 const selectedWindow=dateMode==="fixed"?{id:"fixed",label:say(lang,"Οι ημερομηνίες μου","My dates"),note:"",start:fixedStart,end:fixedEnd}:windows.find(w=>w.id===windowId)??windows[0];

 async function discover(nextAnswers=answers){setBusy(true);setError(null);try{const r=await fetch("/api/escape/discovery",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,initialText,answers:nextAnswers})});if(!r.ok)throw new Error("discovery");const d=await r.json() as Discovery;setDiscovery(d);setStage(d.complete?"dna":"questions")}catch{setError(say(lang,"Δεν κατάφερα να καταλάβω αρκετά. Δοκίμασε ξανά με λίγες περισσότερες λέξεις.","I could not understand enough yet. Try again with a little more detail."))}finally{setBusy(false)}}
 async function start(event:FormEvent){event.preventDefault();if(initialText.trim().length<3)return;await discover([])}
 async function answer(questionId:QuestionId,value:string){const next=[...answers.filter(a=>a.questionId!==questionId),{questionId,value}];setAnswers(next);await discover(next)}

 async function createMission(){if(!discovery)return null;try{const r=await fetch("/api/escape/mission",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,originText:origin,travelWindow:{label:selectedWindow.label,start:selectedWindow.start,end:selectedWindow.end},needText:initialText.slice(0,500),travelerType:discovery.profile.travelerType,groupSize:groupSize(discovery.profile.travelerType),budgetEur:budget,dna:discovery.profile.dnaLabels})});if(!r.ok)return null;const d=await r.json() as {missionId?:string};return d.missionId??null}catch{return null}}
 async function persistFinalists(id:string,finalResult:V8RecommendationResponse){const finalists=finalResult.recommendations.slice(0,3).map(x=>({slug:x.slug,score:x.score,why:x.why,seasonNote:x.seasonNote,budgetLabel:x.budgetLabel,effortLabel:x.effortLabel}));await fetch("/api/escape/matches",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId:id,finalists})}).catch(()=>null)}

 async function solve(){if(!discovery||!selectedWindow)return;setBusy(true);setError(null);setRows([]);setResult(null);setStage("research");const id=await createMission();setMissionId(id);const nights=Math.max(1,Math.round((Date.parse(`${selectedWindow.end}T00:00:00Z`)-Date.parse(`${selectedWindow.start}T00:00:00Z`))/DAY));const tripText=`${initialText}. ${discovery.summary}`.slice(0,320);const payload={origin,startDate:selectedWindow.start,endDate:selectedWindow.end,month:"flexible",nights,budget,moods:discovery.profile.moods.length?discovery.profile.moods:["relax"],travelerType:discovery.profile.travelerType,groupSize:groupSize(discovery.profile.travelerType),language:lang,distancePreference:"any",pace:discovery.profile.pace,hotelStyle:"any",avoid:discovery.profile.avoid,entryMode:"unknown",desiredEnergy:discovery.profile.desiredEnergy,socialPreference:discovery.profile.socialPreference,noveltyPreference:discovery.profile.noveltyPreference,mustHave:discovery.profile.mustHave,dateFlexibility:dateMode==="fixed"?"fixed":"few-days",transportMode:"any",stayLocationPreference:"balanced",tripText};
 try{const response=await fetch("/api/recommend/stream",{method:"POST",headers:{"content-type":"application/json",accept:"application/x-ndjson"},body:JSON.stringify(payload)});if(!response.ok)throw new Error("recommend");const reader=response.body?.getReader();if(!reader)throw new Error("stream");const decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines){if(!line.trim())continue;const item=JSON.parse(line) as StreamRow&{result?:V8RecommendationResponse};if(item.type==="final"&&item.result){setResult(item.result);setStage("results");if(id)void persistFinalists(id,item.result)}else setRows(current=>[...current,item])}}}catch{setError(say(lang,"Η ανάλυση δεν ολοκληρώθηκε. Κράτησα το προφίλ σου — μπορείς να ξαναδοκιμάσεις.","The analysis did not complete. I kept your profile — you can try again."));setStage("constraints")}finally{setBusy(false)}}

 useEffect(()=>{const shortlist=result?.recommendations.slice(0,3)??[];if(!shortlist.length)return;let cancelled=false;Promise.all(shortlist.map(async rec=>{try{const r=await fetch(`/api/escape/media?destination=${encodeURIComponent(rec.destinationEn||rec.destination)}`);const d=await r.json() as {items?:Media[]};return[rec.slug,d.items?.[0]??null] as const}catch{return[rec.slug,null] as const}})).then(entries=>{if(cancelled)return;const next:Record<string,Media>={};for(const [slug,item] of entries)if(item)next[slug]=item;setMedia(next)});return()=>{cancelled=true}},[result]);

 const q=discovery?.nextQuestionId?QUESTIONS[discovery.nextQuestionId]:null;const shortlist=result?.recommendations.slice(0,3)??[];const roleLabels=[say(lang,"Η σωστή για σένα","The right one"),say(lang,"Η συναισθηματική επιλογή","The emotional one"),say(lang,"Η απρόσμενη","The unexpected one")];
 return <main className={styles.shell}>
  <header className={styles.nav}><a className={styles.brand} href={lang==="en"?"/en":"/"}>AI TRAVEL <span>ESCAPE</span></a><a className={styles.lang} href={lang==="en"?"/":"/en"}>{lang==="en"?"Ελληνικά":"English"}</a></header>
  <section className={styles.hero}><div className={styles.aurora}/><div className={styles.heroInner}><p className={styles.kicker}>AI TRAVEL DECISION SYSTEM</p><h1>{say(lang,"Δεν χρειάζεται να ξέρεις πού θέλεις να πας.","You do not need to know where you want to go.")}</h1><p className={styles.lead}>{say(lang,"Πες μου τι χρειάζεσαι από αυτή την απόδραση. Θα μάθω πρώτα εσένα — μετά θα βρω πότε και πού αξίζει να φύγεις.","Tell me what you need from this escape. I will understand you first — then work out when and where it makes sense to go.")}</p>{stage==="listen"&&<form onSubmit={start} className={styles.listen}><textarea value={initialText} onChange={e=>setInitialText(e.target.value)} placeholder={say(lang,"π.χ. Είμαι κουρασμένος, θέλω 4 μέρες με τη σύντροφό μου, χωρίς πολύ τρέξιμο, με καλό φαγητό...","e.g. I am exhausted. I want four days with my partner, little hassle, great food...")} maxLength={700}/><button disabled={busy||initialText.trim().length<3}>{busy?say(lang,"Σε ακούω...","Listening..."):say(lang,"Κατάλαβέ με πρώτα","Understand me first")}</button></form>}<div className={styles.promise}><span>{say(lang,"1 · Σε καταλαβαίνω","1 · Understand you")}</span><span>{say(lang,"2 · Βρίσκω πότε","2 · Find when")}</span><span>{say(lang,"3 · Βρίσκω πού","3 · Find where")}</span><span>{say(lang,"4 · Χτίζω το ταξίδι","4 · Build the trip")}</span></div></div></section>

  {stage==="questions"&&q&&discovery&&<section className={styles.dialogue}><div className={styles.aiBubble}><span>AI</span><p>{discovery.summary}</p></div><div className={styles.question}><p className={styles.step}>AI DISCOVERY</p><h2>{say(lang,q.el,q.en)}</h2><div className={styles.optionGrid}>{q.options.map(option=><button key={option.value} disabled={busy} onClick={()=>answer(discovery.nextQuestionId!,option.value)}><strong>{say(lang,option.el,option.en)}</strong><small>{say(lang,option.hintEl,option.hintEn)}</small></button>)}</div></div></section>}

  {stage==="dna"&&discovery&&<section className={styles.dna}><p className={styles.step}>ESCAPE DNA</p><h2>{say(lang,"Νομίζω ότι αυτό είναι που χρειάζεσαι τώρα.","I think this is what you need right now.")}</h2><blockquote>{discovery.summary}</blockquote><div className={styles.dnaChips}>{discovery.profile.dnaLabels.map(label=><span key={label}>{label}</span>)}</div><div className={styles.dnaActions}><button className={styles.primary} onClick={()=>setStage("dates")}>{say(lang,"Ναι — βρες πότε αξίζει","Yes — find when it makes sense")}</button><button className={styles.secondary} onClick={()=>setStage("listen")}>{say(lang,"Όχι ακριβώς — ξαναπές το","Not quite — let me restate it")}</button></div></section>}

  {stage==="dates"&&discovery&&<section className={styles.panel}><p className={styles.step}>TIME STRATEGY</p><h2>{say(lang,"Θες να μου πεις πότε ή να σου προτείνω εγώ;","Tell me when — or let me suggest it.")}</h2><div className={styles.modeGrid}>{(["suggest","fixed","flexible"] as const).map(mode=><button key={mode} className={dateMode===mode?styles.activeMode:""} onClick={()=>setDateMode(mode)}><strong>{mode==="suggest"?say(lang,"Πρότεινέ μου","Suggest dates"):mode==="fixed"?say(lang,"Ξέρω πότε","I know when"):say(lang,"Έχω ευελιξία","I am flexible")}</strong><small>{mode==="suggest"?say(lang,"Δώσε μου 3 λογικά παράθυρα","Give me three sensible windows"):mode==="fixed"?say(lang,"Έχω συγκεκριμένες ημερομηνίες","I have exact dates"):say(lang,"Μπορώ να κινηθώ λίγο","I can move things around")}</small></button>)}</div>{dateMode==="fixed"?<div className={styles.fixedDates}><label>{say(lang,"Αναχώρηση","Departure")}<input type="date" value={fixedStart} min={iso(new Date())} onChange={e=>setFixedStart(e.target.value)}/></label><label>{say(lang,"Επιστροφή","Return")}<input type="date" value={fixedEnd} min={fixedStart} onChange={e=>setFixedEnd(e.target.value)}/></label></div>:<><div className={styles.duration}><span>{say(lang,"Πόσες νύχτες;","How many nights?")}</span>{[2,3,4,7].map(n=><button key={n} className={duration===n?styles.selectedPill:""} onClick={()=>setDuration(n)}>{n}</button>)}</div><div className={styles.windowGrid}>{windows.map(w=><button key={w.id} className={windowId===w.id?styles.selectedWindow:""} onClick={()=>setWindowId(w.id)}><strong>{w.label}</strong><span>{w.start} → {w.end}</span><small>{w.note}</small></button>)}</div></>}<button className={styles.primary} onClick={()=>setStage("constraints")}>{say(lang,"Κράτα αυτό το παράθυρο","Use this window")}</button></section>}

  {stage==="constraints"&&discovery&&<section className={styles.panel}><p className={styles.step}>REALITY CHECK</p><h2>{say(lang,"Μόνο ό,τι μπορεί πραγματικά να αλλάξει την απόφαση.","Only what can genuinely change the decision.")}</h2><div className={styles.constraintGrid}><label>{say(lang,"Από πού ξεκινάς;","Starting from?")}<input value={origin} onChange={e=>setOrigin(e.target.value)}/></label><label>{say(lang,"Άνετο συνολικό budget","Comfortable total budget")}<div className={styles.budgetPills}>{[500,900,1400,2000].map(v=><button type="button" key={v} className={budget===v?styles.selectedPill:""} onClick={()=>setBudget(v)}>€{v}</button>)}</div></label></div><div className={styles.brief}><span>{say(lang,"Αυτό θα ψάξω:","This is what I will solve:")}</span><p>{discovery.summary}</p><small>{selectedWindow.start} → {selectedWindow.end} · {origin} · €{budget}</small></div><button className={styles.primary} disabled={busy||origin.trim().length<2} onClick={solve}>{say(lang,"Βρες τις 3 αποδράσεις μου","Find my three escapes")}</button></section>}

  {stage==="research"&&<section className={styles.research}><div className={styles.pulse}/><p className={styles.step}>SEMANTIC MATCHING</p><h2>{say(lang,"Δεν ψάχνω ξενοδοχεία ακόμα. Ψάχνω ποια ταξίδια ταιριάζουν σε εσένα.","I am not searching hotels yet. I am finding which trips fit you.")}</h2><div className={styles.researchLines}>{rows.slice(-5).map((row,i)=><span key={`${row.type}-${i}`}>{row.message||say(lang,"Ελέγχω εποχή, πρόσβαση, ρυθμό και πραγματικό fit...","Checking season, access, pace and real fit...")}</span>)}</div></section>}

  {stage==="results"&&result&&<section className={styles.results}><div className={styles.resultsHead}><p className={styles.step}>YOUR ESCAPES</p><h2>{say(lang,"Τρεις επιλογές επέζησαν.","Three escapes survived.")}</h2><p>{result.profileSummary}</p></div><div className={styles.cards}>{shortlist.map((rec,index)=>{const image=media[rec.slug];const href=`/escape/${encodeURIComponent(rec.slug)}?start=${selectedWindow.start}&end=${selectedWindow.end}&budget=${budget}&travelerType=${discovery?.profile.travelerType??"couple"}&mood=${discovery?.profile.moods[0]??"relax"}&origin=${encodeURIComponent(origin)}&lang=${lang}${missionId?`&mission=${missionId}`:""}`;return <article key={rec.slug} className={styles.destinationCard}>{image?<><img src={image.imageUrl} alt={rec.destination} loading={index===0?"eager":"lazy"}/><div className={styles.kenBurns}/></>:<div className={styles.imageFallback}/>}<div className={styles.cardShade}/><div className={styles.cardContent}><span className={styles.role}>{roleLabels[index]}</span><h3>{lang==="en"?rec.destinationEn:rec.destination}</h3><p>{rec.why}</p><div className={styles.facts}><span>{rec.seasonNote}</span><span>{rec.effortLabel}</span><span>{rec.budgetLabel}</span></div><details><summary>{say(lang,"Το trade-off που πρέπει να ξέρεις","The trade-off to know")}</summary><p>{rec.explorationReason}</p></details><a className={styles.choose} href={href}>{say(lang,"Ναι — χτίσε αυτή την απόδραση","Yes — build this escape")}</a>{image&&<small className={styles.credit}>Photo: {image.attribution} · {image.license}</small>}</div></article>})}</div><button className={styles.secondary} onClick={()=>setStage("dates")}>{say(lang,"Άλλαξε ημερομηνίες","Change dates")}</button></section>}

  {error&&<div className={styles.error}>{error}</div>}
 </main>
}
