"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import type { EscapeSolutionResponseV36,EscapeSolutionV36 } from "@/lib/decision/solution-ranking-v36";
import styles from "./v36-escape-funnel.module.css";

type Lang="el"|"en";
type Stage="mood"|"dna"|"time"|"reality"|"solve"|"results";
type QuestionId="companions"|"outcome"|"social"|"novelty"|"must_have"|"friction";
type Answer={questionId:QuestionId;value:string};
type Profile={travelerType:"solo"|"couple"|"family"|"friends";moods:Array<"relax"|"romantic"|"food"|"warmth"|"city"|"nature"|"adventure"|"culture">;pace:"slow"|"balanced"|"full";desiredEnergy:"restore"|"balanced"|"stimulating";socialPreference:"quiet"|"balanced"|"lively";noveltyPreference:"familiar"|"balanced"|"surprise";avoid:"long-travel"|"high-cost"|"crowds"|"none";mustHave:"sea"|"nature"|"culture"|"nightlife"|"none";dnaLabels:string[]};
type Discovery={summary:string;profile:Profile;answered:QuestionId[];nextQuestionId:QuestionId|null;confidence:number;complete:boolean};
type DateWindow={id:string;label:string;note:string;start:string;end:string;reason?:string;confidence?:"HIGH"|"MEDIUM"};
type StreamRow={type:string;progress?:number;message?:string};
type Media={imageUrl:string;sourceUrl:string;title:string;description?:string;license:string;attribution:string};
type World={id:string;query:string;el:string;en:string;hintEl:string;hintEn:string;semanticEl:string;semanticEn:string};

const say=(lang:Lang,el:string,en:string)=>lang==="el"?el:en;
const DAY=86_400_000,iso=(d:Date)=>d.toISOString().slice(0,10),add=(d:Date,days:number)=>new Date(d.getTime()+days*DAY);
const groupSize=(type:Profile["travelerType"])=>type==="solo"?1:type==="couple"?2:4;
function nextWeekday(base:Date,weekday:number,weekOffset=0){const d=new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth(),base.getUTCDate())),delta=(weekday-d.getUTCDay()+7)%7||7;return add(d,delta+weekOffset*7)}

const WORLDS:World[]=[
 {id:"sea-light",query:"Mediterranean island aerial coast",el:"Θάλασσα & φως",en:"Sea & light",hintEl:"Ορίζοντας · νερό · αργός ρυθμός",hintEn:"Horizon · water · slow rhythm",semanticEl:"Θέλω θάλασσα, φως και αργό μεσογειακό ρυθμό.",semanticEn:"I want sea, light and a slow Mediterranean rhythm."},
 {id:"city-night",query:"European old town aerial evening",el:"Πόλη & βράδυ",en:"City & evenings",hintEl:"Βόλτες · φαγητό · ατμόσφαιρα",hintEn:"Walking · food · atmosphere",semanticEl:"Θέλω ατμοσφαιρική πόλη, καλό φαγητό και βραδινή ζωή.",semanticEn:"I want an atmospheric city, great food and evening life."},
 {id:"green-reset",query:"Madeira aerial green mountains",el:"Πράσινο & reset",en:"Green & reset",hintEl:"Φύση · ανάσα · καθαρό μυαλό",hintEn:"Nature · breathing room · reset",semanticEl:"Θέλω πράσινο, φύση και πραγματική αποφόρτιση.",semanticEn:"I want greenery, nature and a proper reset."},
 {id:"mountain-cozy",query:"Alpine village aerial winter mountains",el:"Βουνό & θαλπωρή",en:"Mountains & warmth",hintEl:"Τοπίο · ησυχία · cozy",hintEn:"Landscape · quiet · cosy",semanticEl:"Θέλω βουνό, θαλπωρή και ήρεμες μέρες.",semanticEn:"I want mountains, warmth and quiet days."},
 {id:"adventure",query:"dramatic island aerial cliffs Europe",el:"Περιπέτεια",en:"Adventure",hintEl:"Κίνηση · φύση · ένταση",hintEn:"Movement · nature · energy",semanticEl:"Θέλω περιπέτεια, εντυπωσιακή φύση και κάτι αξέχαστο.",semanticEn:"I want adventure, dramatic nature and something memorable."},
 {id:"surprise",query:"hidden European coast aerial village",el:"Έκπληξέ με",en:"Surprise me",hintEl:"Όχι το προφανές · το σωστό",hintEn:"Not obvious · just right",semanticEl:"Θέλω κάτι που δεν θα έψαχνα μόνος μου, αρκεί να ταιριάζει πραγματικά.",semanticEn:"I want something I would not search for myself, as long as it truly fits."}
];

const QUESTIONS:Record<QuestionId,{el:string;en:string;options:Array<{value:string;el:string;en:string;hintEl:string;hintEn:string}>}>={
 companions:{el:"Με ποιον φεύγεις;",en:"Who are you escaping with?",options:[{value:"solo",el:"Μόνος/η",en:"Solo",hintEl:"Ελευθερία χωρίς συμβιβασμούς",hintEn:"Freedom without compromise"},{value:"couple",el:"Με τον άνθρωπό μου",en:"With my partner",hintEl:"Χρόνος για δύο",hintEn:"Time for two"},{value:"family",el:"Με παιδιά",en:"With kids",hintEl:"Να λειτουργεί για όλους",hintEn:"Make it work for everyone"},{value:"friends",el:"Με φίλους",en:"With friends",hintEl:"Κοινές στιγμές και ενέργεια",hintEn:"Shared moments and energy"}]},
 outcome:{el:"Όταν γυρίσεις, πώς θέλεις να νιώθεις;",en:"How do you want to feel when you return?",options:[{value:"restore",el:"Πραγματικά ξεκούραστος",en:"Properly rested",hintEl:"Χαμηλοί ρυθμοί",hintEn:"Low pace"},{value:"balanced",el:"Γεμάτος ωραίες στιγμές",en:"Full of good memories",hintEl:"Άνεση + εμπειρίες",hintEn:"Ease + experiences"},{value:"stimulating",el:"Ζωντανός και ενθουσιασμένος",en:"Alive and energised",hintEl:"Κάτι αξέχαστο",hintEn:"Something memorable"}]},
 social:{el:"Τι ατμόσφαιρα θέλεις;",en:"What atmosphere fits you?",options:[{value:"quiet",el:"Ήσυχα",en:"Quiet",hintEl:"Λιγότερος κόσμος",hintEn:"Less crowd"},{value:"balanced",el:"Λίγη ζωή, χωρίς χάος",en:"Some life, no chaos",hintEl:"Ισορροπία",hintEn:"Balance"},{value:"lively",el:"Θέλω ενέργεια",en:"I want energy",hintEl:"Βόλτες και βράδυ",hintEn:"Streets and nights"}]},
 novelty:{el:"Πόσο έξω από τα συνηθισμένα;",en:"How far from familiar?",options:[{value:"familiar",el:"Θέλω σιγουριά",en:"Keep it familiar",hintEl:"Εύκολο και προβλέψιμο",hintEn:"Easy and predictable"},{value:"balanced",el:"Κάτι νέο, χωρίς ρίσκο",en:"New, not risky",hintEl:"Ανακάλυψη με ασφάλεια",hintEn:"Discovery with confidence"},{value:"surprise",el:"Έκπληξέ με",en:"Surprise me",hintEl:"Βρες κάτι που δεν θα έψαχνα",hintEn:"Find what I would not search for"}]},
 must_have:{el:"Τι πρέπει οπωσδήποτε να υπάρχει;",en:"What must be there?",options:[{value:"sea",el:"Θάλασσα / φως",en:"Sea / light",hintEl:"Ορίζοντας και νερό",hintEn:"Horizon and water"},{value:"nature",el:"Φύση",en:"Nature",hintEl:"Πράσινο και διαδρομές",hintEn:"Green and trails"},{value:"culture",el:"Κουλτούρα / ιστορία",en:"Culture / history",hintEl:"Κάτι να ανακαλύψω",hintEn:"Something to discover"},{value:"nightlife",el:"Βραδινή ζωή",en:"Nightlife",hintEl:"Η μέρα συνεχίζεται",hintEn:"The day keeps going"},{value:"none",el:"Κανένα must-have",en:"No must-have",hintEl:"Κράτα ανοιχτές επιλογές",hintEn:"Keep options open"}]},
 friction:{el:"Τι δεν θέλεις να πληρώσεις με χρόνο ή νεύρα;",en:"What should not cost you time or energy?",options:[{value:"long-travel",el:"Πολλή μετακίνηση",en:"Long travel",hintEl:"Να αρχίσει γρήγορα",hintEn:"Start quickly"},{value:"crowds",el:"Υπερβολικό κόσμο",en:"Crowds",hintEl:"Όχι ουρές",hintEn:"No queue energy"},{value:"high-cost",el:"Premium χωρίς λόγο",en:"Pointless premium",hintEl:"Θέλω αξία",hintEn:"I want value"},{value:"none",el:"Δεν με περιορίζει κάτι",en:"Nothing specific",hintEl:"Μεγάλος χώρος επιλογών",hintEn:"Wide option space"}]}
};

function fallbackWindows(lang:Lang,duration:number):DateWindow[]{const now=new Date(),fri=nextWeekday(now,5),fri2=nextWeekday(now,5,2),sun=nextWeekday(now,0,1);return[
 {id:"easy",label:say(lang,"Εύκολο weekend","Easy weekend"),note:say(lang,"Παρασκευή · λίγη άδεια","Friday · minimal leave"),start:iso(fri),end:iso(add(fri,duration)),reason:say(lang,"Χαμηλή οργανωτική τριβή","Low planning friction"),confidence:"MEDIUM"},
 {id:"space",label:say(lang,"Περισσότερος χώρος","More room"),note:say(lang,"Λίγο αργότερα","A little later"),start:iso(fri2),end:iso(add(fri2,duration)),reason:say(lang,"Περισσότερος χρόνος για δυνατό matching","More room for stronger matching"),confidence:"MEDIUM"},
 {id:"quiet",label:say(lang,"Πιο ήσυχος ρυθμός","Quieter rhythm"),note:say(lang,"Κυριακή–μέσα εβδομάδας","Sunday into midweek"),start:iso(sun),end:iso(add(sun,duration)),reason:say(lang,"Λιγότερη weekend πίεση","Less weekend pressure"),confidence:"MEDIUM"}
]}

export function V36EscapeFunnel({lang="el"}:{lang?:Lang}){
 const[stage,setStage]=useState<Stage>("mood"),[initialText,setInitialText]=useState(""),[activeWorld,setActiveWorld]=useState("sea-light"),[answers,setAnswers]=useState<Answer[]>([]),[discovery,setDiscovery]=useState<Discovery|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const[dateMode,setDateMode]=useState<"suggest"|"fixed"|"flexible">("suggest"),[duration,setDuration]=useState(3),[horizonDays,setHorizonDays]=useState(90),[dateWindows,setDateWindows]=useState<DateWindow[]>(()=>fallbackWindows(lang,3)),[windowId,setWindowId]=useState("easy"),[dateLoading,setDateLoading]=useState(false);
 const fallback=useMemo(()=>fallbackWindows(lang,3)[0],[lang]);
 const[fixedStart,setFixedStart]=useState(fallback.start),[fixedEnd,setFixedEnd]=useState(fallback.end),[origin,setOrigin]=useState(say(lang,"Αθήνα","Athens")),[budget,setBudget]=useState(1200),[rows,setRows]=useState<StreamRow[]>([]),[result,setResult]=useState<EscapeSolutionResponseV36|null>(null),[solutionIndex,setSolutionIndex]=useState(0),[missionId,setMissionId]=useState<string|null>(null);
 const[moodMedia,setMoodMedia]=useState<Record<string,Media[]>>({}),[solutionMedia,setSolutionMedia]=useState<Record<string,Media[]>>({}),[frame,setFrame]=useState(0);
 const q=discovery?.nextQuestionId?QUESTIONS[discovery.nextQuestionId]:null,solutions=result?.solutions??[],selected=solutions[solutionIndex]??null;
 const selectedWindow=dateMode==="fixed"?{id:"fixed",label:say(lang,"Οι ημερομηνίες μου","My dates"),note:"",start:fixedStart,end:fixedEnd}:dateWindows.find(x=>x.id===windowId)??dateWindows[0];
 const step=stage==="mood"?1:stage==="dna"?2:stage==="time"?3:stage==="reality"?4:5;
 const activeGallery=stage==="results"&&selected?(solutionMedia[selected.recommendation.slug]??[]):(moodMedia[activeWorld]??[]),backdrop=activeGallery.length?activeGallery[frame%activeGallery.length]?.imageUrl:null;

 useEffect(()=>{const timer=window.setInterval(()=>setFrame(v=>v+1),6200);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{let cancelled=false;Promise.all(WORLDS.map(async world=>{try{const r=await fetch(`/api/escape/media?mode=aerial&destination=${encodeURIComponent(world.query)}`);const d=await r.json() as {items?:Media[]};return[world.id,d.items?.slice(0,3)??[]] as [string,Media[]]}catch{return[world.id,[]] as [string,Media[]]}})).then(entries=>{if(cancelled)return;const next:Record<string,Media[]>={};for(const[id,items]of entries)next[id]=items;setMoodMedia(next)});return()=>{cancelled=true}},[]);
 useEffect(()=>{if(stage!=="time"||!discovery||dateMode==="fixed")return;let cancelled=false;setDateLoading(true);fetch("/api/escape/date-opportunities",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,initialText,duration,horizonDays:dateMode==="flexible"?horizonDays:60,profile:{travelerType:discovery.profile.travelerType,desiredEnergy:discovery.profile.desiredEnergy,socialPreference:discovery.profile.socialPreference,noveltyPreference:discovery.profile.noveltyPreference,avoid:discovery.profile.avoid,moods:discovery.profile.moods}})}).then(async r=>r.ok?await r.json():null).then((d:{windows?:DateWindow[]}|null)=>{if(cancelled)return;const windows=d?.windows?.length===3?d.windows:fallbackWindows(lang,duration);setDateWindows(windows);setWindowId(windows[0].id)}).catch(()=>{if(!cancelled){const windows=fallbackWindows(lang,duration);setDateWindows(windows);setWindowId(windows[0].id)}}).finally(()=>{if(!cancelled)setDateLoading(false)});return()=>{cancelled=true}},[stage,discovery,dateMode,duration,horizonDays,initialText,lang]);
 useEffect(()=>{if(!solutions.length)return;let cancelled=false;Promise.all(solutions.map(async solution=>{try{const name=solution.recommendation.destinationEn||solution.recommendation.destination,r=await fetch(`/api/escape/media?mode=aerial&destination=${encodeURIComponent(name)}`),d=await r.json() as {items?:Media[]};return[solution.recommendation.slug,d.items?.slice(0,4)??[]] as [string,Media[]]}catch{return[solution.recommendation.slug,[]] as [string,Media[]]}})).then(entries=>{if(cancelled)return;const next:Record<string,Media[]>={};for(const[slug,items]of entries)next[slug]=items;setSolutionMedia(next)});return()=>{cancelled=true}},[result]);
 useEffect(()=>setFrame(0),[activeWorld,solutionIndex,stage]);

 function chooseWorld(world:World){setActiveWorld(world.id);const semantic=say(lang,world.semanticEl,world.semanticEn);setInitialText(current=>current.includes(semantic)?current:(current.trim()?`${current.trim()} ${semantic}`:semantic));}
 async function discover(nextAnswers=answers){setBusy(true);setError(null);setStage("dna");try{const r=await fetch("/api/escape/discovery",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,initialText,answers:nextAnswers})});if(!r.ok)throw new Error();const d=await r.json() as Discovery;setDiscovery(d)}catch{setError(say(lang,"Δεν κατάφερα να καταλάβω αρκετά. Γράψε λίγο πιο συγκεκριμένα τι χρειάζεσαι.","I could not understand enough. Add one concrete thing you need."));setStage("mood")}finally{setBusy(false)}}
 async function start(e:FormEvent){e.preventDefault();if(initialText.trim().length<3)return;await discover([])}
 async function answer(id:QuestionId,value:string){const next=[...answers.filter(a=>a.questionId!==id),{questionId:id,value}];setAnswers(next);await discover(next)}
 async function createMission(){if(!discovery||!selectedWindow)return null;try{const r=await fetch("/api/escape/mission",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,originText:origin,travelWindow:{label:selectedWindow.label,start:selectedWindow.start,end:selectedWindow.end},needText:initialText.slice(0,500),travelerType:discovery.profile.travelerType,groupSize:groupSize(discovery.profile.travelerType),budgetEur:budget,dna:discovery.profile.dnaLabels})});if(!r.ok)return null;const d=await r.json() as {missionId?:string};return d.missionId??null}catch{return null}}
 async function solve(){if(!discovery||!selectedWindow)return;setBusy(true);setError(null);setRows([]);setResult(null);setSolutionIndex(0);setStage("solve");const id=await createMission();setMissionId(id);const nights=Math.max(1,Math.round((Date.parse(`${selectedWindow.end}T00:00:00Z`)-Date.parse(`${selectedWindow.start}T00:00:00Z`))/DAY)),payload={origin,startDate:selectedWindow.start,endDate:selectedWindow.end,month:"flexible",nights,budget,moods:discovery.profile.moods.length?discovery.profile.moods:["relax"],travelerType:discovery.profile.travelerType,groupSize:groupSize(discovery.profile.travelerType),language:lang,distancePreference:"any",pace:discovery.profile.pace,hotelStyle:"any",avoid:discovery.profile.avoid,entryMode:"idea",desiredEnergy:discovery.profile.desiredEnergy,socialPreference:discovery.profile.socialPreference,noveltyPreference:discovery.profile.noveltyPreference,mustHave:discovery.profile.mustHave,dateFlexibility:dateMode==="fixed"?"fixed":"few-days",transportMode:"any",stayLocationPreference:"balanced",tripText:`${initialText}. ${discovery.summary}`.slice(0,500)};
  try{const response=await fetch("/api/escape/solve-v36/stream",{method:"POST",headers:{"content-type":"application/json",accept:"application/x-ndjson"},body:JSON.stringify(payload)});if(!response.ok)throw new Error();const reader=response.body?.getReader();if(!reader)throw new Error();const decoder=new TextDecoder();let buffer="";const consume=(line:string)=>{if(!line.trim())return;const item=JSON.parse(line) as StreamRow&{result?:EscapeSolutionResponseV36};if(item.type==="final"&&item.result){setResult(item.result);setStage("results")}else if(item.type==="continuity")setError(item.message??say(lang,"Δεν βρήκα ασφαλές αποτέλεσμα. Άνοιξε λίγο ημερομηνίες ή budget.","No safe result yet. Widen dates or budget."));else setRows(current=>[...current,item])};while(true){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines)consume(line)}if(buffer.trim())consume(buffer)}catch{setError(say(lang,"Η ανάλυση δεν ολοκληρώθηκε. Δοκίμασε ξανά ή άνοιξε λίγο ημερομηνίες/budget.","The analysis did not complete. Retry or widen dates/budget."));setStage("reality")}finally{setBusy(false)}}
 function reset(){setStage("mood");setResult(null);setRows([]);setError(null);setSolutionIndex(0)}
 function href(solution:EscapeSolutionV36){const rec=solution.recommendation;return `/escape/${encodeURIComponent(rec.slug)}?start=${selectedWindow?.start}&end=${selectedWindow?.end}&budget=${budget}&travelerType=${discovery?.profile.travelerType??"couple"}&mood=${discovery?.profile.moods[0]??"relax"}&origin=${encodeURIComponent(origin)}&lang=${lang}&offer=${encodeURIComponent(solution.stay.sourceProductId)}${missionId?`&mission=${missionId}`:""}`}
 function move(delta:number){if(!solutions.length)return;setSolutionIndex(v=>(v+delta+solutions.length)%solutions.length)}

 return <main className={styles.shell} data-mood={activeWorld} data-stage={stage}>
  {backdrop?<img key={`${stage}-${activeWorld}-${solutionIndex}-${frame}`} className={styles.backdrop} src={backdrop} alt="" aria-hidden="true"/>:<div className={styles.fallback}/>}<div className={styles.shade}/><div className={styles.grain}/>
  <header className={styles.topbar}><button className={styles.brand} onClick={reset}>AI TRAVEL <b>ESCAPE</b></button><div className={styles.progress}>{[1,2,3,4,5].map(n=><span key={n} className={n===step?styles.active:n<step?styles.done:""}>{n}<i/></span>)}</div><a className={styles.lang} href={lang==="en"?"/":"/en"}>{lang==="en"?"ΕΛ":"EN"}</a></header>

  {stage==="mood"&&<section className={styles.screen}><div className={styles.hero}><span className={styles.kicker}>01 · MOOD</span><h1>{say(lang,"Μην μου πεις πού. Πες μου τι χρειάζεσαι.","Do not tell me where. Tell me what you need.")}</h1><p>{say(lang,"Δώσε μου το πρόβλημα ή διάλεξε την εικόνα που σε τραβάει. Από εκεί ξεκινά η απόφαση.","Give me the problem or choose the image that pulls you. That is where the decision starts.")}</p><form className={styles.prompt} onSubmit={start}><textarea value={initialText} onChange={e=>setInitialText(e.target.value)} placeholder={say(lang,"π.χ. Είμαι κουρασμένος, 4 μέρες με τη σύντροφό μου, ήσυχα αλλά με καλό φαγητό…","e.g. Exhausted, four days with my partner, quiet but with great food…")} maxLength={700}/><button disabled={busy||initialText.trim().length<3}>{say(lang,"Κατάλαβέ με →","Understand me →")}</button></form></div><div className={styles.worlds}>{WORLDS.map(world=>{const image=moodMedia[world.id]?.[frame%(moodMedia[world.id]?.length||1)]?.imageUrl;return <button key={world.id} className={activeWorld===world.id?styles.worldActive:""} onClick={()=>chooseWorld(world)}>{image&&<img src={image} alt=""/>}<i/><strong>{say(lang,world.el,world.en)}</strong><small>{say(lang,world.hintEl,world.hintEn)}</small></button>})}</div></section>}

  {stage==="dna"&&<section className={styles.screen}>{!discovery?<div className={styles.center}><div className={styles.pulse}/><h2>{say(lang,"Σε ακούω…","Listening…")}</h2></div>:q&&!discovery.complete?<><div className={styles.context}><span className={styles.kicker}>02 · TRAVELER DNA</span><p>{discovery.summary}</p><small>{say(lang,"Ρωτάω μόνο ό,τι μπορεί να αλλάξει πραγματικά την επιλογή.","I only ask what can genuinely change the choice.")}</small></div><div className={styles.question}><h2>{say(lang,q.el,q.en)}</h2><div className={styles.choices}>{q.options.map(option=><button key={option.value} disabled={busy} onClick={()=>answer(discovery.nextQuestionId!,option.value)}><b>{say(lang,option.el,option.en)}</b><span>{say(lang,option.hintEl,option.hintEn)}</span></button>)}</div></div></>:<div className={styles.dnaCard}><span className={styles.kicker}>02 · ESCAPE DNA</span><h2>{say(lang,"Αυτό είναι που κατάλαβα ότι χρειάζεσαι.","This is what I think you actually need.")}</h2><blockquote>{discovery.summary}</blockquote><div className={styles.dnaChips}>{discovery.profile.dnaLabels.map(label=><span key={label}>{label}</span>)}</div><div className={styles.actions}><button className={styles.primary} onClick={()=>setStage("time")}>{say(lang,"Σωστά — βρες πότε →","Correct — find when →")}</button><button className={styles.secondary} onClick={()=>setStage("mood")}>{say(lang,"Όχι ακριβώς","Not quite")}</button></div></div>}</section>}

  {stage==="time"&&discovery&&<section className={styles.screen}><div className={styles.timeHead}><span className={styles.kicker}>03 · TIME</span><h2>{say(lang,"Πότε έχει νόημα να φύγεις;","When does it make sense to go?")}</h2><div className={styles.modes}>{(["suggest","fixed","flexible"] as const).map(mode=><button key={mode} className={dateMode===mode?styles.modeActive:""} onClick={()=>setDateMode(mode)}>{mode==="suggest"?say(lang,"Βρες το για μένα","Find it for me"):mode==="fixed"?say(lang,"Ξέρω πότε","I know when"):say(lang,"Είμαι flexible","I am flexible")}</button>)}</div></div>{dateMode==="fixed"?<div className={styles.fixed}><label>{say(lang,"Αναχώρηση","Departure")}<input type="date" value={fixedStart} min={iso(new Date())} onChange={e=>setFixedStart(e.target.value)}/></label><label>{say(lang,"Επιστροφή","Return")}<input type="date" value={fixedEnd} min={fixedStart} onChange={e=>setFixedEnd(e.target.value)}/></label></div>:<div className={styles.timeBody}><div className={styles.pills}><span>{say(lang,"Νύχτες","Nights")}</span>{[2,3,4,5,7].map(n=><button key={n} className={duration===n?styles.pillActive:""} onClick={()=>setDuration(n)}>{n}</button>)}{dateMode==="flexible"&&[60,90,120].map(n=><button key={n} className={horizonDays===n?styles.pillActive:""} onClick={()=>setHorizonDays(n)}>{n}d</button>)}</div><div className={styles.windows}>{dateLoading?<div className={styles.loading}>{say(lang,"Ο Date Agent ψάχνει 3 λογικά παράθυρα…","The Date Agent is finding three sensible windows…")}</div>:dateWindows.map(w=><button key={w.id} className={windowId===w.id?styles.windowActive:""} onClick={()=>setWindowId(w.id)}><small>{w.label}</small><b>{w.start.slice(5)} → {w.end.slice(5)}</b><span>{w.note}</span><em>{w.reason}</em></button>)}</div></div>}<button className={styles.next} disabled={dateLoading||!selectedWindow} onClick={()=>setStage("reality")}>{say(lang,"Συνέχεια →","Continue →")}</button></section>}

  {stage==="reality"&&discovery&&selectedWindow&&<section className={styles.screen}><div className={styles.reality}><span className={styles.kicker}>04 · REALITY</span><h2>{say(lang,"Δύο πράγματα πριν ψάξω πραγματικά.","Two things before I search for real.")}</h2><div className={styles.realityGrid}><label>{say(lang,"Αφετηρία","Starting from")}<input value={origin} onChange={e=>setOrigin(e.target.value)}/></label><div><span>{say(lang,"Άνετο συνολικό budget","Comfortable total budget")}</span><div className={styles.budgets}>{[600,900,1200,1600,2200,3000].map(v=><button key={v} className={budget===v?styles.budgetActive:""} onClick={()=>setBudget(v)}>€{v}</button>)}</div></div></div><div className={styles.brief}><b>{discovery.summary}</b><span>{selectedWindow.start} → {selectedWindow.end} · {origin} · €{budget}</span></div><button className={styles.primary} disabled={busy||origin.trim().length<2} onClick={solve}>{say(lang,"Βρες 10 πραγματικές λύσεις →","Find 10 real solutions →")}</button></div></section>}

  {stage==="solve"&&<section className={styles.screen}><div className={styles.solve}><div className={styles.orbit}><i/><i/><i/><b>AI</b></div><span className={styles.kicker}>05 · BIDIRECTIONAL SEARCH</span><h2>{say(lang,"Δεν ψάχνω μόνο “πού ταιριάζεις”. Ελέγχω και τι μπορούμε πράγματι να σου προσφέρουμε.","I am not only asking where you fit. I am checking what we can actually offer you.")}</h2><div className={styles.agentLines}>{rows.slice(-5).map((row,i)=><p key={`${row.type}-${i}`}><span>{row.progress??"·"}</span>{row.message??row.type}</p>)}</div><small>Need → Destination → Stay ⇄ Stay Inventory → Destination → Need</small></div></section>}

  {stage==="results"&&selected&&selectedWindow&&<section className={`${styles.screen} ${styles.results}`}><button className={styles.prev} onClick={()=>move(-1)}>‹</button><button className={styles.nextResult} onClick={()=>move(1)}>›</button><div className={styles.resultMain}><div className={styles.resultStory}><span className={styles.kicker}>#{selected.rank} · {selected.combinedScore}% · {result?.sourceMode==="reverse-recovery"?"RECOVERED BY INVENTORY":"DUAL-PASS"}</span><h1>{lang==="en"?selected.recommendation.destinationEn:selected.recommendation.destination}</h1><p className={styles.why}>{selected.reasoning.destination}</p><div className={styles.scores}><span>{say(lang,"Destination","Destination")} <b>{selected.destinationScore}</b></span><span>{say(lang,"Stay","Stay")} <b>{selected.stayScore}</b></span><span>{say(lang,"Inventory","Inventory")} <b>{selected.inventoryCount}</b></span></div><div className={styles.reverse}><small>{say(lang,"ΑΝΤΙΣΤΡΟΦΗ ΣΚΕΨΗ","REVERSE REASONING")}</small><p>{selected.reasoning.reverse}</p></div></div><aside className={styles.stay}>{selected.stay.imageUrl&&<img src={selected.stay.imageUrl} alt=""/>}<div><small>{say(lang,"ΤΟ ΚΑΤΑΛΥΜΑ ΠΟΥ ΣΤΗΡΙΖΕΙ ΤΗΝ ΕΠΙΛΟΓΗ","THE STAY SUPPORTING THIS CHOICE")}</small><h3>{selected.stay.propertyName}</h3><p>{selected.reasoning.stay}</p><div className={styles.stayMetrics}><span>semantic <b>{selected.stay.semanticScore}</b></span><span>value <b>{selected.stay.valueScore}</b></span><span>location <b>{selected.stay.locationScore}</b></span></div>{selected.stay.price!=null&&<strong>{selected.stay.currency??"EUR"} {Math.round(selected.stay.price)} <small>{say(lang,"τιμή feed","feed price")}</small></strong>}<small className={styles.tradeoff}>{selected.reasoning.tradeoff}</small>{selected.alternatives.length>0&&<div className={styles.altStays}>{selected.alternatives.slice(0,3).map(x=><span key={x.sourceProductId}>{x.propertyName}</span>)}</div>}<div className={styles.ctas}><a className={styles.primaryLink} href={href(selected)}>{say(lang,"Χτίσε το 360° ταξίδι","Build the 360° trip")}</a><a className={styles.affiliate} href={selected.stay.trackingUrl} target="_blank" rel="sponsored noreferrer">{say(lang,"Δες το κατάλυμα ↗","Check the stay ↗")}</a></div></div></aside></div><div className={styles.rail}>{solutions.map((solution,index)=>{const thumb=solutionMedia[solution.recommendation.slug]?.[0]?.imageUrl??solution.stay.imageUrl;return <button key={`${solution.recommendation.slug}-${solution.stay.sourceProductId}`} className={index===solutionIndex?styles.railActive:""} onClick={()=>setSolutionIndex(index)}>{thumb&&<img src={thumb} alt=""/>}<i/><small>#{index+1}</small><b>{lang==="en"?solution.recommendation.destinationEn:solution.recommendation.destination}</b><span>{solution.stay.propertyName}</span></button>})}</div></section>}

  {error&&<div className={styles.error}>{error}<button onClick={()=>setError(null)}>×</button></div>}
 </main>
}
