"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import type { V8StayOffer } from "@/lib/decision/v8-types";
import type { TripRequest } from "@/lib/validation/trip";
import type { TripBuilderPlanV25 } from "@/lib/trip-builder/types-v25";
import type { LocalIntelligenceV38,LocalPlaceV38,GuestSignalV38 } from "@/lib/data/local-intelligence-v38";
import styles from "./v38-escape-builder.module.css";

type Lang="el"|"en";
type Stage="cinema"|"research"|"explore"|"stay"|"verify"|"email"|"unlocked";
type Media={imageUrl:string;originalUrl?:string;sourceUrl:string;title:string;description?:string;license:string;attribution:string};
type ResearchPlace={id?:string;name:string;summary?:string|null;whyItFits?:string|null};
type Dossier={
 release?:string;
 destination:{slug:string;name:string;nameEn:string;latitude:number;longitude:number;isSummer:boolean};
 weather:{label:string;score:number|null;days:Array<{date:string;temperatureMinC:number|null;temperatureMaxC:number|null;precipitationProbability?:number|null;summary:string}>};
 localIntelligence:LocalIntelligenceV38;
 research:{source:string;overview:string|null;attractions:ResearchPlace[];practicalNotes:string[];sources:Array<{title:string;url:string;domain:string}>};
 budgetBeyondHotel:{totalLow:number;totalHigh:number;note:string};
};
type Tab="highlights"|"eat"|"drinks"|"culture"|"sea"|"practical";

type Props={slug:string;name:string;nameEn:string;trip:TripRequest;offers:V8StayOffer[];lang?:Lang;missionId?:string|null};
const say=(lang:Lang,el:string,en:string)=>lang==="el"?el:en;
const providerPrice=(offer:V8StayOffer,lang:Lang)=>offer.price!=null&&offer.price>0?`${offer.price.toLocaleString(lang==="el"?"el-GR":"en-GB",{maximumFractionDigits:2})} ${offer.currency||"EUR"}`:say(lang,"Τιμή στον πάροχο","Price at provider");
const safeUrl=(value:unknown)=>typeof value==="string"&&/^https:\/\//i.test(value.trim())?value.trim():null;
function collectUrls(value:unknown,out:Set<string>,depth=0){if(depth>3||out.size>=10||value==null)return;if(typeof value==="string"){const direct=safeUrl(value);if(direct)out.add(direct);else for(const token of value.split(/[|,;\s]+/)){const url=safeUrl(token);if(url)out.add(url)}return}if(Array.isArray(value)){for(const item of value)collectUrls(item,out,depth+1);return}if(typeof value==="object"){for(const[key,item]of Object.entries(value as Record<string,unknown>)){if(/image|photo|picture|gallery|thumb|media/i.test(key))collectUrls(item,out,depth+1)}}}
function stayImages(offer:V8StayOffer|null){if(!offer)return[];const out=new Set<string>();for(const candidate of[offer.imageUrl,offer.thumbUrl]){const url=safeUrl(candidate);if(url)out.add(url)}collectUrls(offer.raw,out);return[...out].slice(0,8)}
function sourceBadge(place:LocalPlaceV38){return place.source==="Google Places"?"GOOGLE":place.source==="Foursquare"?"FOURSQUARE":place.source==="Tripadvisor"?"TRIPADVISOR":"OPEN DATA"}
function aiSignalText(signal:GuestSignalV38|null,lang:Lang){if(!signal||signal.aiScore==null||signal.sampleSize<3)return null;return say(lang,`AI Guest Signal ${signal.aiScore}/100 · ${signal.sampleSize} εμπειρίες`,`AI Guest Signal ${signal.aiScore}/100 · ${signal.sampleSize} experiences`)}
function placeSort(rows:LocalPlaceV38[]){return[...rows].sort((a,b)=>(b.internalSignal?.aiScore??-1)-(a.internalSignal?.aiScore??-1)||(b.rating??-1)-(a.rating??-1)||(b.ratingCount??0)-(a.ratingCount??0)).slice(0,8)}

export function V38EscapeBuilderClient({slug,name,nameEn,trip,offers,lang="el",missionId=null}:Props){
 const destination=lang==="en"?nameEn:name;
 const[selected,setSelected]=useState<V8StayOffer|null>(offers[0]??null),[dossier,setDossier]=useState<Dossier|null>(null),[plan,setPlan]=useState<TripBuilderPlanV25|null>(null),[stage,setStage]=useState<Stage>("cinema"),[tab,setTab]=useState<Tab>("highlights"),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const[media,setMedia]=useState<Media[]>([]),[heroFrame,setHeroFrame]=useState(0),[stayFrame,setStayFrame]=useState(0),[email,setEmail]=useState(""),[mailState,setMailState]=useState<"idle"|"sending"|"sent"|"error">("idle");
 const[feedbackRating,setFeedbackRating]=useState(5),[feedbackRecommend,setFeedbackRecommend]=useState(true),[feedbackComment,setFeedbackComment]=useState(""),[feedbackState,setFeedbackState]=useState<"idle"|"sending"|"sent"|"error">("idle");
 const hero=media[heroFrame]?.imageUrl||selected?.imageUrl||selected?.thumbUrl||null,currentOffer=plan?.stay?.trackingUrl||selected?.trackingUrl||"",guideUrl=plan?.guide.path||"",selectedImages=useMemo(()=>stayImages(selected),[selected]),tripComplete=trip.endDate<=new Date().toISOString().slice(0,10);
 const weatherDays=useMemo(()=>dossier?.weather.days.slice(0,5)??[],[dossier]),local=dossier?.localIntelligence??null;
 const track=(eventName:string,payload:Record<string,unknown>={})=>{if(missionId)void fetch("/api/escape/event",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,eventName,payload})}).catch(()=>null)};

 useEffect(()=>{let cancelled=false;async function load(){const aerial=await fetch(`/api/escape/media?destination=${encodeURIComponent(nameEn||name)}&mode=aerial`).then(r=>r.ok?r.json():null).catch(()=>null) as {items?:Media[]}|null;let items=aerial?.items??[];if(!items.length){const normal=await fetch(`/api/escape/media?destination=${encodeURIComponent(nameEn||name)}`).then(r=>r.ok?r.json():null).catch(()=>null) as {items?:Media[]}|null;items=normal?.items??[]}if(!cancelled)setMedia(items.slice(0,6))}void load();return()=>{cancelled=true}},[name,nameEn]);
 useEffect(()=>{if(media.length<2)return;const timer=window.setInterval(()=>setHeroFrame(i=>(i+1)%media.length),6800);return()=>window.clearInterval(timer)},[media.length]);
 useEffect(()=>{setStayFrame(0);if(selectedImages.length<2)return;const timer=window.setInterval(()=>setStayFrame(i=>(i+1)%selectedImages.length),5200);return()=>window.clearInterval(timer)},[selected?.sourceProductId,selectedImages.length]);

 async function research(){setBusy(true);setError(null);setStage("research");track("v38_360_research_started",{destinationId:slug});try{if(missionId)await fetch("/api/escape/select",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,destinationId:slug})}).catch(()=>null);const response=await fetch("/api/escape/research",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip,slug})});if(!response.ok)throw new Error(`research_${response.status}`);const data=await response.json() as Dossier;setDossier(data);setStage("explore");track("v38_360_research_completed",{destinationId:slug,providers:data.localIntelligence?.providers??[]})}catch{setError(say(lang,"Ο 360° έλεγχος δεν ολοκληρώθηκε. Η επιλογή σου έχει κρατηθεί — δεν θα γεμίσω τα κενά με εικασίες.","The 360° check did not complete. Your choice is saved — I will not fill gaps with guesses."));setStage("cinema")}finally{setBusy(false)}}
 async function verifyStay(){if(!selected)return;setBusy(true);setError(null);setStage("verify");track("stay_cinema_selected",{destinationId:slug,offerId:selected.sourceProductId});try{const response=await fetch("/api/trip-builder",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip,slug,offerId:selected.sourceProductId})});if(!response.ok)throw new Error(`builder_${response.status}`);const built=await response.json() as TripBuilderPlanV25;setPlan(built);setStage("email");if(missionId){const mediaRows=[built.stay?.imageUrl?{kind:"stay",url:built.stay.imageUrl}:null,...(local?.attractions??[]).slice(0,5).map(x=>x.imageUrl?{kind:"place",url:x.imageUrl,name:x.name}:null),...(local?.restaurants??[]).slice(0,5).map(x=>x.imageUrl?{kind:"restaurant",url:x.imageUrl,name:x.name}:null)].filter(Boolean).slice(0,20);void fetch("/api/escape/research/complete",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,destinationId:slug,weather:built.weather,places:dossier?.research.attractions??[],restaurants:local?.restaurants??[],practicalNotes:dossier?.research.practicalNotes??[],logistics:{availability:built.availability,flexibleWindows:built.flexibleWindows,budgetBeyondHotel:built.budgetBeyondHotel},sources:dossier?.research.sources??[],media:mediaRows,guidePath:built.guide.path,trackingUrl:built.stay?.trackingUrl??selected.trackingUrl})}).catch(()=>null)}}catch{setError(say(lang,"Δεν μπόρεσα να επιβεβαιώσω αυτή τη διαμονή με ασφάλεια. Διάλεξε άλλη βάση — δεν θα εμφανίσω ψεύτικη διαθεσιμότητα.","I could not verify this stay safely. Choose another base — I will not show fake availability."));setStage("stay")}finally{setBusy(false)}}
 async function sendEmail(event:FormEvent){event.preventDefault();if(!selected||!plan||!email)return;setMailState("sending");try{const response=await fetch("/api/guide/email",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,slug,start:trip.startDate,end:trip.endDate,offer:selected.sourceProductId,language:lang})});if(!response.ok)throw new Error();if(missionId)await fetch("/api/escape/email-state",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,email})}).catch(()=>null);setMailState("sent");setStage("unlocked");track("email_gate_completed",{destinationId:slug,offerId:selected.sourceProductId})}catch{setMailState("error")}}
 async function share(){const url=window.location.href,text=say(lang,`Τι λες για ${destination}; Έφτιαξα μια 360° απόδραση για εμάς.`,`What do you think about ${destination}? I built a 360° escape for us.`);if(navigator.share)await navigator.share({title:destination,text,url}).catch(()=>undefined);else await navigator.clipboard.writeText(url).catch(()=>undefined);track("escape_shared",{destinationId:slug})}
 async function sendFeedback(event:FormEvent){event.preventDefault();if(!missionId||!tripComplete)return;setFeedbackState("sending");try{const response=await fetch("/api/escape/feedback",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,destinationSlug:slug,subjectKind:"destination",subjectKey:`destination:${slug}`,subjectName:destination,went:true,rating:feedbackRating,wouldRecommend:feedbackRecommend,comment:feedbackComment})});if(!response.ok)throw new Error();setFeedbackState("sent")}catch{setFeedbackState("error")}}

 const tabs:Array<{id:Tab;el:string;en:string;count:number}>=[
  {id:"highlights",el:"Μη χάσεις",en:"Don't miss",count:(local?.attractions.length??0)},
  {id:"eat",el:"Φαγητό",en:"Eat",count:(local?.restaurants.length??0)},
  {id:"drinks",el:"Ποτό & βράδυ",en:"Drinks & nights",count:(local?.nightlife.length??0)},
  {id:"culture",el:"Κουλτούρα",en:"Culture",count:(local?.museums.length??0)},
  {id:"sea",el:"Θάλασσα",en:"Sea",count:(local?.beaches.length??0)},
  {id:"practical",el:"Πριν φύγεις",en:"Know before",count:dossier?.research.practicalNotes.length??0},
 ];
 const activePlaces=tab==="highlights"?placeSort(local?.attractions??[]):tab==="eat"?placeSort(local?.restaurants??[]):tab==="drinks"?placeSort(local?.nightlife??[]):tab==="culture"?placeSort(local?.museums??[]):tab==="sea"?placeSort(local?.beaches??[]):[];
 const guestDestination=aiSignalText(local?.destinationSignal??null,lang);

 return <main className={styles.shell}>
  <header className={styles.topbar}><a href={lang==="en"?"/en":"/"} className={styles.brand}><span>AI</span> ESCAPE STUDIO</a><div className={styles.journey}>{(["cinema","explore","stay","email","unlocked"] as Stage[]).map((s,i)=><span key={s} className={stage===s||(["research"].includes(stage)&&s==="cinema")||(["verify"].includes(stage)&&s==="stay")?styles.activeStep:""}>{String(i+1).padStart(2,"0")}</span>)}</div><button type="button" onClick={share} className={styles.share}>{say(lang,"Μοιράσου","Share")}</button></header>

  <section className={styles.hero}>
   <div className={styles.heroFrames}>{media.map((item,index)=><figure key={item.imageUrl} className={`${styles.heroFrame} ${index===heroFrame?styles.heroFrameActive:""}`}><img src={item.imageUrl} alt={item.title}/></figure>)}{!media.length&&hero?<figure className={`${styles.heroFrame} ${styles.heroFrameActive}`}><img src={hero} alt={destination}/></figure>:null}</div>
   <div className={styles.heroShade}/><div className={styles.grain}/>
   <div className={styles.heroCopy}><span className={styles.eyebrow}>YOUR ESCAPE · {trip.startDate} → {trip.endDate}</span><h1>{destination}</h1><p>{say(lang,"Δεν θα σου πουλήσω δωμάτιο πριν καταλάβεις το μέρος. Πρώτα κάνουμε 360° έλεγχο: καιρός, τι αξίζει, πού τρώνε καλά, πού βγαίνεις, τι να αποφύγεις — και μόνο μετά διαμονή.","I will not sell you a room before you understand the place. First comes a 360° check: weather, what matters, where to eat, where to go out, what to avoid — then the stay.")}</p><div className={styles.heroActions}>{stage==="cinema"?<button type="button" onClick={research} disabled={busy}>{say(lang,"Χτίσε μου την απόδραση 360° →","Build my 360° escape →")}</button>:<a href="#escape360">{say(lang,"Άνοιξε το dossier ↓","Open the dossier ↓")}</a>}<span>{say(lang,"Πραγματικές πηγές · καθόλου fake ratings","Real sources · zero fake ratings")}</span></div></div>
   {media[heroFrame]?<div className={styles.mediaCredit}><strong>{/\b(drone|aerial|bird)/i.test(`${media[heroFrame].title} ${media[heroFrame].description??""}`)?say(lang,"AERIAL SOURCE","AERIAL SOURCE"):say(lang,"CINEMATIC SOURCE","CINEMATIC SOURCE")}</strong><span>{media[heroFrame].attribution} · {media[heroFrame].license}</span></div>:null}
   <div className={styles.scrollCue}>360° ↓</div>
  </section>

  {stage==="research"?<section className={styles.agentStage}><div className={styles.orbit}><i/><i/><i/></div><span>LIVE DESTINATION INTELLIGENCE</span><h2>{say(lang,"Οι agents ξεχωρίζουν το ωραίο από το πραγματικά σωστό.","The agents are separating beautiful from genuinely right.")}</h2><div className={styles.agentRail}><b>{say(lang,"Καιρός","Weather")}</b><b>{say(lang,"Μη χάσεις","Don't miss")}</b><b>{say(lang,"Φαγητό","Food")}</b><b>{say(lang,"Βράδυ","Nightlife")}</b><b>{say(lang,"Πρακτικά","Friction")}</b></div></section>:null}

  {dossier&&(["explore","stay","verify","email","unlocked"] as Stage[]).includes(stage)?<section className={styles.dossier} id="escape360">
   <div className={styles.dossierHead}><div><span className={styles.eyebrow}>360° ESCAPE DOSSIER · {local?.providers.join(" + ")||say(lang,"VERIFIED OPEN DATA","VERIFIED OPEN DATA")}</span><h2>{dossier.research.overview||say(lang,"Αυτό είναι το πραγματικό σχήμα της απόδρασης.","This is the real shape of the escape.")}</h2></div><aside><span>{say(lang,"AI FIT","AI FIT")}</span><strong>{dossier.weather.score==null?"—":`${Math.round(dossier.weather.score)}/100`}</strong><small>{dossier.weather.label}</small>{guestDestination?<em>{guestDestination}</em>:null}</aside></div>
   <div className={styles.weatherRail}>{weatherDays.map(day=><article key={day.date}><small>{new Intl.DateTimeFormat(lang==="el"?"el-GR":"en-GB",{weekday:"short",day:"numeric"}).format(new Date(`${day.date}T12:00:00Z`))}</small><strong>{day.temperatureMinC==null?"?":Math.round(day.temperatureMinC)}° <i>→</i> {day.temperatureMaxC==null?"?":Math.round(day.temperatureMaxC)}°</strong><p>{day.summary}</p></article>)}</div>
   <nav className={styles.tabs} aria-label="360 destination sections">{tabs.map(item=><button type="button" key={item.id} onClick={()=>setTab(item.id)} className={tab===item.id?styles.activeTab:""}><span>{say(lang,item.el,item.en)}</span><small>{item.count}</small></button>)}</nav>
   {tab!=="practical"?<div className={styles.placeMasonry}>{activePlaces.length?activePlaces.map((place,index)=><article key={place.id} className={index===0?styles.featurePlace:""}>{place.imageUrl?<div className={styles.placeVisual}><img src={place.imageUrl} alt={place.name}/></div>:<div className={styles.placeVisualFallback}><span>{String(index+1).padStart(2,"0")}</span></div>}<div className={styles.placeBody}><div className={styles.placeBadges}><span>{sourceBadge(place)}</span>{place.ranking!=null?<span>#{place.ranking}</span>:null}</div><h3>{place.name}</h3><div className={styles.ratingLine}>{place.rating!=null?<strong>★ {place.rating.toFixed(1)}</strong>:<strong>{say(lang,"Χωρίς εξωτερικό rating","No external rating")}</strong>}{place.ratingCount!=null&&place.ratingCount>0?<small>{place.ratingCount.toLocaleString()} {say(lang,"κριτικές","reviews")}</small>:null}</div>{aiSignalText(place.internalSignal,lang)?<div className={styles.aiGuest}>{aiSignalText(place.internalSignal,lang)}</div>:null}{place.address?<p>{place.address}</p>:null}{place.url?<a href={place.url} target="_blank" rel="noopener nofollow">{say(lang,"Δες την πηγή ↗","Open source ↗")}</a>:null}</div></article>):<div className={styles.noProof}><strong>{say(lang,"Δεν έχω αρκετή τεκμηρίωση εδώ ακόμη.","I do not have enough evidence here yet.")}</strong><p>{say(lang,"Προτιμώ κενό από ένα επινοημένο “top 10”.","I prefer a gap over an invented “top 10”.")}</p></div>}</div>:<div className={styles.practicalGrid}><article><span>{say(lang,"ΝΑ ΞΕΡΕΙΣ ΠΡΙΝ ΦΥΓΕΙΣ","KNOW BEFORE YOU GO")}</span><ul>{dossier.research.practicalNotes.map((note,i)=><li key={i}>{note}</li>)}</ul></article><article className={styles.budgetCard}><span>{say(lang,"ΕΚΤΙΜΗΣΗ ΕΚΤΟΣ ΔΙΑΜΟΝΗΣ","BEYOND-STAY ESTIMATE")}</span><strong>€{dossier.budgetBeyondHotel.totalLow}–€{dossier.budgetBeyondHotel.totalHigh}</strong><p>{dossier.budgetBeyondHotel.note}</p><small>{say(lang,"Εκτίμηση, όχι live προσφορά. Άγνωστα κόστη δεν γίνονται 0.","Estimate, not a live quote. Unknown costs never become zero.")}</small></article></div>}
   <div className={styles.disclosure}><span>360° DISCLOSURE</span><p>{local?.sourceDisclosure}</p><div>{dossier.research.sources.slice(0,5).map(source=><a href={source.url} target="_blank" rel="noopener nofollow" key={source.url}>{source.domain}</a>)}</div></div>
   {stage==="explore"?<div className={styles.commit}><div><span className={styles.eyebrow}>{say(lang,"ΑΝ ΤΟ ΜΕΡΟΣ ΣΟΥ ΚΑΝΕΙ...","IF THE PLACE FEELS RIGHT...")}</span><h2>{say(lang,"Τώρα διαλέγουμε βάση — όχι πριν.","Now we choose a base — not before.")}</h2></div><button type="button" onClick={()=>setStage("stay")}>{say(lang,"Δείξε μου πού θα μείνω →","Show me where I stay →")}</button></div>:null}
  </section>:null}

  {stage==="stay"&&<section className={styles.stayStudio}>
   <div className={styles.stayCinema}>{selectedImages.length?selectedImages.map((url,index)=><figure key={url} className={`${styles.stayFrame} ${index===stayFrame?styles.stayFrameActive:""}`}><img src={url} alt={selected?.propertyName||destination}/></figure>):<div className={styles.stayFallback}/>}<div className={styles.stayShade}/><div className={styles.stayCinemaCopy}><span>STAY CINEMA · {say(lang,"ΠΗΓΑΙΕΣ ΦΩΤΟΓΡΑΦΙΕΣ","SOURCED PHOTOS")}</span><h2>{selected?.propertyName}</h2><p>{selected?.city||destination}</p><strong>{selected?providerPrice(selected,lang):""}</strong><small>{say(lang,"Cinematic motion πάνω στις πραγματικές φωτογραφίες της πηγής — όχι AI ανακατασκευή του ξενοδοχείου.","Cinematic motion uses the sourced property photos — not an AI reconstruction of the hotel.")}</small></div></div>
   <div className={styles.stayRail}>{offers.slice(0,5).map((offer,index)=><button type="button" key={offer.sourceProductId} className={selected?.sourceProductId===offer.sourceProductId?styles.activeStay:""} onClick={()=>{setSelected(offer);setPlan(null)}}>{offer.imageUrl||offer.thumbUrl?<img src={offer.imageUrl||offer.thumbUrl||""} alt=""/>:<div className={styles.offerFallback}/>}<div><small>{index===0?say(lang,"ΚΥΡΙΑ ΕΠΙΛΟΓΗ","PRIMARY MATCH"):index===1?say(lang,"ΚΑΛΥΤΕΡΗ ΑΞΙΑ","VALUE MATCH"):say(lang,"ΕΝΑΛΛΑΚΤΙΚΗ","ALTERNATIVE")}</small><strong>{offer.propertyName}</strong><span>{offer.city||destination}</span><b>{providerPrice(offer,lang)}</b></div></button>)}</div>
   <div className={styles.stayDecision}><div><span className={styles.eyebrow}>{say(lang,"ΤΕΛΙΚΟΣ ΕΛΕΓΧΟΣ","FINAL CHECK")}</span><h3>{say(lang,"Έλεγξε αυτή τη βάση μέσα στο ταξίδι — όχι μόνη της.","Verify this base inside the trip — not in isolation.")}</h3></div><button type="button" onClick={verifyStay} disabled={!selected||busy}>{busy?say(lang,"Ελέγχω…","Checking…"):say(lang,"Κάνε 360° verification →","Run 360° verification →")}</button></div>
  </section>}

  {stage==="verify"?<section className={styles.agentStage}><div className={styles.orbit}><i/><i/><i/></div><span>STAY + TRIP VERIFICATION</span><h2>{say(lang,"Τσεκάρω ημερομηνίες, feed window, provider handoff και το τελικό dossier.","Checking dates, feed window, provider handoff and the final dossier.")}</h2></section>:null}

  {stage==="email"&&plan?<section className={styles.emailGate}><div className={styles.emailStory}><span>YOUR ESCAPE BOOK</span><h2>{say(lang,"Το ταξίδι είναι έτοιμο. Τώρα κράτησέ το.","Your trip is ready. Now keep it.")}</h2><p>{say(lang,"Στέλνω ένα προσωπικό 360° Escape Book στο email σου. Περιλαμβάνει το dossier, το επιλεγμένο κατάλυμα, τις πηγές, QR και το ακριβές affiliate tracking link. Δεν σε γράφουμε σε newsletter.","I will send your personal 360° Escape Book by email. It includes the dossier, chosen stay, sources, QR and the exact affiliate tracking link. No newsletter signup.")}</p><div className={styles.emailProof}><b>{selected?.propertyName}</b><span>{providerPrice(selected!,lang)}</span><small>{say(lang,"Τελική τιμή, δωμάτιο και live διαθεσιμότητα επιβεβαιώνονται στον πάροχο.","Final price, room and live availability are confirmed with the provider.")}</small></div></div><form onSubmit={sendEmail} className={styles.emailForm}><label>{say(lang,"Πού να στείλω το Escape Book;","Where should I send the Escape Book?")}<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email"/></label><label className={styles.discloseCheck}><input type="checkbox" required/><span>{say(lang,"Καταλαβαίνω ότι το τελικό link προς τον πάροχο είναι affiliate link και ότι μπορεί να υπάρξει προμήθεια χωρίς επιπλέον κόστος για εμένα.","I understand the final provider link is an affiliate link and may generate a commission at no extra cost to me.")}</span></label><button disabled={mailState==="sending"}>{mailState==="sending"?say(lang,"Δημιουργώ & στέλνω…","Creating & sending…"):say(lang,"Στείλε μου το Escape Book →","Send my Escape Book →")}</button>{mailState==="error"?<small className={styles.formError}>{say(lang,"Η αποστολή απέτυχε. Δεν ξεκλειδώνω ψεύτικο link — δοκίμασε ξανά.","Delivery failed. I will not unlock a fake link — try again.")}</small>:null}</form></section>:null}

  {stage==="unlocked"&&plan?<section className={styles.unlocked}><div className={styles.unlockGlow}/><span>ESCAPE UNLOCKED</span><h2>{say(lang,"Έφυγε στο email σου. Και εδώ είναι η διαδρομή προς τα έξω.","It is in your inbox. Here is the handoff.")}</h2><p>{say(lang,"Το ταξίδι σου μένει πρώτο. Η εμπορική ενέργεια είναι ξεκάθαρη και ξεχωριστή.","Your trip stays first. The commercial action is explicit and separate.")}</p><div className={styles.unlockActions}>{guideUrl?<a href={guideUrl} target="_blank" rel="noopener" onClick={()=>track("escape_book_opened",{destinationId:slug})}>{say(lang,"Άνοιξε το Escape Book PDF ↗","Open Escape Book PDF ↗")}</a>:null}{currentOffer?<a href={currentOffer} target="_blank" rel="sponsored nofollow noopener" className={styles.providerCta} onClick={()=>track("affiliate_offer_opened",{destinationId:slug,offerId:selected?.sourceProductId})}>{say(lang,"Δες την τρέχουσα προσφορά στον πάροχο ↗","View current provider offer ↗")}</a>:null}</div><small>{say(lang,"Affiliate disclosure: αν ολοκληρώσεις αγορά μέσω του συνδέσμου, ενδέχεται να λάβουμε προμήθεια. Η τιμή σου δεν αυξάνεται εξαιτίας αυτού.","Affiliate disclosure: if you purchase through the link, we may earn a commission. This does not increase your price.")}</small></section>:null}

  {tripComplete&&missionId&&stage==="unlocked"?<section className={styles.feedback}><span>POST-TRIP SIGNAL</span><h2>{say(lang,"Πήγες τελικά; Η εμπειρία σου εκπαιδεύει το δικό μας signal.","Did you go? Your experience trains our own signal.")}</h2><p>{say(lang,"Το AI Guest Signal εμφανίζεται μόνο όταν υπάρχουν τουλάχιστον 3 πραγματικές δηλώσεις μετά το ταξίδι. Δεν είναι review από το internet ούτε fake rating.","AI Guest Signal appears only after at least 3 real post-trip responses. It is not an internet review or a fabricated rating.")}</p>{feedbackState==="sent"?<div className={styles.thankYou}>{say(lang,"Ευχαριστώ — καταγράφηκε χωρίς δημόσια εμφάνιση προσωπικών στοιχείων.","Thank you — recorded without exposing personal details.")}</div>:<form onSubmit={sendFeedback}><div className={styles.stars}>{[1,2,3,4,5].map(n=><button type="button" key={n} onClick={()=>setFeedbackRating(n)} aria-label={`${n}/5`} className={n<=feedbackRating?styles.starOn:""}>★</button>)}</div><label><input type="checkbox" checked={feedbackRecommend} onChange={e=>setFeedbackRecommend(e.target.checked)}/>{say(lang,"Θα το πρότεινα","I would recommend it")}</label><textarea value={feedbackComment} onChange={e=>setFeedbackComment(e.target.value)} maxLength={800} placeholder={say(lang,"Τι άξιζε περισσότερο; Τι θα άλλαζες;","What was most worth it? What would you change?")}/><button disabled={feedbackState==="sending"}>{say(lang,"Στείλε feedback","Send feedback")}</button></form>}</section>:null}

  {error?<div className={styles.error}>{error}<button type="button" onClick={()=>setError(null)}>×</button></div>:null}
 </main>
}
