"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import type { EscapeSolutionResponseV36,EscapeSolutionV36 } from "@/lib/decision/solution-ranking-v36";
import styles from "./v38-escape-funnel.module.css";

type Lang="el"|"en";
type Stage="feel"|"when"|"reality"|"solving"|"results";
type Traveler="solo"|"couple"|"family"|"friends";
type Mood="relax"|"romantic"|"food"|"warmth"|"city"|"nature"|"adventure"|"culture";
type Profile={travelerType:Traveler;moods:Mood[];pace:"slow"|"balanced"|"full";desiredEnergy:"restore"|"balanced"|"stimulating";socialPreference:"quiet"|"balanced"|"lively";noveltyPreference:"familiar"|"balanced"|"surprise";avoid:"long-travel"|"high-cost"|"crowds"|"none";mustHave:"sea"|"nature"|"culture"|"nightlife"|"none";dnaLabels:string[]};
type Discovery={summary:string;profile:Profile;confidence:number};
type Window={id:string;label:string;note:string;start:string;end:string;reason:string;confidence:"HIGH"|"MEDIUM"};
type Media={imageUrl:string;sourceUrl:string;title:string;description?:string;license:string;attribution:string};
type World={id:string;query:string;labelEl:string;labelEn:string;subEl:string;subEn:string;semantic:string;fallbackMood:Mood};
type StreamRow={type:string;progress?:number;message?:string;result?:EscapeSolutionResponseV36};
const say=(lang:Lang,el:string,en:string)=>lang==="el"?el:en;
const worlds:World[]=[
 {id:"sea",query:"Santorini aerial coast Greece",labelEl:"Θάλασσα & φως",labelEn:"Sea & light",subEl:"Νερό · ήλιος · αργός ρυθμός",subEn:"Water · sun · slow rhythm",semantic:"θέλω θάλασσα, φως, ζεστασιά και αργό ρυθμό",fallbackMood:"warmth"},
 {id:"reset",query:"Madeira aerial green mountains",labelEl:"Reset στη φύση",labelEn:"Nature reset",subEl:"Πράσινο · ανάσα · ησυχία",subEn:"Green · space · quiet",semantic:"θέλω φύση, πράσινο, ησυχία και πραγματικό reset",fallbackMood:"nature"},
 {id:"city",query:"Rome old town aerial evening",labelEl:"Πόλη & βράδυ",labelEn:"City & evenings",subEl:"Βόλτες · φαγητό · ατμόσφαιρα",subEn:"Walking · food · atmosphere",semantic:"θέλω ατμοσφαιρική πόλη, βόλτες, φαγητό και ωραίο βράδυ",fallbackMood:"city"},
 {id:"together",query:"Amalfi coast aerial sunset",labelEl:"Χρόνος για δύο",labelEn:"Time for two",subEl:"Ρομαντικό · όμορφο · χωρίς πίεση",subEn:"Romantic · beautiful · easy",semantic:"θέλω χρόνο για δύο, ρομαντική ατμόσφαιρα και χωρίς πίεση",fallbackMood:"romantic"},
 {id:"adventure",query:"Madeira cliffs aerial ocean",labelEl:"Περιπέτεια",labelEn:"Adventure",subEl:"Τοπίο · κίνηση · κάτι αξέχαστο",subEn:"Landscape · movement · memorable",semantic:"θέλω περιπέτεια, εντυπωσιακή φύση και κάτι που θα θυμάμαι",fallbackMood:"adventure"},
 {id:"surprise",query:"European hidden coastal village aerial",labelEl:"Έκπληξέ με",labelEn:"Surprise me",subEl:"Όχι το προφανές · το σωστό",subEn:"Not obvious · just right",semantic:"βρες κάτι που δεν θα έψαχνα μόνος μου αλλά ταιριάζει πραγματικά",fallbackMood:"relax"}
];
const groupSize=(t:Traveler)=>t==="solo"?1:t==="couple"?2:4;
const DAY=86_400_000,iso=(d:Date)=>d.toISOString().slice(0,10),add=(d:Date,n:number)=>new Date(d.getTime()+n*DAY);
function nextFriday(){const d=new Date(),u=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())),delta=(5-u.getUTCDay()+7)%7||7;return add(u,delta)}
function fallbackWindows(lang:Lang,duration:number):Window[]{const fri=nextFriday();return[{id:"soon",label:say(lang,"Αυτό το weekend","This weekend"),note:say(lang,"Η γρήγορη απόδραση","The quick escape"),start:iso(fri),end:iso(add(fri,duration)),reason:say(lang,"Χαμηλή οργανωτική τριβή.","Low planning friction."),confidence:"MEDIUM"},{id:"space",label:say(lang,"Σε δύο εβδομάδες","In two weeks"),note:say(lang,"Περισσότερος χώρος επιλογών","More room to choose"),start:iso(add(fri,14)),end:iso(add(fri,14+duration)),reason:say(lang,"Περισσότερος χρόνος για σωστό matching.","More room for a stronger match."),confidence:"MEDIUM"},{id:"quiet",label:say(lang,"Κυριακή → μέσα εβδομάδας","Sunday → midweek"),note:say(lang,"Πιο ήσυχος ρυθμός","A quieter rhythm"),start:iso(add(fri,9)),end:iso(add(fri,9+duration)),reason:say(lang,"Διαφορετικός ρυθμός από το κλασικό weekend.","A different rhythm from the classic weekend."),confidence:"MEDIUM"}]}

export function V38EscapeFunnel({lang="el"}:{lang?:Lang}){
 const[stage,setStage]=useState<Stage>("feel"),[world,setWorld]=useState(worlds[0].id),[need,setNeed]=useState(""),[traveler,setTraveler]=useState<Traveler>("couple"),[profile,setProfile]=useState<Profile|null>(null),[summary,setSummary]=useState(""),[duration,setDuration]=useState(3),[windows,setWindows]=useState<Window[]>(()=>fallbackWindows(lang,3)),[windowId,setWindowId]=useState("soon"),[customDates,setCustomDates]=useState(false),[customStart,setCustomStart]=useState(iso(nextFriday())),[customEnd,setCustomEnd]=useState(iso(add(nextFriday(),3))),[origin,setOrigin]=useState(say(lang,"Αθήνα","Athens")),[budget,setBudget]=useState(900),[mustHave,setMustHave]=useState<Profile["mustHave"]>("none"),[avoid,setAvoid]=useState<Profile["avoid"]>("none"),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[worldMedia,setWorldMedia]=useState<Record<string,Media>>({}),[resultMedia,setResultMedia]=useState<Record<string,Media[]>>({}),[result,setResult]=useState<EscapeSolutionResponseV36|null>(null),[solutionIndex,setSolutionIndex]=useState(0),[progress,setProgress]=useState(0),[progressText,setProgressText]=useState(""),[missionId,setMissionId]=useState<string|null>(null);
 const activeWorld=worlds.find(x=>x.id===world)??worlds[0],selectedWindow=customDates?{id:"custom",label:say(lang,"Οι ημερομηνίες μου","My dates"),note:"",start:customStart,end:customEnd,reason:"",confidence:"HIGH" as const}:windows.find(x=>x.id===windowId)??windows[0],solutions=result?.solutions??[],selected=solutions[solutionIndex]??null,selectedMedia=selected?resultMedia[selected.recommendation.slug]??[]:[],heroUrl=stage==="results"?(selectedMedia[0]?.imageUrl||selected?.stay.imageUrl||worldMedia[world]?.imageUrl):(worldMedia[world]?.imageUrl);
 const initialText=useMemo(()=>`${need.trim()?`${need.trim()}. `:""}${activeWorld.semantic}. ${traveler==="couple"?"ταξίδι για δύο":traveler==="family"?"ταξίδι με παιδιά":traveler==="friends"?"ταξίδι με φίλους":"solo ταξίδι"}`,[need,activeWorld,traveler]);

 useEffect(()=>{let cancelled=false;Promise.all(worlds.map(async item=>{const d=await fetch(`/api/escape/media?destination=${encodeURIComponent(item.query)}&mode=aerial`).then(r=>r.ok?r.json():null).catch(()=>null) as {items?:Media[]}|null;return[item.id,d?.items?.[0]??null] as const})).then(rows=>{if(cancelled)return;const map:Record<string,Media>={};for(const[id,item]of rows)if(item)map[id]=item;setWorldMedia(map)});return()=>{cancelled=true}},[]);
 useEffect(()=>{if(!selected)return;const slug=selected.recommendation.slug;if(resultMedia[slug])return;const destination=selected.recommendation.destinationEn||selected.recommendation.destination;fetch(`/api/escape/media?destination=${encodeURIComponent(destination)}&mode=aerial`).then(r=>r.ok?r.json():null).then((d:{items?:Media[]}|null)=>{if(d?.items?.length)setResultMedia(prev=>({...prev,[slug]:d.items!.slice(0,4)}))}).catch(()=>null)},[selected?.recommendation.slug]);

 async function understand(event?:FormEvent){event?.preventDefault();setBusy(true);setError(null);try{const response=await fetch("/api/escape/discovery",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,initialText,answers:[{questionId:"companions",value:traveler}]})});if(!response.ok)throw new Error();const data=await response.json() as Discovery;const nextProfile={...data.profile,travelerType:traveler,moods:data.profile.moods.length?data.profile.moods:[activeWorld.fallbackMood]};setProfile(nextProfile);setSummary(data.summary);setMustHave(nextProfile.mustHave);setAvoid(nextProfile.avoid);setStage("when");void loadDates(nextProfile)}catch{setError(say(lang,"Δεν μπόρεσα να καταλάβω αρκετά το ταξίδι. Δοκίμασε ξανά με μία μικρή φράση.","I could not understand enough about the trip. Try again with one short sentence."))}finally{setBusy(false)}}
 async function loadDates(p:Profile){const backup=fallbackWindows(lang,duration);setWindows(backup);setWindowId(backup[0].id);try{const response=await fetch("/api/escape/date-opportunities",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,initialText,duration,horizonDays:120,profile:{travelerType:p.travelerType,desiredEnergy:p.desiredEnergy,socialPreference:p.socialPreference,noveltyPreference:p.noveltyPreference,avoid:p.avoid,moods:p.moods}})});if(!response.ok)return;const data=await response.json() as {windows?:Window[]};if(data.windows?.length===3){setWindows(data.windows);setWindowId(data.windows[0].id)}}catch{}}
 async function changeDuration(n:number){setDuration(n);const p=profile;if(p)void loadDates(p);if(customDates)setCustomEnd(iso(add(new Date(`${customStart}T00:00:00Z`),n)))}
 async function solve(){if(!profile||!selectedWindow||Date.parse(selectedWindow.end)<=Date.parse(selectedWindow.start))return;setBusy(true);setError(null);setProgress(2);setProgressText(say(lang,"Χτίζω το πρόβλημα ταξιδιού…","Framing the travel problem…"));setStage("solving");const finalProfile={...profile,travelerType:traveler,mustHave,avoid},nights=Math.max(1,Math.round((Date.parse(`${selectedWindow.end}T00:00:00Z`)-Date.parse(`${selectedWindow.start}T00:00:00Z`))/DAY)),trip={origin,startDate:selectedWindow.start,endDate:selectedWindow.end,month:"flexible",nights,budget,moods:finalProfile.moods,travelerType:traveler,language:lang,distancePreference:"any",pace:finalProfile.pace,hotelStyle:"any",avoid:finalProfile.avoid,entryMode:"idea",groupSize:groupSize(traveler),desiredEnergy:finalProfile.desiredEnergy,socialPreference:finalProfile.socialPreference,noveltyPreference:finalProfile.noveltyPreference,mustHave:finalProfile.mustHave,dateFlexibility:customDates?"fixed":"few-days",transportMode:"any",stayLocationPreference:"balanced",tripText:initialText};
  try{let currentMission=missionId;if(!currentMission){const mission=await fetch("/api/escape/mission",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,originText:origin,travelWindow:{label:selectedWindow.label,start:selectedWindow.start,end:selectedWindow.end},needText:need.trim()||activeWorld.semantic,travelerType:traveler,groupSize:groupSize(traveler),budgetEur:budget,dna:finalProfile.dnaLabels.length?finalProfile.dnaLabels:[say(lang,"Προσωπική απόδραση","Personal escape")],profile:finalProfile})}).then(r=>r.ok?r.json():null).catch(()=>null) as {missionId?:string}|null;currentMission=mission?.missionId??null;if(currentMission)setMissionId(currentMission)}
   const response=await fetch("/api/escape/solve-v36/stream",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(trip)});if(!response.ok||!response.body)throw new Error();const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="",finalResult:EscapeSolutionResponseV36|null=null;for(;;){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()??"";for(const line of lines){if(!line.trim())continue;const row=JSON.parse(line) as StreamRow;if(row.progress!=null)setProgress(row.progress);if(row.message)setProgressText(row.message);if(row.type==="final"&&row.result)finalResult=row.result}}
   if(!finalResult?.solutions.length)throw new Error("empty");setResult(finalResult);setSolutionIndex(0);setStage("results")
  }catch{setError(say(lang,"Δεν βρήκα ασφαλή inventory-backed λύση. Άνοιξε λίγο budget ή ημερομηνίες και ξανατρέχω χωρίς να εφεύρω επιλογές.","I did not find a safe inventory-backed solution. Widen the budget or dates and I will rerun without inventing options."));setStage("reality")}finally{setBusy(false)}}
 function escapeHref(solution:EscapeSolutionV36){const p=new URLSearchParams({lang,start:selectedWindow.start,end:selectedWindow.end,offer:solution.stay.sourceProductId,budget:String(budget),origin,travelerType:traveler,mood:solution.recommendation.tags?.[0]??activeWorld.fallbackMood});if(missionId)p.set("mission",missionId);return`/escape/${solution.recommendation.slug}?${p}`}

 return <main className={styles.shell}>
  <div className={styles.bg}>{heroUrl?<img src={heroUrl} alt="" key={heroUrl}/>:null}<div/></div>
  <header className={styles.header}><a href={lang==="en"?"/en":"/"} className={styles.brand}><b>AI</b><span>ESCAPE STUDIO</span></a><div className={styles.stageDots}>{["feel","when","reality","results"].map((s,i)=><span key={s} className={stage===s||(stage==="solving"&&s==="reality")?styles.dotOn:""}>{i+1}</span>)}</div><a className={styles.lang} href={lang==="en"?"/":"/en"}>{lang==="en"?"GR":"EN"}</a></header>

  {stage==="feel"?<section className={styles.screen}><div className={styles.intro}><span>{say(lang,"ΔΕΝ ΧΡΕΙΑΖΕΣΑΙ ΑΛΛΗ ΜΙΑ ΑΝΑΖΗΤΗΣΗ","YOU DON'T NEED ANOTHER SEARCH")}</span><h1>{say(lang,"Πες μου τι χρειάζεσαι να νιώσεις.","Tell me what you need to feel.")}</h1><p>{say(lang,"Θα μετατρέψω αυτό το συναίσθημα σε πραγματικές ημερομηνίες, προορισμούς και καταλύματα.","I will turn that feeling into real dates, destinations and stays.")}</p></div><div className={styles.worlds}>{worlds.map(item=><button type="button" key={item.id} onClick={()=>setWorld(item.id)} className={world===item.id?styles.worldActive:""} style={worldMedia[item.id]?{backgroundImage:`linear-gradient(180deg,rgba(4,10,8,.06),rgba(4,10,8,.78)),url('${worldMedia[item.id].imageUrl}')`}:undefined}><strong>{say(lang,item.labelEl,item.labelEn)}</strong><small>{say(lang,item.subEl,item.subEn)}</small></button>)}</div><form className={styles.needDock} onSubmit={understand}><div className={styles.travelers}>{(["solo","couple","family","friends"] as Traveler[]).map(t=><button type="button" key={t} className={traveler===t?styles.chipOn:""} onClick={()=>setTraveler(t)}>{t==="solo"?say(lang,"Μόνος/η","Solo"):t==="couple"?say(lang,"Δύο","Two"):t==="family"?say(lang,"Οικογένεια","Family"):say(lang,"Φίλοι","Friends")}</button>)}</div><input value={need} onChange={e=>setNeed(e.target.value)} placeholder={say(lang,"π.χ. είμαστε κουρασμένοι, θέλουμε 3 μέρες χωρίς πολύ οδήγηση…","e.g. we're exhausted, want 3 days with very little driving…")}/><button disabled={busy}>{busy?say(lang,"Καταλαβαίνω…","Understanding…"):say(lang,"Βρες το σχήμα της απόδρασης →","Shape my escape →")}</button></form></section>:null}

  {stage==="when"&&profile?<section className={styles.screen}><div className={styles.centerHead}><span>ESCAPE DNA</span><h2>{summary}</h2><div className={styles.dna}>{profile.dnaLabels.map(label=><b key={label}>{label}</b>)}</div></div><div className={styles.duration}><span>{say(lang,"Πόσο χρόνο έχεις;","How much time do you have?")}</span>{[2,3,4,5,7].map(n=><button type="button" key={n} onClick={()=>changeDuration(n)} className={duration===n?styles.chipOn:""}>{n} {say(lang,"νύχτες","nights")}</button>)}</div><div className={styles.windows}>{windows.map(item=><button type="button" key={item.id} className={!customDates&&windowId===item.id?styles.windowOn:""} onClick={()=>{setCustomDates(false);setWindowId(item.id)}}><small>{item.note}</small><strong>{item.label}</strong><span>{item.start.slice(5)} → {item.end.slice(5)}</span><p>{item.reason}</p></button>)}</div><div className={styles.customDate}><button type="button" onClick={()=>setCustomDates(v=>!v)} className={customDates?styles.chipOn:""}>{say(lang,"Έχω δικές μου ημερομηνίες","I have my own dates")}</button>{customDates?<><input type="date" value={customStart} onChange={e=>setCustomStart(e.target.value)}/><input type="date" value={customEnd} min={customStart} onChange={e=>setCustomEnd(e.target.value)}/></>:null}</div><div className={styles.bottomCta}><button type="button" onClick={()=>setStage("reality")}>{say(lang,"Αυτές οι ημερομηνίες μου κάνουν →","These dates work →")}</button></div></section>:null}

  {stage==="reality"&&profile?<section className={styles.screen}><div className={styles.centerHead}><span>{say(lang,"ΜΟΝΟ Η ΠΡΑΓΜΑΤΙΚΟΤΗΤΑ ΠΟΥ ΑΛΛΑΖΕΙ ΤΗΝ ΑΠΟΦΑΣΗ","ONLY REALITY THAT CHANGES THE DECISION")}</span><h2>{say(lang,"Αφετηρία και άνετο συνολικό budget.","Origin and a comfortable total budget.")}</h2><p>{say(lang,"Τα υπόλοιπα τα έχει ήδη καταλάβει ο agent. Αν θέλεις, κάνε ένα μικρό fine-tune.","The agent already understood the rest. Fine-tune only if you want.")}</p></div><div className={styles.realityGrid}><label><span>{say(lang,"Φεύγω από","Leaving from")}</span><input value={origin} onChange={e=>setOrigin(e.target.value)} /></label><label><span>{say(lang,"Συνολικό budget","Total budget")}</span><div className={styles.money}>€<input type="number" min="150" max="10000" step="50" value={budget} onChange={e=>setBudget(Math.max(150,Number(e.target.value)||150))}/></div></label></div><details className={styles.tune}><summary>{say(lang,"Προαιρετικό fine-tune","Optional fine-tune")}</summary><div><span>{say(lang,"Πρέπει να έχει","Must have")}</span>{(["none","sea","nature","culture","nightlife"] as Profile["mustHave"][]).map(x=><button type="button" key={x} className={mustHave===x?styles.chipOn:""} onClick={()=>setMustHave(x)}>{x==="none"?say(lang,"Ό,τι ταιριάζει","Best fit"):x==="sea"?say(lang,"Θάλασσα","Sea"):x==="nature"?say(lang,"Φύση","Nature"):x==="culture"?say(lang,"Κουλτούρα","Culture"):say(lang,"Βράδυ","Nightlife")}</button>)}</div><div><span>{say(lang,"Θέλω να αποφύγω","Avoid")}</span>{(["none","long-travel","high-cost","crowds"] as Profile["avoid"][]).map(x=><button type="button" key={x} className={avoid===x?styles.chipOn:""} onClick={()=>setAvoid(x)}>{x==="none"?say(lang,"Κανένα","Nothing"):x==="long-travel"?say(lang,"Πολλή μετακίνηση","Long travel"):x==="high-cost"?say(lang,"Premium χωρίς λόγο","Pointless premium"):say(lang,"Πολυκοσμία","Crowds")}</button>)}</div></details><div className={styles.bottomCta}><button type="button" onClick={solve} disabled={busy}>{say(lang,"Βρες τις πραγματικές μου λύσεις →","Find my real solutions →")}</button></div></section>:null}

  {stage==="solving"?<section className={styles.solve}><div className={styles.radar}><i/><i/><i/></div><span>DUAL-PASS AGENT</span><h2>{progressText||say(lang,"Ελέγχω προορισμό και πραγματικό inventory και από τις δύο πλευρές.","Checking destination fit and real inventory from both directions.")}</h2><div className={styles.progress}><b style={{width:`${Math.max(3,progress)}%`}}/></div><small>{progress}% · Need → Destination → Stay ⇄ Stay → Destination → Need</small></section>:null}

  {stage==="results"&&selected?<section className={styles.results}><div className={styles.resultCopy}><span>#{selected.rank} · {selected.recommendation.explorationRole.replaceAll("_"," ")}</span><h1>{lang==="en"?selected.recommendation.destinationEn:selected.recommendation.destination}</h1><p>{selected.reasoning.destination}</p><div className={styles.scoreRow}><div><small>{say(lang,"ΣΥΝΟΛΙΚΟ FIT","TOTAL FIT")}</small><strong>{selected.combinedScore}</strong></div><div><small>{say(lang,"ΠΡΟΟΡΙΣΜΟΣ","DESTINATION")}</small><strong>{selected.destinationScore}</strong></div><div><small>{say(lang,"ΔΙΑΜΟΝΗ","STAY")}</small><strong>{selected.stayScore}</strong></div></div><div className={styles.stayPeek}>{selected.stay.imageUrl?<img src={selected.stay.imageUrl} alt=""/>:null}<div><small>{say(lang,"ΠΡΑΓΜΑΤΙΚΗ ΒΑΣΗ","REAL STAY")}</small><strong>{selected.stay.propertyName}</strong><span>{selected.stay.city}</span><b>{selected.stay.price!=null&&selected.stay.price>0?`${selected.stay.price.toLocaleString()} ${selected.stay.currency||"EUR"}`:say(lang,"Τιμή στον πάροχο","Price at provider")}</b></div></div><p className={styles.tradeoff}><b>{say(lang,"Trade-off:","Trade-off:")}</b> {selected.reasoning.tradeoff}</p><a className={styles.build} href={escapeHref(selected)}>{say(lang,"Χτίσε αυτή την απόδραση 360° →","Build this 360° escape →")}</a></div><div className={styles.resultRail}>{solutions.map((solution,index)=><button type="button" key={solution.recommendation.slug} onClick={()=>setSolutionIndex(index)} className={solutionIndex===index?styles.resultOn:""}><small>#{index+1}</small><strong>{lang==="en"?solution.recommendation.destinationEn:solution.recommendation.destination}</strong><span>{solution.combinedScore}/100</span></button>)}</div><div className={styles.resultNav}><button type="button" onClick={()=>setSolutionIndex(i=>(i-1+solutions.length)%solutions.length)}>←</button><span>{solutionIndex+1} / {solutions.length}</span><button type="button" onClick={()=>setSolutionIndex(i=>(i+1)%solutions.length)}>→</button></div></section>:null}
  {error?<div className={styles.error}>{error}<button onClick={()=>setError(null)}>×</button></div>:null}
 </main>
}
