"use client";

import "leaflet/dist/leaflet.css";
import { useEffect,useMemo,useRef,useState } from "react";
import type { V8StayOffer } from "@/lib/decision/v8-types";
import type { TripRequest } from "@/lib/validation/trip";
import type { StayReviewIntelligenceV39 } from "@/lib/data/stay-review-intelligence-v39";
import styles from "./v39-destination-map-workspace.module.css";

type Lang="el"|"en";
type Props={slug:string;name:string;nameEn:string;latitude:number;longitude:number;trip:TripRequest;offers:V8StayOffer[];lang?:Lang;missionId?:string|null};
const say=(l:Lang,el:string,en:string)=>l==="el"?el:en;
const money=(offer:V8StayOffer,lang:Lang)=>offer.price!=null&&offer.price>0?`${offer.price.toLocaleString(lang==="el"?"el-GR":"en-GB",{maximumFractionDigits:2})} ${offer.currency||"EUR"}`:say(lang,"Τιμή στον πάροχο","Price at provider");
const fit=(o:V8StayOffer,index:number)=>Math.max(62,Math.min(98,Math.round((o.semanticScore??.72)*72+(o.demandSignal??0)*.08+Math.max(0,18-index*.9))));
function ratingLabel(intel:StayReviewIntelligenceV39|null,lang:Lang){const ext=intel?.ratings.find(x=>x.provider!=="AI Guest Signal");if(!ext)return say(lang,"Δεν έχει φορτωθεί verified rating","Verified rating not loaded");return `${ext.rating.toFixed(1)}/${ext.scale} · ${ext.provider}${ext.reviewCount!=null?` · ${ext.reviewCount.toLocaleString()} ${say(lang,"αξιολογήσεις","ratings")}`:""}`}
function qs(trip:TripRequest,lang:Lang,missionId:string|null,offerId?:string){const p=new URLSearchParams({lang,start:trip.startDate,end:trip.endDate,budget:String(trip.budget),origin:trip.origin,travelerType:trip.travelerType,mood:trip.moods[0]??"relax"});if(missionId)p.set("mission",missionId);if(offerId)p.set("offer",offerId);return p.toString()}

export function V39DestinationMapWorkspace({slug,name,nameEn,latitude,longitude,trip,offers,lang="el",missionId=null}:Props){
 const destination=lang==="en"?nameEn:name,eligible=useMemo(()=>offers.filter(x=>x.latitude!=null&&x.longitude!=null),[offers]),ranked=useMemo(()=>[...eligible].sort((a,b)=>(b.semanticScore??0)-(a.semanticScore??0)||(b.demandSignal??0)-(a.demandSignal??0)||(a.price??999999)-(b.price??999999)),[eligible]),top=useMemo(()=>ranked.slice(0,10),[ranked]);
 const[selectedId,setSelectedId]=useState(top[0]?.sourceProductId??""),[reviews,setReviews]=useState<Record<string,StayReviewIntelligenceV39|null|undefined>>({}),[showAll,setShowAll]=useState(false),[panel,setPanel]=useState<"cards"|"truth">("cards"),mapHost=useRef<HTMLDivElement|null>(null),cleanup=useRef<(()=>void)|null>(null);
 const visible=showAll?ranked:top,selected=ranked.find(x=>x.sourceProductId===selectedId)??top[0]??null,selectedReview=selected?reviews[selected.sourceProductId]??null:null;
 useEffect(()=>{if(!selectedId&&top[0])setSelectedId(top[0].sourceProductId)},[top,selectedId]);

 useEffect(()=>{let cancelled=false;async function load(){for(const offer of top){if(cancelled||reviews[offer.sourceProductId]!==undefined)continue;setReviews(prev=>({...prev,[offer.sourceProductId]:undefined}));const response=await fetch("/api/escape/stay-reviews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({propertyName:offer.propertyName,sourceProductId:offer.sourceProductId,destinationSlug:slug,destinationName:destination,latitude:offer.latitude,longitude:offer.longitude,language:lang})}).catch(()=>null);const payload=response?.ok?await response.json().catch(()=>null):null;if(cancelled)return;setReviews(prev=>({...prev,[offer.sourceProductId]:payload?.result??null}))}}
  void load();return()=>{cancelled=true}
 },[top.map(x=>x.sourceProductId).join("|"),slug,destination,lang]);

 useEffect(()=>{if(!mapHost.current||!eligible.length)return;let dead=false;cleanup.current?.();async function mount(){const L=await import("leaflet");if(dead||!mapHost.current)return;const map=L.map(mapHost.current,{zoomControl:true,scrollWheelZoom:true,minZoom:5,attributionControl:true}).setView([latitude,longitude],10);L.tileLayer(process.env.NEXT_PUBLIC_MAP_TILE_URL||"https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"© OpenStreetMap contributors"}).addTo(map);const bounds:L.LatLngExpression[]=[],markers:L.Marker[]=[];for(const[index,offer]of eligible.entries()){const active=offer.sourceProductId===selected?.sourceProductId,isTop=top.some(x=>x.sourceProductId===offer.sourceProductId),label=offer.price!=null&&offer.price>0?`${Math.round(offer.price)}${offer.currency==="EUR"||!offer.currency?"€":offer.currency}`:`#${index+1}`,icon=L.divIcon({className:"v39-map-marker-shell",html:`<span class="v39-map-marker ${active?"is-active":""} ${isTop?"is-top":""}">${label}</span>`,iconSize:[72,38],iconAnchor:[36,19]});const marker=L.marker([offer.latitude!,offer.longitude!],{icon,title:offer.propertyName,keyboard:true}).addTo(map);marker.on("click",()=>setSelectedId(offer.sourceProductId));markers.push(marker);bounds.push([offer.latitude!,offer.longitude!])}if(bounds.length>1)map.fitBounds(L.latLngBounds(bounds),{padding:[48,48],maxZoom:12});if(selected?.latitude!=null&&selected.longitude!=null){map.flyTo([selected.latitude,selected.longitude],Math.max(map.getZoom(),13),{duration:.65})}window.setTimeout(()=>map.invalidateSize(),60);cleanup.current=()=>{markers.forEach(x=>x.remove());map.remove()}}
  void mount();return()=>{dead=true;cleanup.current?.();cleanup.current=null}
 },[eligible.map(x=>x.sourceProductId).join("|"),selected?.sourceProductId,latitude,longitude]);

 function select(offer:V8StayOffer){setSelectedId(offer.sourceProductId);setPanel("cards")}
 const externalRatings=selectedReview?.ratings.filter(x=>x.provider!=="AI Guest Signal")??[],guest=selectedReview?.aiGuestSignal??null;
 return <main className={styles.shell}>
  <header className={styles.header}><div><a href={lang==="en"?"/en":"/"} className={styles.brand}><b>AI</b> ESCAPE STUDIO</a><span className={styles.crumb}>/ {destination}</span></div><div className={styles.tripMeta}><span>{trip.startDate} → {trip.endDate}</span><span>{trip.travelerType}</span><span>€{trip.budget}</span></div></header>
  <section className={styles.workspace}>
   <div className={styles.mapWrap}><div ref={mapHost} className={styles.map}/><div className={styles.mapTitle}><small>{say(lang,"Η ΠΕΡΙΟΧΗ ΣΟΥ","YOUR AREA")}</small><strong>{destination}</strong><span>{eligible.length} {say(lang,"πραγματικά stays στον χάρτη","real stays on map")}</span></div>{selected?<div className={styles.mapFloat}><b>{selected.propertyName}</b><span>{selected.city||selected.address}</span><strong>{money(selected,lang)}</strong></div>:null}</div>
   <aside className={styles.panel}>
    <div className={styles.panelHead}><div><span>{say(lang,"STAY DECISION MAP","STAY DECISION MAP")}</span><h1>{say(lang,"Δες πού αξίζει να μείνεις.","See where it makes sense to stay.")}</h1><p>{say(lang,"Το AI συνδυάζει fit, πραγματικό inventory, τοποθεσία και διαθέσιμα review signals πριν επιλέξεις.","AI combines fit, real inventory, location and available review signals before you choose.")}</p></div><button type="button" onClick={()=>setPanel(panel==="truth"?"cards":"truth")}>{panel==="truth"?say(lang,"Πίσω στις επιλογές","Back to stays"):say(lang,"Πώς βαθμολογούμε","How ranking works")}</button></div>
    {panel==="truth"?<div className={styles.truth}><h2>{say(lang,"Τι ξέρουμε και τι όχι","What we know — and what we don't")}</h2><div><b>✓</b><span>{say(lang,"Τα pins προέρχονται από το πραγματικό stay inventory και πραγματικές συντεταγμένες.","Pins come from real stay inventory and real coordinates.")}</span></div><div><b>✓</b><span>{say(lang,"Google / Tripadvisor / Foursquare εμφανίζονται μόνο όταν ο provider επιστρέφει match για το συγκεκριμένο κατάλυμα.","Google / Tripadvisor / Foursquare appear only when the provider returns a match for that exact stay.")}</span></div><div><b>✓</b><span>{say(lang,"Το AI Review Summary συνοψίζει μόνο τα διαθέσιμα review samples — δεν δημιουργεί κριτικές.","AI Review Summary summarizes only available review samples — it never invents reviews.")}</span></div><div><b>○</b><span>{say(lang,"Τελική διαθεσιμότητα, φόροι και όροι κράτησης επιβεβαιώνονται μόνο στον συνεργάτη.","Final availability, taxes and booking terms are confirmed only with the partner.")}</span></div><p>{say(lang,"Affiliate disclosure: αν αργότερα συνεχίσεις από το μοναδικό booking CTA και κάνεις κράτηση, ενδέχεται να λάβουμε προμήθεια χωρίς επιβάρυνση της τιμής σου.","Affiliate disclosure: if you later continue through the single booking CTA and complete a booking, we may receive a commission at no extra cost to you.")}</p></div>:<>
     <div className={styles.summaryBar}><span><b>TOP 10</b> {say(lang,"AI ranked","AI ranked")}</span><span>{ranked.length} {say(lang,"eligible συνολικά","eligible total")}</span></div>
     <div className={styles.cards}>{visible.map((offer,index)=>{const intel=reviews[offer.sourceProductId],active=offer.sourceProductId===selected?.sourceProductId,score=fit(offer,index),best=intel?.ratings.find(x=>x.provider!=="AI Guest Signal"),guestScore=intel?.aiGuestSignal;return <article key={offer.sourceProductId} className={`${styles.card} ${active?styles.cardActive:""}`} onClick={()=>select(offer)}><div className={styles.photo}>{offer.imageUrl?<img src={offer.imageUrl} alt={offer.propertyName} loading="lazy"/>:<span>AI</span>}<i>{score}% FIT</i></div><div className={styles.cardBody}><div className={styles.rank}><span>#{index+1}</span><b>{offer.propertyName}</b></div><small>{offer.city||offer.address||destination}</small><div className={styles.rating}>{intel===undefined?<span className={styles.loading}>{say(lang,"Σκανάρω verified ratings…","Scanning verified ratings…")}</span>:best?<><strong>{best.rating.toFixed(1)}★</strong><span>{best.provider}{best.reviewCount!=null?` · ${best.reviewCount.toLocaleString()}`:""}</span></>:<span>{say(lang,"Δεν βρέθηκε verified external rating","No verified external rating found")}</span>}</div>{guestScore?<span className={styles.guest}>AI Guest Signal {Math.round(guestScore.score)}/100 · {guestScore.sampleSize}</span>:null}<div className={styles.cardFoot}><strong>{money(offer,lang)}</strong><button type="button" onClick={e=>{e.stopPropagation();select(offer)}}>{say(lang,"Zoom","Zoom")}</button></div></div></article>})}</div>
     {ranked.length>10?<button type="button" className={styles.all} onClick={()=>setShowAll(v=>!v)}>{showAll?say(lang,"Δείξε μόνο Top 10","Show Top 10"):say(lang,`Δες και τα ${ranked.length} stays`,`See all ${ranked.length} stays`)}</button>:null}
    </>}
   </aside>
  </section>
  {selected?<section className={styles.decisionDock}><div className={styles.selectedMedia}>{selected.imageUrl?<img src={selected.imageUrl} alt=""/>:null}</div><div className={styles.selectedCopy}><span>{say(lang,"ΕΠΙΛΕΓΜΕΝΗ ΒΑΣΗ","SELECTED BASE")}</span><h2>{selected.propertyName}</h2><p>{selectedReview?.summary||say(lang,"Φόρτωσε την κάρτα για να δεις review intelligence πριν συνεχίσεις.","Load the card to see review intelligence before continuing.")}</p><div className={styles.chips}>{externalRatings.map(r=><b key={r.provider}>{r.rating.toFixed(1)}★ {r.provider}</b>)}{guest?<b>AI Guest {Math.round(guest.score)}/100</b>:null}<b>{fit(selected,Math.max(0,ranked.indexOf(selected)))}% AI Fit</b></div>{selectedReview?.positives.length?<small>✓ {selectedReview.positives.join(" · ")}</small>:null}{selectedReview?.watchouts.length?<small>△ {selectedReview.watchouts.join(" · ")}</small>:null}</div><div className={styles.actions}><strong>{money(selected,lang)}</strong><a href={`/escape/${encodeURIComponent(slug)}/stay/${encodeURIComponent(selected.sourceProductId)}?${qs(trip,lang,missionId,selected.sourceProductId)}`}>{say(lang,"Explore this stay →","Explore this stay →")}</a><small>{say(lang,"Δεν ανοίγει εξωτερικό site. Συνεχίζεις στο δικό μας 360° Escape Studio.","No external site opens. You continue inside our 360° Escape Studio.")}</small></div></section>:null}
 </main>
}
