"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import QRCode from "qrcode";
import type { V8StayOffer } from "@/lib/decision/v8-types";
import type { TripRequest } from "@/lib/validation/trip";
import type { TripBuilderPlanV25,TripadvisorPlaceV25 } from "@/lib/trip-builder/types-v25";
import type { LocalIntelligenceV38,LocalPlaceV38 } from "@/lib/data/local-intelligence-v38";
import type { StayReviewIntelligenceV39 } from "@/lib/data/stay-review-intelligence-v39";
import styles from "./v40-stay-workspace.module.css";

type Lang="el"|"en";
type Media={imageUrl:string;originalUrl?:string;sourceUrl:string;title:string;description?:string;license:string;attribution:string};
type ChatRow={role:"agent"|"user";text:string};
type Props={slug:string;destination:string;destinationEn:string;offer:V8StayOffer;trip:TripRequest;lang:Lang;missionId?:string|null};
type LocalResponse=LocalIntelligenceV38&{stay:{name:string;latitude:number;longitude:number;address:string|null;city:string|null}};
const say=(l:Lang,el:string,en:string)=>l==="el"?el:en;
const fmt=(n:number|null|undefined,l:Lang)=>n==null?"—":n.toLocaleString(l==="el"?"el-GR":"en-GB",{maximumFractionDigits:1});
const dayLabel=(iso:string,l:Lang)=>new Intl.DateTimeFormat(l==="el"?"el-GR":"en-GB",{weekday:"short",day:"numeric",month:"short"}).format(new Date(`${iso}T12:00:00Z`));
const unique=<T,>(rows:T[])=>[...new Set(rows)];
function parseImageValue(v:unknown):string[]{if(!v)return[];if(Array.isArray(v))return v.flatMap(parseImageValue);if(typeof v==="object")return Object.values(v as Record<string,unknown>).flatMap(parseImageValue);if(typeof v!=="string")return[];const s=v.trim();if(!s)return[];if(s.startsWith("[")||s.startsWith("{")){try{return parseImageValue(JSON.parse(s))}catch{}}return s.split(/[|,\n]+/).map(x=>x.trim()).filter(x=>/^https?:\/\//i.test(x))}
function stayImages(offer:V8StayOffer){const raw=offer.raw&&typeof offer.raw==="object"?offer.raw as Record<string,unknown>:{};return unique([offer.imageUrl||"",offer.thumbUrl||"",...parseImageValue(raw.extra_images),...parseImageValue(raw.extraImages),...parseImageValue(raw.variations)]).filter(x=>/^https?:\/\//i.test(x)).slice(0,12)}
function price(offer:V8StayOffer,l:Lang){return offer.price!=null&&offer.price>0?`${offer.price.toLocaleString(l==="el"?"el-GR":"en-GB",{maximumFractionDigits:2})} ${offer.currency||"EUR"}`:say(l,"Τιμή στον πάροχο","Price at provider")}
function urgency(offer:V8StayOffer,l:Lang){if(!offer.validTo)return null;const d=Math.ceil((Date.parse(offer.validTo)-Date.now())/86400000);if(d<0)return null;if(d<=14)return say(l,`Η προσφορά feed λήγει σε ${d} ημέρ${d===1?"α":"ες"}`,`Feed offer ends in ${d} day${d===1?"":"s"}`);if((offer.discount??0)>0)return say(l,`Feed έκπτωση ${Math.round(Number(offer.discount))}%`,`Feed discount ${Math.round(Number(offer.discount))}%`);return null}
function mergePlaces(local:LocalResponse|null,plan:TripBuilderPlanV25|null){if(local){return [...local.attractions,...local.museums,...local.beaches,...local.restaurants,...local.cafes,...local.nightlife]}const rows:LocalPlaceV38[]=[];const add=(kind:LocalPlaceV38["kind"],items:TripadvisorPlaceV25[])=>items.forEach(p=>rows.push({id:`ta:${p.locationId}`,name:p.name,kind,source:"Tripadvisor",rating:p.rating,ratingCount:p.reviewCount,ranking:p.ranking,address:p.address,url:null,imageUrl:p.imageUrl,latitude:null,longitude:null,distanceKm:null,internalSignal:null}));if(plan){add("attraction",plan.tripadvisor.places);add("museum",plan.tripadvisor.museums);add("restaurant",plan.tripadvisor.restaurants);add("nightlife",plan.tripadvisor.nightlife);add("beach",plan.tripadvisor.beaches)}return rows}

export function V40StayWorkspace({slug,destination,destinationEn,offer,trip,lang,missionId=null}:Props){
 const[plan,setPlan]=useState<TripBuilderPlanV25|null>(null),[local,setLocal]=useState<LocalResponse|null>(null),[reviews,setReviews]=useState<StayReviewIntelligenceV39|null>(null),[drone,setDrone]=useState<Media[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState<string|null>(null),[tab,setTab]=useState<"all"|"attraction"|"restaurant"|"nightlife"|"beach">("all"),[pace,setPace]=useState<"slow"|"balanced"|"full">(trip.pace==="slow"?"slow":trip.pace==="full"?"full":"balanced"),[chat,setChat]=useState<ChatRow[]>([{role:"agent",text:say(lang,`Έχουμε κλειδώσει ως βάση το ${offer.propertyName}. Τώρα μπορώ να προσαρμόσω το ταξίδι γύρω από εσένα χωρίς να σε ξαναμπερδέψω με άλλα καταλύματα.`,`We’ve locked ${offer.propertyName} as your base. Now I can tailor the trip around you without throwing more hotels at you.`)}]),[chatInput,setChatInput]=useState(""),[agentBusy,setAgentBusy]=useState(false),[email,setEmail]=useState(""),[emailBusy,setEmailBusy]=useState(false),[unlocked,setUnlocked]=useState(false),[emailMessage,setEmailMessage]=useState(""),[qr,setQr]=useState("");
 const hotelImages=useMemo(()=>stayImages(offer),[offer.sourceProductId]),allPlaces=useMemo(()=>mergePlaces(local,plan),[local,plan]),visiblePlaces=useMemo(()=>allPlaces.filter(p=>tab==="all"||p.kind===tab).slice(0,8),[allPlaces,tab]),urgent=urgency(offer,lang);
 const topRating=reviews?.ratings.find(x=>x.provider!=="AI Guest Signal")??(plan?.tripadvisor.hotel?.rating!=null?{provider:"Tripadvisor",rating:plan.tripadvisor.hotel.rating,scale:5,reviewCount:plan.tripadvisor.hotel.reviewCount}:null);
 useEffect(()=>{let cancelled=false;setBusy(true);Promise.all([
  fetch("/api/trip-builder",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip,slug,offerId:offer.sourceProductId})}).then(r=>r.ok?r.json():null).catch(()=>null),
  fetch("/api/escape/stay-local",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip,slug,offerId:offer.sourceProductId})}).then(r=>r.ok?r.json():null).catch(()=>null),
  fetch("/api/escape/stay-reviews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({propertyName:offer.propertyName,sourceProductId:offer.sourceProductId,destinationSlug:slug,destinationName:lang==="en"?destinationEn:destination,latitude:offer.latitude,longitude:offer.longitude,language:lang})}).then(r=>r.ok?r.json():null).catch(()=>null),
  fetch(`/api/escape/media?destination=${encodeURIComponent(destinationEn)}&mode=aerial`).then(r=>r.ok?r.json():null).catch(()=>null)
 ]).then(([p,l,r,m])=>{if(cancelled)return;setPlan(p as TripBuilderPlanV25|null);setLocal((l as LocalResponse|null));setReviews((r as {result?:StayReviewIntelligenceV39}|null)?.result??null);setDrone(((m as {items?:Media[]}|null)?.items??[]).slice(0,6));if(!p)setError(say(lang,"Δεν μπόρεσα να επαληθεύσω όλο το itinerary layer.","I could not verify the full itinerary layer."))}).finally(()=>{if(!cancelled)setBusy(false)});return()=>{cancelled=true}},[slug,offer.sourceProductId,trip.startDate,trip.endDate]);
 useEffect(()=>{QRCode.toDataURL(offer.trackingUrl,{margin:1,width:180}).then(setQr).catch(()=>setQr(""))},[offer.trackingUrl]);

 async function sendChat(e:FormEvent){e.preventDefault();const q=chatInput.trim();if(!q||agentBusy)return;setChat(v=>[...v,{role:"user",text:q}]);setChatInput("");setAgentBusy(true);try{const res=await fetch("/api/escape/agent-chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip,slug,offerId:offer.sourceProductId,message:q})});const data=await res.json().catch(()=>null) as {reply?:string;preferenceTags?:string[]}|null;if(!res.ok||!data?.reply)throw new Error();setChat(v=>[...v,{role:"agent",text:data.reply!}]);const tags=(data.preferenceTags??[]).join(" ").toLowerCase();if(/slow|quiet|relax|ηρεμ|χαλαρ/.test(tags))setPace("slow");if(/full|active|adventure|γεματ|δραστ/.test(tags))setPace("full")}catch{setChat(v=>[...v,{role:"agent",text:say(lang,"Δεν μπόρεσα να απαντήσω με επαληθευμένο context αυτή τη στιγμή. Δεν θα μαντέψω.","I can’t answer with verified context right now, so I won’t guess.")}])}finally{setAgentBusy(false)}}
 async function sendEmail(){if(!/^\S+@\S+\.\S+$/.test(email)){setEmailMessage(say(lang,"Βάλε ένα έγκυρο email.","Enter a valid email."));return}setEmailBusy(true);setEmailMessage("");try{const res=await fetch("/api/guide/email",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,slug,start:trip.startDate,end:trip.endDate,offer:offer.sourceProductId,language:lang,trip})});const d=await res.json().catch(()=>null) as {ok?:boolean}|null;if(!res.ok||!d?.ok)throw new Error();setUnlocked(true);setEmailMessage(say(lang,"Το Escape Book στάλθηκε. Ξεκλείδωσε και η τελική προσφορά.","Your Escape Book was sent. The final offer is now unlocked."))}catch{setEmailMessage(say(lang,"Η αποστολή email δεν ολοκληρώθηκε. Μπορείς να κρατήσεις το PDF όταν το service επανέλθει.","Email delivery did not complete. You can keep the PDF when the service is back."))}finally{setEmailBusy(false)}}
 const guidePath=plan?.guide.path??null;
 const weather=plan?.weather.days??[];
 const itinerary=useMemo(()=>{const start=Date.parse(`${trip.startDate}T00:00:00Z`),days=Math.max(2,Math.min(6,trip.nights+1)),attractions=allPlaces.filter(x=>x.kind==="attraction"||x.kind==="museum"||x.kind==="beach"),food=allPlaces.filter(x=>x.kind==="restaurant"||x.kind==="cafe"),night=allPlaces.filter(x=>x.kind==="nightlife");return Array.from({length:days},(_,i)=>{const date=new Date(start+i*86400000).toISOString().slice(0,10),rows:Array<{time:string;title:string;note:string}> = [];if(i===0)rows.push({time:"15:00",title:say(lang,"Άφιξη & τακτοποίηση","Arrival & check-in"),note:offer.propertyName});if(i>0&&i<days-1){const a=attractions[(i-1)%Math.max(1,attractions.length)];if(a)rows.push({time:"10:00",title:a.name,note:a.rating!=null?`${a.rating.toFixed(1)}★ · ${a.source}`:a.source});if(pace!=="slow"){const b=attractions[i%Math.max(1,attractions.length)];if(b&&b.id!==a?.id)rows.push({time:"13:00",title:b.name,note:b.address||say(lang,"Στην περιοχή","In the area")})}}const f=food[i%Math.max(1,food.length)];if(f)rows.push({time:i===days-1?"11:00":"20:00",title:f.name,note:f.rating!=null?`${f.rating.toFixed(1)}★${f.ratingCount?` · ${f.ratingCount} reviews`:""}`:f.source});if(pace==="full"&&i<days-1){const n=night[i%Math.max(1,night.length)];if(n)rows.push({time:"22:00",title:n.name,note:n.rating!=null?`${n.rating.toFixed(1)}★ · ${n.source}`:n.source})}if(i===days-1)rows.push({time:"12:30",title:say(lang,"Check-out","Check-out"),note:say(lang,"Χωρίς πρόγραμμα-μαραθώνιο πριν την αναχώρηση.","No itinerary marathon before departure.")});return{date,rows}})},[trip.startDate,trip.nights,pace,allPlaces,offer.propertyName,lang]);

 return <main className={styles.shell}>
  <header className={styles.topbar}><a href={lang==="en"?"/en":"/"} className={styles.brand}><span>AI</span><b>Holiday Escape</b></a><nav><a href={lang==="en"?"/en":"/"}>{say(lang,"Προορισμοί","Destinations")}</a><a>{say(lang,"Εμπειρίες","Experiences")}</a><a>{say(lang,"Το ταξίδι μου","My trip")}</a><a className={styles.navActive}>Travel Agent</a></nav><div className={styles.hello}>{say(lang,"Το ταξίδι σου","Your trip")} ✦</div></header>
  <div className={styles.page}>
   <aside className={styles.agent}><div className={styles.agentTitle}><span>✦</span><div><b>Travel Agent</b><small>● Online · {say(lang,"ξέρει το επιλεγμένο stay & το local dossier","knows your stay & local dossier")}</small></div></div><div className={styles.chat}>{chat.slice(-7).map((m,i)=><div key={i} className={m.role==="agent"?styles.agentBubble:styles.userBubble}>{m.text}</div>)}{agentBusy?<div className={styles.agentBubble}>{say(lang,"Ελέγχω τη βάση και τις τοπικές πηγές…","Checking the database and local sources…")}</div>:null}</div><div className={styles.agentQuick}><button onClick={()=>{setPace("slow");setChat(v=>[...v,{role:"user",text:say(lang,"Θέλω πιο ήρεμο πρόγραμμα.","I want a slower plan.")}])}}>{say(lang,"Πιο ήρεμο","Slower")}</button><button onClick={()=>{setPace("full");setChat(v=>[...v,{role:"user",text:say(lang,"Θέλω πιο γεμάτο πρόγραμμα.","I want a fuller plan.")}])}}>{say(lang,"Πιο γεμάτο","Fuller")}</button></div><form onSubmit={sendChat} className={styles.agentForm}><input value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder={say(lang,"Ρώτησε τον Travel Agent…","Ask the Travel Agent…")}/><button>➜</button></form></aside>
   <section className={styles.content}>
    <div className={styles.breadcrumb}>{say(lang,"Ελλάδα","Greece")} › {destination} › {say(lang,"Κατάλυμα","Stay")} › <b>{offer.propertyName}</b></div>
    <section className={styles.hero}><div className={styles.heroMain}>{hotelImages[0]?<img src={hotelImages[0]} alt={offer.propertyName}/>:drone[0]?<img src={drone[0].imageUrl} alt=""/>:null}<div className={styles.heroShade}/><div className={styles.heroCopy}>{urgent?<span className={styles.urgent}>{urgent}</span>:null}<h1>{offer.propertyName}</h1><div className={styles.stars}>{offer.starLevel?`${"★".repeat(Math.min(5,offer.starLevel))}`:""}</div><p>⌖ {offer.city||destination} {offer.address&&offer.address!==offer.city?` · ${offer.address}`:""}</p></div></div><div className={styles.gallery}>{hotelImages.slice(1,4).map((src,i)=><img key={src} src={src} alt={`${offer.propertyName} ${i+2}`}/>)}{drone.slice(0,2).map((m,i)=><div key={m.imageUrl} className={styles.drone}><img src={m.imageUrl} alt={destination}/><span>{i===0?"Cinematic Drone Gallery":say(lang,"Η περιοχή γύρω σου","Your surrounding area")}</span></div>)}</div><aside className={styles.heroFacts}><strong>{price(offer,lang)}</strong>{topRating?<div className={styles.ratingLine}><b>{topRating.rating.toFixed(1)}★</b><span>{topRating.provider}{topRating.reviewCount?` · ${topRating.reviewCount} reviews`:""}</span></div>:<div className={styles.ratingLine}><span>{say(lang,"Χωρίς verified external rating ακόμη","No verified external rating yet")}</span></div>}<p>{reviews?.summary||plan?.webResearch.overview||say(lang,"Επιλεγμένη βάση για να χτίσουμε την εμπειρία γύρω από τη συγκεκριμένη τοποθεσία.","Selected base for building the experience around this exact location.")}</p><div className={styles.why}><b>{say(lang,"Γιατί το προτείνει ο Travel Agent","Why the Travel Agent picked it")}</b><span>✓ {say(lang,"Το stay παραμένει κλειδωμένο όσο χτίζεις το itinerary","The stay stays locked while you build the itinerary")}</span><span>✓ {say(lang,"Weather + local research γίνονται γύρω από αυτό","Weather + local research are centered around it")}</span><span>✓ {say(lang,"Το booking CTA μένει κρυφό μέχρι το email handoff","Booking CTA stays hidden until email handoff")}</span></div></aside></section>
    <section className={styles.intelRow}><div className={styles.reviewBox}><h2>{say(lang,"Αξιολογήσεις & τι λένε οι ταξιδιώτες","Ratings & traveler signals")}</h2><div className={styles.metrics}>{reviews?.ratings.filter(r=>r.provider!=="AI Guest Signal").slice(0,4).map(r=><article key={r.provider}><strong>{r.rating.toFixed(1)}</strong><span>★ {r.provider}</span><small>{r.reviewCount?`${r.reviewCount} reviews`:say(lang,"verified provider signal","verified provider signal")}</small></article>)}{reviews?.aiGuestSignal?<article><strong>{Math.round(reviews.aiGuestSignal.score)}</strong><span>AI Guest Signal</span><small>{reviews.aiGuestSignal.sampleSize} {say(lang,"δικές μας εμπειρίες","first-party trips")}</small></article>:null}</div>{reviews?.positives?.length?<p className={styles.positive}>✓ {reviews.positives.join(" · ")}</p>:null}{reviews?.watchouts?.length?<p className={styles.watch}>△ {reviews.watchouts.join(" · ")}</p>:null}</div><div className={styles.weatherBox}><h2>{say(lang,"Καιρός στις ημερομηνίες σου","Weather for your dates")}</h2><div className={styles.weatherDays}>{weather.slice(0,4).map(d=><article key={d.date}><b>{dayLabel(d.date,lang)}</b><strong>{d.temperatureMaxC!=null?`${Math.round(d.temperatureMaxC)}°`:"—"}</strong><small>{d.summary}</small></article>)}</div></div></section>
    <section className={styles.nearby}><div className={styles.sectionHead}><div><h2>{say(lang,"Τι να δεις κοντά σου","What to do near your stay")}</h2><p>{say(lang,"Μόνο μέρη από το local intelligence layer, με source/rating όταν υπάρχουν. Κανένα εξωτερικό link.","Only places from the local intelligence layer, with source/rating when available. No external links.")}</p></div><div className={styles.tabs}>{(["all","attraction","restaurant","nightlife","beach"] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?styles.tabOn:""}>{t==="all"?say(lang,"Όλα","All"):t==="attraction"?say(lang,"Αξιοθέατα","Sights"):t==="restaurant"?say(lang,"Εστιατόρια","Food"):t==="nightlife"?"Bars":say(lang,"Παραλίες","Beaches")}</button>)}</div></div><div className={styles.placeRail}>{visiblePlaces.map((p,i)=><article key={p.id}>{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>:drone[i%Math.max(1,drone.length)]?<img src={drone[i%drone.length].imageUrl} alt=""/>:<div className={styles.placeFallback}>⌖</div>}<div><b>{p.name}</b><span>{p.rating!=null?`${p.rating.toFixed(1)}★${p.ratingCount?` · ${p.ratingCount}`:""}`:p.source}</span><p>{p.address||say(lang,"Στην περιοχή του καταλύματος","In the stay area")}</p><small>{p.distanceKm!=null?`${fmt(p.distanceKm,lang)} km · `:""}{p.source}</small></div></article>)}</div></section>
    <section className={styles.itinerary}><div className={styles.sectionHead}><div><h2>{say(lang,"Πρόγραμμα ταξιδιού","Trip itinerary")}</h2><p>{say(lang,"Χτισμένο γύρω από το selected stay, τον καιρό, τον ρυθμό σου και τα καλύτερα διαθέσιμα local signals.","Built around the selected stay, weather, your pace and the strongest available local signals.")}</p></div><div className={styles.pace}><button className={pace==="slow"?styles.tabOn:""} onClick={()=>setPace("slow")}>{say(lang,"Ήρεμο","Slow")}</button><button className={pace==="balanced"?styles.tabOn:""} onClick={()=>setPace("balanced")}>{say(lang,"Ισορροπημένο","Balanced")}</button><button className={pace==="full"?styles.tabOn:""} onClick={()=>setPace("full")}>{say(lang,"Γεμάτο","Full")}</button></div></div><div className={styles.days}>{itinerary.map(day=><article key={day.date}><h3>{dayLabel(day.date,lang)}</h3>{day.rows.map((r,i)=><div className={styles.slot} key={`${r.time}-${i}`}><time>{r.time}</time><span/><div><b>{r.title}</b><small>{r.note}</small></div></div>)}</article>)}</div></section>
   </section>
   <aside className={styles.booking}><div className={styles.saveBox}><h3>{say(lang,"Αποθήκευσε το ταξίδι σου","Save your trip")}</h3><p>{say(lang,"Στείλε το πλήρες Escape Book στο email σου. Μετά ξεκλειδώνει το μοναδικό outbound booking CTA.","Send the full Escape Book to your email. Then the single outbound booking CTA unlocks.")}</p><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder={say(lang,"Το email σου","Your email")}/><button onClick={sendEmail} disabled={emailBusy}>{emailBusy?say(lang,"Αποστολή…","Sending…"):say(lang,"Αποστολή στο email","Send to email")}</button>{guidePath?<a className={styles.pdf} href={guidePath} target="_blank" rel="noopener noreferrer">{say(lang,"Προεπισκόπηση PDF","Preview PDF")}</a>:null}{emailMessage?<small className={styles.message}>{emailMessage}</small>:null}{qr?<div className={styles.qr}><img src={qr} alt="QR"/><span>{say(lang,"QR του ακριβούς tracking URL","Exact tracking URL QR")}</span></div>:null}{unlocked?<a className={styles.book} href={offer.trackingUrl} target="_blank" rel="sponsored nofollow noopener noreferrer">{say(lang,"Συνέχισε στην προσφορά →","Continue to current offer →")}</a>:<div className={styles.locked}>🔒 {say(lang,"Το tracking CTA ξεκλειδώνει μετά το email","Tracking CTA unlocks after email")}</div>}<div className={styles.disclosure}><b>Disclosure</b><p>{say(lang,"Το affiliate CTA είναι ξεχωριστό από την πρόταση. Αν ολοκληρώσεις κράτηση, ενδέχεται να λάβουμε προμήθεια χωρίς επιπλέον κόστος. Τελική τιμή/δωμάτιο/διαθεσιμότητα επιβεβαιώνονται στον πάροχο.","The affiliate CTA is separate from the recommendation. If you book, we may earn a commission at no extra cost. Final price/room/availability are confirmed by the provider.")}</p></div></div></aside>
  </div>
  {busy?<div className={styles.loading}>{say(lang,"Χτίζω weather, reviews, local intelligence και itinerary…","Building weather, reviews, local intelligence and itinerary…")}</div>:null}{error?<div className={styles.error}>{error}</div>:null}
 </main>
}
