"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import type { EscapeSolutionResponseV36 } from "@/lib/decision/solution-ranking-v36";
import styles from "./v40-discovery-experience.module.css";

type Lang="el"|"en";
type Traveler="solo"|"couple"|"family"|"friends";
type Mood="relax"|"romantic"|"food"|"warmth"|"city"|"nature"|"adventure"|"culture";
type QuestionId="companions"|"outcome"|"social"|"novelty"|"must_have"|"friction";
type Phase="welcome"|"discover"|"dates"|"budget"|"origin"|"thinking"|"destinations";
type Answer={questionId:QuestionId;value:string};
type Media={imageUrl:string;sourceUrl:string;title:string;description?:string;license:string;attribution:string};
type Profile={travelerType:Traveler;moods:Mood[];pace:"slow"|"balanced"|"full";desiredEnergy:"restore"|"balanced"|"stimulating";socialPreference:"quiet"|"balanced"|"lively";noveltyPreference:"familiar"|"balanced"|"surprise";avoid:"long-travel"|"high-cost"|"crowds"|"none";mustHave:"sea"|"nature"|"culture"|"nightlife"|"none";dnaLabels:string[]};
type Discovery={summary:string;profile:Profile;answered:QuestionId[];nextQuestionId:QuestionId|null;confidence:number;complete:boolean};
type StreamRow={type:string;message?:string;result?:EscapeSolutionResponseV36};
type ChatRow={role:"agent"|"user";text:string};

type QuestionOption={value:string;el:string;en:string;icon:string};
const DAY=86_400_000;
const say=(l:Lang,el:string,en:string)=>l==="el"?el:en;
const iso=(d:Date)=>d.toISOString().slice(0,10);
function nextFriday(){const now=new Date(),d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())),delta=(5-d.getUTCDay()+7)%7||7;return new Date(d.getTime()+delta*DAY)}

const questions:Record<QuestionId,{titleEl:string;titleEn:string;subEl:string;subEn:string;options:QuestionOption[]}>= {
 companions:{titleEl:"Με ποιον θα ήθελες να το ζήσεις;",titleEn:"Who are you travelling with?",subEl:"Αυτό αλλάζει ρυθμό, περιοχή, διαμονή και πρόγραμμα.",subEn:"This changes pace, location, stay choice and itinerary.",options:[{value:"solo",el:"Μόνος/η",en:"Solo",icon:"◎"},{value:"couple",el:"Με σύντροφο",en:"Partner",icon:"♡"},{value:"family",el:"Με οικογένεια",en:"Family",icon:"✦"},{value:"friends",el:"Με φίλους",en:"Friends",icon:"◌"}]},
 outcome:{titleEl:"Πώς θέλεις να γυρίσεις από αυτό το ταξίδι;",titleEn:"How do you want to feel when you come back?",subEl:"Αυτό είναι πιο χρήσιμο από ένα generic “παραλία ή πόλη”.",subEn:"This is more useful than a generic beach-or-city filter.",options:[{value:"rest reset quiet",el:"Ξεκούραστος/η",en:"Rested",icon:"☁"},{value:"reconnect romantic",el:"Πιο κοντά",en:"Reconnected",icon:"♡"},{value:"stimulating adventure energy",el:"Με ενέργεια",en:"Energised",icon:"△"},{value:"culture inspiration",el:"Με νέες εικόνες",en:"Inspired",icon:"◇"}]},
 social:{titleEl:"Τι ατμόσφαιρα σε τραβάει;",titleEn:"Which atmosphere feels right?",subEl:"Θα επηρεάσει περιοχή, ώρες, φαγητό και βραδινή ζωή.",subEn:"This changes neighbourhood, timing, food and nightlife.",options:[{value:"quiet",el:"Ήσυχη",en:"Quiet",icon:"◌"},{value:"balanced",el:"Ισορροπημένη",en:"Balanced",icon:"◎"},{value:"lively nightlife",el:"Ζωντανή",en:"Lively",icon:"✦"}]},
 novelty:{titleEl:"Σίγουρη επιλογή ή να σε εκπλήξω;",titleEn:"Familiar choice or should I surprise you?",subEl:"Μπορώ να ξεφύγω από τα προφανή όταν υπάρχει καλός λόγος.",subEn:"I can move beyond obvious choices when there is a good reason.",options:[{value:"familiar",el:"Κάτι σίγουρο",en:"Familiar",icon:"○"},{value:"balanced",el:"Ισορροπία",en:"Balanced",icon:"◎"},{value:"surprise different",el:"Έκπληξέ με",en:"Surprise me",icon:"✦"}]},
 must_have:{titleEl:"Τι πρέπει οπωσδήποτε να υπάρχει;",titleEn:"What absolutely needs to be there?",subEl:"Ένα πραγματικό must-have αρκεί.",subEn:"One real must-have is enough.",options:[{value:"sea beach",el:"Θάλασσα",en:"Sea",icon:"≈"},{value:"nature mountain",el:"Φύση",en:"Nature",icon:"♧"},{value:"culture history",el:"Πολιτισμός",en:"Culture",icon:"◇"},{value:"nightlife",el:"Βραδινή ζωή",en:"Nightlife",icon:"✦"},{value:"none",el:"Δεν έχω",en:"No must-have",icon:"○"}]},
 friction:{titleEl:"Τι μπορεί να σου χαλάσει την απόδραση;",titleEn:"What could ruin the escape for you?",subEl:"Αυτό θα το χρησιμοποιήσω σαν πραγματικό constraint.",subEn:"I will treat this as a real constraint.",options:[{value:"short easy no long travel",el:"Πολλή ταλαιπωρία",en:"Long travel",icon:"→"},{value:"budget cheap",el:"Υψηλό κόστος",en:"High cost",icon:"€"},{value:"avoid crowds",el:"Πολυκοσμία",en:"Crowds",icon:"◎"},{value:"none",el:"Τίποτα συγκεκριμένο",en:"Nothing specific",icon:"○"}]}
};

export function V40DiscoveryExperience({lang="el"}:{lang?:Lang}){
 const friday=useMemo(()=>nextFriday(),[]);
 const[phase,setPhase]=useState<Phase>("welcome");
 const[need,setNeed]=useState("");const[answers,setAnswers]=useState<Answer[]>([]);const[profile,setProfile]=useState<Profile|null>(null);const[summary,setSummary]=useState("");const[nextQuestion,setNextQuestion]=useState<QuestionId|null>(null);const[answerText,setAnswerText]=useState("");const[traveler,setTraveler]=useState<Traveler|null>(null);
 const[start,setStart]=useState(iso(friday));const[end,setEnd]=useState(iso(new Date(friday.getTime()+3*DAY)));const[budget,setBudget]=useState(900);const[origin,setOrigin]=useState(say(lang,"Αθήνα","Athens"));
 const[result,setResult]=useState<EscapeSolutionResponseV36|null>(null);const[activeIndex,setActiveIndex]=useState(0);const[media,setMedia]=useState<Record<string,Media[]>>({});const[heroMedia,setHeroMedia]=useState<Media[]>([]);const[frame,setFrame]=useState(0);
 const[busy,setBusy]=useState(false);const[progress,setProgress]=useState("");const[error,setError]=useState<string|null>(null);const[chatOpen,setChatOpen]=useState(false);const[chatInput,setChatInput]=useState("");const[chat,setChat]=useState<ChatRow[]>([{role:"agent",text:say(lang,"Πες μου τι θέλεις να νιώσεις, όχι πού νομίζεις ότι πρέπει να πας.","Tell me how you want to feel, not where you think you should go.")}]);
 const solutions=result?.solutions.slice(0,3)??[];const active=solutions[activeIndex]??solutions[0]??null;const activeSlug=active?.recommendation.slug??"";const activeFrames=activeSlug?media[activeSlug]??[]:heroMedia;const background=activeFrames.length?activeFrames[frame%activeFrames.length].imageUrl:(heroMedia.length?heroMedia[frame%heroMedia.length].imageUrl:"/api/destination-photo?slug=athens");const q=nextQuestion?questions[nextQuestion]:null;

 useEffect(()=>{fetch("/api/escape/media?destination=Greece&mode=aerial").then(r=>r.ok?r.json():null).then((p:{items?:Media[]}|null)=>{if(p?.items?.length)setHeroMedia(p.items.slice(0,8))}).catch(()=>null)},[]);
 useEffect(()=>{if(!solutions.length)return;for(const s of solutions){const slug=s.recommendation.slug;if(media[slug])continue;const destination=s.recommendation.destinationEn||s.recommendation.destination;fetch(`/api/escape/media?destination=${encodeURIComponent(destination)}&mode=aerial`).then(r=>r.ok?r.json():null).then((p:{items?:Media[]}|null)=>{if(p?.items?.length)setMedia(v=>({...v,[slug]:p.items!.slice(0,8)}))}).catch(()=>null)}},[solutions.map(s=>s.recommendation.slug).join("|")]);
 useEffect(()=>{const timer=window.setInterval(()=>setFrame(v=>v+1),7000);return()=>window.clearInterval(timer)},[]);

 function initialText(extra=""){return[need.trim(),extra.trim()].filter(Boolean).join(". ").slice(0,900)||say(lang,"Θέλω μια απόδραση που να μου ταιριάζει πραγματικά.","I want an escape that genuinely fits me.")}
 async function runDiscovery(nextAnswers=answers,extra=""){
  setBusy(true);setError(null);
  try{const r=await fetch("/api/escape/discovery",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,initialText:initialText(extra),answers:nextAnswers})});if(!r.ok)throw new Error();const data=await r.json() as Discovery;setProfile(data.profile);setSummary(data.summary);setNextQuestion(data.nextQuestionId);const raw=nextAnswers.find(a=>a.questionId==="companions")?.value;if(raw==="solo"||raw==="couple"||raw==="family"||raw==="friends")setTraveler(raw);else setTraveler(data.profile.travelerType);return data}
  catch{setError(say(lang,"Δεν έχω αρκετό context ακόμη. Πες μου με μία φυσική πρόταση τι θέλεις να ζήσεις και τι θέλεις να αποφύγεις.","I need a little more context. Tell me naturally what you want to experience and what you want to avoid."));return null}finally{setBusy(false)}
 }
 async function begin(e?:FormEvent){e?.preventDefault();if(need.trim().length<4){setError(say(lang,"Γράψε μου μία κανονική πρόταση — σαν να μιλάς σε travel agent.","Give me one real sentence — as if you were speaking to a travel agent."));return}const data=await runDiscovery();if(!data)return;setChat(v=>[...v,{role:"user",text:need.trim()},{role:"agent",text:data.summary}]);setPhase(data.complete||!data.nextQuestionId?"dates":"discover")}
 async function answer(value:string){if(!nextQuestion)return;const updated=[...answers.filter(a=>a.questionId!==nextQuestion),{questionId:nextQuestion,value:value.slice(0,100)}];setAnswers(updated);setAnswerText("");const data=await runDiscovery(updated);if(!data)return;setChat(v=>[...v,{role:"user",text:value},{role:"agent",text:data.summary}]);setPhase(data.complete||!data.nextQuestionId?"dates":"discover")}
 async function submitCustomAnswer(e:FormEvent){e.preventDefault();const value=answerText.trim();if(value)await answer(value)}
 function flexibleWeekend(){const fri=nextFriday();setStart(iso(fri));setEnd(iso(new Date(fri.getTime()+3*DAY)))}
 async function solve(profileOverride?:Profile){const learned=profileOverride??profile??(await runDiscovery())?.profile;if(!learned)return;const resolvedTraveler=traveler??learned.travelerType;const nights=Math.max(1,Math.round((Date.parse(`${end}T00:00:00Z`)-Date.parse(`${start}T00:00:00Z`))/DAY));const trip={origin,startDate:start,endDate:end,month:"flexible",nights,budget,moods:learned.moods,travelerType:resolvedTraveler,language:lang,distancePreference:"any",pace:learned.pace,hotelStyle:"any",avoid:learned.avoid,entryMode:"idea",groupSize:resolvedTraveler==="solo"?1:resolvedTraveler==="couple"?2:4,desiredEnergy:learned.desiredEnergy,socialPreference:learned.socialPreference,noveltyPreference:learned.noveltyPreference,mustHave:learned.mustHave,dateFlexibility:"few-days",transportMode:"any",stayLocationPreference:"balanced",tripText:[need,summary].filter(Boolean).join(". ").slice(0,900)};setPhase("thinking");setBusy(true);setError(null);setProgress(say(lang,"Συνδέω το travel DNA σου με προορισμούς και πραγματικό stay inventory…","Matching your travel DNA with destinations and real stay inventory…"));try{const r=await fetch("/api/escape/solve-v36/stream",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(trip)});if(!r.ok||!r.body)throw new Error();const reader=r.body.getReader(),decoder=new TextDecoder();let buffer="",final:EscapeSolutionResponseV36|null=null;for(;;){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()??"";for(const line of lines){if(!line.trim())continue;const row=JSON.parse(line) as StreamRow;if(row.message)setProgress(row.message);if(row.type==="final"&&row.result)final=row.result}}if(!final?.solutions.length)throw new Error();setResult(final);setActiveIndex(0);setFrame(0);setPhase("destinations");setChat(v=>[...v,{role:"agent",text:say(lang,"Έχω τρεις διαφορετικές εκδοχές της απόδρασής σου. Διάλεξε πρώτα την εμπειρία· μετά θα ανοίξω stays και local intelligence.","I have three different versions of your escape. Choose the experience first; then I will open stays and local intelligence.")}])}catch{setPhase("budget");setError(say(lang,"Δεν βρήκα αρκετά ισχυρή αντιστοίχιση. Άλλαξε λίγο budget ή ημερομηνίες.","I could not find a strong enough match. Adjust budget or dates slightly."))}finally{setBusy(false);setProgress("")}}
 async function sendChat(e:FormEvent){e.preventDefault();const text=chatInput.trim();if(!text||busy)return;setChat(v=>[...v,{role:"user",text}]);setChatInput("");setNeed(v=>[v,text].filter(Boolean).join(". ").slice(0,900));const data=await runDiscovery(answers,text);if(!data)return;setChat(v=>[...v,{role:"agent",text:data.summary}]);if(phase==="destinations")await solve(data.profile)}
 function destinationQs(){const resolvedTraveler=traveler??profile?.travelerType??"couple";const mood=profile?.moods[0]??"relax";return new URLSearchParams({start,end,budget:String(budget),origin,travelerType:resolvedTraveler,mood,lang}).toString()}
 const progressStep=phase==="welcome"||phase==="discover"?1:phase==="dates"||phase==="budget"||phase==="origin"||phase==="thinking"?2:3;

 return <main className={styles.shell} style={{"--hero":`url(${background})`} as React.CSSProperties}>
  <div className={styles.backdrop}/><div className={styles.vignette}/><div className={styles.grain}/>
  <header className={styles.nav}><a className={styles.brand} href={lang==="en"?"/en":"/"}><span>✦</span><div><b>Holiday Escape</b><small>AI travel studio</small></div></a><div className={styles.navRight}><div className={styles.progress}><i className={progressStep>=1?styles.on:""}/><i className={progressStep>=2?styles.on:""}/><i className={progressStep>=3?styles.on:""}/></div><button type="button" onClick={()=>setChatOpen(true)}>✦ {say(lang,"Travel Agent","Travel Agent")}</button></div></header>
  <section className={styles.stage}>
   {phase==="welcome"&&<div className={styles.heroPanel}><p className={styles.eyebrow}>{say(lang,"AI-led travel discovery","AI-led travel discovery")}</p><h1>{say(lang,"Μην μου πεις πού θέλεις να πας. Πες μου τι θέλεις να ζήσεις.","Do not tell me where to go. Tell me what you want to experience.")}</h1><p className={styles.lead}>{say(lang,"Θα σε ρωτήσω μόνο ό,τι αλλάζει πραγματικά την πρόταση. Μετά θα βρω τον τόπο, τη διαμονή και το itinerary.","I will ask only what materially changes the recommendation. Then I will find the place, the stay and the itinerary.")}</p><form className={styles.agentComposer} onSubmit={begin}><span>✦</span><textarea autoFocus value={need} onChange={e=>setNeed(e.target.value)} placeholder={say(lang,"π.χ. Είμαστε κουρασμένοι, θέλουμε 3-4 μέρες με καλό φαγητό, όμορφο τοπίο, χωρίς πολυκοσμία και χωρίς πολλή ταλαιπωρία…","e.g. We are exhausted and want 3-4 days with great food, beautiful scenery, no crowds and very little friction…")}/><button disabled={busy||need.trim().length<4}>{busy?"…":say(lang,"Μίλα με τον agent","Talk to the agent")} →</button></form>{error&&<p className={styles.error}>{error}</p>}<div className={styles.microTrust}><span>Adaptive questions</span><span>Real inventory later</span><span>No external links</span></div></div>}
   {phase==="discover"&&q&&<div className={styles.questionPanel}><div className={styles.agentCue}><span>✦</span><div><small>{say(lang,"Ο agent κατάλαβε","Agent understanding")}</small><p>{summary}</p></div></div><p className={styles.eyebrow}>{say(lang,"Μία ερώτηση ακόμη","One more question")}</p><h1>{lang==="el"?q.titleEl:q.titleEn}</h1><p className={styles.lead}>{lang==="el"?q.subEl:q.subEn}</p><div className={styles.answerGrid}>{q.options.map(o=><button key={o.value} onClick={()=>answer(o.value)} disabled={busy}><span>{o.icon}</span><b>{lang==="el"?o.el:o.en}</b></button>)}</div><form className={styles.customAnswer} onSubmit={submitCustomAnswer}><input value={answerText} onChange={e=>setAnswerText(e.target.value)} placeholder={say(lang,"Ή απάντησε με δικά σου λόγια…","Or answer in your own words…")}/><button disabled={!answerText.trim()||busy}>→</button></form>{error&&<p className={styles.error}>{error}</p>}</div>}
   {phase==="dates"&&<div className={styles.realityPanel}><p className={styles.eyebrow}>{say(lang,"Πρακτικό constraint 1/3","Practical constraint 1/3")}</p><h1>{say(lang,"Πότε μπορείς να φύγεις;","When can you actually get away?")}</h1><p className={styles.lead}>{say(lang,"Το travel DNA σου έχει κλειδώσει. Τώρα ζητάω μόνο ό,τι επηρεάζει διαθεσιμότητα και εμπειρία.","Your travel DNA is locked. Now I only need what affects availability and experience.")}</p><div className={styles.dateCard}><label><span>{say(lang,"Αναχώρηση","Departure")}</span><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><b>→</b><label><span>{say(lang,"Επιστροφή","Return")}</span><input type="date" value={end} min={start} onChange={e=>setEnd(e.target.value)}/></label></div><div className={styles.inlineActions}><button className={styles.ghost} onClick={flexibleWeekend}>{say(lang,"Επόμενο 3ήμερο","Next 3-night window")}</button><button className={styles.primary} onClick={()=>setPhase("budget")}>{say(lang,"Συνέχεια","Continue")} →</button></div></div>}
   {phase==="budget"&&<div className={styles.realityPanel}><p className={styles.eyebrow}>{say(lang,"Πρακτικό constraint 2/3","Practical constraint 2/3")}</p><h1>{say(lang,"Ποιο συνολικό budget νιώθεις σωστό;","What total budget feels right?")}</h1><div className={styles.budgetHero}><span>€</span><strong>{budget}</strong></div><input className={styles.range} type="range" min="250" max="3000" step="50" value={budget} onChange={e=>setBudget(Number(e.target.value))}/><div className={styles.inlineActions}><button className={styles.ghost} onClick={()=>setBudget(600)}>€600</button><button className={styles.ghost} onClick={()=>setBudget(1000)}>€1000</button><button className={styles.ghost} onClick={()=>setBudget(1500)}>€1500</button><button className={styles.primary} onClick={()=>setPhase("origin")}>{say(lang,"Συνέχεια","Continue")} →</button></div></div>}
   {phase==="origin"&&<div className={styles.realityPanel}><p className={styles.eyebrow}>{say(lang,"Πρακτικό constraint 3/3","Practical constraint 3/3")}</p><h1>{say(lang,"Από πού ξεκινάς;","Where are you starting from?")}</h1><p className={styles.lead}>{say(lang,"Μόνο πόλη ή αεροδρόμιο — για να σταθμίσω σωστά χρόνο και ταλαιπωρία.","Just a city or airport — so I can weigh time and travel friction correctly.")}</p><div className={styles.originBox}><span>⌖</span><input value={origin} onChange={e=>setOrigin(e.target.value)}/></div><button className={styles.primary} onClick={()=>solve()} disabled={!origin.trim()||busy}>{say(lang,"Βρες την απόδρασή μου","Find my escape")} →</button>{error&&<p className={styles.error}>{error}</p>}</div>}
   {phase==="thinking"&&<div className={styles.thinking}><div className={styles.orbit}><span>✦</span><i/><i/><i/></div><p className={styles.eyebrow}>AI Travel Council</p><h1>{say(lang,"Δεν ψάχνω το πιο δημοφιλές. Ψάχνω το σωστό για εσένα.","I am not looking for the most popular. I am looking for the right fit for you.")}</h1><p>{progress}</p></div>}
   {phase==="destinations"&&<div className={styles.results}><div className={styles.resultsTop}><div><p className={styles.eyebrow}>{say(lang,"Destination reveal","Destination reveal")}</p><h1>{say(lang,"Τρεις διαφορετικές εκδοχές της απόδρασής σου.","Three different versions of your escape.")}</h1><p>{summary}</p></div><button className={styles.ghost} onClick={()=>{setResult(null);setPhase("welcome")}}>{say(lang,"Αλλαγή brief","Change brief")}</button></div><div className={styles.destinationDeck}>{solutions.map((s,index)=>{const slug=s.recommendation.slug,items=media[slug]??[],image=items.length?items[(frame+index)%items.length].imageUrl:"/api/destination-photo?slug="+encodeURIComponent(slug),name=lang==="en"?s.recommendation.destinationEn:s.recommendation.destination;return <article key={slug} className={index===activeIndex?styles.destinationActive:""} onMouseEnter={()=>setActiveIndex(index)} onClick={()=>setActiveIndex(index)}><img src={image} alt={name}/><div className={styles.cardShade}/><div className={styles.cardTop}><span>0{index+1}</span><b>{Math.round(s.combinedScore)}% FIT</b></div><div className={styles.cardCopy}><small>{s.recommendation.explorationRole?.replaceAll("_"," ")||"AI MATCH"}</small><h2>{name}</h2><p>{s.reasoning.destination}</p><div className={styles.cardFacts}><span>◎ {s.recommendation.effortLabel}</span><span>◇ {s.recommendation.seasonNote}</span></div><a href={`/escape/${slug}?${destinationQs()}`}>{say(lang,"Άνοιξε την εμπειρία","Open this experience")} →</a></div></article>})}</div><div className={styles.resultFooter}><span>{say(lang,"Πρώτα επιλέγεις τόπο. Μετά ανοίγουν stays, local intelligence και itinerary.","Choose the place first. Then stays, local intelligence and itinerary open.")}</span></div></div>}
  </section>
  <button className={styles.chatFab} type="button" onClick={()=>setChatOpen(v=>!v)}><span>✦</span><div><b>Travel Agent</b><small>{say(lang,"Ξέρει όλο το brief σου","Knows your whole brief")}</small></div></button>
  {chatOpen&&<aside className={styles.chatPanel}><div className={styles.chatHead}><div><span>✦</span><p><b>Holiday Agent</b><small>● {say(lang,"γνωρίζει το ταξίδι σου","knows your trip")}</small></p></div><button onClick={()=>setChatOpen(false)}>×</button></div><div className={styles.chatBody}>{chat.map((row,index)=><div key={`${row.role}-${index}`} className={row.role==="agent"?styles.agentBubble:styles.userBubble}>{row.text}</div>)}</div><form onSubmit={sendChat}><input value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder={say(lang,"π.χ. Δεν θέλω καθόλου τουριστικό μέρος…","e.g. I do not want anywhere touristy…")}/><button disabled={busy||!chatInput.trim()}>↑</button></form></aside>}
 </main>
}
