"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import type { EscapeSolutionResponseV36,EscapeSolutionV36 } from "@/lib/decision/solution-ranking-v36";
import styles from "./v40-discovery-experience.module.css";

type Lang="el"|"en";
type Traveler="solo"|"couple"|"family"|"friends";
type Mood="relax"|"romantic"|"food"|"warmth"|"city"|"nature"|"adventure"|"culture";
type Media={imageUrl:string;sourceUrl:string;title:string;description?:string;license:string;attribution:string};
type ChatRow={role:"agent"|"user";text:string};
type Profile={travelerType:Traveler;moods:Mood[];pace:"slow"|"balanced"|"full";desiredEnergy:"restore"|"balanced"|"stimulating";socialPreference:"quiet"|"balanced"|"lively";noveltyPreference:"familiar"|"balanced"|"surprise";avoid:"long-travel"|"high-cost"|"crowds"|"none";mustHave:"sea"|"nature"|"culture"|"nightlife"|"none";dnaLabels:string[]};
type Discovery={summary:string;profile:Profile;confidence:number};
type StreamRow={type:string;progress?:number;message?:string;result?:EscapeSolutionResponseV36};

const say=(l:Lang,el:string,en:string)=>l==="el"?el:en;
const DAY=86_400_000;
const iso=(d:Date)=>d.toISOString().slice(0,10);
function nextFriday(){const now=new Date(),d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())),delta=(5-d.getUTCDay()+7)%7||7;return new Date(d.getTime()+delta*DAY)}
const travelerLabels:Record<Traveler,[string,string]>={solo:["Μόνος/η","Solo"],couple:["Με σύντροφο","Couple"],family:["Με οικογένεια","Family"],friends:["Με φίλους","Friends"]};
const moods:{id:Mood;el:string;en:string;emoji:string}[]=[
 {id:"relax",el:"Χαλάρωση",en:"Relax",emoji:"☁"},{id:"romantic",el:"Ρομαντισμός",en:"Romance",emoji:"♡"},{id:"nature",el:"Φύση",en:"Nature",emoji:"♧"},{id:"food",el:"Καλό φαγητό",en:"Food",emoji:"◌"},{id:"adventure",el:"Περιπέτεια",en:"Adventure",emoji:"△"},{id:"culture",el:"Πολιτισμός",en:"Culture",emoji:"◇"}
];
const escape=(v:string)=>encodeURIComponent(v);
function price(solution:EscapeSolutionV36,lang:Lang){const p=solution.stay.price;return p!=null&&p>0?`${p.toLocaleString(lang==="el"?"el-GR":"en-GB",{maximumFractionDigits:2})} ${solution.stay.currency||"EUR"}`:say(lang,"Τιμή στον πάροχο","Price at provider")}

export function V40DiscoveryExperience({lang="el"}:{lang?:Lang}){
 const fri=useMemo(()=>nextFriday(),[]),[need,setNeed]=useState(""),[traveler,setTraveler]=useState<Traveler>("couple"),[selectedMoods,setSelectedMoods]=useState<Mood[]>(["relax"]),[start,setStart]=useState(iso(fri)),[end,setEnd]=useState(iso(new Date(fri.getTime()+3*DAY))),[budget,setBudget]=useState(900),[origin,setOrigin]=useState(say(lang,"Αθήνα","Athens")),[profile,setProfile]=useState<Profile|null>(null),[summary,setSummary]=useState(""),[result,setResult]=useState<EscapeSolutionResponseV36|null>(null),[selected,setSelected]=useState(0),[busy,setBusy]=useState(false),[progress,setProgress]=useState(""),[error,setError]=useState<string|null>(null),[media,setMedia]=useState<Record<string,Media[]>>({}),[chatInput,setChatInput]=useState(""),[chat,setChat]=useState<ChatRow[]>([
  {role:"agent",text:say(lang,"Γεια σου 👋 Είμαι ο Travel Agent. Πριν σου προτείνω οτιδήποτε, θέλω να καταλάβω τι χρειάζεσαι από αυτή την απόδραση.","Hi 👋 I’m your Travel Agent. Before recommending anything, I want to understand what you need from this escape.")},
  {role:"agent",text:say(lang,"Τι θέλεις να νιώσεις όταν επιστρέψεις;","How do you want to feel when you return?")}
 ]);
 const solutions=result?.solutions.slice(0,3)??[],active=solutions[selected]??solutions[0]??null;
 const stage=result?3:profile?2:1;

 useEffect(()=>{if(!solutions.length)return;for(const solution of solutions){const slug=solution.recommendation.slug;if(media[slug])continue;const q=solution.recommendation.destinationEn||solution.recommendation.destination;fetch(`/api/escape/media?destination=${escape(q)}&mode=aerial`).then(r=>r.ok?r.json():null).then((p:{items?:Media[]}|null)=>{if(p?.items?.length)setMedia(prev=>({...prev,[slug]:p.items!.slice(0,6)}))}).catch(()=>null)}},[solutions.map(s=>s.recommendation.slug).join("|")]);

 function toggleMood(m:Mood){setSelectedMoods(cur=>cur.includes(m)?(cur.length>1?cur.filter(x=>x!==m):cur):[...cur,m].slice(-3))}
 async function learn(extra?:string){const text=[need.trim(),extra?.trim()].filter(Boolean).join(". ")||say(lang,"Θέλω μια απόδραση που να μου ταιριάζει πραγματικά","I want an escape that truly fits me");setBusy(true);setError(null);try{const res=await fetch("/api/escape/discovery",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,initialText:text,answers:[{questionId:"companions",value:traveler},{questionId:"moods",value:selectedMoods}]})});if(!res.ok)throw new Error();const d=await res.json() as Discovery;const p={...d.profile,travelerType:traveler,moods:selectedMoods.length?selectedMoods:d.profile.moods};setProfile(p);setSummary(d.summary);setChat(cur=>[...cur,{role:"agent",text:say(lang,`Σε κατάλαβα: ${d.summary}. Τώρα θα ψάξω με βάση πραγματικό inventory, όχι γενικές ιδέες.`,`I understand: ${d.summary}. I’ll now search against real inventory, not generic ideas.`)}])}catch{setError(say(lang,"Δεν μπόρεσα να διαβάσω σωστά το request. Δώσε μου λίγο πιο συγκεκριμένα τι θες να ζήσεις.","I couldn’t understand that clearly. Tell me a little more about the experience you want."))}finally{setBusy(false)}}
 async function submitChat(e:FormEvent){e.preventDefault();const q=chatInput.trim();if(!q)return;setChat(cur=>[...cur,{role:"user",text:q}]);setChatInput("");setNeed(cur=>[cur,q].filter(Boolean).join(". ").slice(0,500));await learn(q)}
 async function solve(){let p=profile;if(!p){await learn();return}if(Date.parse(end)<=Date.parse(start)){setError(say(lang,"Η ημερομηνία επιστροφής πρέπει να είναι μετά την αναχώρηση.","Return date must be after departure."));return}setBusy(true);setError(null);setProgress(say(lang,"Ο Travel Agent συγκρίνει ανάγκη, προορισμούς και πραγματικό stay inventory…","The Travel Agent is comparing your needs, destinations and real stay inventory…"));const nights=Math.max(1,Math.round((Date.parse(`${end}T00:00:00Z`)-Date.parse(`${start}T00:00:00Z`))/DAY));const trip={origin,startDate:start,endDate:end,month:"flexible",nights,budget,moods:p.moods,travelerType:traveler,language:lang,distancePreference:"any",pace:p.pace,hotelStyle:"any",avoid:p.avoid,entryMode:"idea",groupSize:traveler==="solo"?1:traveler==="couple"?2:4,desiredEnergy:p.desiredEnergy,socialPreference:p.socialPreference,noveltyPreference:p.noveltyPreference,mustHave:p.mustHave,dateFlexibility:"few-days",transportMode:"any",stayLocationPreference:"balanced",tripText:[need,summary].filter(Boolean).join(". ")};try{const res=await fetch("/api/escape/solve-v36/stream",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(trip)});if(!res.ok||!res.body)throw new Error();const reader=res.body.getReader(),decoder=new TextDecoder();let buffer="",final:EscapeSolutionResponseV36|null=null;for(;;){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()??"";for(const line of lines){if(!line.trim())continue;const row=JSON.parse(line) as StreamRow;if(row.message)setProgress(row.message);if(row.type==="final"&&row.result)final=row.result}}if(!final?.solutions.length)throw new Error();setResult(final);setSelected(0);setChat(cur=>[...cur,{role:"agent",text:say(lang,`Βρήκα ${Math.min(3,final!.solutions.length)} ξεκάθαρα διαφορετικές επιλογές. Δεν χρειάζεται να διαλέξεις ξενοδοχείο ακόμη — πρώτα διάλεξε ποιο μέρος σε τραβά περισσότερο.`,`I found ${Math.min(3,final!.solutions.length)} clearly different options. You don’t need to choose a hotel yet — first choose which place feels right.`)}])}catch{setError(say(lang,"Ο travel engine δεν ολοκλήρωσε σωστά την αναζήτηση. Δεν θα σου δείξω ψεύτικες επιλογές.","The travel engine did not complete correctly. I won’t show fabricated options."))}finally{setBusy(false);setProgress("")}}
 const qs=(solution:EscapeSolutionV36)=>new URLSearchParams({start,end,budget:String(budget),origin,travelerType:traveler,mood:selectedMoods[0]||"relax",lang,offer:solution.stay.sourceProductId}).toString();

 return <main className={styles.shell}>
  <header className={styles.topbar}><a className={styles.brand} href={lang==="en"?"/en":"/"}><span>AI</span><b>Holiday Escape</b><small>{say(lang,"Εμπειρίες που σε καταλαβαίνουν","Experiences that understand you")}</small></a><nav><a className={styles.navActive}>{say(lang,"Ανακάλυψη","Discover")}</a><a>{say(lang,"Αποδράσεις","Escapes")}</a><a>{say(lang,"Πώς δουλεύει","How it works")}</a><a>{say(lang,"Οι κρατήσεις μου","My trips")}</a></nav><a className={styles.startBtn} href="#studio">{say(lang,"Ξεκίνα","Start")} →</a></header>
  <div className={styles.progress}><span className={stage>=1?styles.on:""}>1<small>Mood & {say(lang,"Ανάγκη","Need")}</small></span><i/><span className={stage>=2?styles.on:""}>2<small>{say(lang,"Ημερομηνίες","Dates")}</small></span><i/><span className={stage>=3?styles.on:""}>3<small>{say(lang,"Προορισμοί","Destinations")}</small></span><i/><span>4<small>{say(lang,"Κατάλυμα","Stay")}</small></span><i/><span>5<small>Itinerary</small></span></div>
  <section className={styles.layout} id="studio">
   <aside className={styles.agent}><div className={styles.agentHead}><div className={styles.bot}>✦</div><div><b>Travel Agent</b><small>● Online · {say(lang,"ο προσωπικός σου σύμβουλος","your personal travel advisor")}</small></div></div><div className={styles.chat}>{chat.slice(-6).map((m,i)=><div key={i} className={m.role==="agent"?styles.agentBubble:styles.userBubble}>{m.text}</div>)}</div><div className={styles.quick}><button onClick={()=>toggleMood("relax")}>☁ {say(lang,"Χαλάρωση","Relax")}</button><button onClick={()=>toggleMood("romantic")}>♡ {say(lang,"Ρομαντισμός","Romance")}</button><button onClick={()=>toggleMood("nature")}>♧ {say(lang,"Φύση","Nature")}</button><button onClick={()=>toggleMood("adventure")}>△ {say(lang,"Περιπέτεια","Adventure")}</button></div><form className={styles.chatForm} onSubmit={submitChat}><input value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder={say(lang,"Γράψε τι έχεις στο μυαλό σου…","Tell me what you have in mind…")}/><button>➜</button></form><p className={styles.agentNote}>{say(lang,"Τα καλύτερα ταξίδια ξεκινούν με μια καλή κουβέντα.","The best trips start with a good conversation.")}</p></aside>
   <section className={styles.main}>
    <div className={styles.hero}><div><small>{say(lang,"Η επόμενη απόδρασή σου ξεκινά εδώ","YOUR NEXT ESCAPE STARTS HERE")}</small><h1>{say(lang,"Ας σε γνωρίσουμε καλύτερα.","Let’s get to know you better.")}</h1><p>{summary||say(lang,"Πες μου λίγα πράγματα και ο agent θα ψάξει πρώτα τι σου ταιριάζει — μετά θα σου δείξει προορισμούς και μόνο έπειτα καταλύματα.","Tell me a little about yourself. The agent will first understand the fit, then destinations, and only then stays.")}</p></div><div className={styles.heroMark}>✦</div></div>
    <div className={styles.filters}>
     <div><label>{say(lang,"Διάθεση","Mood")}</label><div className={styles.chips}>{moods.map(m=><button key={m.id} onClick={()=>toggleMood(m.id)} className={selectedMoods.includes(m.id)?styles.chipOn:""}>{m.emoji} {lang==="el"?m.el:m.en}</button>)}</div></div>
     <div><label>{say(lang,"Με ποιον ταξιδεύεις;","Who with?")}</label><div className={styles.chips}>{(Object.keys(travelerLabels) as Traveler[]).map(t=><button key={t} onClick={()=>setTraveler(t)} className={traveler===t?styles.chipOn:""}>{travelerLabels[t][lang==="el"?0:1]}</button>)}</div></div>
     <div><label>{say(lang,"Ημερομηνίες","Dates")}</label><div className={styles.dates}><input type="date" value={start} onChange={e=>setStart(e.target.value)}/><span>→</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div></div>
     <div><label>Budget</label><div className={styles.money}><span>€</span><input type="number" min={150} max={5000} step={50} value={budget} onChange={e=>setBudget(Number(e.target.value)||900)}/></div></div>
     <div><label>{say(lang,"Από πού ξεκινάς;","Starting from")}</label><input className={styles.textInput} value={origin} onChange={e=>setOrigin(e.target.value)}/></div>
     <div><label>{say(lang,"Τι θέλεις να αποφύγεις / να ζήσεις;","Anything else?")}</label><input className={styles.textInput} value={need} onChange={e=>setNeed(e.target.value)} placeholder={say(lang,"π.χ. λίγη οδήγηση, ησυχία, καλό φαγητό…","e.g. little driving, quiet, great food…")}/></div>
    </div>
    <div className={styles.actionRow}><button onClick={()=>profile?solve():learn()} disabled={busy}>{busy?say(lang,"Ο agent δουλεύει…","Agent is working…"):profile?say(lang,"Βρες τις 3 καλύτερες αποδράσεις →","Find my 3 best escapes →"):say(lang,"Κατάλαβέ με πρώτα →","Understand me first →")}</button>{progress?<span>{progress}</span>:null}{error?<em>{error}</em>:null}</div>
    {solutions.length?<section className={styles.results}><div className={styles.sectionTitle}><span>✦</span><div><h2>{say(lang,"3 προορισμοί που ταιριάζουν σε εσένα","3 destinations that fit you")}</h2><p>{say(lang,"Διάλεξε πρώτα τόπο. Το κατάλυμα θα το αποφασίσουμε μετά στον χάρτη, με reviews και τοποθεσία.","Choose the place first. We’ll decide the stay next on the map, with reviews and location context.")}</p></div></div><div className={styles.destinationGrid}>{solutions.map((s,i)=>{const pics=media[s.recommendation.slug]??[],img=pics[0]?.imageUrl||s.stay.imageUrl||"";return <article key={s.recommendation.slug} onMouseEnter={()=>setSelected(i)} className={i===selected?styles.destinationActive:""}><div className={styles.destImage}>{img?<img src={img} alt={s.recommendation.destination}/>:null}<span>{i===0?say(lang,"★ Ιδανική επιλογή","★ Best fit"):i===1?say(lang,"Weekend pick","Weekend pick"):say(lang,"Εναλλακτική","Alternative")}</span><strong>{s.recommendation.destination}</strong></div><div className={styles.destBody}><p>{s.reasoning.destination}</p><div className={styles.miniStay}>{s.stay.imageUrl?<img src={s.stay.imageUrl} alt=""/>:null}<div><b>{s.stay.propertyName}</b><small>{s.stay.city||s.stay.address||s.recommendation.destination}</small></div><strong>{price(s,lang)}</strong></div><a href={`/escape/${escape(s.recommendation.slug)}?${qs(s)}`}>{say(lang,"Δες την περιοχή & όλα τα stays →","See area & all stays →")}</a></div></article>})}</div></section>:null}
   </section>
   <aside className={styles.visual}><div className={styles.visualSearch}>⌕ {say(lang,"Ο χάρτης της απόδρασής σου","Your escape map")}</div>{active?<><div className={styles.visualImage}>{(media[active.recommendation.slug]?.[1]?.imageUrl||media[active.recommendation.slug]?.[0]?.imageUrl||active.stay.imageUrl)?<img src={media[active.recommendation.slug]?.[1]?.imageUrl||media[active.recommendation.slug]?.[0]?.imageUrl||active.stay.imageUrl||""} alt=""/>:null}<div className={styles.pin}>●<span>{active.recommendation.destination}</span></div></div><div className={styles.visualCard}>{active.stay.imageUrl?<img src={active.stay.imageUrl} alt=""/>:null}<div><b>{active.stay.propertyName}</b><small>{active.stay.city||active.recommendation.destination}</small><p>{Math.round(active.combinedScore)}% AI Fit</p></div><a href={`/escape/${escape(active.recommendation.slug)}?${qs(active)}`}>→</a></div></>:<div className={styles.visualEmpty}><span>⌖</span><b>{say(lang,"Οι προτάσεις θα εμφανιστούν εδώ","Your recommendations will appear here")}</b><small>{say(lang,"Πρώτα μιλάς με τον agent. Μετά βλέπεις τόπους και stays.","First talk to the agent. Then see places and stays.")}</small></div>}</aside>
  </section>
 </main>
}
