"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import type { EscapeSolutionResponseV36 } from "@/lib/decision/solution-ranking-v36";
import styles from "./v40-discovery-experience.module.css";

type Lang="el"|"en";
type Traveler="solo"|"couple"|"family"|"friends";
type Mood="relax"|"romantic"|"food"|"warmth"|"city"|"nature"|"adventure"|"culture";
type Media={imageUrl:string;sourceUrl:string;title:string;description?:string;license:string;attribution:string};
type Profile={travelerType:Traveler;moods:Mood[];pace:"slow"|"balanced"|"full";desiredEnergy:"restore"|"balanced"|"stimulating";socialPreference:"quiet"|"balanced"|"lively";noveltyPreference:"familiar"|"balanced"|"surprise";avoid:"long-travel"|"high-cost"|"crowds"|"none";mustHave:"sea"|"nature"|"culture"|"nightlife"|"none";dnaLabels:string[]};
type Discovery={summary:string;profile:Profile;confidence:number};
type StreamRow={type:string;message?:string;result?:EscapeSolutionResponseV36};
type ChatRow={role:"agent"|"user";text:string};
type Step="intent"|"company"|"dates"|"budget"|"discovering"|"destinations";

const DAY=86_400_000;
const say=(l:Lang,el:string,en:string)=>l==="el"?el:en;
const iso=(d:Date)=>d.toISOString().slice(0,10);
function nextFriday(){const now=new Date(),d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())),delta=(5-d.getUTCDay()+7)%7||7;return new Date(d.getTime()+delta*DAY)}
const travelerOptions:{id:Traveler;icon:string;el:string;en:string;subEl:string;subEn:string}[]=[
 {id:"couple",icon:"♡",el:"Με σύντροφο",en:"With my partner",subEl:"Ρομαντισμός, ποιότητα, χρόνος μαζί",subEn:"Romance, quality time, shared moments"},
 {id:"family",icon:"✦",el:"Με οικογένεια",en:"With family",subEl:"Άνεση, εύκολες μετακινήσεις, εμπειρίες",subEn:"Comfort, easy logistics, shared experiences"},
 {id:"friends",icon:"◎",el:"Με φίλους",en:"With friends",subEl:"Ενέργεια, φαγητό, βραδινή ζωή",subEn:"Energy, food, nightlife"},
 {id:"solo",icon:"△",el:"Μόνος/η",en:"Solo",subEl:"Ελευθερία, ανακάλυψη, ο δικός σου ρυθμός",subEn:"Freedom, discovery, your own pace"}
];
const moodOptions:{id:Mood;emoji:string;el:string;en:string}[]=[
 {id:"relax",emoji:"☁",el:"Να ξεκουραστώ",en:"Feel restored"},{id:"romantic",emoji:"♡",el:"Να ξανασυνδεθώ",en:"Reconnect"},{id:"food",emoji:"◌",el:"Να φάω εξαιρετικά",en:"Eat exceptionally"},{id:"nature",emoji:"♧",el:"Να μπω στη φύση",en:"Get into nature"},{id:"adventure",emoji:"△",el:"Να ζήσω κάτι νέο",en:"Try something new"},{id:"culture",emoji:"◇",el:"Να γεμίσω εικόνες",en:"Feel inspired"}
];
const fallbackHero="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2200&q=86";

export function V40DiscoveryExperience({lang="el"}:{lang?:Lang}){
 const fri=useMemo(()=>nextFriday(),[]);
 const[start,setStart]=useState(iso(fri)),[end,setEnd]=useState(iso(new Date(fri.getTime()+3*DAY))),[budget,setBudget]=useState(900),[origin,setOrigin]=useState(say(lang,"Αθήνα","Athens"));
 const[traveler,setTraveler]=useState<Traveler>("couple"),[selectedMoods,setSelectedMoods]=useState<Mood[]>([]),[need,setNeed]=useState("");
 const[profile,setProfile]=useState<Profile|null>(null),[summary,setSummary]=useState(""),[result,setResult]=useState<EscapeSolutionResponseV36|null>(null),[selected,setSelected]=useState(0),[step,setStep]=useState<Step>("intent");
 const[busy,setBusy]=useState(false),[progress,setProgress]=useState(""),[error,setError]=useState<string|null>(null),[media,setMedia]=useState<Record<string,Media[]>>({}),[chatOpen,setChatOpen]=useState(false),[chatInput,setChatInput]=useState(""),[chat,setChat]=useState<ChatRow[]>([{role:"agent",text:say(lang,"Πες μου τι έχεις ανάγκη από αυτό το ταξίδι. Δεν χρειάζεται να ξέρεις προορισμό — αυτό είναι δική μου δουλειά.","Tell me what you need from this trip. You do not need to know the destination — that is my job.")}]);
 const solutions=result?.solutions.slice(0,4)??[],active=solutions[selected]??solutions[0]??null;
 const activeMedia=active?media[active.recommendation.slug]?.[0]?.imageUrl:null;
 const background=activeMedia||media[solutions[0]?.recommendation.slug||""]?.[0]?.imageUrl||fallbackHero;

 useEffect(()=>{for(const solution of solutions){const slug=solution.recommendation.slug;if(media[slug])continue;const q=solution.recommendation.destinationEn||solution.recommendation.destination;fetch(`/api/escape/media?destination=${encodeURIComponent(q)}&mode=aerial`).then(r=>r.ok?r.json():null).then((p:{items?:Media[]}|null)=>{if(p?.items?.length)setMedia(v=>({...v,[slug]:p.items!.slice(0,6)}))}).catch(()=>null)}},[solutions.map(s=>s.recommendation.slug).join("|")]);

 function toggleMood(m:Mood){setSelectedMoods(v=>v.includes(m)?v.filter(x=>x!==m):[...v,m].slice(-3))}
 async function learn(extra?:string){const text=[need.trim(),extra?.trim(),selectedMoods.map(x=>moodOptions.find(m=>m.id===x)?.[lang==="el"?"el":"en"]||x).join(", ")].filter(Boolean).join(". ")||say(lang,"Θέλω μια απόδραση που να μου ταιριάζει πραγματικά","I want an escape that genuinely fits me");setBusy(true);setError(null);try{const res=await fetch("/api/escape/discovery",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,initialText:text,answers:[{questionId:"companions",value:traveler},{questionId:"moods",value:selectedMoods}]})});if(!res.ok)throw new Error();const d=await res.json() as Discovery;setProfile({...d.profile,travelerType:traveler,moods:selectedMoods.length?selectedMoods:d.profile.moods});setSummary(d.summary);return d.profile}catch{setError(say(lang,"Δεν κατάφερα να σε καταλάβω αρκετά. Πες το όπως θα το έλεγες σε έναν travel agent: τι θέλεις να νιώσεις, τι θέλεις να αποφύγεις ή τι σε έχει κουράσει.","I need a little more context. Say it like you would to a travel agent: how you want to feel, what you want to avoid, or what has been tiring you lately."));return null}finally{setBusy(false)}}
 async function solve(){const learned=profile??await learn();if(!learned)return;setStep("discovering");setBusy(true);setError(null);setProgress(say(lang,"Συνδυάζω το travel DNA σου με πραγματική διαθεσιμότητα…","Matching your travel DNA with real inventory…"));const p={...learned,travelerType:traveler,moods:selectedMoods.length?selectedMoods:learned.moods};const nights=Math.max(1,Math.round((Date.parse(`${end}T00:00:00Z`)-Date.parse(`${start}T00:00:00Z`))/DAY));const trip={origin,startDate:start,endDate:end,month:"flexible",nights,budget,moods:p.moods,travelerType:traveler,language:lang,distancePreference:"any",pace:p.pace,hotelStyle:"any",avoid:p.avoid,entryMode:"idea",groupSize:traveler==="solo"?1:traveler==="couple"?2:4,desiredEnergy:p.desiredEnergy,socialPreference:p.socialPreference,noveltyPreference:p.noveltyPreference,mustHave:p.mustHave,dateFlexibility:"few-days",transportMode:"any",stayLocationPreference:"balanced",tripText:[need,summary].filter(Boolean).join(". ")};try{const res=await fetch("/api/escape/solve-v36/stream",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(trip)});if(!res.ok||!res.body)throw new Error();const reader=res.body.getReader(),decoder=new TextDecoder();let buffer="",final:EscapeSolutionResponseV36|null=null;for(;;){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()??"";for(const line of lines){if(!line.trim())continue;const row=JSON.parse(line) as StreamRow;if(row.message)setProgress(row.message);if(row.type==="final"&&row.result)final=row.result}}if(!final?.solutions.length)throw new Error();setResult(final);setSelected(0);setStep("destinations");setChat(v=>[...v,{role:"agent",text:say(lang,`Έχω ${Math.min(4,final!.solutions.length)} προορισμούς που αξίζουν για εσένα. Διάλεξε πρώτα τόπο. Τα καταλύματα θα έρθουν στο επόμενο, ξεχωριστό βήμα.`,`I found ${Math.min(4,final!.solutions.length)} destinations worth considering. Choose the place first. Stays come in the next, separate step.`)}])}catch{setStep("budget");setError(say(lang,"Δεν βρήκα αρκετά ισχυρή, επαληθευμένη αντιστοίχιση για αυτά τα δεδομένα. Άλλαξε λίγο ημερομηνίες ή budget και ξαναδοκιμάζω.","I could not find a strong enough verified match for those constraints. Adjust dates or budget slightly and I’ll try again."))}finally{setBusy(false);setProgress("")}}
 async function submitChat(e:FormEvent){e.preventDefault();const q=chatInput.trim();if(!q)return;setChat(v=>[...v,{role:"user",text:q}]);setNeed(v=>[v,q].filter(Boolean).join(". ").slice(0,700));setChatInput("");const p=await learn(q);if(p)setChat(v=>[...v,{role:"agent",text:say(lang,"Το κρατάω. Θα επηρεάσει τις επόμενες προτάσεις χωρίς να σε γυρίσω πίσω σε φόρμα.","Got it. I’ll use it in the next recommendations without sending you back through a form.")}])}
 const destinationQs=()=>new URLSearchParams({start,end,budget:String(budget),origin,travelerType:traveler,mood:selectedMoods[0]||"relax",lang}).toString();

 return <main className={styles.shell} style={{"--hero":`url(${background})`} as React.CSSProperties}>
  <div className={styles.backdrop}/><div className={styles.vignette}/>
  <header className={styles.nav}><a href={lang==="en"?"/en":"/"} className={styles.brand}><span>✦</span><b>Holiday Escape</b></a><div className={styles.navMeta}><span>{say(lang,"AI travel concierge","AI travel concierge")}</span><button onClick={()=>setChatOpen(true)}>Travel Agent</button></div></header>
  <div className={styles.rail}><i className={step!=="intent"?styles.done:styles.active}/><i className={["dates","budget","discovering","destinations"].includes(step)?styles.done:""}/><i className={["budget","discovering","destinations"].includes(step)?styles.done:""}/><i className={step==="destinations"?styles.active:""}/></div>
  <section className={styles.stage}>
   {step==="intent"&&<div className={styles.panel}><p className={styles.kicker}>{say(lang,"Δεν ψάχνεις προορισμό. Ψάχνεις πώς θέλεις να νιώσεις.","You are not choosing a destination. You are choosing how you want to feel.")}</p><h1>{say(lang,"Τι χρειάζεσαι πραγματικά από αυτή την απόδραση;","What do you really need from this escape?")}</h1><p className={styles.lead}>{say(lang,"Διάλεξε έως 3 — ή γράψε το με δικά σου λόγια. Ο agent θα κάνει τις σωστές ερωτήσεις μετά.","Pick up to 3 — or say it in your own words. The agent will ask only what matters next.")}</p><div className={styles.choiceGrid}>{moodOptions.map(m=><button key={m.id} className={selectedMoods.includes(m.id)?styles.selectedChoice:""} onClick={()=>toggleMood(m.id)}><span>{m.emoji}</span>{lang==="el"?m.el:m.en}</button>)}</div><div className={styles.freeInput}><textarea value={need} onChange={e=>setNeed(e.target.value)} placeholder={say(lang,"π.χ. Έχω κουραστεί, θέλω 3 μέρες χωρίς πολυκοσμία, καλό φαγητό και θάλασσα…","e.g. I’m tired, want 3 quiet days, great food and the sea…")}/></div>{error&&<p className={styles.error}>{error}</p>}<button className={styles.primary} disabled={busy||(!selectedMoods.length&&!need.trim())} onClick={()=>setStep("company")}>{say(lang,"Συνέχισε","Continue")} <span>→</span></button></div>}
   {step==="company"&&<div className={styles.panel}><p className={styles.kicker}>{say(lang,"Μία ακόμη λεπτομέρεια","One useful detail")}</p><h1>{say(lang,"Με ποιον θέλεις να το ζήσεις;","Who are you sharing this with?")}</h1><div className={styles.peopleGrid}>{travelerOptions.map(t=><button key={t.id} className={traveler===t.id?styles.selectedCard:""} onClick={()=>setTraveler(t.id)}><span className={styles.bigIcon}>{t.icon}</span><b>{lang==="el"?t.el:t.en}</b><small>{lang==="el"?t.subEl:t.subEn}</small></button>)}</div><button className={styles.primary} onClick={()=>setStep("dates")}>{say(lang,"Πάμε στις ημερομηνίες","Set the dates")} <span>→</span></button><button className={styles.back} onClick={()=>setStep("intent")}>← {say(lang,"πίσω","back")}</button></div>}
   {step==="dates"&&<div className={styles.panel}><p className={styles.kicker}>{say(lang,"Χρόνος, όχι φόρμα","Time, not paperwork")}</p><h1>{say(lang,"Πότε μπορείς να φύγεις;","When can you get away?")}</h1><div className={styles.dateRow}><label><span>{say(lang,"Αναχώρηση","Departure")}</span><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><div className={styles.arrow}>→</div><label><span>{say(lang,"Επιστροφή","Return")}</span><input type="date" value={end} min={start} onChange={e=>setEnd(e.target.value)}/></label></div><label className={styles.origin}><span>{say(lang,"Αφετηρία","Starting from")}</span><input value={origin} onChange={e=>setOrigin(e.target.value)}/></label><button className={styles.primary} disabled={Date.parse(end)<=Date.parse(start)} onClick={()=>setStep("budget")}>{say(lang,"Σχεδόν έτοιμο","Almost there")} <span>→</span></button><button className={styles.back} onClick={()=>setStep("company")}>← {say(lang,"πίσω","back")}</button></div>}
   {step==="budget"&&<div className={styles.panel}><p className={styles.kicker}>{say(lang,"Το budget είναι φίλτρο, όχι περιορισμός","Budget is a filter, not a limitation")}</p><h1>{say(lang,"Πόσο θέλεις να επενδύσεις σε αυτή την εμπειρία;","What feels comfortable for this escape?")}</h1><div className={styles.budgetBox}><span>€</span><input type="number" min={150} step={50} value={budget} onChange={e=>setBudget(Math.max(150,Number(e.target.value)||150))}/><small>{say(lang,"συνολικό budget ταξιδιού","total trip budget")}</small></div><div className={styles.agentRead}><span>✦</span><div><b>{say(lang,"Ο agent έχει αρκετά δεδομένα","The agent has enough context")}</b><p>{summary||say(lang,"Θα συνδυάσω διάθεση, παρέα, ημερομηνίες, αφετηρία και budget με πραγματικό inventory.","I’ll combine mood, company, dates, origin and budget with real inventory.")}</p></div></div>{error&&<p className={styles.error}>{error}</p>}<button className={styles.primary} disabled={busy} onClick={solve}>{busy?say(lang,"Σε καταλαβαίνω…","Learning your trip…"):say(lang,"Βρες μου το σωστό ταξίδι","Find my right escape")} <span>✦</span></button><button className={styles.back} onClick={()=>setStep("dates")}>← {say(lang,"πίσω","back")}</button></div>}
   {step==="discovering"&&<div className={styles.searching}><div className={styles.orbit}><span>✦</span></div><p>{say(lang,"Ο Travel Agent δουλεύει","Your Travel Agent is working")}</p><h1>{progress||say(lang,"Ψάχνω προορισμούς που ταιριάζουν σε εσένα — όχι απλώς δημοφιλή μέρη.","Finding destinations that fit you — not just popular places.")}</h1><small>{say(lang,"Ελέγχω προφίλ, εποχή, απόσταση, διαθεσιμότητα και πραγματικά stays στο παρασκήνιο.","Checking profile, season, distance, availability and real stays in the background.")}</small></div>}
   {step==="destinations"&&<div className={styles.results}><div className={styles.resultsHead}><div><p className={styles.kicker}>{say(lang,"Πρώτα ο τόπος","Destination first")}</p><h1>{say(lang,"Διάλεξε την εμπειρία. Το κατάλυμα έρχεται μετά.","Choose the experience. The stay comes next.")}</h1><p>{summary}</p></div><button className={styles.restart} onClick={()=>{setResult(null);setStep("intent")}}>{say(lang,"Ξεκίνα ξανά","Start over")}</button></div><div className={styles.destinationDeck}>{solutions.map((s,i)=>{const img=media[s.recommendation.slug]?.[0]?.imageUrl||fallbackHero;return <article key={s.recommendation.slug} className={i===selected?styles.activeDestination:""} onMouseEnter={()=>setSelected(i)} onClick={()=>setSelected(i)}><img src={img} alt=""/><div className={styles.cardShade}/><div className={styles.rank}>0{i+1}</div><div className={styles.cardBody}><small>{s.combinedScore}% {say(lang,"ταιριάζει στο προφίλ σου","fit")}</small><h2>{lang==="en"?s.recommendation.destinationEn:s.recommendation.destination}</h2><p>{s.reasoning.destination}</p><a href={`/escape/${s.recommendation.slug}?${destinationQs()}`}>{say(lang,"Δες αυτόν τον προορισμό","Explore this destination")} →</a></div></article>})}</div><div className={styles.resultHint}>✦ {say(lang,"Στο επόμενο βήμα θα δεις μόνο πραγματικά διαθέσιμα καταλύματα αυτού του προορισμού, με φωτογραφίες, rating, reviews, τοποθεσία και διεύθυνση.","Next you’ll see only real stay inventory for this destination, with photos, ratings, reviews, location and address.")}</div></div>}
  </section>
  <button className={styles.chatFab} onClick={()=>setChatOpen(v=>!v)}><span>✦</span><div><b>Travel Agent</b><small>{say(lang,"Ρώτησέ με οτιδήποτε","Ask me anything")}</small></div></button>
  {chatOpen&&<aside className={styles.chatPanel}><div className={styles.chatHead}><div><span>✦</span><b>Travel Agent</b><small>● online · {say(lang,"γνωρίζει το travel DNA σου","knows your travel DNA")}</small></div><button onClick={()=>setChatOpen(false)}>×</button></div><div className={styles.chatBody}>{chat.slice(-8).map((m,i)=><p key={i} className={m.role==="agent"?styles.agentBubble:styles.userBubble}>{m.text}</p>)}</div><form onSubmit={submitChat}><input value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder={say(lang,"π.χ. δεν θέλω πλοίο / θέλω spa / θέλω κάτι πιο local…","e.g. no ferry / I want a spa / make it more local…")}/><button disabled={busy}>→</button></form></aside>}
 </main>
}
