"use client";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import QRCode from "qrcode";
import {ArrowLeft,ArrowRight,CheckCircle,CloudSun,DownloadSimple,EnvelopeSimple,MapPin,PaperPlaneTilt,Sparkle,Star} from "@phosphor-icons/react";
import styles from "./v67-four-step-funnel.module.css";

type Stay={productId:string;name:string;location:string;address:string;latitude:number;longitude:number;price:number|null;currency:string;availability:string;imageUrl?:string|null;trackingUrl:string;role:string};
type Candidate={score:number;role:string;roleLabel:string;color:string;size:number;destination:{slug:string;name:string;nameEn:string;regionGroup:string;latitude:number;longitude:number;tags:string[]};heroImage?:string|null;evidence:{userFit:number;seasonality:number;weather:number;weatherLabel:string;demand:number|null;value:number;budgetFit:number;spatial:number;demandUsed:boolean};why:string[];tradeoff:string;stays:Stay[]};
type Place={id?:string;locationId?:string;name:string;kind?:string;source?:string;rating?:number|null;reviewCount?:number|null;address?:string|null;imageUrl?:string|null;distanceKm?:number|null;description?:string|null};
type Plan={trip:any;weather:{days:Array<{date:string;temperatureMinC:number|null;temperatureMaxC:number|null;precipitationProbability:number|null;windKmh:number|null;summary:string}>;score:number|null;label:string};tripadvisor:{restaurants:Place[];nightlife:Place[]};guide:{path:string;canvaTemplateStatus:string}};
type Local={restaurants?:Place[];cafes?:Place[];nightlife?:Place[];attractions?:Place[];museums?:Place[]};
type EventItem={id:string;name:string;date:string;time:string|null;venue:string|null;city:string;imageUrl:string|null};

const now=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Athens",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const add=(s:string,n:number)=>{const d=new Date(s+"T00:00:00Z");d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
const money=(n:number|null,c="EUR")=>n!=null&&n>=5?new Intl.NumberFormat("el-GR",{style:"currency",currency:c,maximumFractionDigits:0}).format(n):"Τιμή στον πάροχο";
const dateLabel=(s:string)=>new Intl.DateTimeFormat("el-GR",{weekday:"short",day:"numeric",month:"short"}).format(new Date(s+"T12:00:00Z"));
const colorHex=(c:string)=>({gold:"#d8aa55",green:"#2e9b68",blue:"#3a7bd5",purple:"#7d5ce7",orange:"#e7893c",cyan:"#3ba6ad"}[c]??"#4f7668");

export function V67FourStepFunnel(){
 const today=useMemo(now,[]),[step,setStep]=useState(1),[start,setStart]=useState(add(today,7)),[end,setEnd]=useState(add(today,10)),[budget,setBudget]=useState(850);
 const[traveler,setTraveler]=useState("couple"),[terrain,setTerrain]=useState("any"),[mood,setMood]=useState("relax"),[region,setRegion]=useState(""),[text,setText]=useState("");
 const[quiet,setQuiet]=useState(false),[noCar,setNoCar]=useState(false),[busy,setBusy]=useState(false),[candidates,setCandidates]=useState<Candidate[]>([]),[selected,setSelected]=useState<Candidate|null>(null),[stay,setStay]=useState<Stay|null>(null),[trip,setTrip]=useState<any>(null);
 const[plan,setPlan]=useState<Plan|null>(null),[local,setLocal]=useState<Local|null>(null),[events,setEvents]=useState<EventItem[]>([]),[eventNote,setEventNote]=useState(""),[email,setEmail]=useState(""),[emailState,setEmailState]=useState(""),[qr,setQr]=useState(""),[error,setError]=useState(""),[audit,setAudit]=useState(""),[mapFocus,setMapFocus]=useState<{lat:number;lon:number;radiusKm:number}|null>(null);
 const mapHost=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),layerRef=useRef<any>(null);

 useEffect(()=>{if(!mapHost.current)return;let dead=false;void import("leaflet").then(L=>{if(dead||!mapHost.current)return;if(!mapRef.current){mapRef.current=L.map(mapHost.current,{zoomControl:false,attributionControl:false,minZoom:5}).setView([38.3,23.7],6);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18}).addTo(mapRef.current);L.control.zoom({position:"bottomright"}).addTo(mapRef.current);mapRef.current.on("click",(e:any)=>setMapFocus({lat:e.latlng.lat,lon:e.latlng.lng,radiusKm:160}))}layerRef.current?.remove();const g=L.layerGroup().addTo(mapRef.current);layerRef.current=g;if(mapFocus)L.circle([mapFocus.lat,mapFocus.lon],{radius:mapFocus.radiusKm*1000,color:"#3ba6ad",weight:2,fillOpacity:.05}).addTo(g);
 candidates.forEach(c=>{const hex=colorHex(c.color),size=Math.round(c.size),isSelected=selected?.destination.slug===c.destination.slug,icon=L.divIcon({className:isSelected?"v68StarPin v68Selected":"v68StarPin",html:`<span style="width:${size}px;height:${size}px;background:${hex};font-size:${Math.max(14,Math.round(size*.42))}px">★</span>`,iconSize:[size,size],iconAnchor:[size/2,size/2]});
 const marker=L.marker([c.destination.latitude,c.destination.longitude],{icon,zIndexOffset:isSelected?2000:Math.round(c.score*10)}).addTo(g);
 marker.bindTooltip(`<div class="v68Tip">${c.heroImage?`<img src="${c.heroImage}" alt=""/>`:""}<div><small>${c.roleLabel}</small><b>${c.destination.name}</b><strong>AI Fit ${c.score}</strong><p>Season ${c.evidence.seasonality} · Weather ${c.evidence.weather} · ${c.evidence.demandUsed?`Demand ${c.evidence.demand}`:"Demand n/a"} · Value ${c.evidence.value}</p><em>${c.tradeoff}</em></div></div>`,{direction:"top",offset:[0,-size/2],opacity:1,className:"v68LeafletTip"});
 marker.on("click",()=>{setSelected(c);setStay(null);setPlan(null);setLocal(null);setEvents([]);setStep(2)});
 });
 if(selected)mapRef.current.flyTo([selected.destination.latitude,selected.destination.longitude],9,{duration:.7});setTimeout(()=>mapRef.current?.invalidateSize(),80)});return()=>{dead=true}},[candidates,selected,mapFocus]);

 async function discover(e:FormEvent){e.preventDefault();setBusy(true);setError("");setSelected(null);setStay(null);setPlan(null);setQr("");try{const r=await fetch("/api/v67/select-one",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({start,end,budget,traveler,terrain,mood,region:region||undefined,quiet,noCar,userText:text,mapCenter:mapFocus})}),p=await r.json();if(!r.ok||!p.ok||!Array.isArray(p.candidates)||!p.candidates.length)throw new Error();setCandidates(p.candidates);setTrip(p.trip);setAudit(`${p.considered?.inventory??0} stays → ${p.considered?.afterHardFilters??0} eligible → ${p.considered?.destinationsWeatherChecked??0} destinations checked · horizon: ${p.horizon??"adaptive"}`)}catch{setError("Δεν βρήκα αρκετές ασφαλείς επιλογές. Άνοιξε λίγο budget ή ένα constraint.")}finally{setBusy(false)}}
 async function loadTrip(selectedStay:Stay){if(!selected||!trip)return;setStay(selectedStay);setBusy(true);setError("");try{const [a,b,c]=await Promise.all([fetch("/api/trip-builder",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip,slug:selected.destination.slug,offerId:selectedStay.productId})}),fetch("/api/escape/stay-local",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip,slug:selected.destination.slug,offerId:selectedStay.productId})}),fetch("/api/escape/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({destination:selected.destination.name,start,end,latitude:selectedStay.latitude,longitude:selectedStay.longitude})})]);const pa=await a.json(),pb=await b.json().catch(()=>null),pc=await c.json().catch(()=>null);if(!a.ok)throw new Error();setPlan(pa);setLocal(b.ok?pb:null);setEvents(Array.isArray(pc?.events)?pc.events:[]);setEventNote(String(pc?.disclosure??""));setStep(4)}catch{setError("Δεν μπόρεσα να χτίσω το local trip intelligence για αυτό το stay.")}finally{setBusy(false)}}
 async function mail(){if(!selected||!stay||!trip||!/^\S+@\S+\.\S+$/.test(email)){setEmailState("error");return}setEmailState("sending");const r=await fetch("/api/guide/email",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,slug:selected.destination.slug,start,end,offer:stay.productId,language:"el",trip})}).catch(()=>null);setEmailState(r?.ok?"sent":"error")}

 useEffect(()=>{if(step===5&&stay)QRCode.toDataURL(stay.trackingUrl,{width:240,margin:1,errorCorrectionLevel:"H"}).then(setQr).catch(()=>setQr(""));},[step,stay]);

 const restaurants=(local?.restaurants?.length?local.restaurants:plan?.tripadvisor.restaurants??[]).slice(0,6),nightlife=(local?.nightlife?.length?local.nightlife:plan?.tripadvisor.nightlife??[]).slice(0,5),cafes=(local?.cafes??[]).slice(0,4),sights=[...(local?.attractions??[]),...(local?.museums??[])].slice(0,5);
 const days=useMemo(()=>{if(!selected||!plan)return[];const count=Math.max(1,Math.round((Date.parse(end)-Date.parse(start))/86400000))+1;return Array.from({length:count},(_,i)=>{const d=add(start,i),w=plan.weather.days.find(x=>x.date===d),r=restaurants[i%Math.max(1,restaurants.length)],n=nightlife[i%Math.max(1,nightlife.length)],s=sights[i%Math.max(1,sights.length)];return{date:d,rows:[{t:"10:00",x:s?.name||"Local discovery",n:w?.summary||"Area-aware morning"},{t:"13:30",x:r?.name||"Local lunch",n:r?.rating?"★ "+r.rating.toFixed(1):"Food intelligence"},{t:"20:30",x:n?.name||"Evening nearby",n:n?.rating?"★ "+n.rating.toFixed(1):"Nightlife intelligence"}]}})},[selected,plan,start,end,restaurants,nightlife,sights]);

 const labels=["Discover","Why here","Choose stay","Local reality","Build trip"];
 return <main className={styles.app}><header className={styles.header}><b>✦ TravelAI</b><div>{[1,2,3,4,5].map(n=><span key={n} className={step>=n?styles.done:""} title={labels[n-1]}>{step>n?<CheckCircle weight="fill"/>:n}</span>)}</div></header><section className={styles.layout}><aside className={styles.side}><small>5-STEP AI DECISION FUNNEL</small><h1>{labels[step-1]}</h1><p>{step===1?"AI map με date-aware demand, seasonality, weather, value και spatial awareness.":step===2?"Κατανόησε γιατί αξίζει αυτή η περιοχή πριν επιλέξεις stay.":step===3?"Διάλεξε βάση χωρίς να φύγεις από το TravelAI.":step===4?"Δες τι θα ζήσεις πραγματικά γύρω από το stay.":"Χτίσε το 360° itinerary και μόνο τότε άνοιξε την τελική προσφορά."}</p>{selected?<div className={styles.lock}><small>{selected.roleLabel}</small><b>{selected.destination.name}</b><span>{stay?.name??"Destination selected"}</span><strong>{selected.score}%</strong></div>:null}</aside><section className={styles.content}>
 {step===1?<div className={styles.step}><div className={styles.mapWrap}><div ref={mapHost} className={styles.map}/><div className={styles.mapNote}><b>AI OPPORTUNITY MAP</b><span>Μέγεθος = συνολικό relevance. Χρώμα = γιατί το AI το προτείνει. Hover για explanation, click για να μπεις στο funnel.</span></div><div className={styles.legend}>{[["gold","Best Match"],["green","Season"],["blue","Weather"],["purple","Demand"],["orange","Value"],["cyan","Alternative"]].map(x=><span key={x[0]}><i style={{background:colorHex(x[0])}}/> {x[1]}</span>)}</div></div><form className={styles.filters} onSubmit={discover}><Title n="01" title="AI infographic filter"/><div className={styles.grid4}><Field label="Από"><input type="date" min={today} value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Έως"><input type="date" min={start} value={end} onChange={e=>setEnd(e.target.value)}/></Field><Field label="Budget stay"><input type="number" min="150" step="50" value={budget} onChange={e=>setBudget(Number(e.target.value)||150)}/></Field><Field label="Ταξιδιώτες"><select value={traveler} onChange={e=>setTraveler(e.target.value)}><option value="solo">Solo</option><option value="couple">Ζευγάρι</option><option value="family">Οικογένεια</option><option value="friends">Φίλοι</option></select></Field></div><Choice title="Τοπίο" value={terrain} set={setTerrain} items={[["any","Όλα"],["sea","Θάλασσα"],["mountain","Βουνό"],["city","Πόλη"]]}/><Choice title="Travel intent" value={mood} set={setMood} items={[["relax","Relax"],["romantic","Romantic"],["food","Food"],["culture","Culture"],["nightlife","Nightlife"],["nature","Nature"],["adventure","Adventure"]]}/><div className={styles.grid2}><Field label="Περιοχή"><input value={region} onChange={e=>setRegion(e.target.value)} placeholder="π.χ. Πελοπόννησος"/></Field><Field label="Natural language filter"><input value={text} onChange={e=>setText(e.target.value)} placeholder="ήσυχα, καλό φαγητό, όχι πολύ οδήγηση…"/></Field></div><div className={styles.checks}>{mapFocus?<button type="button" onClick={()=>setMapFocus(null)}>✕ Καθάρισε map bias</button>:null}<label><input type="checkbox" checked={quiet} onChange={e=>setQuiet(e.target.checked)}/> χωρίς πολυκοσμία</label><label><input type="checkbox" checked={noCar} onChange={e=>setNoCar(e.target.checked)}/> χωρίς αυτοκίνητο</label></div>{audit?<p className={styles.audit}>{audit}</p>:null}{error?<p className={styles.error}>{error}</p>:null}<button className={styles.primary} disabled={busy}>{busy?<><Sparkle/> AI αναλύει opportunities…</>:<>Ανάλυσε τον χάρτη <ArrowRight/></>}</button></form></div>:null}
 {step===2&&selected?<div className={styles.step}><Title n="02" title="Γιατί αυτή η περιοχή τώρα"/><div className={styles.destinationHero}>{selected.heroImage?<img src={selected.heroImage} alt={selected.destination.name}/>:<div className={styles.heroFallback}><MapPin/></div>}<div><small>{selected.roleLabel}</small><h2>{selected.destination.name}</h2><strong>AI Fit {selected.score}/100</strong><p>{selected.tradeoff}</p></div></div><div className={styles.scoreGrid}>{[["Your fit",selected.evidence.userFit],["Season",selected.evidence.seasonality],["Weather",selected.evidence.weather],["Demand",selected.evidence.demand??"—"],["Value",selected.evidence.value],["Spatial",selected.evidence.spatial]].map(x=><article key={String(x[0])}><b>{x[1]}</b><span>{x[0]}</span></article>)}</div><section className={styles.reason}><h3>Γιατί στο προτείνει η AI</h3>{selected.why.map(x=><p key={x}>✓ {x}</p>)}<h4>Trade-off</h4><p>{selected.tradeoff}</p></section><Nav back={()=>setStep(1)} next={()=>setStep(3)} label="Δες τις καλύτερες βάσεις"/></div>:null}
 {step===3&&selected?<div className={styles.step}><Title n="03" title="Choose your base"/><div className={styles.stayGrid}>{selected.stays.map((s,i)=><button key={s.productId} type="button" className={stay?.productId===s.productId?styles.stayOn:""} onClick={()=>setStay(s)}>{s.imageUrl?<img src={s.imageUrl} alt={s.name}/>:<div className={styles.fallback}><MapPin/></div>}<small>{i===0?"AI RECOMMENDED":s.role.replaceAll("-"," ").toUpperCase()}</small><b>{s.name}</b><span>{s.location}</span><strong>{money(s.price,s.currency)}</strong><em>{s.availability}</em></button>)}</div>{error?<p className={styles.error}>{error}</p>:null}<div className={styles.nav}><button onClick={()=>setStep(2)}><ArrowLeft/> Πίσω</button><button className={styles.primary} disabled={!stay||busy} onClick={()=>stay&&void loadTrip(stay)}>{busy?"AI χτίζει local intelligence…":"Συνέχισε με αυτό το stay"} <ArrowRight/></button></div></div>:null}
 {step===4&&selected&&stay&&plan?<div className={styles.step}><Title n="04" title="Weather + local life + events"/><div className={styles.weatherHero}><div><CloudSun size={46}/><b>{selected.destination.name}</b><strong>{selected.evidence.weather}/100</strong><span>{selected.evidence.weatherLabel}</span></div><div>{[["Season",selected.evidence.seasonality],["Demand",selected.evidence.demand??"—"],["Value",selected.evidence.value],["Spatial",selected.evidence.spatial]].map(x=><article key={String(x[0])}><b>{x[1]}</b><small>{x[0]}</small></article>)}</div></div><div className={styles.weather}>{plan.weather.days.map(d=><article key={d.date}><small>{dateLabel(d.date)}</small><strong>{d.temperatureMinC==null?"—":Math.round(d.temperatureMinC)}° → {d.temperatureMaxC==null?"—":Math.round(d.temperatureMaxC)}°</strong><p>{d.summary}</p><span>🌧 {d.precipitationProbability??"—"}% · 💨 {d.windKmh==null?"—":Math.round(d.windKmh)} km/h</span></article>)}</div><PlaceSection title="🍽 Restaurants" rows={restaurants}/><PlaceSection title="🍸 Drinks & nightlife" rows={nightlife}/>{cafes.length?<PlaceSection title="☕ Cafés" rows={cafes}/>:null}<section className={styles.places}><h3>🎟 Events στις ημερομηνίες σου <span>{events.length}</span></h3>{events.length?<div className={styles.eventGrid}>{events.map(e=><article key={e.id}>{e.imageUrl?<img src={e.imageUrl} alt={e.name}/>:null}<small>{dateLabel(e.date)} {e.time?"· "+e.time.slice(0,5):""}</small><b>{e.name}</b><span>{e.venue||e.city}</span></article>)}</div>:<p className={styles.empty}>{eventNote||"Δεν βρέθηκε verified event."}</p>}</section><Nav back={()=>setStep(3)} next={()=>setStep(5)} label="Build my 360° trip"/></div>:null}
 {step===5&&selected&&stay&&plan?<div className={styles.step}><Title n="05" title="360° Escape Book"/><div className={styles.finalHero}><div><small>YOUR SELECTED BASE</small><h2>{selected.destination.name}</h2><b>{stay.name}</b><strong>{money(stay.price,stay.currency)}</strong></div>{qr?<img src={qr} alt="Final tracking QR"/>:null}</div><div className={styles.itinerary}>{days.map(d=><article key={d.date}><h3>{dateLabel(d.date)}</h3>{d.rows.map((r,i)=><div key={i}><time>{r.t}</time><span/><p><b>{r.x}</b><small>{r.n}</small></p></div>)}</article>)}</div><div className={styles.finalGrid}><article><DownloadSimple size={30}/><small>CANVA-READY PDF</small><h3>Escape Book</h3><p>Weather · local life · itinerary · disclosure · QR.</p><a href={plan.guide.path} target="_blank" rel="noopener noreferrer">Άνοιξε PDF <ArrowRight/></a><em>Canva: {plan.guide.canvaTemplateStatus}</em></article><article><EnvelopeSimple size={30}/><small>EMAIL</small><h3>Στείλ’ το στο email</h3><div><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@email.com"/><button onClick={()=>void mail()}><PaperPlaneTilt/></button></div><em>{emailState==="sent"?"✓ Στάλθηκε":emailState==="sending"?"Αποστολή…":emailState==="error"?"Έλεγξε το email":""}</em></article></div><div className={styles.exit}><small>THE ONLY EXTERNAL COMMERCIAL EXIT</small><p>Το TravelAI σε κράτησε μέσα στο funnel μέχρι να ελέγξεις περιοχή, stay, καιρό, local life και itinerary.</p><a href={stay.trackingUrl} target="_blank" rel="sponsored nofollow noopener noreferrer">Check final live price <ArrowRight/></a></div><button className={styles.back} onClick={()=>setStep(4)}><ArrowLeft/> Πίσω</button></div>:null}
 </section></section></main>
}

function Title({n,title}:{n:string;title:string}){return <div className={styles.title}><span>{n}</span><h2>{title}</h2></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className={styles.field}><span>{label}</span>{children}</label>}
function Choice({title,value,set,items}:{title:string;value:string;set:(v:any)=>void;items:string[][]}){return <div className={styles.choice}><b>{title}</b><div>{items.map(x=><button type="button" key={x[0]} className={value===x[0]?styles.on:""} onClick={()=>set(x[0])}>{x[1]}</button>)}</div></div>}
function Nav({back,next,label}:{back:()=>void;next:()=>void;label:string}){return <div className={styles.nav}><button onClick={back}><ArrowLeft/> Πίσω</button><button className={styles.primary} onClick={next}>{label} <ArrowRight/></button></div>}
function PlaceSection({title,rows}:{title:string;rows:Place[]}){return <section className={styles.places}><h3>{title} <span>{rows.length}</span></h3><div className={styles.placeGrid}>{rows.map((p,i)=><article key={(p.id??p.locationId??p.name)+i}>{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>:<div className={styles.fallback}><MapPin/></div>}<div><small>{p.source??p.kind??"LOCAL"}</small><b>{p.name}</b><p>{p.address||p.description||"Κοντά στην επιλεγμένη βάση."}</p><span>{p.rating!=null?<><Star weight="fill"/> {p.rating.toFixed(1)} </>:null}{p.distanceKm!=null?" · "+p.distanceKm.toFixed(1)+" km":""}</span></div></article>)}</div></section>}
