"use client";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import QRCode from "qrcode";
import {ArrowLeft,ArrowRight,CheckCircle,CloudSun,DownloadSimple,EnvelopeSimple,MapPin,PaperPlaneTilt,Sparkle,Star} from "@phosphor-icons/react";
import styles from "./v67-four-step-funnel.module.css";

type Winner={score:number;destination:{slug:string;name:string;nameEn:string;regionGroup:string;latitude:number;longitude:number;tags:string[]};stay:{productId:string;name:string;location:string;address:string;latitude:number;longitude:number;price:number|null;currency:string;trackingUrl:string;availability:string};evidence:{userFit:number;seasonality:number;weather:number;weatherLabel:string;demand:number|null;value:number;budgetFit:number;demandUsed:boolean}};
type Place={id?:string;locationId?:string;name:string;kind?:string;source?:string;rating?:number|null;reviewCount?:number|null;address?:string|null;imageUrl?:string|null;distanceKm?:number|null;description?:string|null};
type Plan={trip:any;weather:{days:Array<{date:string;temperatureMinC:number|null;temperatureMaxC:number|null;precipitationProbability:number|null;windKmh:number|null;summary:string}>;score:number|null;label:string};tripadvisor:{restaurants:Place[];nightlife:Place[]};guide:{path:string;canvaTemplateStatus:string}};
type Local={restaurants?:Place[];cafes?:Place[];nightlife?:Place[];attractions?:Place[];museums?:Place[]};
type EventItem={id:string;name:string;date:string;time:string|null;venue:string|null;city:string;imageUrl:string|null};
type MapStay={productId:string;name:string;location:string;latitude:number;longitude:number;price:number|null;currency:string;intelligenceScore?:number};

const now=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Athens",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const add=(s:string,n:number)=>{const d=new Date(s+"T00:00:00Z");d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
const money=(n:number|null,c="EUR")=>n!=null&&n>=5?new Intl.NumberFormat("el-GR",{style:"currency",currency:c,maximumFractionDigits:0}).format(n):"Τιμή στον πάροχο";
const dateLabel=(s:string)=>new Intl.DateTimeFormat("el-GR",{weekday:"short",day:"numeric",month:"short"}).format(new Date(s+"T12:00:00Z"));

export function V67FourStepFunnel(){
 const today=useMemo(now,[]),[step,setStep]=useState(1),[start,setStart]=useState(add(today,7)),[end,setEnd]=useState(add(today,10)),[budget,setBudget]=useState(850);
 const[traveler,setTraveler]=useState("couple"),[terrain,setTerrain]=useState("any"),[mood,setMood]=useState("relax"),[region,setRegion]=useState(""),[text,setText]=useState("");
 const[quiet,setQuiet]=useState(false),[noCar,setNoCar]=useState(false),[busy,setBusy]=useState(false),[winner,setWinner]=useState<Winner|null>(null),[trip,setTrip]=useState<any>(null);
 const[plan,setPlan]=useState<Plan|null>(null),[local,setLocal]=useState<Local|null>(null),[events,setEvents]=useState<EventItem[]>([]),[eventNote,setEventNote]=useState(""),[mapStays,setMapStays]=useState<MapStay[]>([]);
 const[email,setEmail]=useState(""),[emailState,setEmailState]=useState(""),[qr,setQr]=useState(""),[error,setError]=useState(""),[audit,setAudit]=useState(""),[mapFocus,setMapFocus]=useState<{lat:number;lon:number;radiusKm:number}|null>(null);
 const mapHost=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),layerRef=useRef<any>(null);

 useEffect(()=>{let dead=false;fetch("/api/v50/map-stays?mode=quick&limit=60&start="+encodeURIComponent(start),{cache:"no-store"}).then(r=>r.json()).then(p=>{if(!dead&&Array.isArray(p.products))setMapStays(p.products)}).catch(()=>{});return()=>{dead=true}},[start]);
 useEffect(()=>{if(!mapHost.current)return;let dead=false;void import("leaflet").then(L=>{if(dead||!mapHost.current)return;if(!mapRef.current){mapRef.current=L.map(mapHost.current,{zoomControl:false,attributionControl:false,minZoom:5}).setView([38.3,23.7],6);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18}).addTo(mapRef.current);L.control.zoom({position:"bottomright"}).addTo(mapRef.current);mapRef.current.on("click",(e:any)=>setMapFocus({lat:e.latlng.lat,lon:e.latlng.lng,radiusKm:160}))}layerRef.current?.remove();const g=L.layerGroup().addTo(mapRef.current);layerRef.current=g;if(mapFocus)L.circle([mapFocus.lat,mapFocus.lon],{radius:mapFocus.radiusKm*1000,color:"#d8aa55",weight:2,fillOpacity:.05}).addTo(g);mapStays.forEach(p=>{const win=winner?.stay.productId===p.productId,size=win?44:(p.intelligenceScore??0)>80?27:18,icon=L.divIcon({className:win?"v67WinnerPin":"v67MapPin",html:'<span style="width:'+size+'px;height:'+size+'px">'+(win?"★":"•")+"</span>",iconSize:[size,size],iconAnchor:[size/2,size/2]});L.marker([p.latitude,p.longitude],{icon,zIndexOffset:win?2000:100}).addTo(g).bindTooltip(p.name+" · "+money(p.price,p.currency))});if(winner)mapRef.current.flyTo([winner.stay.latitude,winner.stay.longitude],10,{duration:1.1});setTimeout(()=>mapRef.current?.invalidateSize(),80)});return()=>{dead=true}},[mapStays,winner]);

 async function choose(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/v67/select-one",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({start,end,budget,traveler,terrain,mood,region:region||undefined,quiet,noCar,userText:text,mapCenter:mapFocus})}),p=await r.json();if(!r.ok||!p.ok||!p.winner||!p.trip)throw new Error();setWinner(p.winner);setTrip(p.trip);setAudit(String(p.considered?.inventory??0)+" stays → "+String(p.considered?.afterHardFilters??0)+" hard-filtered → "+String(p.considered?.destinationsWeatherChecked??0)+" weather-checked destinations → 1 winner");const calls=await Promise.all([fetch("/api/trip-builder",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip:p.trip,slug:p.winner.destination.slug,offerId:p.winner.stay.productId})}),fetch("/api/escape/stay-local",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip:p.trip,slug:p.winner.destination.slug,offerId:p.winner.stay.productId})}),fetch("/api/escape/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({destination:p.winner.destination.name,start,end,latitude:p.winner.stay.latitude,longitude:p.winner.stay.longitude})})]);const a=await calls[0].json(),b=await calls[1].json().catch(()=>null),c=await calls[2].json().catch(()=>null);if(!calls[0].ok)throw new Error();setPlan(a);setLocal(calls[1].ok?b:null);setEvents(Array.isArray(c?.events)?c.events:[]);setEventNote(String(c?.disclosure??""));QRCode.toDataURL(p.winner.stay.trackingUrl,{width:240,margin:1,errorCorrectionLevel:"H"}).then(setQr).catch(()=>setQr(""));setStep(2)}catch{setError("Δεν βρήκα ασφαλή winner. Άνοιξε λίγο budget ή ένα constraint.")}finally{setBusy(false)}}
 async function mail(){if(!winner||!trip||!/^\\S+@\\S+\\.\\S+$/.test(email)){setEmailState("error");return}setEmailState("sending");const r=await fetch("/api/guide/email",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,slug:winner.destination.slug,start,end,offer:winner.stay.productId,language:"el",trip})}).catch(()=>null);setEmailState(r?.ok?"sent":"error")}

 const restaurants=(local?.restaurants?.length?local.restaurants:plan?.tripadvisor.restaurants??[]).slice(0,6),nightlife=(local?.nightlife?.length?local.nightlife:plan?.tripadvisor.nightlife??[]).slice(0,5),cafes=(local?.cafes??[]).slice(0,4),sights=[...(local?.attractions??[]),...(local?.museums??[])].slice(0,5);
 const days=useMemo(()=>{if(!winner)return[];const count=Math.max(1,Math.round((Date.parse(end)-Date.parse(start))/86400000))+1;return Array.from({length:count},(_,i)=>{const d=add(start,i),w=plan?.weather.days.find(x=>x.date===d),r=restaurants[i%Math.max(1,restaurants.length)],n=nightlife[i%Math.max(1,nightlife.length)],s=sights[i%Math.max(1,sights.length)];return{date:d,rows:[{t:"10:00",x:s?.name||"Local discovery",n:w?.summary||"Area-aware morning"},{t:"13:30",x:r?.name||"Local lunch",n:r?.rating?"★ "+r.rating.toFixed(1):"Food intelligence"},{t:"20:30",x:n?.name||"Evening nearby",n:n?.rating?"★ "+n.rating.toFixed(1):"Nightlife intelligence"}]}})},[winner,plan,start,end,restaurants,nightlife,sights]);

 return <main className={styles.app}><header className={styles.header}><b>✦ TravelAI</b><div>{[1,2,3,4].map(n=><span key={n} className={step>=n?styles.done:""}>{step>n?<CheckCircle weight="fill"/>:n}</span>)}</div></header><section className={styles.layout}><aside className={styles.side}><small>4-STEP AI FUNNEL</small><h1>{step===1?"Map + filters":step===2?"Weather":step===3?"Area life":"360° itinerary"}</h1><p>{step===1?"Μία επιλογή από όλο το πραγματικό inventory.":step===2?"Weather + seasonality για τις ακριβείς ημερομηνίες.":step===3?"Restaurants, drinks, nightlife και verified events.":"Canva-ready PDF, email, QR και μόνο το tracking URL ως έξοδος."}</p>{winner?<div className={styles.lock}><small>AI WINNER</small><b>{winner.destination.name}</b><span>{winner.stay.name}</span><strong>{winner.score}%</strong></div>:null}</aside><section className={styles.content}>
 {step===1?<div className={styles.step}><div className={styles.mapWrap}><div ref={mapHost} className={styles.map}/><div className={styles.mapNote}><b>FROM THE MAP → ONE WINNER</b><span>Τα pins είναι real stays. Η επιλογή γίνεται από dates + filters + weather + season + demand + value. Πάτησε στον χάρτη για geographic focus.</span></div></div><form className={styles.filters} onSubmit={choose}><Title n="01" title="Ημερομηνίες + φίλτρα χρήστη"/><div className={styles.grid4}><Field label="Από"><input type="date" min={today} value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Έως"><input type="date" min={start} value={end} onChange={e=>setEnd(e.target.value)}/></Field><Field label="Budget stay"><input type="number" min="150" step="50" value={budget} onChange={e=>setBudget(Number(e.target.value)||150)}/></Field><Field label="Ταξιδιώτες"><select value={traveler} onChange={e=>setTraveler(e.target.value)}><option value="solo">Solo</option><option value="couple">Ζευγάρι</option><option value="family">Οικογένεια</option><option value="friends">Φίλοι</option></select></Field></div><Choice title="Τοπίο" value={terrain} set={setTerrain} items={[["any","Όλα"],["sea","Θάλασσα"],["mountain","Βουνό"],["city","Πόλη"]]}/><Choice title="Travel intent" value={mood} set={setMood} items={[["relax","Relax"],["romantic","Romantic"],["food","Food"],["culture","Culture"],["nightlife","Nightlife"],["nature","Nature"],["adventure","Adventure"]]}/><div className={styles.grid2}><Field label="Περιοχή"><input value={region} onChange={e=>setRegion(e.target.value)} placeholder="π.χ. Πελοπόννησος"/></Field><Field label="Natural language filter"><input value={text} onChange={e=>setText(e.target.value)} placeholder="ήσυχα, καλό φαγητό, όχι πολύ οδήγηση…"/></Field></div><div className={styles.checks}>{mapFocus?<button type="button" onClick={()=>setMapFocus(null)}>✕ Καθάρισε map focus 160 km</button>:null}<label><input type="checkbox" checked={quiet} onChange={e=>setQuiet(e.target.checked)}/> χωρίς πολυκοσμία</label><label><input type="checkbox" checked={noCar} onChange={e=>setNoCar(e.target.checked)}/> χωρίς αυτοκίνητο</label></div>{error?<p className={styles.error}>{error}</p>:null}<button className={styles.primary} disabled={busy}>{busy?<><Sparkle/> AI συγκρίνει όλο το inventory…</>:<>Βρες τη μία καλύτερη επιλογή <ArrowRight/></>}</button></form></div>:null}
 {step===2&&winner&&plan?<div className={styles.step}><Title n="02" title="Weather στις δικές σου ημερομηνίες"/><div className={styles.weatherHero}><div><CloudSun size={46}/><b>{winner.destination.name}</b><strong>{winner.evidence.weather}/100</strong><span>{winner.evidence.weatherLabel}</span></div><div>{[["Fit",winner.evidence.userFit],["Season",winner.evidence.seasonality],["Demand",winner.evidence.demand??"—"],["Value",winner.evidence.value]].map(x=><article key={String(x[0])}><b>{x[1]}</b><small>{x[0]}</small></article>)}</div></div><div className={styles.weather}>{plan.weather.days.map(d=><article key={d.date}><small>{dateLabel(d.date)}</small><strong>{d.temperatureMinC==null?"—":Math.round(d.temperatureMinC)}° → {d.temperatureMaxC==null?"—":Math.round(d.temperatureMaxC)}°</strong><p>{d.summary}</p><span>🌧 {d.precipitationProbability??"—"}% · 💨 {d.windKmh==null?"—":Math.round(d.windKmh)} km/h</span></article>)}</div><p className={styles.audit}>{audit}</p><Nav back={()=>setStep(1)} next={()=>setStep(3)} label="Food, drinks & events"/></div>:null}
 {step===3&&winner&&plan?<div className={styles.step}><Title n="03" title="Η περιοχή γύρω από το stay"/><PlaceSection title="🍽 Restaurants" rows={restaurants}/><PlaceSection title="🍸 Drinks & nightlife" rows={nightlife}/>{cafes.length?<PlaceSection title="☕ Cafés" rows={cafes}/>:null}<section className={styles.places}><h3>🎟 Events στις ημερομηνίες σου <span>{events.length}</span></h3>{events.length?<div className={styles.eventGrid}>{events.map(e=><article key={e.id}>{e.imageUrl?<img src={e.imageUrl} alt={e.name}/>:null}<small>{dateLabel(e.date)} {e.time?"· "+e.time.slice(0,5):""}</small><b>{e.name}</b><span>{e.venue||e.city}</span></article>)}</div>:<p className={styles.empty}>{eventNote||"Δεν βρέθηκε verified event."}</p>}</section><Nav back={()=>setStep(2)} next={()=>setStep(4)} label="Build 360° itinerary"/></div>:null}
 {step===4&&winner&&plan?<div className={styles.step}><Title n="04" title="360° Escape Book"/><div className={styles.finalHero}><div><small>AI SELECTED BASE</small><h2>{winner.destination.name}</h2><b>{winner.stay.name}</b><strong>{money(winner.stay.price,winner.stay.currency)}</strong></div>{qr?<img src={qr} alt="Tracking QR"/>:null}</div><div className={styles.itinerary}>{days.map(d=><article key={d.date}><h3>{dateLabel(d.date)}</h3>{d.rows.map((r,i)=><div key={i}><time>{r.t}</time><span/><p><b>{r.x}</b><small>{r.n}</small></p></div>)}</article>)}</div><div className={styles.finalGrid}><article><DownloadSimple size={30}/><small>CANVA-READY PDF</small><h3>Escape Book</h3><p>Weather · local life · itinerary · disclosure · QR.</p><a href={plan.guide.path} target="_blank" rel="noopener noreferrer">Άνοιξε PDF <ArrowRight/></a><em>Canva: {plan.guide.canvaTemplateStatus}</em></article><article><EnvelopeSimple size={30}/><small>EMAIL</small><h3>Στείλ’ το στο email</h3><div><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@email.com"/><button onClick={()=>void mail()}><PaperPlaneTilt/></button></div><em>{emailState==="sent"?"✓ Στάλθηκε":emailState==="sending"?"Αποστολή…":emailState==="error"?"Έλεγξε το email":""}</em></article></div><div className={styles.exit}><small>THE ONLY EXTERNAL EXIT</small><p>Tripadvisor, maps και event providers χρησιμοποιούνται μόνο ως intelligence. Δεν υπάρχουν εξωτερικά links προς αυτούς.</p><a href={winner.stay.trackingUrl} target="_blank" rel="sponsored nofollow noopener noreferrer">Τελική προσφορά στον πάροχο <ArrowRight/></a></div><button className={styles.back} onClick={()=>setStep(3)}><ArrowLeft/> Πίσω</button></div>:null}
 </section></section></main>
}

function Title({n,title}:{n:string;title:string}){return <div className={styles.title}><span>{n}</span><h2>{title}</h2></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className={styles.field}><span>{label}</span>{children}</label>}
function Choice({title,value,set,items}:{title:string;value:string;set:(v:any)=>void;items:string[][]}){return <div className={styles.choice}><b>{title}</b><div>{items.map(x=><button type="button" key={x[0]} className={value===x[0]?styles.on:""} onClick={()=>set(x[0])}>{x[1]}</button>)}</div></div>}
function Nav({back,next,label}:{back:()=>void;next:()=>void;label:string}){return <div className={styles.nav}><button onClick={back}><ArrowLeft/> Πίσω</button><button className={styles.primary} onClick={next}>{label} <ArrowRight/></button></div>}
function PlaceSection({title,rows}:{title:string;rows:Place[]}){return <section className={styles.places}><h3>{title} <span>{rows.length}</span></h3><div className={styles.placeGrid}>{rows.map((p,i)=><article key={(p.id??p.locationId??p.name)+i}>{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>:<div className={styles.fallback}><MapPin/></div>}<div><small>{p.source??p.kind??"LOCAL"}</small><b>{p.name}</b><p>{p.address||p.description||"Κοντά στην επιλεγμένη βάση."}</p><span>{p.rating!=null?<><Star weight="fill"/> {p.rating.toFixed(1)} </>:null}{p.distanceKm!=null?" · "+p.distanceKm.toFixed(1)+" km":""}</span></div></article>)}</div></section>}
