import {createHash} from "node:crypto";
import {NextResponse} from "next/server";
import {loadJourneyBySlugV70,updateJourneyV70} from "@/lib/ai/journey-store-v70";
import {renderJourneyPdfV70} from "@/lib/ai/journey-pdf-v70";
import {requestOwnsProfileV70} from "@/lib/ai/v70-auth";
import {asRecord,asString} from "@/lib/ai/agentic-model-v70";

export const runtime="nodejs";export const dynamic="force-dynamic";export const maxDuration=60;
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/,rate=new Map<string,{count:number;until:number}>();
function esc(v:string){return v.replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[ch]??ch)}
function limited(key:string){const now=Date.now(),x=rate.get(key);if(!x||x.until<now){rate.set(key,{count:1,until:now+10*60_000});return false}x.count++;return x.count>3}
export async function POST(request:Request){
 const body=await request.json().catch(()=>null) as Record<string,unknown>|null,email=typeof body?.email==="string"?body.email.trim().toLowerCase():"",slug=typeof body?.journeySlug==="string"?body.journeySlug.trim():"";if(!emailPattern.test(email)||email.length>180||!slug||slug.length>180)return NextResponse.json({ok:false,error:"Valid email and journeySlug required"},{status:400});
 const journey=await loadJourneyBySlugV70(slug).catch(()=>null);if(!journey||!requestOwnsProfileV70(request,journey.profile_key))return NextResponse.json({ok:false,error:"Journey not found"},{status:404});const client=`${request.headers.get("x-forwarded-for")?.split(",")[0]??"unknown"}:${createHash("sha256").update(email).digest("hex").slice(0,12)}`;if(limited(client))return NextResponse.json({ok:false,error:"Rate limited"},{status:429});
 const origin=new URL(request.url).origin,pdfUrl=`${origin}/api/v70/journey/pdf?slug=${encodeURIComponent(slug)}`,resend=process.env.RESEND_API_KEY,from=process.env.TRAVEL_GUIDE_FROM_EMAIL;if(!resend||!from){await updateJourneyV70(journey.id,{email_to:email,email_status:"failed"}).catch(()=>null);return NextResponse.json({ok:true,delivery:"download",pdfUrl},{headers:{"cache-control":"no-store"}})}
 await updateJourneyV70(journey.id,{email_to:email,email_status:"pending"}).catch(()=>null);try{const bytes=await renderJourneyPdfV70(journey,origin),live=asRecord(journey.live_state),stay=asRecord(live.selectedStay),tracking=asRecord(live.trackingAction),code=asString(tracking.code,40),trackingUrl=code?`${origin}/api/v70/track?code=${encodeURIComponent(code)}`:"",subject=journey.locale==="en"?`Your TravelAI journey · ${journey.destination_name}`:`Το TravelAI ταξίδι σου · ${journey.destination_name}`,html=`<div style="font-family:Arial,sans-serif;background:#071512;padding:32px;color:#f7f3ea"><div style="max-width:640px;margin:auto"><p style="color:#d3ae68;font-size:11px;font-weight:800;letter-spacing:.14em">TRAVELAI · V70 JOURNEY</p><h1 style="font-family:Georgia,serif;font-weight:400;font-size:38px">${esc(journey.destination_name)}</h1><p style="line-height:1.65;color:#c5d0ca">${journey.locale==="en"?"Your grounded 360° itinerary is attached as a PDF.":"Το τεκμηριωμένο 360° itinerary σου είναι συνημμένο σε PDF."}</p><p><strong>${esc(asString(stay.propertyName,220))}</strong></p>${trackingUrl?`<a href="${esc(trackingUrl)}" style="display:inline-block;background:#d3ae68;color:#0d1c17;text-decoration:none;padding:13px 18px;border-radius:999px;font-weight:800">${journey.locale==="en"?"Open provider offer":"Άνοιγμα προσφοράς παρόχου"}</a>`:""}<p style="font-size:12px;color:#87968f;margin-top:24px">${journey.locale==="en"?"Final price, room and live availability are confirmed by the provider. Affiliate tracking may generate a commission at no extra cost to you.":"Η τελική τιμή, το δωμάτιο και η live διαθεσιμότητα επιβεβαιώνονται στον πάροχο. Το affiliate tracking μπορεί να αποφέρει προμήθεια χωρίς επιπλέον κόστος για εσένα."}</p></div></div>`,idempotency=`travel-v70-${createHash("sha256").update(`${journey.id}|${email}`).digest("hex").slice(0,32)}`,response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${resend}`,"content-type":"application/json","Idempotency-Key":idempotency},body:JSON.stringify({from,to:[email],subject,html,attachments:[{filename:journey.pdf_filename||"TravelAI_Journey.pdf",content:Buffer.from(bytes).toString("base64")}]}),signal:AbortSignal.timeout(15_000)});if(!response.ok)throw new Error(`Resend ${response.status}`);await updateJourneyV70(journey.id,{email_to:email,email_status:"sent",status:"emailed"});return NextResponse.json({ok:true,delivery:"email",pdfUrl},{headers:{"cache-control":"no-store"}})}catch(error){await updateJourneyV70(journey.id,{email_to:email,email_status:"failed"}).catch(()=>null);console.error("V70 journey email failed",error);return NextResponse.json({ok:false,delivery:"download",pdfUrl},{status:502,headers:{"cache-control":"no-store"}})}
}
