export const V24_AGENT_SKILLS=[
 {id:"semantic-formulation",owner:"traveler-understanding",input:"structured fields + free text",output:"canonical 24D fuzzy contract",tools:["DeepSeek V4 Pro preferred","strong OpenAI reasoner fallback","deterministic multilingual fallback"],rule:"formulator never names or ranks destinations/hotels"},
 {id:"dated-locality-retrieval",owner:"inventory-grounder",input:"exact dates",output:"first-class dated locality candidates",tools:["Supabase locality semantic profiles","dated stay inventory"],rule:"property count is observability only; canonical parent is optional"},
 {id:"fuzzy-multi-criteria",owner:"decision-engine",input:"24D contract + locality profiles",output:"criterion-sensitive locality recall",tools:["weighted fuzzy membership","explicit negative membership","non-compensatory priority floor"],rule:"hard constraints remain deterministic"},
 {id:"locality-evidence-rerank",owner:"locality-evidence-agent",input:"top locality recall + 24D contract",output:"grounded locality score adjustments",tools:["Wikipedia","Wikivoyage","reasoner limited to supplied evidence"],rule:"no model-memory facts; missing evidence is uncertainty"},
 {id:"exact-locality-stay-gate",owner:"inventory-grounder",input:"locality_id + dates + stay requirements",output:"verified matching stays",tools:["get_locality_stays_v23","stay semantic profiles"],rule:"hard stay failure rejects candidate; inventory depth never boosts score"},
 {id:"season-route-weather",owner:"date-feasibility",input:"locality coordinates + dates + origin",output:"season/weather/effort evidence",tools:["weather adapter","trusted parent route knowledge when available"],rule:"unknown route evidence lowers confidence; it is never invented"},
 {id:"independent-critique",owner:"skeptical-auditor",input:"ranked verified localities",output:"pass/repair/reject",tools:["deterministic hard audit","separate reasoning run"],rule:"critic cannot author evidence or override hard constraints"},
 {id:"session-learning-observer",owner:"memory-curator",input:"anonymous session contract + outcomes",output:"evaluation/training observations",tools:["match_sessions","match_outcomes"],rule:"no cross-session personalization or learned reranker without consent, validation volume and calibration"},
] as const;
