import type { DestinationInsightsResponse, DestinationResearchPlace, DestinationResearchSource, DestinationResearchReview } from "@/lib/decision/types";

type ResearchJson={overview?:string;things_to_do?:Array<{name?:string;summary?:string;why_it_fits?:string;evidence_strength?:"HIGH"|"MEDIUM"|"LOW"}>;food_local_life?:Array<{name?:string;summary?:string;why_it_fits?:string;evidence_strength?:"HIGH"|"MEDIUM"|"LOW";kind?:"food"|"local_life"}>;review_pulse?:Array<{title?:string;summary?:string;evidence_strength?:"HIGH"|"MEDIUM"|"LOW"}>;practical_notes?:string[]};
type DeepSeekResponse={choices?:Array<{message?:{content?:string|null}}>};
type WikiSearch={query?:{search?:Array<{title?:string}>}}; type WikiExtract={query?:{pages?:Array<{title?:string;extract?:string}>}};
const clean=(v:unknown,max=420)=>typeof v==="string"?v.trim().slice(0,max):"";
const slug=(v:string)=>v.replace(/ /g,"_");
async function wikiSource(host:string,query:string,maxChars:number):Promise<{title:string;text:string;url:string}|null>{try{const search=new URL(`https://${host}/w/api.php`);search.search=new URLSearchParams({action:"query",list:"search",srsearch:query,srlimit:"1",format:"json",formatversion:"2",origin:"*"}).toString();const s=await fetch(search,{next:{revalidate:86400},signal:AbortSignal.timeout(3500)});if(!s.ok)return null;const sj=await s.json() as WikiSearch,title=sj.query?.search?.[0]?.title;if(!title)return null;const extract=new URL(`https://${host}/w/api.php`);extract.search=new URLSearchParams({action:"query",prop:"extracts",explaintext:"1",redirects:"1",titles:title,format:"json",formatversion:"2",origin:"*"}).toString();const e=await fetch(extract,{next:{revalidate:86400},signal:AbortSignal.timeout(4000)});if(!e.ok)return null;const ej=await e.json() as WikiExtract,row=ej.query?.pages?.[0],text=clean(row?.extract,maxChars);if(!text)return null;return{title:row?.title??title,text,url:`https://${host}/wiki/${encodeURIComponent(slug(row?.title??title))}`}}catch{return null}}
function parseJson(raw:string):ResearchJson{const cleaned=raw.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim(),a=cleaned.indexOf("{"),b=cleaned.lastIndexOf("}");if(a<0||b<=a)throw new Error("Invalid research JSON");return JSON.parse(cleaned.slice(a,b+1)) as ResearchJson}
function place(item:NonNullable<ResearchJson["things_to_do"]>[number],i:number,category:"ATTRACTION"|"RESTAURANT"|"OTHER"):DestinationResearchPlace|null{const name=clean(item.name,140),summary=clean(item.summary,280);if(!name||!summary)return null;return{id:`research-${i}-${name.toLowerCase().replace(/[^a-z0-9α-ωάέήίόύώϊϋ]+/gi,"-").slice(0,36)}`,name,category,summary,whyItFits:clean(item.why_it_fits,180)||null,evidenceStrength:item.evidence_strength??"MEDIUM",rating:null,reviewCount:null,imageUrl:null,address:null,distanceKm:null,attribution:"Wikivoyage/Wikipedia synthesis"}}
function pulse(item:NonNullable<ResearchJson["review_pulse"]>[number],i:number):DestinationResearchReview|null{const t=clean(item.summary,320);if(!t)return null;return{id:`pulse-${i}`,title:clean(item.title,100)||"Travel guide pulse",text:t,rating:null,publishedDate:null,author:"Travel Guru research",evidenceStrength:item.evidence_strength??"MEDIUM"}}

export async function researchDestination(input:{destination:string;latitude?:number|null;longitude?:number|null;language?:"el"|"en";travelerType?:string|null;moods?:string[];nights?:number|null}):Promise<DestinationInsightsResponse>{
  const key=process.env.DEEPSEEK_API_KEY;if(!key)return{source:"research-pending",destination:input.destination,researchedAt:new Date().toISOString(),overview:null,restaurants:[],attractions:[],reviews:[],practicalNotes:[],sources:[],attributionRequired:false};
  const [voy,wiki]=await Promise.all([wikiSource(input.language==="en"?"en.wikivoyage.org":"el.wikivoyage.org",input.destination,4200),wikiSource(input.language==="en"?"en.wikipedia.org":"el.wikipedia.org",input.destination,2600)]);
  const raw=[voy,wiki].filter((x):x is NonNullable<typeof x>=>Boolean(x));if(!raw.length)return{source:"unavailable",destination:input.destination,researchedAt:new Date().toISOString(),overview:null,restaurants:[],attractions:[],reviews:[],practicalNotes:[],sources:[],attributionRequired:false};
  const sources:DestinationResearchSource[]=raw.map(x=>({title:x.title,url:x.url,domain:new URL(x.url).hostname,sourceType:"web"}));
  const sourceText=raw.map((x,i)=>`SOURCE ${i+1} ${x.title}:\n${x.text}`).join("\n\n").slice(0,7600);
  const language=input.language==="en"?"English":"Greek",model=process.env.DEEPSEEK_RESEARCH_MODEL||"deepseek-v4-flash",base=process.env.DEEPSEEK_BASE_URL||"https://api.deepseek.com";
  const system="Use only supplied travel source text. Synthesize compactly. Never invent businesses, ratings, rankings, prices or opening hours. If specific restaurants are not evidenced, return local food themes instead. JSON only; no chain-of-thought.";
  const prompt=`Destination=${input.destination}; language=${language}; traveler=${input.travelerType??"unknown"}; moods=${(input.moods??[]).join(",")}; nights=${input.nights??"unknown"}. Return up to 5 things_to_do, 5 food/local-life items, 3 source-synthesis themes and 5 practical notes as {"overview":"...","things_to_do":[{"name":"...","summary":"...","why_it_fits":"...","evidence_strength":"HIGH|MEDIUM|LOW"}],"food_local_life":[{"name":"...","kind":"food|local_life","summary":"...","why_it_fits":"...","evidence_strength":"HIGH|MEDIUM|LOW"}],"review_pulse":[{"title":"...","summary":"...","evidence_strength":"HIGH|MEDIUM|LOW"}],"practical_notes":["..."]}.\n${sourceText}`;
  try{const response=await fetch(`${base}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,messages:[{role:"system",content:system},{role:"user",content:prompt}],thinking:{type:"enabled"},reasoning_effort:"high",response_format:{type:"json_object"},max_tokens:720}),signal:AbortSignal.timeout(9000)});if(!response.ok)throw new Error("research failed");const payload=await response.json() as DeepSeekResponse,content=payload.choices?.[0]?.message?.content;if(!content)throw new Error("empty research");const data=parseJson(content);const attractions=(data.things_to_do??[]).map((x,i)=>place(x,i,"ATTRACTION")).filter((x):x is DestinationResearchPlace=>Boolean(x)).slice(0,5);const restaurants=(data.food_local_life??[]).map((x,i)=>place(x as NonNullable<ResearchJson["things_to_do"]>[number],i,x.kind==="food"?"RESTAURANT":"OTHER")).filter((x):x is DestinationResearchPlace=>Boolean(x)).slice(0,5);const reviews=(data.review_pulse??[]).map(pulse).filter((x):x is DestinationResearchReview=>Boolean(x)).slice(0,3);return{source:"verified-synthesis",destination:input.destination,researchedAt:new Date().toISOString(),overview:clean(data.overview,600)||null,restaurants,attractions,reviews,practicalNotes:Array.isArray(data.practical_notes)?data.practical_notes.map(x=>clean(x,180)).filter(Boolean).slice(0,5):[],sources,attributionRequired:false}}catch{return{source:"unavailable",destination:input.destination,researchedAt:new Date().toISOString(),overview:null,restaurants:[],attractions:[],reviews:[],practicalNotes:[],sources,attributionRequired:false}}
}
