import type {JsonRecord,V70Locale} from "@/lib/ai/travel-intelligence-v70";

export type JourneyRowV70={id:string;session_id:string|null;profile_key:string|null;auth_user_id:string|null;locale:V70Locale;journey_slug:string;destination_key:string;destination_name:string;stay_place_id:string|null;status:string;trip_context:JsonRecord;itinerary:JsonRecord;evidence_refs:unknown[];live_state:JsonRecord;pdf_object_path:string|null;pdf_filename:string|null;email_status:string;email_to:string|null;created_at:string;updated_at:string};
const base=()=>process.env.NEXT_PUBLIC_SUPABASE_URL??process.env.SUPABASE_URL??"https://bgvgstpoypqbjnemqcqp.supabase.co";
const key=()=>process.env.SUPABASE_SERVICE_ROLE_KEY??"";
function h(extra:Record<string,string>={}){const k=key();if(!k)throw new Error("SUPABASE_SERVICE_ROLE_KEY is required");return{apikey:k,Authorization:`Bearer ${k}`,"content-type":"application/json",...extra}}
async function parse<T>(r:Response):Promise<T>{if(!r.ok)throw new Error(`V70 journey store ${r.status}: ${(await r.text()).slice(0,400)}`);return await r.json() as T}
export async function createJourneyV70(input:{sessionId:string;profileKey:string|null;authUserId?:string|null;locale:V70Locale;journeySlug:string;destinationKey:string;destinationName:string;stayPlaceId:string;tripContext:JsonRecord;itinerary:JsonRecord;evidenceRefs:unknown[];pdfFilename:string}){
 const r=await fetch(`${base().replace(/\/$/,"")}/rest/v1/travel_journeys_v70`,{method:"POST",headers:h({Prefer:"return=representation"}),body:JSON.stringify({session_id:input.sessionId,profile_key:input.profileKey,auth_user_id:input.authUserId??null,locale:input.locale,journey_slug:input.journeySlug,destination_key:input.destinationKey,destination_name:input.destinationName,stay_place_id:input.stayPlaceId,status:"ready",trip_context:input.tripContext,itinerary:input.itinerary,evidence_refs:input.evidenceRefs,live_state:{},pdf_filename:input.pdfFilename}),cache:"no-store",signal:AbortSignal.timeout(6000)});const rows=await parse<JourneyRowV70[]>(r);if(!rows[0])throw new Error("Journey insert returned no row");return rows[0]
}
export async function loadJourneyBySlugV70(slug:string){const r=await fetch(`${base().replace(/\/$/,"")}/rest/v1/travel_journeys_v70?journey_slug=eq.${encodeURIComponent(slug)}&select=*&limit=1`,{headers:h(),cache:"no-store",signal:AbortSignal.timeout(5000)});return(await parse<JourneyRowV70[]>(r))[0]??null}
export async function loadJourneyByIdV70(id:string){const r=await fetch(`${base().replace(/\/$/,"")}/rest/v1/travel_journeys_v70?id=eq.${encodeURIComponent(id)}&select=*&limit=1`,{headers:h(),cache:"no-store",signal:AbortSignal.timeout(5000)});return(await parse<JourneyRowV70[]>(r))[0]??null}
export async function updateJourneyV70(id:string,patch:Partial<Pick<JourneyRowV70,"status"|"live_state"|"pdf_object_path"|"pdf_filename"|"email_status"|"email_to"|"itinerary">>){const r=await fetch(`${base().replace(/\/$/,"")}/rest/v1/travel_journeys_v70?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:h({Prefer:"return=representation"}),body:JSON.stringify({...patch,updated_at:new Date().toISOString()}),cache:"no-store",signal:AbortSignal.timeout(5000)});const rows=await parse<JourneyRowV70[]>(r);if(!rows[0])throw new Error("Journey update returned no row");return rows[0]}
export function journeyFilenameV70(destination:string,startDate?:unknown,endDate?:unknown){const clean=destination.normalize("NFKD").replace(/[^\p{L}\p{N}]+/gu,"_").replace(/^_+|_+$/g,"").slice(0,50)||"Greece";const start=typeof startDate==="string"?startDate:"Trip",end=typeof endDate==="string"?endDate:"";return `TravelAI_${clean}_Journey_${start}${end?`_to_${end}`:""}.pdf`}
export function journeySlugV70(destination:string,startDate?:unknown){const clean=destination.normalize("NFKD").toLowerCase().replace(/[^a-z0-9\p{L}]+/gu,"-").replace(/^-+|-+$/g,"").slice(0,50)||"greece";const date=typeof startDate==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(startDate)?startDate: new Date().toISOString().slice(0,10);return `${clean}-${date}-${crypto.randomUUID().slice(0,8)}`}
