import type {JsonRecord,V70Locale} from "@/lib/ai/travel-intelligence-v70";
import {callV70Backend} from "@/lib/ai/v70-supabase-gateway";

export type JourneyRowV70={id:string;session_id:string|null;profile_key:string|null;auth_user_id:string|null;locale:V70Locale;journey_slug:string;destination_key:string;destination_name:string;stay_place_id:string|null;status:string;trip_context:JsonRecord;itinerary:JsonRecord;evidence_refs:unknown[];live_state:JsonRecord;pdf_object_path:string|null;pdf_filename:string|null;email_status:string;email_to:string|null;created_at:string;updated_at:string};
export async function createJourneyV70(input:{sessionId:string;profileKey:string|null;authUserId?:string|null;locale:V70Locale;journeySlug:string;destinationKey:string;destinationName:string;stayPlaceId:string;tripContext:JsonRecord;itinerary:JsonRecord;evidenceRefs:unknown[];pdfFilename:string}){
 const rows=await callV70Backend<JourneyRowV70[]>("create_journey",{row:{session_id:input.sessionId,profile_key:input.profileKey,auth_user_id:input.authUserId??null,locale:input.locale,journey_slug:input.journeySlug,destination_key:input.destinationKey,destination_name:input.destinationName,stay_place_id:input.stayPlaceId,status:"ready",trip_context:input.tripContext,itinerary:input.itinerary,evidence_refs:input.evidenceRefs,live_state:{},pdf_filename:input.pdfFilename}},6000);if(!rows[0])throw new Error("Journey insert returned no row");return rows[0]
}
export async function loadJourneyBySlugV70(slug:string){const rows=await callV70Backend<JourneyRowV70[]>("load_journey_by_slug",{slug},5000);return rows[0]??null}
export async function loadJourneyByIdV70(id:string){const rows=await callV70Backend<JourneyRowV70[]>("load_journey_by_id",{id},5000);return rows[0]??null}
export async function updateJourneyV70(id:string,patch:Partial<Pick<JourneyRowV70,"status"|"live_state"|"pdf_object_path"|"pdf_filename"|"email_status"|"email_to"|"itinerary">>){const rows=await callV70Backend<JourneyRowV70[]>("update_journey",{id,patch},5000);if(!rows[0])throw new Error("Journey update returned no row");return rows[0]}
export function journeyFilenameV70(destination:string,startDate?:unknown,endDate?:unknown){const clean=destination.normalize("NFKD").replace(/[^\p{L}\p{N}]+/gu,"_").replace(/^_+|_+$/g,"").slice(0,50)||"Greece";const start=typeof startDate==="string"?startDate:"Trip",end=typeof endDate==="string"?endDate:"";return `TravelAI_${clean}_Journey_${start}${end?`_to_${end}`:""}.pdf`}
export function journeySlugV70(destination:string,startDate?:unknown){const clean=destination.normalize("NFKD").toLowerCase().replace(/[^a-z0-9\p{L}]+/gu,"-").replace(/^-+|-+$/g,"").slice(0,50)||"greece";const date=typeof startDate==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(startDate)?startDate:new Date().toISOString().slice(0,10);return `${clean}-${date}-${crypto.randomUUID().slice(0,8)}`}
