import {asRecord,asRecordArray,asString,asStringArray,qualitativeConfidence,runAgentJsonV70} from "@/lib/ai/agentic-model-v70";
import {createJourneyV70,journeyFilenameV70,journeySlugV70,updateJourneyV70,type JourneyRowV70} from "@/lib/ai/journey-store-v70";
import {createTrackingActionV70,loadStayInventoryV70,publicStayV70,type StayInventoryV70} from "@/lib/ai/stay-commerce-v70";
import {appendFunnelTurnV70,loadAgentProfilesV70,loadCandidateUniverseV70,loadDestinationBundleV70,loadFunnelTurnsV70,updateFunnelSessionV70,type FunnelSessionV70,type JsonRecord} from "@/lib/ai/travel-intelligence-v70";
import {loadWeatherContextsV70} from "@/lib/ai/weather-context-v70";

export type JourneyDayV70={day:number;date:string|null;title:string;rhythm:string;morning:string;afternoon:string;evening:string;food:string;mobility:string;planB:string;uncertainty:string;evidenceRefs:string[]};
export type JourneyMapPinV70={entityId:string;name:string;type:string;latitude:number|null;longitude:number|null;why:string;evidenceRefs:string[]};
export type JourneyPlanV70={headline:string;summary:string;stayLogic:string;routeLogic:string;days:JourneyDayV70[];mapPins:JourneyMapPinV70[];bookingSequence:string[];practicalNotes:string[];uncertainties:string[];confidence:"low"|"medium"|"high";evidenceRefs:string[]};
export type BuiltJourneyV70={journey:JourneyRowV70;plan:JourneyPlanV70;destination:{key:string;slug:string;name:string};stay:ReturnType<typeof publicStayV70>;trackingCode:string;model:string};
const iso=/^\d{4}-\d{2}-\d{2}$/;
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:null}
function validatePlan(value:JsonRecord):JourneyPlanV70|null{
 const days=asRecordArray(value.days,21).map((x,index):JourneyDayV70=>({day:Math.max(1,Math.min(99,Math.trunc(Number(x.day)||index+1))),date:iso.test(asString(x.date,10))?asString(x.date,10):null,title:asString(x.title,220),rhythm:asString(x.rhythm,500),morning:asString(x.morning,900),afternoon:asString(x.afternoon,900),evening:asString(x.evening,900),food:asString(x.food,700),mobility:asString(x.mobility,650),planB:asString(x.planB,650),uncertainty:asString(x.uncertainty,500),evidenceRefs:asStringArray(x.evidenceRefs,30)}));
 const mapPins=asRecordArray(value.mapPins,80).map((x):JourneyMapPinV70=>({entityId:asString(x.entityId,180),name:asString(x.name,220),type:asString(x.type,80),latitude:n(x.latitude),longitude:n(x.longitude),why:asString(x.why,600),evidenceRefs:asStringArray(x.evidenceRefs,20)})).filter(x=>x.name);
 const headline=asString(value.headline,260),summary=asString(value.summary,1600);
 if(!headline||!summary||!days.length||days.some(x=>!x.title||(!x.morning&&!x.afternoon&&!x.evening)))return null;
 return{headline,summary,stayLogic:asString(value.stayLogic,1100),routeLogic:asString(value.routeLogic,1100),days,mapPins,bookingSequence:asStringArray(value.bookingSequence,20),practicalNotes:asStringArray(value.practicalNotes,30),uncertainties:asStringArray(value.uncertainties,30),confidence:qualitativeConfidence(value.confidence),evidenceRefs:asStringArray(value.evidenceRefs,120)};
}
function curatedProducts(turns:Awaited<ReturnType<typeof loadFunnelTurnsV70>>){for(const turn of [...turns].reverse()){const choices=asRecordArray(asRecord(turn.structured_extract).stayChoices,8);if(choices.length)return new Set(choices.map(x=>asString(x.sourceProductId,180)).filter(Boolean))}return new Set<string>()}
function refs(plan:JourneyPlanV70){return[...new Set([...plan.evidenceRefs,...plan.days.flatMap(x=>x.evidenceRefs),...plan.mapPins.flatMap(x=>x.evidenceRefs)])].slice(0,300)}

export async function buildJourneyV70(input:{session:FunnelSessionV70;sourceProductId:string}):Promise<BuiltJourneyV70>{
 const session=input.session,selectedKey=session.chosen_destination_key;
 if(!selectedKey||!["selected","journey"].includes(session.status))throw new Error("V70 session is not ready for journey finalization");
 const [profiles,turns,bundle,universe]=await Promise.all([loadAgentProfilesV70(),loadFunnelTurnsV70(session.id,50),loadDestinationBundleV70([selectedKey],session.locale,12,120),loadCandidateUniverseV70(session.locale,574)]);
 const curated=curatedProducts(turns);if(!curated.size||!curated.has(input.sourceProductId))throw new Error("Selected stay is not one of the curated session choices");
 const destination=asRecord(bundle.destinations[0]),slug=asString(destination.canonicalSlug,160),name=asString(destination.name,220);if(!slug||!name)throw new Error("Selected destination could not be resolved");
 const inventory=await loadStayInventoryV70(slug,160),stay=inventory.find(x=>x.source_product_id===input.sourceProductId);if(!stay||!stay.place_id||!stay.tracking_url)throw new Error("Selected stay is no longer in truthful destination inventory");
 const node=universe.find(x=>x.node_key===selectedKey),start=asString(session.current_context.startDate,10),end=asString(session.current_context.endDate,10),weather=node&&iso.test(start)&&iso.test(end)&&Date.parse(end)>Date.parse(start)?await loadWeatherContextsV70([node],{startDate:start,endDate:end,locale:session.locale,limit:1}):[];
 const agent=profiles.get("journey-synthesizer");if(!agent)throw new Error("Missing journey-synthesizer profile");
 const safeStay={sourceProductId:stay.source_product_id,placeId:stay.place_id,propertyName:stay.property_name,locationLabel:stay.location_label,description:stay.description?.slice(0,900)??null,price:stay.price,currency:stay.currency,availability:stay.in_stock===false?"unavailable":stay.availability??"provider-confirm",validTo:stay.valid_to,latitude:stay.latitude,longitude:stay.longitude,semanticText:stay.semantic_text?.slice(0,900)??null,semanticTags:stay.semantic_tags,travelerFit:stay.traveler_fit,evidenceScore:stay.evidence_score};
 const prompt=`TRAVELLER CONTEXT:\n${JSON.stringify(session.current_context)}\nSELECTED DESTINATION:\n${JSON.stringify(destination)}\nSELECTED STAY (affiliate URL deliberately withheld from reasoning):\n${JSON.stringify(safeStay)}\nWEATHER EVIDENCE:\n${JSON.stringify(weather)}\nDESTINATION KNOWLEDGE:\n${JSON.stringify({entities:bundle.entities.slice(0,110),facts:bundle.facts.slice(0,190),edges:bundle.edges.slice(0,240)})}\n\nBuild the final 360-degree journey for this traveller. Use the selected stay as the spatial anchor. Respect dates, companions, psychology, mobility, pace, food interests, weather, geography and evidence. Compose realistic days rather than a checklist. Never invent opening hours, transport schedules, ratings, availability or amenities. When a detail is not verified, state uncertainty or a plan-B rather than fabricating it. Return one JSON object with: headline,summary,stayLogic,routeLogic,days[] (day,date,title,rhythm,morning,afternoon,evening,food,mobility,planB,uncertainty,evidenceRefs[]),mapPins[] (entityId,name,type,latitude,longitude,why,evidenceRefs[]),bookingSequence[],practicalNotes[],uncertainties[],confidence(low|medium|high),evidenceRefs[]. Keep the result useful and compact enough for a mobile itinerary/PDF.`;
 const run=await runAgentJsonV70({profile:agent,prompt,validate:validatePlan,maxOutputTokens:5200,timeoutMs:25000});
 const plan=run.value,journeySlug=journeySlugV70(name,start),pdfFilename=journeyFilenameV70(name,start,end),tracking=await createTrackingActionV70({sessionId:session.id,actionType:"stay",subjectKey:stay.place_id,trackingUrl:stay.tracking_url,metadata:{journeySlug,destinationKey:selectedKey,destinationSlug:slug,sourceProductId:stay.source_product_id}});
 const evidenceRefs=refs(plan),created=await createJourneyV70({sessionId:session.id,profileKey:session.profile_key,authUserId:session.auth_user_id,locale:session.locale,journeySlug,destinationKey:selectedKey,destinationName:name,stayPlaceId:stay.place_id,tripContext:session.current_context,itinerary:plan as unknown as JsonRecord,evidenceRefs,pdfFilename});
 const liveState={destinationSlug:slug,selectedStay:publicStayV70(stay,session.locale),selectedSourceProductId:stay.source_product_id,trackingAction:{id:tracking.id,code:tracking.code},journeyModel:run.modelLabel};
 const journey=await updateJourneyV70(created.id,{live_state:liveState});
 await updateFunnelSessionV70(session.id,{status:"journey",chosen_stay_id:stay.place_id,model_trace:{...session.model_trace,journeyModel:run.modelLabel,journeyId:journey.id}});
 await appendFunnelTurnV70({sessionId:session.id,role:"system_event",content:`Journey finalized: ${name} · ${stay.property_name}`,stage:"journey",structuredExtract:{journeyId:journey.id,journeySlug,stayPlaceId:stay.place_id,sourceProductId:stay.source_product_id,trackingCode:tracking.code},evidenceRefs});
 return{journey,plan,destination:{key:selectedKey,slug,name},stay:publicStayV70(stay,session.locale),trackingCode:tracking.code,model:run.modelLabel};
}
