import { createLLMRequestBudgetV16,generateJsonWithRoutingV16,type LLMRequestBudgetV16 } from "@/lib/ai/model-router-v9";
import { scoreEvidenceTextV23 } from "@/lib/ai/locality-evidence-reranker-v23";
import type { LocalityProfileV23 } from "@/lib/data/locality-profiles-v23";
import { buildFuzzyContractV23,compactFuzzyContractV23 } from "@/lib/decision/fuzzy-semantic-v23";
import type { V8IntentProfile } from "@/lib/decision/v8-types";
import type { V8Ranked } from "@/lib/decision/v8-matcher";
import type { TripRequest } from "@/lib/validation/trip";

type SourceEvidence={title:string;domain:string;url:string;snippet:string};
type CandidateEvidence={candidateSlug:string;localityId:string;localityLabel:string;sources:SourceEvidence[]};
type AIScore={candidateSlug:string;fit:number;confidence:number};
export interface LocalityEvidenceAuditV24{ran:boolean;source:"ai"|"deterministic-evidence"|"no-evidence";inspectedCandidates:string[];inspectedLocalities:string[];evidenceDomains:string[];scoreByCandidate:Record<string,number>;model:string|null;}
const clamp01=(v:number)=>Math.max(0,Math.min(1,v)),clamp100=(v:number)=>Math.max(0,Math.min(100,v));
const clean=(value:unknown,max=4000)=>typeof value==="string"?value.replace(/\s+/g," ").trim().slice(0,max):"";
const slugTitle=(value:string)=>value.replace(/ /g,"_");
async function wikiEvidence(host:string,query:string):Promise<SourceEvidence|null>{try{const url=new URL(`https://${host}/w/api.php`);url.search=new URLSearchParams({action:"query",generator:"search",gsrsearch:query,gsrlimit:"1",prop:"extracts",explaintext:"1",redirects:"1",format:"json",formatversion:"2",origin:"*"}).toString();const response=await fetch(url,{cache:"no-store",signal:AbortSignal.timeout(3500)});if(!response.ok)return null;const payload=await response.json() as {query?:{pages?:Array<{title?:string;extract?:string}>}},page=payload.query?.pages?.[0],title=clean(page?.title,160),snippet=clean(page?.extract,4000);if(!title||!snippet)return null;return{title,domain:host,url:`https://${host}/wiki/${encodeURIComponent(slugTitle(title))}`,snippet};}catch{return null}}
function recall(ranked:V8Ranked[],localities:LocalityProfileV23[]){const byId=new Map(localities.map(x=>[x.localityId,x] as const)),out:Array<{item:V8Ranked;locality:LocalityProfileV23}>=[];for(const item of ranked){const id=item.destination.localityId;if(!id)continue;const locality=byId.get(id);if(!locality)continue;out.push({item,locality});if(out.length>=20)break}return out;}
async function collectEvidence(request:TripRequest,candidates:ReturnType<typeof recall>):Promise<CandidateEvidence[]>{const rows=await Promise.all(candidates.map(async({item,locality})=>{const q=`${locality.locationLabel} Greece`,[el,en,voyage]=await Promise.all([wikiEvidence("el.wikipedia.org",q),wikiEvidence("en.wikipedia.org",q),wikiEvidence("en.wikivoyage.org",q)]),sources=[request.language==="el"?el:en,request.language==="el"?en:el,voyage].filter((x):x is SourceEvidence=>Boolean(x));return{candidateSlug:item.destination.slug,localityId:locality.localityId,localityLabel:locality.locationLabel,sources};}));return rows.filter(row=>row.sources.length>0);}
export function applyLocalityEvidenceScoresV24(ranked:V8Ranked[],scoreByCandidate:Record<string,number>){return ranked.map(item=>{const evidence=scoreByCandidate[item.destination.slug];if(!Number.isFinite(evidence))return item;const conviction=Math.min(1,Math.abs(evidence-50)/50),evidenceWeight=.08+.44*conviction,score=clamp100(item.score*(1-evidenceWeight)+evidence*evidenceWeight),preScore=clamp100(item.preScore*(1-evidenceWeight)+evidence*evidenceWeight);return{...item,score,preScore}}).sort((a,b)=>b.score-a.score)}
export async function runLocalityEvidenceRerankerV24(request:TripRequest,intent:V8IntentProfile,ranked:V8Ranked[],localities:LocalityProfileV23[],budget:LLMRequestBudgetV16=createLLMRequestBudgetV16()):Promise<{ranked:V8Ranked[];audit:LocalityEvidenceAuditV24}>{const candidates=recall(ranked,localities),evidence=await collectEvidence(request,candidates);if(!evidence.length)return{ranked,audit:{ran:false,source:"no-evidence",inspectedCandidates:[],inspectedLocalities:[],evidenceDomains:[],scoreByCandidate:{},model:null}};const contract=intent.semantic24??buildFuzzyContractV23(request,intent.semantic),deterministic:Record<string,number>={};for(const row of evidence){const text=row.sources.map(x=>x.snippet).join(" "),score=scoreEvidenceTextV23(text,contract),raw=score.fit*100-score.negativeConflict*12;deterministic[row.candidateSlug]=clamp100(50+(raw-50)*score.confidence)}
 const payload=evidence.map(row=>({candidateSlug:row.candidateSlug,locality:row.localityLabel,evidence:row.sources.map(s=>({domain:s.domain,text:s.snippet.slice(0,1900)}))})),routed=await generateJsonWithRoutingV16<AIScore[]>({context:{task:"research",text:request.tripText,deterministicConfidence:intent.semantic24?.confidence??intent.semantic?.confidence??.7,forceSemantic:true,preferReasoner:true},budget,preference:"critical",system:`You are a locality evidence reranker. Score ONLY supplied candidateSlug values against the supplied traveller contract. Use ONLY supplied evidence text; do not use model memory. Missing evidence is uncertainty, not rejection. Strong negative criteria reduce fit. Priority criteria matter more than secondary preferences. Return JSON only: {"scores":[{"candidateSlug":"...","fit":0..1,"confidence":0..1}]}.`,prompt:JSON.stringify({contract:compactFuzzyContractV23(contract),candidates:payload}),validate(raw){const rows=Array.isArray(raw.scores)?raw.scores:[],out:AIScore[]=[];for(const row of rows){if(!row||typeof row!=="object")continue;const r=row as Record<string,unknown>,candidateSlug=typeof r.candidateSlug==="string"?r.candidateSlug:"",fit=Number(r.fit),confidence=Number(r.confidence);if(candidateSlug&&Number.isFinite(fit)&&Number.isFinite(confidence)&&ranked.some(x=>x.destination.slug===candidateSlug))out.push({candidateSlug,fit:clamp01(fit),confidence:clamp01(confidence)});}return out.length?out:null;}}),scoreByCandidate={...deterministic};if(routed){for(const row of routed.value){const ai=50+(row.fit*100-50)*row.confidence,base=deterministic[row.candidateSlug];scoreByCandidate[row.candidateSlug]=Number.isFinite(base)?clamp100(base*.35+ai*.65):clamp100(ai)}}return{ranked:applyLocalityEvidenceScoresV24(ranked,scoreByCandidate),audit:{ran:true,source:routed?"ai":"deterministic-evidence",inspectedCandidates:evidence.map(x=>x.candidateSlug),inspectedLocalities:evidence.map(x=>x.localityLabel),evidenceDomains:[...new Set(evidence.flatMap(x=>x.sources.map(s=>s.domain)))],scoreByCandidate,model:routed?.label??null}};}
