import { createLLMRequestBudgetV16,generateJsonWithRoutingV16,type LLMRequestBudgetV16 } from "@/lib/ai/model-router-v9";
import type { LocalityProfileV23 } from "@/lib/data/locality-profiles-v23";
import { buildFuzzyContractV23,compactFuzzyContractV23,fuzzyVectorFitV23 } from "@/lib/decision/fuzzy-semantic-v23";
import { V23_SEMANTIC_DIMENSIONS,type V23FuzzyIntentContract,type V23SemanticDimension,type V8IntentProfile } from "@/lib/decision/v8-types";
import type { V8Ranked } from "@/lib/decision/v8-matcher";
import type { TripRequest } from "@/lib/validation/trip";

type SourceEvidence={title:string;domain:string;url:string;snippet:string};
type CandidateEvidence={slug:string;localityLabel:string;sources:SourceEvidence[]};
type AIScore={slug:string;fit:number;confidence:number};
export interface LocalityEvidenceAuditV23{ran:boolean;source:"ai"|"deterministic-evidence"|"no-evidence";inspectedLocalities:string[];evidenceDomains:string[];scoreBySlug:Record<string,number>;model:string|null;}
const clamp01=(v:number)=>Math.max(0,Math.min(1,v)),clamp100=(v:number)=>Math.max(0,Math.min(100,v));
const clean=(value:unknown,max=3500)=>typeof value==="string"?value.replace(/\s+/g," ").trim().slice(0,max):"";
const slugTitle=(value:string)=>value.replace(/ /g,"_");
async function wikiEvidence(host:string,query:string):Promise<SourceEvidence|null>{try{const url=new URL(`https://${host}/w/api.php`);url.search=new URLSearchParams({action:"query",generator:"search",gsrsearch:query,gsrlimit:"1",prop:"extracts",explaintext:"1",redirects:"1",format:"json",formatversion:"2",origin:"*"}).toString();const response=await fetch(url,{cache:"no-store",signal:AbortSignal.timeout(3500)});if(!response.ok)return null;const payload=await response.json() as {query?:{pages?:Array<{title?:string;extract?:string}>}},page=payload.query?.pages?.[0],title=clean(page?.title,160),snippet=clean(page?.extract,3500);if(!title||!snippet)return null;return{title,domain:host,url:`https://${host}/wiki/${encodeURIComponent(slugTitle(title))}`,snippet};}catch{return null}}
const conceptTerms:Partial<Record<V23SemanticDimension,RegExp[]>>={
 food:[/\b(?:cuisine|food|restaurant|tavern|gastronom|wine|local dish|culinary)\w*/gi,/φαγητ|γαστρονομ|ταβερν|κρασι/gi],
 culture:[/\b(?:museum|archaeolog|ancient|historic|heritage|castle|fortress|old town|byzantine|unesco|monument)\w*/gi,/μουσει|αρχαιο|ιστορ|κληρονομ|καστρ|παλια πολη|βυζαντ/gi],
 nature:[/\b(?:mountain|forest|gorge|lake|river|waterfall|national park|hiking|trail|landscape|wetland)\w*/gi,/βουνο|δασ|φαραγγ|λιμν|ποταμ|καταρρακ|πεζοπορ|μονοπατ/gi],
 nightlife:[/\b(?:nightlife|night club|nightclub|bar|party|club scene)\w*/gi,/νυχτεριν|μπαρ|παρτι/gi],
 beach_season:[/\b(?:beach|coast|seaside|swimming|bay|shore)\w*/gi,/παραλι|ακτ|θαλασσ|μπανι/gi],
 city:[/\b(?:city centre|city center|urban|neighbou?rhood|metro|downtown|pedestrian)\w*/gi,/κεντρο πολ|αστικ|γειτονι|πεζοδρομ/gi],
 relax:[/\b(?:quiet|peaceful|relax|tranquil|slow pace|small village)\w*/gi,/ησυχ|ηρεμ|χαλαρ|χωριο/gi],
 adventure:[/\b(?:hiking|climbing|diving|kayak|rafting|cycling|outdoor activit)\w*/gi,/πεζοπορ|αναρριχ|καταδυ|δραστηριοτ/gi],
 wellness:[/\b(?:spa|thermal|wellness|hot spring)\w*/gi,/σπα|ιαματικ|ευεξ/gi],
 romantic:[/\b(?:romantic|sunset|picturesque|scenic)\w*/gi,/ρομαντ|ηλιοβασιλ|γραφικ/gi],
};
function evidenceMembership(text:string,dimension:V23SemanticDimension){const terms=conceptTerms[dimension];if(!terms?.length)return null;let hits=0;for(const pattern of terms){pattern.lastIndex=0;hits+=(text.match(pattern)?.length??0);}if(!hits)return 0;return clamp01(.32+Math.log2(1+hits)*.18);}
export function scoreEvidenceTextV23(text:string,contract:V23FuzzyIntentContract){let sum=0,weights=0,negativeConflict=0,negativeWeight=0;const priorities=new Map(contract.priorities.slice(0,4).map((d,i)=>[d,[2.1,1.6,1.3,1.15][i]]));for(const d of V23_SEMANTIC_DIMENSIONS){const membership=evidenceMembership(text,d);if(membership==null)continue;const p=clamp01(contract.positive[d]??0),n=clamp01(contract.negative[d]??0),priority=priorities.get(d)??1;if(p>=.12){const w=p*priority;sum+=membership*w;weights+=w;}if(n>=.12){const w=n*(n>=.85?1.35:1);sum+=(1-membership)*w;weights+=w;negativeConflict+=membership*w;negativeWeight+=w;}}return{fit:weights?clamp01(sum/weights):.5,confidence:weights?clamp01(.35+Math.min(.6,weights*.12)):.2,negativeConflict:negativeWeight?negativeConflict/negativeWeight:0};}
function localityRecall(request:TripRequest,intent:V8IntentProfile,localities:LocalityProfileV23[]){const contract=intent.semantic24??buildFuzzyContractV23(request,intent.semantic),rows=localities.filter(x=>Boolean(x.canonicalSlug)).map(locality=>{const fit=fuzzyVectorFitV23(locality.semanticVector,contract),confidence=.45+.55*locality.profileConfidence,score=.5+(fit.fit-.5)*confidence;return{locality,score};}).sort((a,b)=>b.score-a.score),perSlug=new Map<string,number>(),selected:LocalityProfileV23[]=[];for(const row of rows){const count=perSlug.get(row.locality.canonicalSlug)??0;if(count>=2)continue;selected.push(row.locality);perSlug.set(row.locality.canonicalSlug,count+1);if(selected.length>=18)break;}return selected;}
async function collectEvidence(request:TripRequest,candidates:LocalityProfileV23[]):Promise<CandidateEvidence[]>{const rows=await Promise.all(candidates.map(async locality=>{const primary=request.language==="en"?"en.wikipedia.org":"el.wikipedia.org",query=`${locality.locationLabel} Greece`,[wiki,voyage]=await Promise.all([wikiEvidence(primary,query),wikiEvidence("en.wikivoyage.org",query)]),sources=[wiki,voyage].filter((x):x is SourceEvidence=>Boolean(x));return{slug:locality.canonicalSlug,localityLabel:locality.locationLabel,sources};}));return rows.filter(row=>row.sources.length>0);}
export function applyLocalityEvidenceScoresV23(ranked:V8Ranked[],scoreBySlug:Record<string,number>){return ranked.map(item=>{const evidence=scoreBySlug[item.destination.slug];if(!Number.isFinite(evidence))return item;const delta=Math.max(-10,Math.min(10,(evidence-50)*.20));return{...item,score:clamp100(item.score+delta),preScore:clamp100(item.preScore+delta)};}).sort((a,b)=>b.score-a.score)}
export async function runLocalityEvidenceRerankerV23(request:TripRequest,intent:V8IntentProfile,ranked:V8Ranked[],localities:LocalityProfileV23[],budget:LLMRequestBudgetV16=createLLMRequestBudgetV16()):Promise<{ranked:V8Ranked[];audit:LocalityEvidenceAuditV23}>{const recall=localityRecall(request,intent,localities),evidence=await collectEvidence(request,recall);if(!evidence.length)return{ranked,audit:{ran:false,source:"no-evidence",inspectedLocalities:[],evidenceDomains:[],scoreBySlug:{},model:null}};const contract=intent.semantic24??buildFuzzyContractV23(request,intent.semantic),bySlug=new Map<string,Array<{fit:number;confidence:number;negativeConflict:number}>>();for(const row of evidence){const text=row.sources.map(x=>x.snippet).join(" "),score=scoreEvidenceTextV23(text,contract),list=bySlug.get(row.slug)??[];list.push(score);bySlug.set(row.slug,list);}const deterministic:Record<string,number>={};for(const [slug,list] of bySlug){const best=[...list].sort((a,b)=>b.confidence-a.confidence||b.fit-a.fit)[0],raw=(best.fit*100-best.negativeConflict*10);deterministic[slug]=clamp100(50+(raw-50)*best.confidence);}
 const payload=evidence.map(row=>({slug:row.slug,locality:row.localityLabel,evidence:row.sources.map(s=>({domain:s.domain,text:s.snippet.slice(0,1800)}))})),routed=await generateJsonWithRoutingV16<AIScore[]>({context:{task:"research",text:request.tripText,deterministicConfidence:intent.semantic24?.confidence??intent.semantic?.confidence??.7,forceSemantic:true,preferReasoner:true},budget,preference:"critical",system:`You are a locality evidence reranker. Score ONLY the supplied candidate slugs against the supplied 24D traveller contract. Use only supplied evidence text. Do not use model memory. Missing evidence is uncertainty, not rejection. Return JSON only: {"scores":[{"slug":"...","fit":0..1,"confidence":0..1}]}. Strong negative criteria must reduce fit. Priority criteria matter more than secondary preferences.`,prompt:JSON.stringify({contract:compactFuzzyContractV23(contract),candidates:payload}),validate(raw){const rows=Array.isArray(raw.scores)?raw.scores:[];const out:AIScore[]=[];for(const row of rows){if(!row||typeof row!=="object")continue;const r=row as Record<string,unknown>,slug=typeof r.slug==="string"?r.slug:"",fit=Number(r.fit),confidence=Number(r.confidence);if(slug&&Number.isFinite(fit)&&Number.isFinite(confidence)&&ranked.some(x=>x.destination.slug===slug))out.push({slug,fit:clamp01(fit),confidence:clamp01(confidence)});}return out.length?out:null;}}),scoreBySlug={...deterministic};if(routed){for(const row of routed.value){const ai=50+(row.fit*100-50)*row.confidence,base=deterministic[row.slug];scoreBySlug[row.slug]=Number.isFinite(base)?clamp100(base*.35+ai*.65):clamp100(ai);}}
 return{ranked:applyLocalityEvidenceScoresV23(ranked,scoreBySlug),audit:{ran:true,source:routed?"ai":"deterministic-evidence",inspectedLocalities:evidence.map(x=>x.localityLabel),evidenceDomains:[...new Set(evidence.flatMap(x=>x.sources.map(s=>s.domain)))],scoreBySlug,model:routed?.label??null}};}
