import type { TripRequest } from "@/lib/validation/trip";
import type { V8Ranked } from "@/lib/decision/v8-matcher";
import { createLLMRequestBudgetV16,generateJsonWithRoutingV16,type LLMRequestBudgetV16 } from "@/lib/ai/model-router-v9";

type Verify={pass?:boolean;reason?:string;reject_slugs?:string[]};
function needs(ranked:V8Ranked[]){if(ranked.length<8)return false;const top=ranked.slice(0,6);if(top.some(x=>x.breakdown.season<48||x.breakdown.routeConfidence<62))return true;if(Math.abs(ranked[5].score-ranked[6].score)<1.4)return true;if(Math.abs(ranked[0].score-ranked[1].score)<1.2)return true;return false}
export async function verifyV8(request:TripRequest,ranked:V8Ranked[],budget:LLMRequestBudgetV16=createLLMRequestBudgetV16()):Promise<{checked:boolean;passed:boolean;reason:string|null;rejectSlugs:string[];model:string|null}>{
 if(!needs(ranked))return{checked:false,passed:true,reason:null,rejectSlugs:[],model:null};
 const candidates=ranked.slice(0,10).map((x,i)=>({rank:i+1,slug:x.destination.slug,name:x.destination.nameEn,score:Math.round(x.score),intent:x.breakdown.intent,season:x.breakdown.season,effort:x.breakdown.effort,duration:x.breakdown.duration,budget:x.breakdown.budget,weather:x.breakdown.weather,traveler:x.breakdown.traveler,route:x.breakdown.routeConfidence,tags:x.destination.tags}));
 const hardLanguage=/(?:μονο|χωρις|οπωσδηποτε|\b(?:only|mono|without|must)\b)/i.test(request.tripText??""),veryWeak=ranked.slice(0,6).some(x=>x.breakdown.season<40||x.breakdown.routeConfidence<50),nearTie=Math.abs(ranked[0].score-ranked[1].score)<.65,severe=hardLanguage&&veryWeak&&nearTie;
 const system="You are a final consistency checker, not a travel planner. Numeric and supplied evidence are authoritative. Never invent flights, prices, weather, hotels, attractions or availability.";
 const prompt=`Check only whether any of ranks 1-6 is clearly dominated by ranks 7-10 for this request. Reject only obvious inconsistencies. Request=${JSON.stringify({origin:request.origin,dates:[request.startDate,request.endDate],nights:request.nights,totalBudget:request.budget,groupSize:request.groupSize,moods:request.moods,traveler:request.travelerType,energy:request.desiredEnergy,social:request.socialPreference,mustHave:request.mustHave,distance:request.distancePreference,avoid:request.avoid,freeText:request.tripText??null})}. Candidates=${JSON.stringify(candidates)}. Return JSON only: {"pass":true|false,"reason":"max 120 chars","reject_slugs":["slug"]}.`;
 const routed=await generateJsonWithRoutingV16<Verify>({context:{task:"verification",text:request.tripText,deterministicConfidence:severe?.35:veryWeak?.68:.78,hardConstraintRisk:severe,contradictorySignals:veryWeak&&nearTie},budget,system,prompt,preference:"critical",validate(value){const pass=value.pass!==false,reason=typeof value.reason==="string"?value.reason.slice(0,140):undefined,reject_slugs=Array.isArray(value.reject_slugs)?value.reject_slugs.filter((x):x is string=>typeof x==="string"&&ranked.some(item=>item.destination.slug===x)).slice(0,2):[];return{pass,reason,reject_slugs};}});
 if(!routed)return{checked:false,passed:true,reason:null,rejectSlugs:[],model:null};
 return{checked:true,passed:routed.value.pass!==false,reason:routed.value.reason??null,rejectSlugs:routed.value.reject_slugs??[],model:routed.label};
}
