import type { TripRequest } from "@/lib/validation/trip";
import type { V8Ranked } from "@/lib/decision/v8-matcher";

type Verify={pass?:boolean;reason?:string;reject_slugs?:string[]};
function needs(ranked:V8Ranked[]){if(ranked.length<8)return false;const top=ranked.slice(0,6);if(top.some(x=>x.breakdown.season<48||x.breakdown.routeConfidence<62))return true;if(Math.abs(ranked[5].score-ranked[6].score)<1.4)return true;if(Math.abs(ranked[0].score-ranked[1].score)<1.2)return true;return false}
function text(payload:unknown){const p=payload as {output_text?:string;output?:Array<{content?:Array<{text?:string}>}>};if(typeof p.output_text==="string")return p.output_text;return(p.output??[]).flatMap(x=>x.content??[]).map(x=>x.text??"").join("\n")}
function parse(raw:string):Verify{const s=raw.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim(),a=s.indexOf("{"),b=s.lastIndexOf("}");if(a<0||b<=a)return{pass:true};try{return JSON.parse(s.slice(a,b+1)) as Verify}catch{return{pass:true}}}

export async function verifyV8(request:TripRequest,ranked:V8Ranked[]):Promise<{checked:boolean;passed:boolean;reason:string|null;rejectSlugs:string[];model:string|null}>{
 const key=process.env.OPENAI_API_KEY;if(!key||!needs(ranked))return{checked:false,passed:true,reason:null,rejectSlugs:[],model:null};
 const model=process.env.OPENAI_VERIFY_MODEL||"gpt-5.4-nano";
 const candidates=ranked.slice(0,10).map((x,i)=>({rank:i+1,slug:x.destination.slug,name:x.destination.nameEn,score:Math.round(x.score),intent:x.breakdown.intent,season:x.breakdown.season,effort:x.breakdown.effort,duration:x.breakdown.duration,budget:x.breakdown.budget,weather:x.breakdown.weather,traveler:x.breakdown.traveler,route:x.breakdown.routeConfidence,tags:x.destination.tags}));
 const prompt=`You are a cheap final consistency checker, not a travel planner. The numeric evidence is authoritative. Check only whether any of ranks 1-6 is clearly dominated by ranks 7-10 for this request. Do not invent flights, prices, weather, hotels or attractions. Reject only obvious inconsistencies. Request: origin=${request.origin}; dates=${request.startDate}..${request.endDate}; nights=${request.nights}; totalBudget=${request.budget}; groupSize=${request.groupSize}; moods=${request.moods.join(",")}; traveler=${request.travelerType}; energy=${request.desiredEnergy}; social=${request.socialPreference}; mustHave=${request.mustHave}; distance=${request.distancePreference}; avoid=${request.avoid}. Candidates=${JSON.stringify(candidates)}. Return JSON only: {"pass":true|false,"reason":"max 120 chars","reject_slugs":["slug"]}.`;
 try{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,input:prompt,reasoning:{effort:"minimal"},max_output_tokens:180,store:false}),signal:AbortSignal.timeout(4500)});if(!response.ok)return{checked:false,passed:true,reason:null,rejectSlugs:[],model:null};const p=parse(text(await response.json()));return{checked:true,passed:p.pass!==false,reason:typeof p.reason==="string"?p.reason.slice(0,140):null,rejectSlugs:Array.isArray(p.reject_slugs)?p.reject_slugs.filter(x=>typeof x==="string").slice(0,2):[],model}}catch{return{checked:false,passed:true,reason:null,rejectSlugs:[],model:null}}
}
