import type { GuruRecommendation } from "@/lib/decision/types";
import type { TripRequest } from "@/lib/validation/trip";
import { deterministicGuruFallback, type RankedAffiliateCandidate } from "@/lib/decision/affiliate-engine";

type GuruJson={picks?:Array<{destination_id?:string;role?:string;why_this_place?:string;why_now?:string;tags?:string[];confidence?:"HIGH"|"MEDIUM"|"LOW"}>};
type DeepSeekResponse={choices?:Array<{message?:{content?:string|null;reasoning_content?:string|null}}>};
const clean=(v:unknown,max=220)=>typeof v==="string"?v.trim().slice(0,max):"";
const roles=new Set(["GURU PICK","WEATHER FIT","LUXURY DEPTH","BEST VALUE","EASY ESCAPE","ROMANTIC FIT","STRONG DEAL SIGNAL","SMART ALTERNATIVE","WILDCARD"]);
function config(){return{apiKey:process.env.DEEPSEEK_API_KEY,baseUrl:process.env.DEEPSEEK_BASE_URL||"https://api.deepseek.com",model:process.env.DEEPSEEK_MODEL||"deepseek-v4-pro",effort:process.env.DEEPSEEK_REASONING_EFFORT==="max"?"max":"high"} as const}
function priceLabel(item:RankedAffiliateCandidate){const c=item.candidate;if(c.minPrice==null)return"Price not supplied";const prefix=c.currency?`${c.currency} `:"feed price ";return`${prefix}${Math.round(c.minPrice)}${c.medianPrice!=null&&c.medianPrice!==c.minPrice?`–${Math.round(c.medianPrice)}`:""}`}
function build(item:RankedAffiliateCandidate,pick:NonNullable<GuruJson["picks"]>[number],index:number):GuruRecommendation{const c=item.candidate,rawRole=clean(pick.role,40).toUpperCase(),role=roles.has(rawRole)?rawRole:index===0?"GURU PICK":"SMART ALTERNATIVE",confidence=pick.confidence==="HIGH"||pick.confidence==="MEDIUM"||pick.confidence==="LOW"?pick.confidence:c.activeOfferCount>=8&&c.weather?.confidence!=="LOW"?"HIGH":c.activeOfferCount>=4?"MEDIUM":"LOW",tags=Array.isArray(pick.tags)?pick.tags.map(t=>clean(t,28).toLowerCase()).filter(Boolean).slice(0,4):[];return{destinationId:c.destinationId,destination:c.locationLabel,country:c.countryHint??"Feed location",role,score:Math.round(item.score),confidence,whyThisPlace:clean(pick.why_this_place)||`${c.locationLabel} fits the selected date range, weather and travel profile.`,whyNow:clean(pick.why_now)||`${c.activeOfferCount} active tracked offers overlap the exact dates.`,tags:tags.length?tags:["weather-screened","feed-backed"],imageUrl:c.heroImageUrl,feedPriceLabel:priceLabel(item),propertyCount:c.propertyCount,activeOfferCount:c.activeOfferCount,fiveStarOfferCount:c.fiveStarOfferCount,alternativeOfferCount:c.alternativeOfferCount,demandScore:Math.round(c.demandScore),maxDiscount:c.maxDiscount,latitude:c.latitude,longitude:c.longitude,distanceKm:item.distanceKm==null?null:Math.round(item.distanceKm),breakdown:item.breakdown,offers:c.topOffers.slice(0,5),weather:c.weather}}
function norm(v:string){return v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zα-ω0-9]+/gi," ").trim()}
function overlaps(a:string,b:string){const x=norm(a),y=norm(b);if(x===y||x.includes(y)||y.includes(x))return true;const xa=x.split(" ").filter(v=>v.length>4),ya=y.split(" ").filter(v=>v.length>4);return xa.filter(v=>ya.includes(v)).length>=2}

const SYSTEM=`You are Travel Guru, a senior travel decision agent. Select only IDs supplied by the deterministic engine. Facts are authoritative; you cannot override date validity, weather evidence, star evidence, prices or affiliate availability. Never invent flights, ferries, weather, ratings or currency. Choose exactly five distinct places. Prefer user fit and weather/seasonality over commercial depth. Commercial signals break close ties only. Return concise JSON; never expose chain-of-thought.`;

export async function runTravelGuru(request:TripRequest,ranked:RankedAffiliateCandidate[]):Promise<{mode:"travel-guru-deepseek"|"deterministic-affiliate-fallback";recommendations:GuruRecommendation[]}>{
  const fallback=deterministicGuruFallback(request,ranked),c=config();if(!c.apiKey||ranked.length<5)return{mode:"deterministic-affiliate-fallback",recommendations:fallback};
  const shortlist=ranked.slice(0,12);
  const data=shortlist.map(({candidate,score,distanceKm,breakdown})=>({id:candidate.destinationId,place:candidate.locationLabel,score:Math.round(score),km:distanceKm==null?null:Math.round(distanceKm),b:breakdown,weather:candidate.weather?{source:candidate.weather.source,score:candidate.weather.score,min:candidate.weather.temperatureMinC,max:candidate.weather.temperatureMaxC,rain:candidate.weather.precipitationMmDay,sun:candidate.weather.sunSignal,summary:candidate.weather.summary}:null,period:{offers:candidate.activeOfferCount,stars5:candidate.fiveStarOfferCount,priceMin:candidate.minPrice,priceMedian:candidate.medianPrice,currency:candidate.currency,demandSignal:Math.round(candidate.demandScore)},hint:(candidate.semanticText??"").slice(0,320)}));
  const outputLanguage=request.language==="en"?"English":"Greek";
  const prompt=`TRIP ${request.startDate} to ${request.endDate}; origin=${request.origin}; nights=${request.nights}; budget_signal=${request.budget}; moods=${request.moods.join(",")}; traveler=${request.travelerType}; distance=${request.distancePreference}; pace=${request.pace}; hotel=${request.hotelStyle}; avoid=${request.avoid}.\nCANDIDATES=${JSON.stringify(data)}\nChoose exactly 5 distinct IDs in best order. Weather and seasonality are already scored by deterministic evidence: do not promote a materially worse-weather destination merely because it has more offers. Period demandSignal is only a feed signal from offers overlapping these dates, not a market-wide demand claim. Write why_this_place and why_now in ${outputLanguage}. Return {"picks":[{"destination_id":"id","role":"GURU PICK|WEATHER FIT|LUXURY DEPTH|BEST VALUE|EASY ESCAPE|ROMANTIC FIT|STRONG DEAL SIGNAL|SMART ALTERNATIVE|WILDCARD","why_this_place":"short","why_now":"short","tags":["tag","tag"],"confidence":"HIGH|MEDIUM|LOW"},...5]}.`;
  try{const response=await fetch(`${c.baseUrl}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${c.apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:c.model,messages:[{role:"system",content:SYSTEM},{role:"user",content:prompt}],reasoning_effort:c.effort,thinking:{type:"enabled"},response_format:{type:"json_object"},max_tokens:950}),signal:AbortSignal.timeout(18000)});if(!response.ok)return{mode:"deterministic-affiliate-fallback",recommendations:fallback};const payload=await response.json() as DeepSeekResponse,content=payload.choices?.[0]?.message?.content;if(!content)return{mode:"deterministic-affiliate-fallback",recommendations:fallback};const parsed=JSON.parse(content) as GuruJson;if(!Array.isArray(parsed.picks)||parsed.picks.length!==5)return{mode:"deterministic-affiliate-fallback",recommendations:fallback};const ids=parsed.picks.map(p=>clean(p.destination_id,80));if(new Set(ids).size!==5)return{mode:"deterministic-affiliate-fallback",recommendations:fallback};const lookup=new Map(shortlist.map(item=>[item.candidate.destinationId,item]));if(ids.some(id=>!lookup.has(id)))return{mode:"deterministic-affiliate-fallback",recommendations:fallback};const selected=ids.map(id=>lookup.get(id) as RankedAffiliateCandidate);for(let i=0;i<selected.length;i++)for(let j=i+1;j<selected.length;j++)if(overlaps(selected[i].candidate.locationLabel,selected[j].candidate.locationLabel))return{mode:"deterministic-affiliate-fallback",recommendations:fallback};return{mode:"travel-guru-deepseek",recommendations:parsed.picks.map((pick,index)=>build(selected[index],pick,index))}}catch{return{mode:"deterministic-affiliate-fallback",recommendations:fallback}}
}
