import { interpretIntentV8 } from "@/lib/ai/intent-v8";
import { verifyV8 } from "@/lib/ai/openai-verifier-v8";
import { auditAndRepairV24 } from "@/lib/ai/result-auditor-v24";
import { applyResearchScoutRanking,runRecommendationResearchAgent } from "@/lib/ai/recommendation-research-agent-v14";
import { writeRecommendationAudit,writeRecommendationAuditError } from "@/lib/ai/recommendation-audit";
import { runTravelCouncilV9 } from "@/lib/ai/travel-council-v9";
import { runtimeAgentRoles } from "@/lib/ai/agent-roles-v15";
import { createLLMRequestBudgetV16 } from "@/lib/ai/model-router-v9";
import { runLocalityEvidenceRerankerV24,applyLocalityEvidenceScoresV24 } from "@/lib/ai/locality-evidence-reranker-v24";
import { fullContinuity } from "@/lib/continuity";
import { loadV8DestinationCatalog } from "@/lib/data/destination-v8";
import { loadLocalityProfilesV23 } from "@/lib/data/locality-profiles-v23";
import { recordV8RecommendationSession } from "@/lib/data/match-learning-v8";
import { enrichV8Weather } from "@/lib/data/weather-v8";
import { screenResearchEvidence } from "@/lib/decision/research-intent-v13";
import { buildSmartDateWindows } from "@/lib/decision/date-windows-v9";
import { canonicalRankingInputsV19 } from "@/lib/decision/canonical-ranking-v19";
import { semanticNeedsClarificationV19 } from "@/lib/ai/semantic-policy-v19";
import { filterPortfolioV21 } from "@/lib/decision/choice-correctness-v21";
import { applyChoiceCorrectnessV24 } from "@/lib/decision/choice-correctness-v24";
import { applyLocalityNativeRankingV24 } from "@/lib/decision/locality-native-ranking-v24";
import { buildLocalityCandidateCatalogV24 } from "@/lib/decision/locality-candidate-v24";
import { diversifyV24,finalRankV24,preRankV24,responseFeasibilityV24,toRecommendationsV24 } from "@/lib/decision/v24-matcher";
import { interpretStayConstraintsV16 } from "@/lib/ai/stay-constraint-interpreter-v16";
import type { V8RecommendationResponse } from "@/lib/decision/v8-types";
import type { V8Ranked } from "@/lib/decision/v8-matcher";
import type { TripRequest } from "@/lib/validation/trip";

export type TravelOrchestratorEvent={type:string;progress:number;payload?:Record<string,unknown>};
export type TravelOrchestratorEmitter=(event:TravelOrchestratorEvent)=>void;
export class TravelDecisionErrorV24 extends Error{constructor(public readonly status:number,public readonly publicMessage:string,public readonly stage:string){super(publicMessage);this.name="TravelDecisionErrorV24"}}
const noop:TravelOrchestratorEmitter=()=>{};
function repair(selected:V8Ranked[],pool:V8Ranked[],reject:string[]){if(!reject.length)return selected;const bad=new Set(reject);return diversifyV24(pool.filter(item=>!bad.has(item.destination.slug)),12)}
function profileSummary(trip:TripRequest){if(trip.language==="en"){const energy=trip.desiredEnergy==="restore"?"restoration":trip.desiredEnergy==="stimulating"?"energy and discovery":"balance",social=trip.socialPreference==="quiet"?"a quiet rhythm":trip.socialPreference==="lively"?"lively energy":"a flexible social rhythm";return `${energy}, ${social}, ${trip.nights} nights, ${trip.groupSize} travellers`;}const energy=trip.desiredEnergy==="restore"?"αποφόρτιση":trip.desiredEnergy==="stimulating"?"ένταση και ανακάλυψη":"ισορροπία",social=trip.socialPreference==="quiet"?"ήσυχο ρυθμό":trip.socialPreference==="lively"?"ζωντανή ενέργεια":"ευέλικτο κοινωνικό ρυθμό";return `${energy}, ${social}, ${trip.nights} νύχτες, ${trip.groupSize} ταξιδιώτες`;}
function noResult(trip:TripRequest){return trip.language==="en"?"I could not verify a locality and stay combination that satisfies those constraints for the selected dates.":"Δεν μπόρεσα να επιβεβαιώσω συνδυασμό περιοχής και διαμονής που να καλύπτει αυτά τα κριτήρια στις επιλεγμένες ημερομηνίες."}

export async function runTravelOrchestratorV24(trip:TripRequest,sessionId:string,emit:TravelOrchestratorEmitter=noop):Promise<V8RecommendationResponse>{const started=Date.now(),timings:Record<string,number>={},roles=runtimeAgentRoles().map(role=>role.id),llmBudget=createLLMRequestBudgetV16();let stage="start",last=started;const mark=(name:string)=>{const now=Date.now();timings[name]=now-last;last=now;stage=name};const signal=(type:string,progress:number,payload:Record<string,unknown>={})=>emit({type,progress,payload});try{
 signal("understand:start",7,{hasFreeText:Boolean(trip.tripText),agent:"semantic-formulator"});signal("locality:start",10,{agent:"locality-retriever"});stage="intent+localities";
 const[intent,stayRequirements,canonical,localities]=await Promise.all([interpretIntentV8(trip,llmBudget),interpretStayConstraintsV16(trip.tripText,llmBudget),loadV8DestinationCatalog(),loadLocalityProfilesV23(trip.startDate,trip.endDate).catch(()=>[])]);mark("intent+localities");
 if(localities.length<20)throw new TravelDecisionErrorV24(503,trip.language==="en"?"The dated locality inventory is not complete enough to make a reliable decision.":"Το διαθέσιμο locality inventory για αυτές τις ημερομηνίες δεν είναι αρκετά πλήρες για αξιόπιστη απόφαση.","locality-retrieval");
 const hasHardSemanticContext=Boolean(stayRequirements.hard.length||stayRequirements.soft.length);if(semanticNeedsClarificationV19(intent,trip.tripText,hasHardSemanticContext))throw new TravelDecisionErrorV24(422,trip.language==="en"?"I could not formulate the free-text note with enough confidence. Add one concrete preference or exclusion.":"Δεν μπόρεσα να διατυπώσω το ελεύθερο κείμενο με αρκετή βεβαιότητα. Πρόσθεσε μία συγκεκριμένη προτίμηση ή εξαίρεση.","intent-clarification");
 const localityCatalog=buildLocalityCandidateCatalogV24(canonical.filter(d=>d.countryCode==="GR"),localities),{hardConstraint,constrainedCatalog,rankingTrip}=canonicalRankingInputsV19(trip,localityCatalog);signal("understand:ready",21,{summary:intent.summary,semanticSource:intent.source,formulationModel:intent.formulationModel??"deterministic",priorities:intent.semantic24?.priorities??[],agent:"semantic-formulator"});signal("locality:ready",30,{localityCount:localities.length,localityOnly:localities.filter(x=>!x.canonicalSlug).length,safeParents:localities.filter(x=>Boolean(x.canonicalSlug)).length,agent:"locality-retriever"});
 stage="fuzzy-recall";const base=preRankV24(rankingTrip,intent,constrainedCatalog,100),fuzzy=applyLocalityNativeRankingV24(trip,intent,base,localities);mark("fuzzy-recall");signal("choice:recall",37,{agent:"fuzzy-matcher",candidates:fuzzy.ranked.length,exactLocality:fuzzy.audit.candidatesWithExactLocality,localityOnly:fuzzy.audit.localityOnlyCandidates});
 stage="locality-evidence";const evidencePre=await runLocalityEvidenceRerankerV24(trip,intent,fuzzy.ranked,localities,llmBudget);mark("locality-evidence");signal("research:locality",44,{agent:"locality-evidence-reranker",ran:evidencePre.audit.ran,source:evidencePre.audit.source,checked:evidencePre.audit.inspectedLocalities.length});
 stage="choice-correctness";const choice=await applyChoiceCorrectnessV24(trip,intent,stayRequirements,evidencePre.ranked.slice(0,48)),minimum=(hardConstraint||stayRequirements.hard.length)?1:3,pre=choice.ranked.slice(0,30);mark("choice-correctness");signal("choice:ready",51,{agent:"locality-choice-gate",checkedLocalities:choice.audit.checkedLocalities,hardStayRejected:choice.audit.hardStayRejected.length,retrievalFailed:choice.audit.retrievalFailed.length});if(pre.length<minimum)throw new TravelDecisionErrorV24(422,noResult(trip),"choice-correctness");
 signal("shortlist:ready",56,{preview:pre.slice(0,7).map(x=>({locality:x.destination.localityLabel??x.destination.nameEl,parent:x.destination.canonicalParentSlug??null})),agent:"orchestrator"});
 stage="weather";signal("weather:start",60,{candidates:Math.min(14,pre.length),agent:"season-route"});const weather=await enrichV8Weather(trip,pre.map(x=>x.destination),14),weatherBase=finalRankV24(rankingTrip,intent,pre,weather),weatherFuzzy=applyLocalityNativeRankingV24(trip,intent,weatherBase,localities),weatherRanked=applyLocalityEvidenceScoresV24(weatherFuzzy.ranked,evidencePre.audit.scoreByCandidate);mark("weather");signal("weather:ready",70,{checked:weather.size,agent:"season-route"});
 stage="stored-evidence";const research=await screenResearchEvidence(trip,weatherRanked,18);mark("stored-evidence");signal("research:start",73,{agent:"research-scout"});stage="research-scout";const researchScout=await runRecommendationResearchAgent(trip,research.ranked,llmBudget),ranked=applyResearchScoutRanking(research.ranked,researchScout);mark("research-scout");signal("research:ready",82,{webBacked:researchScout.ran,checked:researchScout.inspectedSlugs.length,confidence:researchScout.confidence,agent:"research-scout"});
 const selected=diversifyV24(ranked,12),selectedIds=new Set(selected.map(x=>x.destination.slug)),verifyPool=[...selected,...ranked.filter(x=>!selectedIds.has(x.destination.slug))].slice(0,18);signal("verify:start",86,{agent:"skeptical-auditor"});stage="verifier";const verification=await verifyV8(trip,verifyPool,llmBudget),fixed=verification.checked&&!verification.passed?repair(selected,ranked,verification.rejectSlugs):selected;mark("verifier");stage="auditor";const audited=await auditAndRepairV24(trip,fixed,ranked,12,research.evidence,llmBudget);mark("auditor");if(!audited.audit.passed||!audited.items.length)throw new TravelDecisionErrorV24(422,trip.language==="en"?"There is not enough verified evidence for those criteria and dates yet.":"Δεν υπάρχουν ακόμη επαρκή επαληθευμένα στοιχεία για αυτά τα κριτήρια και τις ημερομηνίες.","auditor");
 signal("council:start",92,{agent:"traveler-advocate"});stage="council";const councilPool=filterPortfolioV21(audited.items),council=await runTravelCouncilV9(trip,councilPool,llmBudget),ordered=council.agreement==="STRONG"?[...councilPool].sort((a,b)=>a.destination.slug===council.finalSlug?-1:b.destination.slug===council.finalSlug?1:0):councilPool;mark("council");signal("council:ready",97,{agreement:council.agreement,publicCandidates:councilPool.length,agent:"traveler-advocate"});
 const recommendations=toRecommendationsV24(trip,ordered).map(x=>({...x,dateWindows:buildSmartDateWindows(trip,x)})),{formulationModel:_model,interpretedText:_text,...publicIntent}=intent;void _model;void _text;const publicStayRequirements={...stayRequirements,source:"deterministic" as const,needsSemanticAssist:false},result:V8RecommendationResponse={version:9,experienceVersion:16,request:trip,generatedAt:new Date().toISOString(),source:"verified-travel-knowledge",intent:publicIntent,stayRequirements:publicStayRequirements,catalogSize:localityCatalog.length,eligibleCount:ranked.length,explorationCount:Math.max(0,recommendations.length-3),mode:"guided",resultCount:recommendations.length,profileSummary:profileSummary(trip),feasibility:responseFeasibilityV24(ordered),council,continuity:fullContinuity(),recommendations};
 stage="learning";await recordV8RecommendationSession(sessionId,trip,intent,recommendations,stayRequirements).catch(()=>false);mark("learning");writeRecommendationAudit({sessionId,status:"success",stage:"final-v24",timingsMs:{...timings,total:Date.now()-started},intentSource:intent.source,hardConstraint:hardConstraint?.id??null,stayRequirements:{hard:stayRequirements.hard,soft:stayRequirements.soft,source:stayRequirements.source,formulationModel:intent.formulationModel??"deterministic",localityNative:fuzzy.audit,localityEvidence:evidencePre.audit,choiceCorrectness:choice.audit},llmBudget:llmBudget.snapshot(),catalogSize:localityCatalog.length,preCandidates:pre.slice(0,8).map(item=>item.destination.slug),researchScout:{ran:researchScout.ran,source:researchScout.source,inspectedSlugs:researchScout.inspectedSlugs,preferredSlugs:researchScout.preferredSlugs,rejectSlugs:researchScout.rejectSlugs,confidence:researchScout.confidence,evidenceDomains:researchScout.evidenceDomains},verifier:{checked:verification.checked,passed:verification.passed,rejectSlugs:verification.rejectSlugs,model:verification.model},auditor:{passed:audited.audit.passed,confidence:audited.audit.confidence,attempts:audited.audit.attempts,checkedBy:audited.audit.checkedBy,roles},council:{agreement:council.agreement,finalSlug:council.finalSlug},finalSlugs:recommendations.slice(0,6).map(item=>item.slug)});return result;
 }catch(error){if(error instanceof TravelDecisionErrorV24)throw error;writeRecommendationAuditError(sessionId,stage,error,{...timings,total:Date.now()-started});throw error;}}
