import { createHash } from "node:crypto";
import { NextResponse } from "next/server";
import { loadV8StayOffers } from "@/lib/data/destination-v8";
import { parseTripRequest } from "@/lib/validation/trip";

export const runtime="nodejs";
export const dynamic="force-dynamic";
export const maxDuration=60;
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/,slugPattern=/^[a-z0-9-]{2,80}$/,safeId=/^[a-zA-Z0-9:_-]{1,180}$/,iso=/^\d{4}-\d{2}-\d{2}$/;
const rate=new Map<string,{count:number;until:number}>();
function escapeHtml(value:string){return value.replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[ch]??ch)}
function limited(key:string){const now=Date.now(),current=rate.get(key);if(!current||current.until<now){rate.set(key,{count:1,until:now+10*60_000});return false}current.count++;return current.count>3}

export async function POST(request:Request){
 const body=await request.json().catch(()=>null) as Record<string,unknown>|null,email=typeof body?.email==="string"?body.email.trim().toLowerCase():"",slug=typeof body?.slug==="string"?body.slug.trim().toLowerCase():"",start=typeof body?.start==="string"?body.start:"",end=typeof body?.end==="string"?body.end:"",offerId=typeof body?.offer==="string"?body.offer:"",language=body?.language==="en"?"en":"el";
 if(!emailPattern.test(email)||email.length>180||!slugPattern.test(slug)||!safeId.test(offerId)||!iso.test(start)||!iso.test(end)||Date.parse(end)<=Date.parse(start))return NextResponse.json({ok:false,delivery:"download"},{status:400});
 const clientKey=`${request.headers.get("x-forwarded-for")?.split(",")[0]??"unknown"}:${createHash("sha256").update(email).digest("hex").slice(0,12)}`;if(limited(clientKey))return NextResponse.json({ok:false,delivery:"download"},{status:429});
 const offers=await loadV8StayOffers(slug,start,end,60).catch(()=>[]),selected=offers.find(item=>item.sourceProductId===offerId&&item.trackingUrl.startsWith("https://go.linkwi.se/")&&item.trackingUrl.includes("/CD104/"));if(!selected)return NextResponse.json({ok:false,delivery:"download"},{status:404});
 const resendKey=process.env.RESEND_API_KEY,from=process.env.TRAVEL_GUIDE_FROM_EMAIL;
 const parsedTrip=parseTripRequest(body?.trip),tripToken=parsedTrip.success&&parsedTrip.data.startDate===start&&parsedTrip.data.endDate===end?Buffer.from(JSON.stringify(parsedTrip.data),"utf8").toString("base64url"):null,origin=new URL(request.url).origin,guideUrl=new URL("/api/guide",origin);guideUrl.searchParams.set("slug",slug);guideUrl.searchParams.set("start",start);guideUrl.searchParams.set("end",end);guideUrl.searchParams.set("offer",offerId);guideUrl.searchParams.set("lang",language);if(tripToken)guideUrl.searchParams.set("trip",tripToken);
 const guideResponse=await fetch(guideUrl,{cache:"no-store",signal:AbortSignal.timeout(45_000)}).catch(()=>null);if(!guideResponse?.ok||!(guideResponse.headers.get("content-type")??"").includes("application/pdf"))return NextResponse.json({ok:false,delivery:"download"},{status:502});const attachment=Buffer.from(await guideResponse.arrayBuffer()).toString("base64"),downloadUrl=`${guideUrl.pathname}${guideUrl.search}`;if(!resendKey||!from)return NextResponse.json({ok:true,delivery:"download",guideUrl:downloadUrl},{headers:{"cache-control":"no-store","x-escape-book-delivery":"download-fallback"}});const safeDates=`${escapeHtml(start)} – ${escapeHtml(end)}`,safeHotel=escapeHtml(selected.propertyName),safeTracking=escapeHtml(selected.trackingUrl),subject=language==="el"?`Το Escape Book σου είναι έτοιμο · ${start}`:`Your Escape Book is ready · ${start}`;
 const html=language==="el"?`<div style="font-family:Arial,sans-serif;background:#06110f;padding:34px;color:#f7f3ea"><div style="max-width:650px;margin:auto"><p style="color:#8de4dd;font-size:11px;font-weight:800;letter-spacing:.15em">AI ESCAPE STUDIO · 360°</p><h1 style="font-family:Georgia,serif;font-size:42px;line-height:1.02;font-weight:400">Το ταξίδι σου είναι έτοιμο να το πάρεις μαζί.</h1><p style="color:#c2cbc5;line-height:1.7">Επισυνάπτεται το προσωπικό Escape Book για ${safeDates}, με 360° dossier, πηγές, local επιλογές, την επιλεγμένη βάση <strong>${safeHotel}</strong> και QR προς το ακριβές tracking URL.</p><div style="margin:28px 0;padding:18px;border:1px solid #31473e;border-radius:16px"><strong>Η εμπορική ενέργεια είναι ξεχωριστή.</strong><p style="color:#adb9b2;line-height:1.55">Το παρακάτω link είναι affiliate link. Αν προχωρήσεις σε αγορά, ενδέχεται να λάβουμε προμήθεια χωρίς επιπλέον κόστος για εσένα. Τελική τιμή, δωμάτιο και διαθεσιμότητα επιβεβαιώνονται στον πάροχο.</p><a href="${safeTracking}" style="display:inline-block;background:#dfbc7c;color:#122018;text-decoration:none;padding:13px 18px;border-radius:999px;font-weight:800">Δες την τρέχουσα προσφορά στον πάροχο ↗</a></div><p style="font-size:12px;color:#7f9187">Δεν σε προσθέσαμε σε newsletter και δεν θα ακολουθήσει άλλο email από αυτή την αποστολή.</p></div></div>`:`<div style="font-family:Arial,sans-serif;background:#06110f;padding:34px;color:#f7f3ea"><div style="max-width:650px;margin:auto"><p style="color:#8de4dd;font-size:11px;font-weight:800;letter-spacing:.15em">AI ESCAPE STUDIO · 360°</p><h1 style="font-family:Georgia,serif;font-size:42px;line-height:1.02;font-weight:400">Your trip is ready to take with you.</h1><p style="color:#c2cbc5;line-height:1.7">Your personal Escape Book for ${safeDates} is attached, with the 360° dossier, sources, local picks, your selected base <strong>${safeHotel}</strong> and a QR to the exact tracking URL.</p><div style="margin:28px 0;padding:18px;border:1px solid #31473e;border-radius:16px"><strong>The commercial action is separate.</strong><p style="color:#adb9b2;line-height:1.55">The link below is an affiliate link. If you purchase, we may earn a commission at no extra cost to you. Final price, room and live availability are confirmed with the provider.</p><a href="${safeTracking}" style="display:inline-block;background:#dfbc7c;color:#122018;text-decoration:none;padding:13px 18px;border-radius:999px;font-weight:800">View the current provider offer ↗</a></div><p style="font-size:12px;color:#7f9187">You were not added to a newsletter and no other email follows from this send.</p></div></div>`;
 const idempotencyKey=`escape-book-${createHash("sha256").update(`${email}|${slug}|${start}|${end}|${offerId}`).digest("hex").slice(0,32)}`,response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${resendKey}`,"content-type":"application/json","Idempotency-Key":idempotencyKey},body:JSON.stringify({from,to:[email],subject,html,attachments:[{filename:`escape-book-${slug}.pdf`,content:attachment}]}),signal:AbortSignal.timeout(15_000)}).catch(()=>null);if(!response?.ok)return NextResponse.json({ok:false,delivery:"download"},{status:502});return NextResponse.json({ok:true,delivery:"email"},{headers:{"cache-control":"no-store"}})
}
