import { readFile } from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";
import fontkit from "@pdf-lib/fontkit";
import { PDFDocument, PDFFont, PDFImage, PDFPage, rgb } from "pdf-lib";
import QRCode from "qrcode";
import { loadV8DestinationCatalog, loadV8StayOffers } from "@/lib/data/destination-v8";
import { loadDestinationEvidence } from "@/lib/data/evidence-v12";
import type { V8Destination, V8StayOffer } from "@/lib/decision/v8-types";

export const runtime="nodejs";export const dynamic="force-dynamic";
const A4:[number,number]=[595.28,841.89],iso=/^\d{4}-\d{2}-\d{2}$/;
const colors={night:rgb(.025,.078,.14),paper:rgb(.975,.958,.925),white:rgb(1,.995,.98),ink:rgb(.06,.125,.19),cyan:rgb(.2,.84,.91),violet:rgb(.56,.42,1),muted:rgb(.36,.43,.49)};
const themeTags:Record<string,string[]>={romance:["romantic","food","culture"],sea:["beach","warmth","relax"],food:["food","culture","city"],culture:["culture","city","food"],nature:["nature","adventure","relax"],family:["family","beach","nature"],surprise:["shoulder_season","value","nature"]};
const themeNames:Record<string,string>={romance:"Αποδράσεις για δύο",sea:"Θάλασσα χωρίς βιασύνη",food:"Ταξίδια με γεύση",culture:"Πολιτισμός & τοπική ζωή",nature:"Φύση που αλλάζει ρυθμό",family:"Έξυπνες οικογενειακές αποδράσεις",surprise:"Οι απρόσμενες επιλογές του Guru"};

function wrap(text:string,font:PDFFont,size:number,width:number){const lines:string[]=[];let line="";for(const word of text.replace(/\s+/g," ").trim().split(" ")){const candidate=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(candidate,size)<=width)line=candidate;else{if(line)lines.push(line);line=word}}if(line)lines.push(line);return lines}
function drawBlock(page:PDFPage,text:string,font:PDFFont,size:number,x:number,y:number,width:number,color=colors.ink,lineHeight=size*1.45){const lines=wrap(text,font,size,width);lines.forEach((line,index)=>page.drawText(line,{x,y:y-index*lineHeight,size,font,color}));return y-lines.length*lineHeight}
async function photo(pdf:PDFDocument,url?:string|null):Promise<PDFImage|null>{if(!url)return null;try{const response=await fetch(url,{signal:AbortSignal.timeout(5500)});if(!response.ok)return null;const bytes=new Uint8Array(await response.arrayBuffer());return(response.headers.get("content-type")??"").includes("png")?await pdf.embedPng(bytes):await pdf.embedJpg(bytes)}catch{return null}}
function validOffer(offer:V8StayOffer,start:string,end:string){return offer.trackingUrl.startsWith("https://go.linkwi.se/")&&offer.trackingUrl.includes("/CD104/")&&(!offer.validFrom||Date.parse(offer.validFrom)<=Date.parse(`${start}T23:59:59Z`))&&Boolean(offer.validTo)&&Date.parse(offer.validTo as string)>=Date.parse(`${end}T00:00:00Z`)}
function score(destination:V8Destination,month:number,tags:string[]){const affinity=tags.reduce((sum,tag)=>sum+(destination.tags.includes(tag as V8Destination["tags"][number])?1:0),0);return(destination.monthFit[month]??50)*.58+affinity*13-destination.crowdLevel*1.5-destination.costTier}

export async function GET(request:Request){
  const url=new URL(request.url),start=url.searchParams.get("start")??"",end=url.searchParams.get("end")??"",theme=url.searchParams.get("theme")??"surprise";
  if(!iso.test(start)||!iso.test(end)||Date.parse(end)<=Date.parse(start)||!themeTags[theme])return NextResponse.json({error:"Invalid thematic guide request"},{status:400});
  const month=Math.max(0,Math.min(11,Number(start.slice(5,7))-1)),catalog=(await loadV8DestinationCatalog().catch(()=>[])).filter(item=>item.countryCode==="GR").sort((a,b)=>score(b,month,themeTags[theme])-score(a,month,themeTags[theme])).slice(0,14);
  const candidates=(await Promise.all(catalog.map(async destination=>{const offers=(await loadV8StayOffers(destination.slug,start,end,8).catch(()=>[])).filter(item=>validOffer(item,start,end));return offers[0]?{destination,offer:offers[0]}:null}))).filter((item):item is {destination:V8Destination;offer:V8StayOffer}=>item!==null).slice(0,6);
  if(candidates.length<3)return NextResponse.json({error:"Not enough fully valid choices for this period"},{status:404});
  const pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);const[regularBytes,boldBytes]=await Promise.all([readFile(path.join(process.cwd(),"public/fonts/DejaVuSans.ttf")),readFile(path.join(process.cwd(),"public/fonts/DejaVuSans-Bold.ttf"))]),regular=await pdf.embedFont(regularBytes,{subset:true}),bold=await pdf.embedFont(boldBytes,{subset:true});
  const dateLabel=`${new Intl.DateTimeFormat("el-GR",{day:"numeric",month:"long"}).format(new Date(`${start}T12:00:00Z`))} — ${new Intl.DateTimeFormat("el-GR",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${end}T12:00:00Z`))}`;
  const cover=pdf.addPage(A4);cover.drawRectangle({x:0,y:0,width:A4[0],height:A4[1],color:colors.night});cover.drawText("THEMATIC EDITION · ΕΠΙΛΟΓΕΣ ΜΕ ΕΝΕΡΓΟ TRACKING",{x:46,y:790,size:8,font:bold,color:colors.cyan});drawBlock(cover,themeNames[theme],bold,43,46,680,500,colors.white,50);cover.drawText(dateLabel,{x:48,y:570,size:14,font:regular,color:colors.white});drawBlock(cover,`Ο Guru σύγκρινε εποχή, ρυθμό κόσμου, κόστος και διαθέσιμες επιλογές που καλύπτουν ολόκληρο το διάστημα. Κάθε QR οδηγεί στο ακριβές CD104 link της συγκεκριμένης επιλογής.`,regular,15,48,470,480,colors.white,23);cover.drawText(`${candidates.length} ΔΙΑΦΟΡΕΤΙΚΕΣ ΕΠΙΛΟΓΕΣ`,{x:48,y:176,size:11,font:bold,color:colors.cyan});cover.drawText("ΕΛΛΗΝΙΚΟΣ AI TRAVEL GURU",{x:48,y:135,size:18,font:bold,color:colors.white});
  const overview=pdf.addPage(A4);overview.drawRectangle({x:0,y:0,width:A4[0],height:A4[1],color:colors.paper});overview.drawText("Ο ΧΑΡΤΗΣ ΤΗΣ ΑΠΟΦΑΣΗΣ",{x:45,y:782,size:9,font:bold,color:colors.violet});drawBlock(overview,"Διαφορετικοί δρόμοι, ίδιος αυστηρός έλεγχος",bold,30,45,736,500,colors.ink,37);let oy=645;candidates.forEach((item,index)=>{const seasonal=item.destination.monthFit[month]??50;overview.drawText(`0${index+1}`,{x:47,y:oy,size:20,font:bold,color:colors.violet});overview.drawText(item.destination.nameEl,{x:93,y:oy+3,size:14,font:bold,color:colors.ink});overview.drawRectangle({x:290,y:oy+2,width:205,height:8,color:rgb(.84,.84,.84)});overview.drawRectangle({x:290,y:oy+2,width:205*seasonal/100,height:8,color:seasonal>=75?colors.cyan:colors.violet});overview.drawText(`${seasonal}/100`,{x:505,y:oy,size:8,font:bold,color:colors.muted});oy-=67;});drawBlock(overview,"Το score εποχής είναι ένδειξη καταλληλότητας της περιόδου, όχι πρόγνωση καιρού ούτε εγγύηση εμπειρίας.",regular,9,46,164,480,colors.muted,14);
  for(let index=0;index<candidates.length;index+=1){const{destination,offer}=candidates[index];const[evidence,img,qrData]=await Promise.all([loadDestinationEvidence(destination.slug,start,end),photo(pdf,offer.imageUrl||offer.thumbUrl),QRCode.toDataURL(offer.trackingUrl,{errorCorrectionLevel:"H",margin:2,width:420,color:{dark:"#061424",light:"#FFFDF8"}})]),qr=await pdf.embedPng(Buffer.from(qrData.split(",")[1],"base64")),page=pdf.addPage(A4);page.drawRectangle({x:0,y:0,width:A4[0],height:A4[1],color:colors.paper});if(img){const scaled=img.scaleToFit(A4[0],345);page.drawImage(img,{x:(A4[0]-scaled.width)/2,y:497,width:scaled.width,height:scaled.height});page.drawRectangle({x:0,y:497,width:A4[0],height:345,color:colors.night,opacity:.28});}page.drawText(`0${index+1} · ${themeNames[theme].toUpperCase()}`,{x:43,y:790,size:8,font:bold,color:colors.cyan});page.drawText(destination.nameEl,{x:43,y:665,size:44,font:bold,color:colors.white});page.drawText(dateLabel,{x:45,y:630,size:11,font:regular,color:colors.white});page.drawText("Η ΕΠΙΛΟΓΗ ΔΙΑΜΟΝΗΣ",{x:44,y:450,size:8,font:bold,color:colors.violet});drawBlock(page,offer.propertyName,bold,20,44,418,350,colors.ink,26);drawBlock(page,`Καλύπτει όλες τις ημερομηνίες της έκδοσης. Η τελική τιμή, ο τύπος δωματίου και οι όροι επιβεβαιώνονται μετά το scan.`,regular,10,44,350,345,colors.muted,15);page.drawImage(qr,{x:407,y:310,width:135,height:135});page.drawText("SCAN ΤΗΣ ΣΥΓΚΕΚΡΙΜΕΝΗΣ ΕΠΙΛΟΓΗΣ",{x:390,y:287,size:6.5,font:bold,color:colors.violet});const ta=evidence.tripadvisor[0],event=evidence.events[0];page.drawRectangle({x:44,y:205,width:498,height:58,color:colors.white,borderColor:rgb(.83,.8,.92),borderWidth:.6});page.drawText(ta?`ΕΠΑΛΗΘΕΥΜΕΝΟ SNAPSHOT · ${ta.sourceMonth?.slice(0,7)??ta.observedAt.slice(0,10)}`:"ΧΩΡΙΣ ΕΝΕΡΓΟ ΕΞΩΤΕΡΙΚΟ RANKING",{x:57,y:240,size:7,font:bold,color:colors.violet});drawBlock(page,ta?ta.headline:"Δεν εμφανίζεται μη επαληθευμένο rating.",regular,9,57,221,450,colors.ink,13);page.drawRectangle({x:44,y:126,width:498,height:58,color:colors.white,borderColor:rgb(.83,.8,.92),borderWidth:.6});page.drawText(event?"ΕΚΔΗΛΩΣΗ ΣΤΙΣ ΗΜΕΡΟΜΗΝΙΕΣ ΣΟΥ":"ΠΡΟΓΡΑΜΜΑ ΧΩΡΙΣ ΚΑΤΑΣΚΕΥΑΣΜΕΝΟ EVENT",{x:57,y:161,size:7,font:bold,color:colors.violet});drawBlock(page,event?`${event.subjectName} · ${event.headline}`:"Δεν έχει επαληθευτεί ακόμη σχετική εκδήλωση για το διάστημα.",regular,9,57,142,450,colors.ink,13);page.drawText(`${index+3}/${candidates.length+2}`,{x:520,y:38,size:7,font:bold,color:colors.muted});}
  pdf.setTitle(`${themeNames[theme]} - ${dateLabel}`);pdf.setAuthor("Ελληνικός AI Travel Guru");pdf.setSubject("Θεματικό travel dossier με επαληθευμένες χρονικές επιλογές");const bytes=await pdf.save();return new NextResponse(Buffer.from(bytes),{headers:{"content-type":"application/pdf","content-disposition":`attachment; filename="travel-guru-${theme}-${start}.pdf"`,"cache-control":"private, no-store","x-content-type-options":"nosniff"}});
}
