import assert from "node:assert/strict";
import { structuredIntent } from "../lib/ai/intent-v8";
import { diversifyV8,finalRankV8,preRankV8 } from "../lib/decision/v8-matcher";
import { geographyConstraint,matchesGeographyConstraint } from "../lib/decision/geography-constraint";
import { loadV8DestinationCatalog } from "../lib/data/destination-v8";
import type { WeatherEvidence } from "../lib/decision/types";
import type { Mood,TripRequest } from "../lib/validation/trip";

const COUNT=10_000,seed=0x10000ace;let state=seed;
const random=()=>{let t=state+=0x6d2b79f5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296};
const pick=<T>(values:readonly T[])=>values[Math.floor(random()*values.length)],addDays=(iso:string,days:number)=>new Date(Date.parse(`${iso}T00:00:00Z`)+days*86400000).toISOString().slice(0,10);
const moods:readonly Mood[]=["relax","romantic","food","warmth","city","nature","adventure","culture"],starts=["2026-09-18","2026-10-16","2026-11-13","2027-01-15","2027-04-16","2027-06-18","2027-08-20"];
const constraints=[
 {id:"western-greece",phrases:["θέλω μόνο δυτική Ελλάδα","αποκλειστικά δυτικά της Ελλάδας","only western Greece"]},{id:"crete",phrases:["θέλω μόνο Κρήτη","αποκλειστικά Κρήτη","Crete only"]},
 {id:"peloponnese",phrases:["θέλω μόνο Πελοπόννησο","αποκλειστικά Πελοπόννησος","Peloponnese only"]},{id:"ionian",phrases:["θέλω μόνο Ιόνιο","αποκλειστικά Ιόνια νησιά","Ionian only"]},
 {id:"epirus",phrases:["θέλω μόνο Ήπειρο","αποκλειστικά Ήπειρος","Epirus only"]},{id:"cyclades",phrases:["θέλω μόνο Κυκλάδες","αποκλειστικά Κυκλάδες","Cyclades only"]},
 {id:"dodecanese",phrases:["θέλω μόνο Δωδεκάνησα","αποκλειστικά Δωδεκάνησα","Dodecanese only"]},{id:"sporades",phrases:["θέλω μόνο Σποράδες","αποκλειστικά Σποράδες","Sporades only"]},
 {id:"northern-greece",phrases:["θέλω μόνο βόρεια Ελλάδα","αποκλειστικά βόρεια της Ελλάδας","Northern Greece only"]},{id:"central-greece",phrases:["θέλω μόνο Στερεά Ελλάδα","αποκλειστικά κεντρική Ελλάδα","Central Greece only"]},
 {id:"mainland-only",phrases:["όχι νησί","χωρίς νησί παρακαλώ","mainland only"]},{id:"island-only",phrases:["θέλω μόνο νησί","μόνο νησί παρακαλώ","island only"]},
] as const;
const weather=(score:number):WeatherEvidence=>({source:"climatology",sourceLabel:"10k-audit",score,confidence:"MEDIUM",typical:true,temperatureMeanC:20,summary:"audit",researchedAt:new Date(0).toISOString()});
function baseRequest(index:number):TripRequest{const travelerType=pick(["solo","couple","family","friends"] as const),groupSize=travelerType==="solo"?1:travelerType==="couple"?2:pick([3,4,5,6]),startDate=pick(starts),nights=pick([2,3,4,5,7,9]),chosen=[...moods].sort(()=>random()-.5).slice(0,pick([1,2,3]));return{origin:pick(["Athens","Thessaloniki","Patras","Heraklion","Larissa","Ioannina"]),startDate,endDate:addDays(startDate,nights),month:"flexible",nights,budget:Math.min(5000,Math.max(150,pick([55,85,120,180])*groupSize*nights)),moods:chosen,travelerType,language:index%7===0?"en":"el",distancePreference:"any",pace:pick(["slow","balanced","full"] as const),hotelStyle:pick(["luxury","boutique","resort","value","any"] as const),avoid:pick(["long-travel","high-cost","crowds","none"] as const),entryMode:"unknown",groupSize,desiredEnergy:pick(["restore","balanced","stimulating"] as const),socialPreference:pick(["quiet","balanced","lively"] as const),noveltyPreference:pick(["familiar","balanced","surprise"] as const),mustHave:pick(["sea","nature","culture","nightlife","none"] as const),dateFlexibility:pick(["fixed","few-days","open"] as const),transportMode:pick(["no-car","car","electric-car","any"] as const),stayLocationPreference:pick(["central","balanced","outside"] as const)};}
function rank(request:TripRequest,catalog:Awaited<ReturnType<typeof loadV8DestinationCatalog>>){const intent=structuredIntent(request),pre=preRankV8(request,intent,catalog,30),evidence=new Map(pre.map(item=>[item.destination.slug,weather(item.destination.monthFit[Number(request.startDate.slice(5,7))-1]??60)]));return diversifyV8(finalRankV8(request,intent,pre,evidence),12)}
async function main(){
 const catalog=(await loadV8DestinationCatalog()).filter(item=>item.countryCode==="GR"),violations:string[]=[],recognitionFailures:string[]=[],falsePositives:string[]=[],emptyByConstraint=new Map<string,number>(),winners=new Map<string,number>();let changedByText=0,nonEmpty=0,stable=0;
 for(let index=0;index<COUNT;index+=1){const spec=constraints[index%constraints.length],base=baseRequest(index),phrase=spec.phrases[index%spec.phrases.length],request={...base,tripText:`${phrase}. ${index%2?"Θέλω να περάσουμε όμορφα χωρίς άγχος.":"Budget και εποχή να είναι ρεαλιστικά."}`},constraint=geographyConstraint(request);if(constraint?.id!==spec.id){recognitionFailures.push(`${spec.id}:${phrase}->${constraint?.id??"none"}`);continue}const result=rank(request,catalog),again=rank(request,catalog),baseline=rank({...base,tripText:"Θέλω να περάσουμε όμορφα χωρίς άγχος."},catalog);if(result.map(x=>x.destination.slug).join("|")===again.map(x=>x.destination.slug).join("|"))stable+=1;if(result.slice(0,3).map(x=>x.destination.slug).join("|")!==baseline.slice(0,3).map(x=>x.destination.slug).join("|"))changedByText+=1;if(!result.length){emptyByConstraint.set(spec.id,(emptyByConstraint.get(spec.id)??0)+1);continue}nonEmpty+=1;const winner=result[0].destination.slug;winners.set(winner,(winners.get(winner)??0)+1);const leaked=result.filter(item=>!matchesGeographyConstraint(item.destination,constraint));if(leaked.length)violations.push(`${spec.id}:${leaked.map(x=>x.destination.slug).join(",")}`)}
 const neutral=["όχι μόνο νησιά που μοιάζουν μεταξύ τους","δεν θέλω μόνο Κρήτη, είμαι ανοιχτός παντού","not only islands, show mainland too","θα προτιμούσα δυτική Ελλάδα αλλά δεν είναι υποχρεωτικό","ίσως Κυκλάδες, ίσως και κάπου αλλού"];
 for(let index=0;index<1000;index+=1){const text=neutral[index%neutral.length],detected=geographyConstraint({...baseRequest(index),tripText:text});if(detected)falsePositives.push(`${text}->${detected.id}`)}
 const output={seed,cases:COUNT,adversarialControls:1000,catalogSize:catalog.length,constraints:constraints.length,recognitionAccuracy:1-recognitionFailures.length/COUNT,falsePositiveRate:falsePositives.length/1000,hardConstraintViolations:violations.length,nonEmptyRate:nonEmpty/COUNT,deterministicRate:stable/COUNT,freeTextTop3ChangeRate:changedByText/COUNT,emptyByConstraint:Object.fromEntries(emptyByConstraint),uniqueWinners:winners.size,topWinners:[...winners].sort((a,b)=>b[1]-a[1]).slice(0,12)};console.log("V10_10000_AUDIT_OK",JSON.stringify(output));
 assert.equal(recognitionFailures.length,0,`Constraint recognition failures: ${recognitionFailures.slice(0,10)}`);assert.equal(falsePositives.length,0,`False-positive constraints: ${falsePositives.slice(0,10)}`);assert.equal(violations.length,0,`Hard constraint leaks: ${violations.slice(0,10)}`);assert.equal(stable,COUNT,"Same input/evidence must be deterministic");assert(nonEmpty/COUNT>=.72,`Only ${(nonEmpty/COUNT*100).toFixed(1)}% of constrained briefs have viable results`);assert(changedByText/COUNT>=.8,`Free text changes only ${(changedByText/COUNT*100).toFixed(1)}% of top-three outputs`);
}
void main();
