import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { applyLocalityFuzzyRankingV23 } from "../lib/decision/locality-fuzzy-ranking-v23";
import { buildFuzzyContractV23,vectorFromSemanticMapV23 } from "../lib/decision/fuzzy-semantic-v23";
import { stayOfferCriterionDeltaV23 } from "../lib/decision/stay-offer-score";
import type { LocalityProfileV23 } from "../lib/data/locality-profiles-v23";
import type { StayConstraintSpec,V23FuzzyIntentContract,V23SemanticDimension,V8Destination,V8IntentProfile,V8StayOffer } from "../lib/decision/v8-types";
import type { V8Ranked } from "../lib/decision/v8-matcher";
import type { TripRequest } from "../lib/validation/trip";

const trip:TripRequest={origin:"Athens",startDate:"2026-09-18",endDate:"2026-09-22",month:"september",nights:4,budget:900,moods:["relax"],travelerType:"couple",language:"el",distancePreference:"any",pace:"balanced",hotelStyle:"any",avoid:"none",entryMode:"unknown",groupSize:2,desiredEnergy:"balanced",socialPreference:"balanced",noveltyPreference:"balanced",mustHave:"none",dateFlexibility:"fixed",transportMode:"any",stayLocationPreference:"balanced",tripText:"food first"};
function destination(slug:string):V8Destination{return{slug,nameEl:slug,nameEn:slug,countryCode:"GR",countryEl:"Ελλάδα",countryEn:"Greece",latitude:38,longitude:23,regionGroup:"test",aliases:[],tags:["food","culture","nature","relax"],vector:Array(16).fill(.7),monthFit:Array(12).fill(85),idealNightsMin:2,idealNightsMax:5,costTier:3,effortAthens:"road-medium",effortThessaloniki:"road-medium",directFromAthens:true,routeConfidence:.9,travelerFit:{},crowdLevel:3,hotelRadiusKm:30,knowledgeSource:"test",seasonProfile:"test"};}
function ranked(slug:string):V8Ranked{return{destination:destination(slug),score:72,preScore:72,breakdown:{intent:75,season:80,effort:75,duration:90,budget:75,weather:70,traveler:75,crowdFit:75,routeConfidence:90}};}
function contract(primary:V23SemanticDimension,negative?:V23SemanticDimension):V23FuzzyIntentContract{const positive:Partial<Record<V23SemanticDimension,number>>={[primary]:.98,couple:.7,short_break:.35},neg:Partial<Record<V23SemanticDimension,number>>={};if(negative)neg[negative]=.95;return{positive,negative:neg,priorities:[primary],qualifiers:{avoidCrowds:0,easyAccess:0,slowRhythm:0,walkable:0,localCharacter:0},confidence:.98,source:"structured+deepseek",positiveVector:vectorFromSemanticMapV23(positive),negativeVector:vectorFromSemanticMapV23(neg)};}
function locality(id:string,slug:string,label:string,traits:Partial<Record<V23SemanticDimension,number>>):LocalityProfileV23{return{localityId:id,locationLabel:label,latitude:38,longitude:23,semanticVector:vectorFromSemanticMapV23({relax:.55,couple:.7,short_break:.6,...traits}),profileConfidence:.95,eligibleOfferCount:1,canonicalSlug:slug,canonicalDistanceKm:5};}
const pool=[ranked("food-place"),ranked("culture-place"),ranked("nature-place"),ranked("generic")],localities=[locality("1","food-place","Food Town",{food:.96,culture:.25,nature:.25}),locality("2","culture-place","Heritage Town",{food:.25,culture:.96,nature:.25}),locality("3","nature-place","Mountain Town",{food:.25,culture:.25,nature:.96}),locality("4","generic","Generic Town",{food:.4,culture:.4,nature:.4})];
function intent(c:V23FuzzyIntentContract):V8IntentProfile{return{weights:{romantic:0,relax:.5,food:0,culture:0,city:0,nature:0,beach:0,adventure:0,nightlife:0,family:0,luxury:0,value:0,warmth:0,wellness:0,short_break:.4,shoulder_season:0},source:"structured+deepseek",summary:"test",semantic24:c};}
const food=applyLocalityFuzzyRankingV23({...trip,tripText:"food first"},intent(contract("food")),pool,localities).ranked,culture=applyLocalityFuzzyRankingV23({...trip,tripText:"culture first"},intent(contract("culture")),pool,localities).ranked,nature=applyLocalityFuzzyRankingV23({...trip,tripText:"nature first"},intent(contract("nature")),pool,localities).ranked;
assert.equal(food[0].destination.slug,"food-place");assert.equal(culture[0].destination.slug,"culture-place");assert.equal(nature[0].destination.slug,"nature-place");assert.notDeepEqual(food.slice(0,3).map(x=>x.destination.slug),culture.slice(0,3).map(x=>x.destination.slug));assert.notDeepEqual(culture.slice(0,3).map(x=>x.destination.slug),nature.slice(0,3).map(x=>x.destination.slug));

const formulated=buildFuzzyContractV23({...trip,tripText:"boutique, not a resort, xoris poli odigisi"});assert.ok((formulated.positive.boutique??0)>=.7);assert.ok((formulated.negative.resort??0)>=.85);assert.ok((formulated.positive.low_effort??0)>=.7);
const emptySpec:StayConstraintSpec={hard:[],soft:[],confidence:"HIGH",source:"deterministic",needsSemanticAssist:false};function hotel(id:string,boutique:number,resort:number):V8StayOffer{return{sourceProductId:id,propertyName:id,trackingUrl:"https://go.linkwi.se/z/CD104/x",distanceKm:2,semanticVector:vectorFromSemanticMapV23({boutique,resort,couple:.8,relax:.7}),semanticConfidence:.95,raw:{}};}
const boutiqueHotel=hotel("boutique",.95,.1),resortHotel=hotel("resort",.1,.95),hotelContract=contract("boutique","resort"),boutiqueDelta=stayOfferCriterionDeltaV23(boutiqueHotel,emptySpec,hotelContract),resortDelta=stayOfferCriterionDeltaV23(resortHotel,emptySpec,hotelContract);assert.ok(boutiqueDelta>resortDelta+20,"free-text hotel semantics must materially reorder offers");

const migration=readFileSync("supabase/migrations/20260815010000_v23_locality_first_fuzzy_retrieval.sql","utf8");assert.match(migration,/get_locality_profiles_v23/i);assert.match(migration,/destination_semantic_profiles/i);assert.match(migration,/revoke all on function public\.get_locality_profiles_v23\(date,date\) from public,anon,authenticated/i);assert.match(migration,/grant execute on function public\.get_locality_profiles_v23\(date,date\) to service_role/i);assert.doesNotMatch(migration,/order\s+by[^\n;]*eligible_offer_count/i,"inventory depth must not appear in any ORDER BY expression");
const orchestrator=readFileSync("lib/ai/travel-orchestrator-v23.ts","utf8"),intentCode=readFileSync("lib/ai/intent-v8.ts","utf8");assert.match(orchestrator,/applyLocalityFuzzyRankingV23/);assert.match(orchestrator,/localities\.length<10/);assert.match(intentCode,/preferReasoner:true/);assert.match(intentCode,/V23_SEMANTIC_DIMENSIONS/);
console.log("V23_FUZZY_LOCALITY_OK",JSON.stringify({food:food.slice(0,3).map(x=>x.destination.slug),culture:culture.slice(0,3).map(x=>x.destination.slug),nature:nature.slice(0,3).map(x=>x.destination.slug),hotelDelta:{boutique:boutiqueDelta,resort:resortDelta}}));
