import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { buildLocalityCandidateCatalogV24,localityIdFromRecommendationSlugV24 } from "../lib/decision/locality-candidate-v24";
import { applyLocalityNativeRankingV24 } from "../lib/decision/locality-native-ranking-v24";
import { applyLocalityEvidenceScoresV24 } from "../lib/ai/locality-evidence-reranker-v24";
import { vectorFromSemanticMapV23 } from "../lib/decision/fuzzy-semantic-v23";
import { preRankV24 } from "../lib/decision/v24-matcher";
import type { LocalityProfileV23 } from "../lib/data/locality-profiles-v23";
import type { V23FuzzyIntentContract,V23SemanticDimension,V8Destination,V8IntentProfile } from "../lib/decision/v8-types";
import type { TripRequest } from "../lib/validation/trip";

const trip:TripRequest={origin:"Athens",startDate:"2026-09-18",endDate:"2026-09-22",month:"september",nights:4,budget:900,moods:["relax"],travelerType:"couple",language:"el",distancePreference:"any",pace:"balanced",hotelStyle:"any",avoid:"none",entryMode:"unknown",groupSize:2,desiredEnergy:"balanced",socialPreference:"balanced",noveltyPreference:"balanced",mustHave:"none",dateFlexibility:"fixed",transportMode:"any",stayLocationPreference:"balanced",tripText:"food first"};
function parent(slug:string):V8Destination{return{slug,nameEl:slug,nameEn:slug,countryCode:"GR",countryEl:"Ελλάδα",countryEn:"Greece",latitude:38,longitude:23,regionGroup:"test",aliases:[slug],tags:["food","culture","nature","relax"],vector:Array(16).fill(.65),monthFit:Array(12).fill(82),idealNightsMin:2,idealNightsMax:5,costTier:3,effortAthens:"road-medium",effortThessaloniki:"road-medium",directFromAthens:true,routeConfidence:.9,travelerFit:{couple:.8},crowdLevel:3,hotelRadiusKm:30,knowledgeSource:"test",seasonProfile:"test"};}
function locality(id:string,label:string,canonicalSlug:string|null,traits:Partial<Record<V23SemanticDimension,number>>):LocalityProfileV23{return{localityId:id,locationLabel:label,latitude:38,longitude:23,semanticVector:vectorFromSemanticMapV23({relax:.55,couple:.75,short_break:.6,...traits}),profileConfidence:.95,eligibleOfferCount:1,canonicalSlug,canonicalDistanceKm:canonicalSlug?3:null};}
const foodId="11111111111111111111111111111111",cultureId="22222222222222222222222222222222",natureId="33333333333333333333333333333333";
const localities=[locality(foodId,"Food Town","parent-a",{food:.97,culture:.2,nature:.2}),locality(cultureId,"Culture Quarter","parent-a",{food:.2,culture:.97,nature:.2}),locality(natureId,"Wild Valley",null,{food:.2,culture:.2,nature:.98})],catalog=buildLocalityCandidateCatalogV24([parent("parent-a")],localities);
assert.equal(catalog.length,3);assert.equal(catalog.filter(x=>!x.canonicalParentSlug).length,1,"locality-only candidate must remain in the public candidate universe");assert.equal(localityIdFromRecommendationSlugV24(catalog[0].slug),foodId,"recommendation slug must recover exact locality identity");
function contract(primary:V23SemanticDimension):V23FuzzyIntentContract{const positive:Partial<Record<V23SemanticDimension,number>>={[primary]:.98,couple:.7,short_break:.35};return{positive,negative:{},priorities:[primary],qualifiers:{avoidCrowds:0,easyAccess:0,slowRhythm:0,walkable:0,localCharacter:0},confidence:.98,source:"structured+deepseek",positiveVector:vectorFromSemanticMapV23(positive),negativeVector:Array(24).fill(0)};}
function intent(c:V23FuzzyIntentContract):V8IntentProfile{return{weights:{romantic:0,relax:.2,food:0,culture:0,city:0,nature:0,beach:0,adventure:0,nightlife:0,family:0,luxury:0,value:0,warmth:0,wellness:0,short_break:.2,shoulder_season:0},source:"structured+deepseek",summary:"test",semantic24:c};}
function rank(primary:V23SemanticDimension){const c=contract(primary),base=preRankV24({...trip,tripText:`${primary} first`},intent(c),catalog,20);return applyLocalityNativeRankingV24({...trip,tripText:`${primary} first`},intent(c),base,localities).ranked;}
const food=rank("food"),culture=rank("culture"),nature=rank("nature");assert.equal(food[0].destination.localityId,foodId);assert.equal(culture[0].destination.localityId,cultureId);assert.equal(nature[0].destination.localityId,natureId,"unmapped locality must be able to win on user criteria");assert.notDeepEqual(food.slice(0,3).map(x=>x.destination.localityId),culture.slice(0,3).map(x=>x.destination.localityId));
const sameParent=food.filter(x=>x.destination.canonicalParentSlug==="parent-a"),reranked=applyLocalityEvidenceScoresV24(sameParent,{[sameParent[0].destination.slug]:20,[sameParent[1].destination.slug]:95});assert.equal(reranked[0].destination.slug,sameParent[1].destination.slug,"evidence must score exact locality candidates independently even with same parent");
const loader=readFileSync("lib/data/locality-profiles-v23.ts","utf8"),detail=readFileSync("app/api/destination-detail/route.ts","utf8"),orchestrator=readFileSync("lib/ai/travel-orchestrator-v24.ts","utf8"),choice=readFileSync("lib/decision/choice-correctness-v24.ts","utf8"),jsonRoute=readFileSync("app/api/recommend/route.ts","utf8"),streamRoute=readFileSync("app/api/recommend/stream/route.ts","utf8");assert.doesNotMatch(loader,/!canonicalSlug/);assert.match(loader,/canonicalSlug:string\|null/);assert.match(detail,/localityIdFromRecommendationSlugV24/);assert.match(detail,/loadLocalityStayOffersV24/);assert.match(choice,/loadLocalityStayOffersV24/);assert.ok(orchestrator.indexOf("runLocalityEvidenceRerankerV24")<orchestrator.indexOf("applyChoiceCorrectnessV24"),"evidence reranking must happen before shortlist choice correctness");assert.match(jsonRoute,/runTravelOrchestratorV24/);assert.match(streamRoute,/runTravelOrchestratorV24/);
console.log("V24_LOCALITY_NATIVE_OK",JSON.stringify({food:food[0].destination.localityLabel,culture:culture[0].destination.localityLabel,nature:nature[0].destination.localityLabel,localityOnly:true,exactStayIdentity:true}));
