import type { AffiliateDestinationCandidate, GuruRecommendation, GuruScoreBreakdown } from "@/lib/decision/types";
import type { TripRequest } from "@/lib/validation/trip";

export type RankedAffiliateCandidate = { candidate: AffiliateDestinationCandidate; score: number; distanceKm: number | null; breakdown: GuruScoreBreakdown };
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v)); const round=(v:number)=>Math.round(v);
const originCoordinates:Record<string,[number,number]>={athens:[37.9838,23.7275],athina:[37.9838,23.7275],"αθήνα":[37.9838,23.7275],thessaloniki:[40.6401,22.9444],"θεσσαλονίκη":[40.6401,22.9444],patra:[38.2466,21.7346],"πάτρα":[38.2466,21.7346],heraklion:[35.3387,25.1442],"ηράκλειο":[35.3387,25.1442],chania:[35.5138,24.0180],"χανιά":[35.5138,24.0180]};
const intentWords:Record<TripRequest["moods"][number],string[]>={relax:["spa","resort","beach","seaside","sea","suite","wellness","pool","παραλία","θάλασσα","σπα","πισίνα","ηρεμ"],romantic:["boutique","suite","luxury","sea view","romantic","adults","villa","honeymoon","μπουτίκ","σουίτα","πολυτελ","βίλα"],food:["restaurant","gastronomy","breakfast","tavern","food","wine","εστιατόρ","πρωινό","κρασί","γαστρο"],warmth:["beach","sea","seaside","island","pool","παραλία","θάλασσα","νησί","πισίνα"],city:["city","center","centre","urban","old town","κέντρο","πόλη","παλιά πόλη"],nature:["mountain","forest","lake","nature","village","sea","beach","βουνό","δάσος","λίμνη","χωριό","φύση"],adventure:["mountain","aqua","park","hiking","outdoor","surf","diving","βουνό","πεζοπο","κατάδυ","θαλάσ"],culture:["historic","old town","museum","heritage","traditional","ιστορ","παραδοσιακ","παλιά πόλη"]};
const travelerWords:Record<TripRequest["travelerType"],string[]>={solo:["center","city","boutique","κέντρο","πόλη"],couple:["suite","boutique","luxury","adults","villa","σουίτα","μπουτίκ","βίλα"],family:["family","aqua","apartment","kids","pool","οικογεν","παιδ","διαμέρισμα","πισίνα"],friends:["city","beach","apartment","villa","pool","πόλη","παραλία","διαμέρισμα","βίλα"]};
function haversine(a:[number,number],b:[number,number]){const r=6371,rad=(x:number)=>x*Math.PI/180,dLat=rad(b[0]-a[0]),dLon=rad(b[1]-a[1]);const q=Math.sin(dLat/2)**2+Math.cos(rad(a[0]))*Math.cos(rad(b[0]))*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(q));}
function originPoint(origin:string){return originCoordinates[origin.trim().toLowerCase()]??null}
function textFor(c:AffiliateDestinationCandidate){return `${c.locationLabel} ${c.semanticText??""} ${c.topOffers.map(o=>`${o.propertyName} ${o.description??""}`).join(" ")}`.toLowerCase()}
function keywordFit(request:TripRequest,c:AffiliateDestinationCandidate){const hay=textFor(c);let hits=0,possible=0;for(const mood of request.moods){const words=intentWords[mood];possible+=Math.min(words.length,5);hits+=words.filter(w=>hay.includes(w)).length;}const tw=travelerWords[request.travelerType];possible+=Math.min(tw.length,4);hits+=tw.filter(w=>hay.includes(w)).length;return clamp(48+(hits/Math.max(1,possible))*58)}
function valueFit(request:TripRequest,c:AffiliateDestinationCandidate){if(c.minPrice==null)return 48;const ratio=c.minPrice/Math.max(1,request.budget);if(ratio<=.15)return 100;if(ratio<=.35)return 92;if(ratio<=.6)return 82;if(ratio<=1)return 66;if(ratio<=1.5)return 42;return 20}
function dealFit(c:AffiliateDestinationCandidate){const d=c.maxDiscount??0;return d>0?clamp(45+d*.9):42}
function effortFit(request:TripRequest,c:AffiliateDestinationCandidate){const origin=originPoint(request.origin);if(!origin||c.latitude==null||c.longitude==null)return{score:60,distance:null};const distance=haversine(origin,[c.latitude,c.longitude]);return{score:clamp(100-distance/(request.nights<=3?9:13)),distance}}
function refinementBoost(request:TripRequest,b:GuruScoreBreakdown,c:AffiliateDestinationCandidate){if(!request.refinement)return 0;if(request.refinement==="cheaper")return b.value*.08;if(request.refinement==="closer"||request.refinement==="shorter")return b.effort*.08;if(request.refinement==="romantic")return keywordFit({...request,moods:["romantic"]},c)*.08;if(request.refinement==="adventurous")return keywordFit({...request,moods:["adventure"]},c)*.08;if(request.refinement==="warmer")return keywordFit({...request,moods:["warmth"]},c)*.08;return 0}
function feedPriceLabel(c:AffiliateDestinationCandidate){if(c.minPrice==null)return"Price not supplied";const prefix=c.currency?`${c.currency} `:"feed price ";return`${prefix}${Math.round(c.minPrice)}${c.medianPrice!=null&&c.medianPrice!==c.minPrice?`–${Math.round(c.medianPrice)}`:""}`}
function roleFor(i:number,r:RankedAffiliateCandidate){if(i===0)return"GURU PICK";const b=r.breakdown;if(b.value>=86)return"BEST VALUE";if(b.effort>=84)return"EASY ESCAPE";if(b.deal>=75)return"STRONG DEAL SIGNAL";return i===1?"SMART ALTERNATIVE":"WILDCARD"}
function similarity(a:AffiliateDestinationCandidate,b:AffiliateDestinationCandidate){const x=a.locationLabel.toLowerCase(),y=b.locationLabel.toLowerCase();if(x.includes(y)||y.includes(x))return 35;const ax=x.split(",").map(s=>s.trim()),by=y.split(",").map(s=>s.trim());return ax.some(v=>v.length>3&&by.includes(v))?18:0}
export function rankAffiliateCandidates(request:TripRequest,candidates:AffiliateDestinationCandidate[],limit=18):RankedAffiliateCandidate[]{const maxSupply=Math.max(1,...candidates.map(c=>c.activeOfferCount)),maxDemand=Math.max(1,...candidates.map(c=>c.demandScore));return candidates.map(candidate=>{const supply=clamp(35+65*Math.log1p(candidate.activeOfferCount)/Math.log1p(maxSupply)),demand=clamp(30+70*Math.log1p(candidate.demandScore)/Math.log1p(maxDemand)),value=valueFit(request,candidate),deal=dealFit(candidate),intent=keywordFit(request,candidate),effort=effortFit(request,candidate),breakdown={supply:round(supply),value:round(value),demand:round(demand),deal:round(deal),intent:round(intent),effort:round(effort.score)},base=supply*.22+value*.20+demand*.12+deal*.10+intent*.22+effort.score*.14;return{candidate,score:clamp(base+refinementBoost(request,breakdown,candidate)),distanceKm:effort.distance,breakdown}}).sort((a,b)=>b.score-a.score).slice(0,Math.max(3,limit))}
export function deterministicGuruFallback(request:TripRequest,ranked:RankedAffiliateCandidate[]):GuruRecommendation[]{const selected:RankedAffiliateCandidate[]=[];for(const item of ranked){const penalty=selected.reduce((sum,s)=>sum+similarity(item.candidate,s.candidate),0)*.35;if(item.score-penalty<40&&selected.length>=2)continue;selected.push({...item,score:item.score-penalty});if(selected.length===3)break;}return selected.slice(0,3).map((item,index)=>{const c=item.candidate;return{destinationId:c.destinationId,destination:c.locationLabel,country:c.countryHint??"Feed location",role:roleFor(index,item),score:round(item.score),confidence:c.activeOfferCount>=5?"MEDIUM":"LOW",whyThisPlace:`${c.locationLabel} ranks strongly on your selected intent, value and current feed-supply signals.`,whyNow:`${c.activeOfferCount} active tracked offers overlap the requested period${c.maxDiscount&&c.maxDiscount>0?`, with feed discount signals up to ${Math.round(c.maxDiscount)}%`:""}.`,tags:[request.moods[0],item.breakdown.value>=85?"value":"curated",item.breakdown.effort>=80?"lower effort":"feed active"],imageUrl:c.heroImageUrl,feedPriceLabel:feedPriceLabel(c),propertyCount:c.propertyCount,activeOfferCount:c.activeOfferCount,demandScore:round(c.demandScore),maxDiscount:c.maxDiscount,distanceKm:item.distanceKm==null?null:round(item.distanceKm),breakdown:item.breakdown,offers:c.topOffers.slice(0,3)}})}
