import type { AffiliateDestinationCandidate, GuruRecommendation, GuruScoreBreakdown } from "@/lib/decision/types";
import type { TripRequest } from "@/lib/validation/trip";

export type RankedAffiliateCandidate = { candidate: AffiliateDestinationCandidate; score: number; distanceKm: number | null; breakdown: GuruScoreBreakdown };
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v)); const round=(v:number)=>Math.round(v);
const originCoordinates:Record<string,[number,number]>={athens:[37.9838,23.7275],athina:[37.9838,23.7275],"αθήνα":[37.9838,23.7275],thessaloniki:[40.6401,22.9444],"θεσσαλονίκη":[40.6401,22.9444],patra:[38.2466,21.7346],"πάτρα":[38.2466,21.7346],heraklion:[35.3387,25.1442],"ηράκλειο":[35.3387,25.1442],chania:[35.5138,24.0180],"χανιά":[35.5138,24.0180]};
const intentWords:Record<TripRequest["moods"][number],string[]>={relax:["spa","resort","beach","seaside","sea","suite","wellness","pool","παραλία","θάλασσα","σπα","πισίνα","ηρεμ"],romantic:["boutique","suite","luxury","sea view","romantic","adults","villa","honeymoon","μπουτίκ","σουίτα","πολυτελ","βίλα"],food:["restaurant","gastronomy","breakfast","tavern","food","wine","εστιατόρ","πρωινό","κρασί","γαστρο"],warmth:["beach","sea","seaside","island","pool","παραλία","θάλασσα","νησί","πισίνα"],city:["city","center","centre","urban","old town","κέντρο","πόλη","παλιά πόλη"],nature:["mountain","forest","lake","nature","village","sea","beach","βουνό","δάσος","λίμνη","χωριό","φύση"],adventure:["mountain","aqua","park","hiking","outdoor","surf","diving","βουνό","πεζοπο","κατάδυ","θαλάσ"],culture:["historic","old town","museum","heritage","traditional","ιστορ","παραδοσιακ","παλιά πόλη"]};
const travelerWords:Record<TripRequest["travelerType"],string[]>={solo:["center","city","boutique","κέντρο","πόλη"],couple:["suite","boutique","luxury","adults","villa","σουίτα","μπουτίκ","βίλα"],family:["family","aqua","apartment","kids","pool","οικογεν","παιδ","διαμέρισμα","πισίνα"],friends:["city","beach","apartment","villa","pool","πόλη","παραλία","διαμέρισμα","βίλα"]};
const hotelWords={luxury:["5*","5 star","luxury","palace","premium","suite","villa","πολυτελ","παλάτι","βίλα"],boutique:["boutique","design","suite","old town","μπουτίκ","σουίτα"],resort:["resort","beach","pool","spa","all inclusive","παραλία","πισίνα","σπα"],value:["deal","offer","discount","value","προσφορά","έκπτωση"]};
const summerWords=["beach","seaside","sea view","pool","aqua","all inclusive","παραλία","θάλασσα","πισίνα","χαλκιδ","νησί","island","resort"];
function haversine(a:[number,number],b:[number,number]){const r=6371,rad=(x:number)=>x*Math.PI/180,dLat=rad(b[0]-a[0]),dLon=rad(b[1]-a[1]);const q=Math.sin(dLat/2)**2+Math.cos(rad(a[0]))*Math.cos(rad(b[0]))*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(q));}
function originPoint(origin:string){return originCoordinates[origin.trim().toLowerCase()]??null}
function textFor(c:AffiliateDestinationCandidate){return `${c.locationLabel} ${c.semanticText??""} ${c.topOffers.map(o=>`${o.propertyName} ${o.description??""}`).join(" ")}`.toLowerCase()}
function keywordFit(request:TripRequest,c:AffiliateDestinationCandidate){const hay=textFor(c);let hits=0,possible=0;for(const mood of request.moods){const words=intentWords[mood];possible+=Math.min(words.length,5);hits+=words.filter(w=>hay.includes(w)).length;}const tw=travelerWords[request.travelerType];possible+=Math.min(tw.length,4);hits+=tw.filter(w=>hay.includes(w)).length;const style=request.hotelStyle??"any";if(style!=="any"){const sw=hotelWords[style];possible+=Math.min(sw.length,5);hits+=sw.filter(w=>hay.includes(w)).length;}return clamp(45+(hits/Math.max(1,possible))*62)}
function valueFit(request:TripRequest,c:AffiliateDestinationCandidate){if(c.minPrice==null)return 48;const ratio=c.minPrice/Math.max(1,request.budget);let score=ratio<=.15?100:ratio<=.35?92:ratio<=.6?82:ratio<=1?66:ratio<=1.5?42:20;if(request.avoid==="high-cost")score=clamp(score+12);if(request.hotelStyle==="value")score=clamp(score+10);return score}
function dealFit(c:AffiliateDestinationCandidate){const d=c.maxDiscount??0;return d>0?clamp(45+d*.9):42}
function luxuryFit(request:TripRequest,c:AffiliateDestinationCandidate){const density=c.activeOfferCount?c.fiveStarOfferCount/c.activeOfferCount:0;let score=clamp(32+c.fiveStarOfferCount*9+density*35);if(request.hotelStyle==="luxury")score=clamp(score+14);if(request.hotelStyle==="value")score=clamp(score-8);return score}
function effortFit(request:TripRequest,c:AffiliateDestinationCandidate){const origin=originPoint(request.origin);if(!origin||c.latitude==null||c.longitude==null)return{score:58,distance:null};const distance=haversine(origin,[c.latitude,c.longitude]);const pref=request.distancePreference??"any";let divisor=request.nights<=3?9:13;if(pref==="nearby")divisor=4.2;if(pref==="easy-hop")divisor=7.5;if(pref==="any")divisor=request.nights<=3?9:13;let score=clamp(100-distance/divisor);if(pref==="island"){const h=textFor(c);const islandish=["island","νησί","μύκονος","πάρος","νάξος","σαντορίνη","κέρκυρα","ζάκυνθος","ρόδος","κρήτη","θάσος","σκιάθος"].some(x=>h.includes(x));score=clamp(score+(islandish?22:-8));}if(request.pace==="slow")score=clamp(score+6);if(request.avoid==="long-travel")score=clamp(score+12);return{score,distance}}
function seasonalityFit(request:TripRequest,c:AffiliateDestinationCandidate,periodSupply:number){const weather=c.weather?.score??50;const h=textFor(c),summerHeavy=summerWords.some(x=>h.includes(x));const max=c.weather?.temperatureMaxC;let score=weather*.76+periodSupply*.24;if(summerHeavy&&max!=null&&max<18)score-=18;if(request.moods.includes("warmth")&&max!=null&&max<20)score-=22;if(c.weather?.source==="unavailable")score=Math.min(score,52);return clamp(score)}
function refinementBoost(request:TripRequest,b:GuruScoreBreakdown,c:AffiliateDestinationCandidate){if(!request.refinement)return 0;if(request.refinement==="cheaper")return b.value*.06;if(request.refinement==="closer"||request.refinement==="shorter")return b.effort*.06;if(request.refinement==="romantic")return keywordFit({...request,moods:["romantic"]},c)*.06;if(request.refinement==="adventurous")return keywordFit({...request,moods:["adventure"]},c)*.06;if(request.refinement==="warmer")return b.weather*.09;return 0}
function avoidancePenalty(request:TripRequest,b:GuruScoreBreakdown){if(request.avoid==="long-travel")return (100-b.effort)*.10;if(request.avoid==="high-cost")return (100-b.value)*.10;if(request.avoid==="crowds")return Math.max(0,b.demand-68)*.08;return 0}
function feedPriceLabel(c:AffiliateDestinationCandidate){if(c.minPrice==null)return"Price not supplied";const prefix=c.currency?`${c.currency} `:"feed price ";return`${prefix}${Math.round(c.minPrice)}${c.medianPrice!=null&&c.medianPrice!==c.minPrice?`–${Math.round(c.medianPrice)}`:""}`}
function roleFor(i:number,r:RankedAffiliateCandidate){if(i===0)return"GURU PICK";const b=r.breakdown;if(b.weather>=82)return"WEATHER FIT";if(r.candidate.fiveStarOfferCount>=5&&b.luxury>=75)return"LUXURY DEPTH";if(b.value>=86)return"BEST VALUE";if(b.effort>=84)return"EASY ESCAPE";return i===1?"SMART ALTERNATIVE":"WILDCARD"}
function normalizeLabel(value:string){return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zα-ω0-9]+/gi," ").trim()}
function samePlaceGroup(a:AffiliateDestinationCandidate,b:AffiliateDestinationCandidate){const x=normalizeLabel(a.locationLabel),y=normalizeLabel(b.locationLabel);if(x===y||x.includes(y)||y.includes(x))return true;const xa=x.split(" ").filter(v=>v.length>3),ya=y.split(" ").filter(v=>v.length>3);return xa.filter(v=>ya.includes(v)).length>=2}

export function rankAffiliateCandidates(request:TripRequest,candidates:AffiliateDestinationCandidate[],limit=24):RankedAffiliateCandidate[]{
  const maxSupply=Math.max(1,...candidates.map(c=>c.activeOfferCount)),maxDemand=Math.max(1,...candidates.map(c=>c.demandScore));
  return candidates.map(candidate=>{
    const supply=clamp(30+70*Math.log1p(candidate.activeOfferCount)/Math.log1p(maxSupply));
    const demand=clamp(28+72*Math.log1p(candidate.demandScore)/Math.log1p(maxDemand));
    const value=valueFit(request,candidate),deal=dealFit(candidate),intent=keywordFit(request,candidate),effort=effortFit(request,candidate),luxury=luxuryFit(request,candidate);
    const weather=clamp(candidate.weather?.score??50),seasonality=seasonalityFit(request,candidate,supply);
    const breakdown={supply:round(supply),value:round(value),demand:round(demand),deal:round(deal),intent:round(intent),effort:round(effort.score),luxury:round(luxury),weather:round(weather),seasonality:round(seasonality)};
    let base=seasonality*.22+weather*.12+intent*.19+supply*.12+demand*.09+value*.11+effort.score*.09+luxury*.05+deal*.01;
    if(request.hotelStyle==="luxury")base+=luxury*.04;if(request.hotelStyle==="value")base+=value*.04;
    base-=avoidancePenalty(request,breakdown);
    return{candidate,score:clamp(base+refinementBoost(request,breakdown,candidate)),distanceKm:effort.distance,breakdown};
  }).sort((a,b)=>b.score-a.score).slice(0,Math.max(5,limit));
}

export function deterministicGuruFallback(request:TripRequest,ranked:RankedAffiliateCandidate[]):GuruRecommendation[]{
  const selected:RankedAffiliateCandidate[]=[];for(const item of ranked){if(selected.some(s=>samePlaceGroup(item.candidate,s.candidate)))continue;selected.push(item);if(selected.length===5)break;}
  if(selected.length<5){for(const item of ranked){if(selected.some(s=>s.candidate.destinationId===item.candidate.destinationId))continue;selected.push(item);if(selected.length===5)break;}}
  return selected.slice(0,5).map((item,index)=>{const c=item.candidate,greek=request.language!=="en",weather=c.weather;
    return{destinationId:c.destinationId,destination:c.locationLabel,country:c.countryHint??(greek?"Προορισμός feed":"Feed location"),role:roleFor(index,item),score:round(item.score),confidence:c.activeOfferCount>=8&&weather?.confidence!=="LOW"?"HIGH":c.activeOfferCount>=4?"MEDIUM":"LOW",
      whyThisPlace:greek?`${c.locationLabel} περνά το date-range, weather και personal-fit screening καλύτερα από τις διαθέσιμες εναλλακτικές.`:`${c.locationLabel} passes the date-range, weather and personal-fit screen better than the available alternatives.`,
      whyNow:greek?`${c.activeOfferCount} tracked προσφορές καλύπτουν ακριβώς ${request.startDate}–${request.endDate}. ${weather?.summary??""}`:`${c.activeOfferCount} tracked offers overlap exactly ${request.startDate}–${request.endDate}. ${weather?.summary??""}`,
      tags:[request.moods[0],item.breakdown.weather>=75?"weather fit":item.breakdown.seasonality>=65?"season fit":"season caution",item.breakdown.value>=85?"value":"curated",c.fiveStarOfferCount>=5?"5-star depth":"mixed stays"],imageUrl:c.heroImageUrl,feedPriceLabel:feedPriceLabel(c),propertyCount:c.propertyCount,activeOfferCount:c.activeOfferCount,fiveStarOfferCount:c.fiveStarOfferCount,alternativeOfferCount:c.alternativeOfferCount,demandScore:round(c.demandScore),maxDiscount:c.maxDiscount,latitude:c.latitude,longitude:c.longitude,distanceKm:item.distanceKm==null?null:round(item.distanceKm),breakdown:item.breakdown,offers:c.topOffers.slice(0,5),weather};
  });
}
