import { loadGlobalStayCandidatesV21,type GlobalStayCandidateV21 } from "@/lib/data/global-stays-v21";
import { V8_DIMENSIONS,type StayConstraintKind,type StayConstraintSpec,type V23FuzzyIntentContract,type V8Dimension,type V8IntentProfile } from "@/lib/decision/v8-types";
import { fuzzyVectorFitV23 } from "@/lib/decision/fuzzy-semantic-v23";
import type { V8Ranked } from "@/lib/decision/v8-matcher";
import type { HotelStyle,StayLocationPreference,TripRequest } from "@/lib/validation/trip";

const clamp=(value:number,min=0,max=100)=>Math.max(min,Math.min(max,value));
const negativeGateDimensions=new Set<V8Dimension>(["nightlife","luxury","adventure","city"]);
const styleVectorIndex:Record<Exclude<HotelStyle,"any">,number>={luxury:8,boutique:9,resort:10,value:11};
const travelerVectorIndex:Record<TripRequest["travelerType"],number>={family:12,couple:13,solo:14,friends:15};
export interface V21ChoiceAudit{semanticRejected:string[];stayScanRan:boolean;stayScanFailed:boolean;mappedStayCount:number;destinationsWithMappedStays:number;hardStayRejected:string[];bestStayFit:Record<string,number>}
function affinity(item:V8Ranked,dimension:V8Dimension){const index=V8_DIMENSIONS.indexOf(dimension);return index>=0?item.destination.vector[index]??0:0;}
export function structuredEligibilityReasonV21(item:V8Ranked,request:TripRequest):string|null{if(request.mustHave==="nightlife"&&!item.destination.tags.includes("nightlife"))return "hard-must:nightlife";if(request.mustHave==="culture"&&!item.destination.tags.includes("culture"))return "hard-must:culture";if(request.mustHave==="nature"&&!item.destination.tags.includes("nature"))return "hard-must:nature";if(request.mustHave==="sea"&&!item.destination.tags.includes("beach"))return "hard-must:sea";return null;}
export function semanticEligibilityReasonV21(item:V8Ranked,intent:V8IntentProfile):string|null{const semantic=intent.semantic;if(!semantic)return null;for(const [dimension,weight] of Object.entries(semantic.negative) as Array<[V8Dimension,number|undefined]>){const negative=weight??0,positive=semantic.positive[dimension]??0;if(negativeGateDimensions.has(dimension)&&negative>=.86&&positive<.30&&affinity(item,dimension)>=.75)return `negative:${dimension}`;}const firstPriority=semantic.priorities[0];if(firstPriority&&(semantic.positive[firstPriority]??0)>=.82&&affinity(item,firstPriority)<.50)return `priority-miss:${firstPriority}`;if(semantic.qualifiers.avoidCrowds>=.90&&item.destination.crowdLevel>=4)return "negative:crowds";if(semantic.qualifiers.avoidCrowds>=.76&&item.destination.crowdLevel>=5)return "negative:crowds";if(semantic.qualifiers.easyAccess>=.92&&item.breakdown.effort<52)return "negative:access";return null;}
export function filterPortfolioV21(items:readonly V8Ranked[]):V8Ranked[]{if(!items.length)return[];const best=items[0]?.score??0;if(best<60)return[...items].filter(item=>item.score>0&&item.breakdown.season>=30&&item.breakdown.budget>=20&&item.breakdown.crowdFit>20);const floor=Math.max(50,best-16),kept=items.filter(item=>item.score>=floor&&item.breakdown.season>=40&&item.breakdown.budget>25&&item.breakdown.crowdFit>25);return kept.length?kept:[items[0]];}
function fallbackStyleAffinity(candidate:GlobalStayCandidateV21,style:HotelStyle){if(style==="any")return 70;if(style==="boutique")return candidate.styleHints.boutique?90:48;if(style==="resort")return candidate.styleHints.resort?90:45;if(style==="luxury")return candidate.starLevel!=null&&candidate.starLevel>=5?95:candidate.starLevel===4?70:candidate.styleHints.luxury?82:45;if(style==="value")return candidate.valueSignal;return 60;}
function vectorAffinity(candidate:GlobalStayCandidateV21,index:number,fallback:number){return candidate.semanticVector.length===24?clamp((candidate.semanticVector[index]??.5)*100):fallback;}
function locationAffinity(distance:number|null|undefined,preference:StayLocationPreference){if(preference==="balanced")return 72;const d=distance??20;if(preference==="central")return clamp(100-d*5,30,100);if(d>=4&&d<=22)return 92;if(d<4)return clamp(58+d*6,58,82);return clamp(92-(d-22)*2,42,92);}
function constraintEvaluation(candidate:GlobalStayCandidateV21,spec:StayConstraintSpec){const has=(kind:StayConstraintKind)=>candidate.constraintEvidence[kind]===true,hardFailures=spec.hard.filter(kind=>!has(kind)),softMatches=spec.soft.filter(has);return{passed:hardFailures.length===0,hardFailures,softMatches};}
export function scoreGlobalStayCandidateV21(candidate:GlobalStayCandidateV21,request:TripRequest,spec:StayConstraintSpec,contract?:V23FuzzyIntentContract){const evaluation=constraintEvaluation(candidate,spec);if(!evaluation.passed)return{eligible:false,score:0,softMatches:evaluation.softMatches.length,hardFailures:evaluation.hardFailures};const hotelStyle=request.hotelStyle??"any",stayLocationPreference=request.stayLocationPreference??"balanced",styleFallback=fallbackStyleAffinity(candidate,hotelStyle),style=hotelStyle==="any"?70:vectorAffinity(candidate,styleVectorIndex[hotelStyle],styleFallback),traveler=vectorAffinity(candidate,travelerVectorIndex[request.travelerType],68),location=locationAffinity(candidate.distanceKm,stayLocationPreference),soft=spec.soft.length?50+50*(evaluation.softMatches.length/spec.soft.length):70,truthScore=candidate.availabilityTruth==="CONFIRMED_ACTIVE"?82:65,fuzzy=contract&&candidate.semanticVector.length===24?fuzzyVectorFitV23(candidate.semanticVector,contract):null,semantic=fuzzy?clamp(fuzzy.fit*100-fuzzy.negativeConflict*10):70;const score=fuzzy?style*.24+traveler*.10+location*.16+soft*.14+truthScore*.08+semantic*.28:style*.36+traveler*.16+location*.20+soft*.20+truthScore*.08;return{eligible:true,score:clamp(score),softMatches:evaluation.softMatches.length,hardFailures:[] as StayConstraintKind[]};}
function hasAccommodationSignal(request:TripRequest,spec:StayConstraintSpec,intent:V8IntentProfile){return spec.hard.length>0||spec.soft.length>0||(request.hotelStyle??"any")!=="any"||(request.stayLocationPreference??"balanced")!=="balanced"||Boolean(request.tripText&&intent.semantic24);}
export async function applyChoiceCorrectnessV21(request:TripRequest,intent:V8IntentProfile,spec:StayConstraintSpec,ranked:V8Ranked[]):Promise<{ranked:V8Ranked[];audit:V21ChoiceAudit}>{const semanticRejected:string[]=[],semanticSurvivors=ranked.filter(item=>{const reason=structuredEligibilityReasonV21(item,request)??semanticEligibilityReasonV21(item,intent);if(reason){semanticRejected.push(`${item.destination.slug}:${reason}`);return false}return true}),baseAudit:V21ChoiceAudit={semanticRejected,stayScanRan:false,stayScanFailed:false,mappedStayCount:0,destinationsWithMappedStays:0,hardStayRejected:[],bestStayFit:{}};if(!hasAccommodationSignal(request,spec,intent)||!semanticSurvivors.length)return{ranked:semanticSurvivors,audit:baseAudit};try{const stays=await loadGlobalStayCandidatesV21(request.startDate,request.endDate,60),bySlug=new Map<string,GlobalStayCandidateV21[]>();for(const stay of stays){const list=bySlug.get(stay.destinationSlug)??[];list.push(stay);bySlug.set(stay.destinationSlug,list)}const hardStayRejected:string[]=[],bestStayFit:Record<string,number>={},rescored:V8Ranked[]=[];for(const item of semanticSurvivors){const candidates=bySlug.get(item.destination.slug)??[],scores=candidates.map(candidate=>scoreGlobalStayCandidateV21(candidate,request,spec,intent.semantic24)).filter(row=>row.eligible).map(row=>row.score),best=scores.length?Math.max(...scores):null;if(spec.hard.length&&best==null){hardStayRejected.push(item.destination.slug);continue}if(best!=null)bestStayFit[item.destination.slug]=Math.round(best);const delta=best==null?-3:clamp((best-62)*.14,-4,8),score=clamp(item.score+delta);rescored.push({...item,score,preScore:clamp(item.preScore+delta)});}rescored.sort((a,b)=>b.score-a.score);return{ranked:rescored,audit:{semanticRejected,stayScanRan:true,stayScanFailed:false,mappedStayCount:stays.length,destinationsWithMappedStays:bySlug.size,hardStayRejected,bestStayFit}};}catch{return{ranked:semanticSurvivors,audit:{...baseAudit,stayScanRan:true,stayScanFailed:true}};}}
