import { loadLocalityStayOffersV24 } from "@/lib/data/locality-stays-v24";
import { evaluateStayOfferV16 } from "@/lib/decision/stay-constraints-v16";
import { scoreStayOffer,stayOfferCriterionDeltaV23 } from "@/lib/decision/stay-offer-score";
import { semanticEligibilityReasonV21,structuredEligibilityReasonV21 } from "@/lib/decision/choice-correctness-v21";
import type { StayConstraintSpec,V8IntentProfile,V8StayOffer } from "@/lib/decision/v8-types";
import type { V8Ranked } from "@/lib/decision/v8-matcher";
import type { TripRequest } from "@/lib/validation/trip";

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
export interface V24ChoiceAudit{semanticRejected:string[];stayScanRan:boolean;checkedLocalities:number;retrievalFailed:string[];hardStayRejected:string[];bestStayFit:Record<string,number>;}
function accommodationSignal(request:TripRequest,spec:StayConstraintSpec,intent:V8IntentProfile){return spec.hard.length>0||spec.soft.length>0||(request.hotelStyle??"any")!=="any"||(request.stayLocationPreference??"balanced")!=="balanced"||Boolean(request.tripText&&intent.semantic24)}
function offerFit(offer:V8StayOffer,request:TripRequest,spec:StayConstraintSpec,intent:V8IntentProfile){const evaluation=evaluateStayOfferV16(offer,spec);if(evaluation.hardFailures.length)return null;const semanticDelta=stayOfferCriterionDeltaV23(offer,spec,intent.semantic24),scored={...offer,semanticScore:semanticDelta};const raw=scoreStayOffer(scored,request.hotelStyle,request.stayLocationPreference);return clamp(50+(raw-95)*.72,0,100)}
export async function applyChoiceCorrectnessV24(request:TripRequest,intent:V8IntentProfile,spec:StayConstraintSpec,ranked:V8Ranked[]):Promise<{ranked:V8Ranked[];audit:V24ChoiceAudit}>{const semanticRejected:string[]=[],survivors=ranked.filter(item=>{const reason=structuredEligibilityReasonV21(item,request)??semanticEligibilityReasonV21(item,intent);if(reason){semanticRejected.push(`${item.destination.slug}:${reason}`);return false}return true}),base:V24ChoiceAudit={semanticRejected,stayScanRan:false,checkedLocalities:0,retrievalFailed:[],hardStayRejected:[],bestStayFit:{}};if(!survivors.length||!accommodationSignal(request,spec,intent))return{ranked:survivors,audit:base};
 const retrievalFailed:string[]=[],hardStayRejected:string[]=[],bestStayFit:Record<string,number>={},rescored:V8Ranked[]=[];for(let offset=0;offset<survivors.length;offset+=8){const batch=survivors.slice(offset,offset+8),rows=await Promise.all(batch.map(async item=>{const localityId=item.destination.localityId;if(!localityId)return{item,offers:[] as V8StayOffer[],failed:true};try{return{item,offers:await loadLocalityStayOffersV24(localityId,request.startDate,request.endDate,30),failed:false}}catch{return{item,offers:[] as V8StayOffer[],failed:true}}}));for(const row of rows){const slug=row.item.destination.slug;if(row.failed)retrievalFailed.push(slug);const fits=row.offers.map(offer=>offerFit(offer,request,spec,intent)).filter((x):x is number=>x!=null),best=fits.length?Math.max(...fits):null;if(spec.hard.length&&best==null){hardStayRejected.push(slug);continue}if(best!=null)bestStayFit[slug]=Math.round(best);const delta=best==null?-4:clamp((best-55)*.16,-4,8),score=clamp(row.item.score+delta);rescored.push({...row.item,score,preScore:clamp(row.item.preScore+delta)})}}
 rescored.sort((a,b)=>b.score-a.score);return{ranked:rescored,audit:{semanticRejected,stayScanRan:true,checkedLocalities:survivors.length,retrievalFailed,hardStayRejected,bestStayFit}};}
