import type { LocalityProfileV23 } from "@/lib/data/locality-profiles-v23";
import { buildFuzzyContractV23,fuzzyVectorFitV23 } from "@/lib/decision/fuzzy-semantic-v23";
import type { V8IntentProfile } from "@/lib/decision/v8-types";
import type { V8Ranked } from "@/lib/decision/v8-matcher";
import type { TripRequest } from "@/lib/validation/trip";

const clamp=(value:number,min=0,max=100)=>Math.max(min,Math.min(max,value));
export interface LocalityNativeAuditV24{localityCount:number;candidatesWithExactLocality:number;localityOnlyCandidates:number;freeTextWeight:number;contractConfidence:number;fitByCandidate:Record<string,number>;scoreDelta:Record<string,number>;topLocalities:Array<{candidateSlug:string;localityId:string;label:string;fit:number;confidence:number;canonicalParentSlug:string|null}>;}
function calibrated(raw:number,confidence:number){const strength=.42+.58*Math.max(0,Math.min(1,confidence));return .5+(raw-.5)*strength;}
export function applyLocalityNativeRankingV24(request:TripRequest,intent:V8IntentProfile,items:V8Ranked[],localities:LocalityProfileV23[]):{ranked:V8Ranked[];audit:LocalityNativeAuditV24}{const contract=intent.semantic24??buildFuzzyContractV23(request,intent.semantic),byId=new Map(localities.map(x=>[x.localityId,x] as const)),hasFreeText=Boolean(request.tripText&&request.tripText.trim().length>=3),freeTextWeight=hasFreeText?.58:.36,fitByCandidate:Record<string,number>={},scoreDelta:Record<string,number>={},topLocalities:LocalityNativeAuditV24["topLocalities"]=[],ranked=items.map(item=>{const id=item.destination.localityId,locality=id?byId.get(id):undefined;if(!locality)return item;const raw=fuzzyVectorFitV23(locality.semanticVector,contract),fit=calibrated(raw.fit,locality.profileConfidence),primary=contract.priorities[0],primaryIndex=primary?[
"relax","romantic","food","warmth","city","nature","adventure","culture","luxury","boutique","resort","value","family","couple","solo","friends","low_effort","warm_climate","all_weather","beach_season","nightlife","wellness","short_break","shoulder_season"].indexOf(primary):-1,primaryMembership=primaryIndex>=0?locality.semanticVector[primaryIndex]??.5:.5,priorityFloor=primary&&(contract.positive[primary]??0)>=.82?Math.max(-14,Math.min(8,(primaryMembership-.55)*30)):0,negativePenalty=raw.negativeConflict*14,blend=item.score*(1-freeTextWeight)+fit*100*freeTextWeight,score=clamp(blend+priorityFloor-negativePenalty),delta=score-item.score;fitByCandidate[item.destination.slug]=Number((fit*100).toFixed(1));scoreDelta[item.destination.slug]=Number(delta.toFixed(2));topLocalities.push({candidateSlug:item.destination.slug,localityId:locality.localityId,label:locality.locationLabel,fit:Number((fit*100).toFixed(1)),confidence:Number(locality.profileConfidence.toFixed(2)),canonicalParentSlug:locality.canonicalSlug});return{...item,score,preScore:clamp(item.preScore+delta)}}).sort((a,b)=>b.score-a.score);return{ranked,audit:{localityCount:localities.length,candidatesWithExactLocality:Object.keys(fitByCandidate).length,localityOnlyCandidates:localities.filter(x=>!x.canonicalSlug).length,freeTextWeight,contractConfidence:Number(contract.confidence.toFixed(3)),fitByCandidate,scoreDelta,topLocalities:topLocalities.sort((a,b)=>b.fit-a.fit).slice(0,15)}};}
