import type { WeatherEvidence,Confidence } from "@/lib/decision/types";
import type { TripRequest } from "@/lib/validation/trip";
import { V8_DIMENSIONS,type V8Destination,type V8Dimension,type V8ExplorationRole,type V8IntentProfile,type V8Recommendation,type V8ScoreBreakdown } from "@/lib/decision/v8-types";
import { geographyConstraint,GREEK_ISLAND_SLUGS,matchesGeographyConstraint } from "@/lib/decision/geography-constraint";
import type { V8Ranked } from "@/lib/decision/v8-matcher";

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const norm=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zα-ω0-9]+/gi," ").trim();
const index=Object.fromEntries(V8_DIMENSIONS.map((d,i)=>[d,i])) as Record<V8Dimension,number>;
const effectiveSlug=(d:V8Destination)=>d.canonicalParentSlug??d.slug;
const isIsland=(d:V8Destination)=>GREEK_ISLAND_SLUGS.has(effectiveSlug(d));
const effortBase:Record<string,number>={local:100,"road-near":96,"ferry-easy":90,"road-medium":82,"domestic-flight":80,"short-flight":78,"domestic-flight-plus-road":68,"medium-flight":62,"ferry-long":58,"road-long":55,"long-flight":44,medium:62};
const origins:Record<string,{lat:number;lon:number}>={athens:{lat:37.984,lon:23.728},thessaloniki:{lat:40.640,lon:22.944},patras:{lat:38.246,lon:21.735},heraklion:{lat:35.338,lon:25.144},larissa:{lat:39.639,lon:22.419},ioannina:{lat:39.665,lon:20.853}};
const radians=(value:number)=>value*Math.PI/180;
function km(a:{lat:number;lon:number},b:{latitude:number;longitude:number}){const dLat=radians(b.latitude-a.lat),dLon=radians(b.longitude-a.lon),x=Math.sin(dLat/2)**2+Math.cos(radians(a.lat))*Math.cos(radians(b.latitude))*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function originPoint(origin:string){const n=norm(origin);if(n.includes("thessalon" )||n.includes("θεσσαλον"))return origins.thessaloniki;if(n.includes("patr")||n.includes("πατρ"))return origins.patras;if(n.includes("herak")||n.includes("ηρακλ"))return origins.heraklion;if(n.includes("laris")||n.includes("λαρισ"))return origins.larissa;if(n.includes("ioannin")||n.includes("ιωανν"))return origins.ioannina;return origins.athens;}
function isOrigin(r:TripRequest,d:V8Destination){const o=norm(r.origin);return[norm(d.nameEl),norm(d.nameEn),...d.aliases.map(norm)].includes(o)}
function intentFit(intent:V8IntentProfile,d:V8Destination){let sum=0,wSum=0;for(const dim of V8_DIMENSIONS){const w=intent.weights[dim]??0;if(w<=.01)continue;sum+=w*(d.vector[index[dim]]??.05);wSum+=w}return wSum?clamp(sum/wSum*100):55}
function seasonFit(r:TripRequest,d:V8Destination){const m=Math.max(1,Math.min(12,Number(r.startDate.slice(5,7))))-1;return clamp(d.monthFit[m]??60)}
function durationFit(r:TripRequest,d:V8Destination){if(r.nights>=d.idealNightsMin&&r.nights<=d.idealNightsMax)return 100;const diff=r.nights<d.idealNightsMin?d.idealNightsMin-r.nights:r.nights-d.idealNightsMax;return clamp(100-diff*18,35,100)}
function budgetTarget(r:TripRequest){const people=Math.max(1,r.groupSize??(r.travelerType==="solo"?1:r.travelerType==="couple"?2:4)),perPersonNight=r.budget/Math.max(2,r.nights)/people;if(perPersonNight<55)return 1;if(perPersonNight<90)return 2;if(perPersonNight<145)return 3;if(perPersonNight<225)return 4;return 5}
function budgetFit(r:TripRequest,d:V8Destination){const target=budgetTarget(r),over=Math.max(0,d.costTier-target),under=Math.max(0,target-d.costTier);let s=100-over*23-under*2;if(r.avoid==="high-cost"&&d.costTier>=4)s-=18;if(d.tags.includes("value"))s+=5;return clamp(s,20,100)}
function effort(r:TripRequest,d:V8Destination){const parent=d.canonicalParentSlug?true:false;let klass=(norm(r.origin).includes("thessalon")||norm(r.origin).includes("θεσσαλον"))?d.effortThessaloniki:d.effortAthens;let base=effortBase[klass];if(base==null||!parent){const distance=km(originPoint(r.origin),d);base=distance<70?94:distance<160?84:distance<300?73:distance<500?63:53;klass=parent?klass:"route-needs-verification";if(isIsland(d)&&!d.canonicalParentSlug)base-=6;}
 let s=base;if(r.nights<=3&&s<70)s-=10;if(r.distancePreference==="nearby")s+=s>=85?4:-30;if(r.distancePreference==="easy-hop"&&s<68)s-=15;if(r.avoid==="long-travel"&&s<75)s-=18;s=s*.84+d.routeConfidence*16;return{score:clamp(s,20,100),klass};}
function travelerFit(r:TripRequest,d:V8Destination){const explicit=d.travelerFit[r.travelerType];if(Number.isFinite(explicit))return clamp(Number(explicit)*100,45,100);if(r.travelerType==="family")return d.tags.includes("family")?96:74;if(r.travelerType==="couple")return d.tags.includes("romantic")?97:d.tags.includes("relax")?89:80;if(r.travelerType==="friends")return d.tags.includes("nightlife")||d.tags.includes("adventure")?95:78;return d.tags.includes("city")||d.tags.includes("culture")||d.tags.includes("adventure")?92:80}
function crowdFit(r:TripRequest,d:V8Destination){if(r.avoid==="crowds")return clamp(112-d.crowdLevel*18,22,100);if(r.socialPreference==="quiet")return clamp(108-d.crowdLevel*14,38,100);if(r.socialPreference==="lively")return clamp(58+d.crowdLevel*8,60,98);return clamp(100-(d.crowdLevel-1)*5,75,100)}
function matchesMustHave(r:TripRequest,d:V8Destination){if(r.mustHave==="sea")return d.tags.includes("beach");if(r.mustHave==="nature")return d.tags.includes("nature");if(r.mustHave==="culture")return d.tags.includes("culture");if(r.mustHave==="nightlife")return d.tags.includes("nightlife")||d.tags.includes("city");return true}
function consideredFit(r:TripRequest,d:V8Destination){const candidate=norm(r.consideredDestination??"");if(!candidate)return false;return[norm(d.slug),norm(d.nameEl),norm(d.nameEn),norm(d.localityLabel??""),norm(d.canonicalParentSlug??""),...d.aliases.map(norm)].some(value=>value&& (value===candidate||value.includes(candidate)||candidate.includes(value)))}
function weights(r:TripRequest,intent:V8IntentProfile){const outdoor=Math.max(intent.weights.warmth,intent.weights.beach,intent.weights.nature,intent.weights.adventure);if(outdoor>=.7)return{intent:.30,season:.15,effort:.13,duration:.08,budget:.08,weather:.14,traveler:.07,crowd:.05};if(outdoor>=.35)return{intent:.32,season:.16,effort:.13,duration:.08,budget:.09,weather:.10,traveler:.07,crowd:.05};return{intent:.33,season:.16,effort:.14,duration:.08,budget:.09,weather:.06,traveler:.08,crowd:.06}}
function compute(r:TripRequest,intent:V8IntentProfile,d:V8Destination,weather?:WeatherEvidence|null):V8Ranked{const e=effort(r,d),b:V8ScoreBreakdown={intent:Math.round(intentFit(intent,d)),season:Math.round(seasonFit(r,d)),effort:Math.round(e.score),duration:Math.round(durationFit(r,d)),budget:Math.round(budgetFit(r,d)),weather:Math.round(weather?.score??62),traveler:Math.round(travelerFit(r,d)),crowdFit:Math.round(crowdFit(r,d)),routeConfidence:Math.round(d.routeConfidence*100)},w=weights(r,intent);let score=b.intent*w.intent+b.season*w.season+b.effort*w.effort+b.duration*w.duration+b.budget*w.budget+b.weather*w.weather+b.traveler*w.traveler+b.crowdFit*w.crowd;
 if(isOrigin(r,d))score=0;if(r.distancePreference==="island"&&!isIsland(d))score=0;if(!matchesMustHave(r,d))score=0;if(r.avoid==="crowds"&&d.crowdLevel>=5)score=Math.min(score-16,20);if(r.avoid==="high-cost"&&d.costTier>budgetTarget(r)+1)score-=18;if(r.socialPreference==="quiet"&&d.crowdLevel>=5)score-=9;if(consideredFit(r,d)&&b.season>=55&&b.budget>=48)score+=12;if(b.season<40)score-=8;if(r.moods.includes("warmth")&&b.season<55)score=Math.min(score,48);if(r.distancePreference==="nearby"&&e.score<70)score-=25+(70-e.score)*1.5;if(r.distancePreference==="easy-hop"&&e.score<55)score-=20+(55-e.score);if(r.transportMode==="no-car"&&e.score<58)score-=14;if(r.avoid==="long-travel"&&e.score<60)score-=22+(60-e.score);if(weather?.temperatureMeanC!=null&&r.moods.includes("warmth")&&weather.temperatureMeanC<18)score=Math.min(score,46);return{destination:d,score:clamp(score),preScore:clamp(score),breakdown:b,weather};}

export function preRankV24(r:TripRequest,intent:V8IntentProfile,catalog:V8Destination[],limit=60){const geo=geographyConstraint(r,catalog),eligible=catalog.filter(d=>matchesGeographyConstraint(d,geo)&&(r.distancePreference!=="island"||isIsland(d))&&matchesMustHave(r,d)&&(r.avoid!=="crowds"||d.crowdLevel<5)&&(r.avoid!=="high-cost"||d.costTier<5)),ranked=eligible.map(d=>compute(r,intent,d)).filter(x=>x.score>0).sort((a,b)=>b.score-a.score),size=Math.max(24,Math.min(120,limit)),selected=ranked.slice(0,size),considered=ranked.find(x=>consideredFit(r,x.destination));if(considered&&!selected.some(x=>x.destination.slug===considered.destination.slug)){if(selected.length>=size)selected[selected.length-1]=considered;else selected.push(considered)}return selected;}
export function finalRankV24(r:TripRequest,intent:V8IntentProfile,pre:V8Ranked[],weather:Map<string,WeatherEvidence>){return pre.map(x=>compute(r,intent,x.destination,weather.get(x.destination.slug)??null)).sort((a,b)=>b.score-a.score)}
function jaccard(a:string[],b:string[]){const A=new Set(a),B=new Set(b),i=[...A].filter(x=>B.has(x)).length,u=new Set([...a,...b]).size;return u?i/u:0}
function diversityValue(candidate:V8Ranked,selected:V8Ranked[]){if(!selected.length)return candidate.score;const semanticSimilarity=Math.max(...selected.map(s=>jaccard(s.destination.tags,candidate.destination.tags))),sameParent=selected.some(s=>Boolean(candidate.destination.canonicalParentSlug)&&s.destination.canonicalParentSlug===candidate.destination.canonicalParentSlug),sameRegion=selected.filter(s=>s.destination.regionGroup===candidate.destination.regionGroup).length;return candidate.score-semanticSimilarity*13-(sameParent?18:0)-sameRegion*5;}
export function diversifyV24(ranked:V8Ranked[],count=12){const pool=[...ranked],selected:V8Ranked[]=[];while(pool.length&&selected.length<count){let bestIndex=0,best=-Infinity;for(let i=0;i<pool.length;i++){const value=diversityValue(pool[i],selected);if(value>best){best=value;bestIndex=i}}const item=pool.splice(bestIndex,1)[0],roles:V8ExplorationRole[]=["BEST_FIT","EASIEST","QUIETER","SMART_VALUE","GEOGRAPHY_CONTRAST","BEST_SEASON","NATURE_AND_SEA","CITY_AND_SEA","HIDDEN_GEM","DIFFERENT_RHYTHM","WILDCARD","ALTERNATIVE"];selected.push({...item,explorationRole:roles[selected.length]??"ALTERNATIVE"})}return selected;}
function confidenceFor(item:V8Ranked):Confidence{return item.destination.routeConfidence>=.75&&item.destination.localityProfileConfidence!=null&&item.destination.localityProfileConfidence>=.7?"HIGH":"MEDIUM"}
function roleText(role:V8ExplorationRole){return role.replaceAll("_"," ").toLowerCase()}
export function toRecommendationsV24(r:TripRequest,items:V8Ranked[]):V8Recommendation[]{return items.map((item,index)=>{const d=item.destination,role=item.explorationRole??(index===0?"BEST_FIT":"ALTERNATIVE"),why=r.language==="en"?`${d.nameEn} matches the strongest parts of your brief while keeping the main trade-offs visible.`:`Το ${d.nameEl} ταιριάζει στα ισχυρότερα στοιχεία του brief σου, χωρίς να κρύβει τα βασικά trade-offs.`;return{slug:d.slug,destination:d.nameEl,destinationEn:d.nameEn,country:r.language==="en"?d.countryEn:d.countryEl,countryCode:d.countryCode,regionGroup:d.regionGroup,role:roleText(role),explorationRole:role,explorationReason:roleText(role),score:Math.round(item.score),fitStatus:item.score>=74?"strong":item.score>=60?"good":"compromise",confidence:confidenceFor(item),why,seasonNote:r.language==="en"?`Season fit ${item.breakdown.season}/100.`:`Εποχική καταλληλότητα ${item.breakdown.season}/100.`,effortLabel:r.language==="en"?`Travel effort ${item.breakdown.effort}/100`:`Κόπος μετάβασης ${item.breakdown.effort}/100`,budgetLabel:r.language==="en"?`Budget fit ${item.breakdown.budget}/100`:`Ταίριασμα budget ${item.breakdown.budget}/100`,tags:d.tags,latitude:d.latitude,longitude:d.longitude,directFromAthens:d.directFromAthens,routeConfidence:d.routeConfidence,breakdown:item.breakdown,weather:item.weather??null,localityId:d.localityId,localityLabel:d.localityLabel,canonicalParentSlug:d.canonicalParentSlug??null};});}
export function responseFeasibilityV24(items:V8Ranked[]):"STRONG"|"MIXED"|"COMPROMISE"{if(!items.length)return"COMPROMISE";const top=items.slice(0,3),avg=top.reduce((s,x)=>s+x.score,0)/top.length;if(avg>=74&&top.every(x=>x.breakdown.budget>=45&&x.breakdown.season>=48))return"STRONG";if(avg>=58)return"MIXED";return"COMPROMISE";}
