import type { WeatherEvidence,Confidence } from "@/lib/decision/types";
import type { TripRequest } from "@/lib/validation/trip";
import { V8_DIMENSIONS,type V8Destination,type V8Dimension,type V8IntentProfile,type V8Recommendation,type V8ScoreBreakdown } from "@/lib/decision/v8-types";

export interface V8Ranked{destination:V8Destination;score:number;preScore:number;breakdown:V8ScoreBreakdown;weather?:WeatherEvidence|null}
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const norm=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zα-ω0-9]+/gi," ").trim();
const index=Object.fromEntries(V8_DIMENSIONS.map((d,i)=>[d,i])) as Record<V8Dimension,number>;
const effortBase:Record<string,number>={local:100,"road-near":96,"ferry-easy":90,"road-medium":82,"domestic-flight":80,"short-flight":78,"domestic-flight-plus-road":68,"medium-flight":62,"ferry-long":58,"road-long":55,"long-flight":44,medium:62};
export const V8_ISLAND_SLUGS=new Set(["aegina","chania","corfu","hydra","naxos","paros","rhodes","santorini","syros"]);

function isOrigin(r:TripRequest,d:V8Destination){const o=norm(r.origin);return[norm(d.nameEl),norm(d.nameEn),...d.aliases.map(norm)].includes(o)}
function intentFit(intent:V8IntentProfile,d:V8Destination){let sum=0,wSum=0;for(const dim of V8_DIMENSIONS){const w=intent.weights[dim]??0;if(w<=.01)continue;sum+=w*(d.vector[index[dim]]??.05);wSum+=w}return wSum?clamp(sum/wSum*100):55}
function seasonFit(r:TripRequest,d:V8Destination){const m=Math.max(1,Math.min(12,Number(r.startDate.slice(5,7))))-1;return clamp(d.monthFit[m]??60)}
function durationFit(r:TripRequest,d:V8Destination){if(r.nights>=d.idealNightsMin&&r.nights<=d.idealNightsMax)return 100;const diff=r.nights<d.idealNightsMin?d.idealNightsMin-r.nights:r.nights-d.idealNightsMax;return clamp(100-diff*19,35,100)}
function budgetTarget(r:TripRequest){const people=Math.max(1,r.groupSize??(r.travelerType==="solo"?1:r.travelerType==="couple"?2:4)),perPersonNight=r.budget/Math.max(2,r.nights)/people;if(perPersonNight<55)return 1;if(perPersonNight<90)return 2;if(perPersonNight<145)return 3;if(perPersonNight<225)return 4;return 5}
function budgetFit(r:TripRequest,d:V8Destination){const target=budgetTarget(r),over=Math.max(0,d.costTier-target),under=Math.max(0,target-d.costTier);let s=100-over*23-under*2;if(r.avoid==="high-cost"&&d.costTier>=4)s-=18;if(d.tags.includes("value"))s+=5;return clamp(s,20,100)}
function effort(r:TripRequest,d:V8Destination){const o=norm(r.origin),fromThess=o.includes("θεσσαλον")||o.includes("thessalon"),fromPatras=o.includes("πατρ")||o.includes("patr"),fromCrete=o.includes("ηρακλ")||o.includes("herakl");let klass=fromThess?d.effortThessaloniki:d.effortAthens;if(fromPatras&&d.regionGroup==="peloponnese")klass="road-near";else if(fromPatras&&d.regionGroup==="ionian")klass="road-medium";else if(fromCrete&&d.regionGroup==="crete")klass="road-medium";else if(fromCrete&&d.slug==="rhodes")klass="domestic-flight";let s=effortBase[klass]??60;if(r.nights<=3&&s<70)s-=10;if(r.distancePreference==="nearby")s+=s>=85?4:-30;if(r.distancePreference==="easy-hop"&&s<68)s-=15;if(r.avoid==="long-travel"&&s<75)s-=18;if(!fromThess&&(o.includes("athen")||o.includes("αθην"))&&d.directFromAthens&&klass.includes("flight"))s+=6;s=s*.88+d.routeConfidence*12;return{score:clamp(s,20,100),klass}}
function travelerFit(r:TripRequest,d:V8Destination){if(r.travelerType==="family")return d.tags.includes("family")?98:d.tags.includes("nightlife")?62:78;if(r.travelerType==="couple")return d.tags.includes("romantic")?98:d.tags.includes("relax")?90:82;if(r.travelerType==="friends")return d.tags.includes("nightlife")||d.tags.includes("adventure")?96:d.tags.includes("city")?90:75;return d.tags.includes("city")||d.tags.includes("culture")||d.tags.includes("adventure")?94:82}
function crowdFit(r:TripRequest,d:V8Destination){if(r.avoid==="crowds")return clamp(112-d.crowdLevel*18,22,100);if(r.socialPreference==="quiet")return clamp(108-d.crowdLevel*14,38,100);if(r.socialPreference==="lively")return clamp(58+d.crowdLevel*8,60,98);return clamp(100-(d.crowdLevel-1)*5,75,100)}
function matchesMustHave(r:TripRequest,d:V8Destination){if(r.mustHave==="sea")return d.tags.includes("beach");if(r.mustHave==="nature")return d.tags.includes("nature");if(r.mustHave==="culture")return d.tags.includes("culture");if(r.mustHave==="nightlife")return d.tags.includes("nightlife")||d.tags.includes("city");return true}
function consideredFit(r:TripRequest,d:V8Destination){const candidate=norm(r.consideredDestination??"");if(!candidate)return false;return[norm(d.slug),norm(d.nameEl),norm(d.nameEn),...d.aliases.map(norm)].some(value=>value===candidate||value.includes(candidate)||candidate.includes(value))}
function weights(r:TripRequest,intent:V8IntentProfile){const outdoor=Math.max(intent.weights.warmth,intent.weights.beach,intent.weights.nature,intent.weights.adventure);if(outdoor>=.7)return{intent:.31,season:.16,effort:.12,duration:.09,budget:.08,weather:.14,traveler:.08,crowd:.02};if(outdoor>=.35)return{intent:.33,season:.18,effort:.12,duration:.09,budget:.09,weather:.10,traveler:.07,crowd:.02};return{intent:.34,season:.18,effort:.12,duration:.09,budget:.09,weather:.06,traveler:.08,crowd:.04}}
function compute(r:TripRequest,intent:V8IntentProfile,d:V8Destination,weather?:WeatherEvidence|null):V8Ranked{
 const e=effort(r,d),b:V8ScoreBreakdown={intent:Math.round(intentFit(intent,d)),season:Math.round(seasonFit(r,d)),effort:Math.round(e.score),duration:Math.round(durationFit(r,d)),budget:Math.round(budgetFit(r,d)),weather:Math.round(weather?.score??62),traveler:Math.round(travelerFit(r,d)),crowdFit:Math.round(crowdFit(r,d)),routeConfidence:Math.round(d.routeConfidence*100)},w=weights(r,intent);
 let score=b.intent*w.intent+b.season*w.season+b.effort*w.effort+b.duration*w.duration+b.budget*w.budget+b.weather*w.weather+b.traveler*w.traveler+b.crowdFit*w.crowd;
 if(isOrigin(r,d))score=0;if(r.distancePreference==="island"&&!V8_ISLAND_SLUGS.has(d.slug))score=0;if(!matchesMustHave(r,d))score=0;if(r.moods.includes("warmth")&&!d.tags.includes("warmth"))score=Math.min(score-12,52);if(r.avoid==="crowds"&&d.crowdLevel>=5)score-=16;if(r.avoid==="high-cost"&&d.costTier>budgetTarget(r)+1)score-=18;if(r.avoid==="high-cost"&&d.costTier>=5)score=Math.min(score,45);if(r.socialPreference==="quiet"&&d.crowdLevel>=5)score-=9;if(r.noveltyPreference==="surprise"&&d.crowdLevel<=3)score+=4;if(r.noveltyPreference==="familiar"&&d.routeConfidence>=.95)score+=3;if(consideredFit(r,d)&&b.season>=55&&b.budget>=48)score+=7;if(b.season<40)score-=8;
 // Explicit warmth is a feasibility requirement, not a soft style preference. Diversity cannot rescue a cold/off-season beach destination.
 if(r.moods.includes("warmth")&&b.season<55)score=Math.min(score,48);
 if(r.moods.includes("warmth")&&weather&&weather.source!=="unavailable"&&weather.score<55)score=Math.min(score,48);
 if(r.moods.includes("warmth")&&weather?.temperatureMeanC!=null&&weather.temperatureMeanC<18)score=Math.min(score,46);
 return{destination:d,score:clamp(score),preScore:clamp(score),breakdown:b,weather};
}

export function preRankV8(r:TripRequest,intent:V8IntentProfile,catalog:V8Destination[],limit=18){const eligible=catalog.filter(d=>(!r.moods.includes("warmth")||d.tags.includes("warmth"))&&(r.distancePreference!=="island"||V8_ISLAND_SLUGS.has(d.slug))&&matchesMustHave(r,d));return eligible.map(d=>compute(r,intent,d,null)).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,Math.max(10,limit))}
export function finalRankV8(r:TripRequest,intent:V8IntentProfile,pre:V8Ranked[],weather:Map<string,WeatherEvidence>){return pre.map(x=>compute(r,intent,x.destination,weather.get(x.destination.slug)??null)).sort((a,b)=>b.score-a.score)}
function jaccard(a:string[],b:string[]){const A=new Set(a),B=new Set(b),i=[...A].filter(x=>B.has(x)).length,u=new Set([...a,...b]).size;return u?i/u:0}
export function diversifyV8(ranked:V8Ranked[],count=6){const pool=[...ranked],selected:V8Ranked[]=[];while(pool.length&&selected.length<count){let bi=0,bv=-Infinity;for(let i=0;i<pool.length;i++){const c=pool[i],sameRegion=selected.filter(x=>x.destination.regionGroup===c.destination.regionGroup).length,sim=selected.length?Math.max(...selected.map(x=>jaccard(x.destination.tags,c.destination.tags))):0,regionPenalty=sameRegion>=2?55:sameRegion*8,adjusted=c.score-regionPenalty-sim*7;if(adjusted>bv){bv=adjusted;bi=i}}selected.push(pool.splice(bi,1)[0])}return selected}

function effortLabel(r:TripRequest,d:V8Destination){const k=effort(r,d).klass,el=r.language!=="en",m:Record<string,[string,string]>={local:["τοπικά","local"],"road-near":["κοντινή οδική απόδραση","nearby road trip"],"road-medium":["μεσαία οδική διαδρομή","medium road trip"],"road-long":["μεγαλύτερη οδική διαδρομή","longer road trip"],"ferry-easy":["εύκολη ακτοπλοϊκή απόδραση","easy ferry escape"],"ferry-long":["μεγαλύτερη ακτοπλοϊκή διαδρομή","longer ferry trip"],"domestic-flight":["σύντομη εσωτερική πτήση","short domestic flight"],"domestic-flight-plus-road":["πτήση + οδική συνέχεια","flight + road connection"],"short-flight":["σύντομη πτήση","short flight"],"medium-flight":["μεσαία πτήση","medium flight"],"long-flight":["μεγαλύτερη πτήση","longer flight"]};return m[k]?.[el?0:1]??k}
function budgetLabel(r:TripRequest,d:V8Destination){const x=r.language!=="en"?["","οικονομικό","καλή αξία","μεσαίο κόστος","premium","υψηλό κόστος"]:["","budget","good value","mid-range","premium","high-cost"];return x[d.costTier]??"cost"}
function role(i:number,x:V8Ranked){if(i===0)return"BEST FIT";const b=x.breakdown;if(b.effort>=90)return"EASIEST";if(b.budget>=92&&x.destination.tags.includes("value"))return"SMART VALUE";if(b.season>=92)return"BEST THEN";if(x.destination.crowdLevel<=2)return"QUIETER";if(i>=4)return"WILDCARD";return"ALTERNATIVE"}
function conf(x:V8Ranked):Confidence{if(x.score>=82&&x.breakdown.intent>=75&&x.breakdown.season>=70&&x.destination.routeConfidence>=.75&&x.weather?.confidence!=="LOW")return"HIGH";if(x.score>=68&&x.breakdown.season>=55)return"MEDIUM";return"LOW"}
const feeling:Record<string,[string,string]>={romantic:["ρομαντισμό","romance"],relax:["ηρεμία","a slower rhythm"],food:["καλό φαγητό","great food"],culture:["πολιτισμό","culture"],city:["ζωντανή πόλη","city energy"],nature:["φύση","nature"],beach:["θάλασσα","the sea"],adventure:["περιπέτεια","adventure"],value:["καλή αξία","good value"],warmth:["ζεστό καιρό","warmer days"],wellness:["αποφόρτιση","time to reset"]};
function why(r:TripRequest,x:V8Ranked){const d=x.destination,el=r.language!=="en",themes=d.tags.filter(t=>feeling[t]).slice(0,3).map(t=>feeling[t][el?0:1]);const joined=themes.length>1?`${themes.slice(0,-1).join(", ")} ${el?"και":"and"} ${themes.at(-1)}`:themes[0]||(el?"αυτό που ζήτησες":"what you asked for");return el?`${d.nameEl}: συνδυάζει ${joined}, στην εποχή και στον ρυθμό μετακίνησης που διάλεξες.`:`${d.nameEn}: brings together ${joined}, at a time and travel pace that suit your brief.`}
function seasonNote(r:TripRequest,x:V8Ranked){if(x.weather&&x.weather.source!=="unavailable")return x.weather.summary;return r.language==="en"?"This period is a sound seasonal choice for the destination.":"Η περίοδος που διάλεξες είναι εποχικά κατάλληλη για τον προορισμό."}
function fitStatus(x:V8Ranked):V8Recommendation["fitStatus"]{if(x.score>=78&&x.breakdown.season>=65&&x.breakdown.budget>=55)return"strong";if(x.score>=64&&x.breakdown.season>=50)return"good";return"compromise"}
export function responseFeasibility(ranked:V8Ranked[]):"STRONG"|"MIXED"|"COMPROMISE"{const statuses=ranked.slice(0,6).map(fitStatus);if(statuses.filter(x=>x==="strong").length>=3)return"STRONG";if(statuses.some(x=>x!=="compromise"))return"MIXED";return"COMPROMISE"}
export function toRecommendationsV8(r:TripRequest,ranked:V8Ranked[],count=6):V8Recommendation[]{return ranked.slice(0,count).map((x,i)=>({slug:x.destination.slug,destination:r.language==="en"?x.destination.nameEn:x.destination.nameEl,destinationEn:x.destination.nameEn,country:r.language==="en"?x.destination.countryEn:x.destination.countryEl,countryCode:x.destination.countryCode,regionGroup:x.destination.regionGroup,role:role(i,x),score:Math.round(x.score),fitStatus:fitStatus(x),confidence:conf(x),why:why(r,x),seasonNote:seasonNote(r,x),effortLabel:effortLabel(r,x.destination),budgetLabel:budgetLabel(r,x.destination),tags:x.destination.tags.slice(0,7),latitude:x.destination.latitude,longitude:x.destination.longitude,directFromAthens:x.destination.directFromAthens,routeConfidence:x.destination.routeConfidence,breakdown:x.breakdown,weather:x.weather}))}
