import type { WeatherEvidence,Confidence } from "@/lib/decision/types";
import type { TripRequest } from "@/lib/validation/trip";
import { V8_DIMENSIONS,type V8Destination,type V8Dimension,type V8IntentProfile,type V8Recommendation,type V8ScoreBreakdown } from "@/lib/decision/v8-types";

export interface V8Ranked { destination:V8Destination; score:number; preScore:number; breakdown:V8ScoreBreakdown; weather?:WeatherEvidence|null; }
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const norm=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zα-ω0-9]+/gi," ").trim();
const dimIndex=Object.fromEntries(V8_DIMENSIONS.map((d,i)=>[d,i])) as Record<V8Dimension,number>;

function isOrigin(request:TripRequest,d:V8Destination){const o=norm(request.origin);return[o,norm(d.nameEl),norm(d.nameEn),...d.aliases.map(norm)].filter(Boolean).some(x=>x===o)}
function intentFit(intent:V8IntentProfile,d:V8Destination){let weighted=0,total=0;for(const dim of V8_DIMENSIONS){const w=intent.weights[dim]??0;if(w<=.01)continue;const trait=d.vector[dimIndex[dim]]??.05;weighted+=w*trait;total+=w;}return total?clamp(weighted/total*100):55}
function monthFit(request:TripRequest,d:V8Destination){const month=Math.max(1,Math.min(12,Number(request.startDate.slice(5,7))))-1;return clamp(d.monthFit[month]??60)}
function durationFit(request:TripRequest,d:V8Destination){if(request.nights>=d.idealNightsMin&&request.nights<=d.idealNightsMax)return 100;const diff=request.nights<d.idealNightsMin?d.idealNightsMin-request.nights:request.nights-d.idealNightsMax;return clamp(100-diff*19,35,100)}
function budgetTarget(budget:number,nights:number){const normalized=budget/Math.max(2,nights);if(budget<=300||normalized<105)return 1;if(budget<=450||normalized<145)return 2;if(budget<=650||normalized<205)return 3;if(budget<=950||normalized<300)return 4;return 5}
function budgetFit(request:TripRequest,d:V8Destination){const target=budgetTarget(request.budget,request.nights),over=Math.max(0,d.costTier-target),under=Math.max(0,target-d.costTier);let score=100-over*23-under*2;if(request.avoid==="high-cost"&&d.costTier>=4)score-=18;if(d.tags.includes("value"))score+=5;return clamp(score,20,100)}
const effortBase:Record<string,number>={local:100,"road-near":96,"ferry-easy":90,"road-medium":82,"domestic-flight":80,"short-flight":78,"domestic-flight-plus-road":68,"medium-flight":62,"ferry-long":58,"road-long":55,"long-flight":44,medium:62};
function effortForOrigin(request:TripRequest,d:V8Destination){const o=norm(request.origin);const klass=o.includes("θεσσαλον")||o.includes("thessalon")?d.effortThessaloniki:d.effortAthens;let score=effortBase[klass]??60;if(request.nights<=3&&score<70)score-=10;if(request.distancePreference==="nearby"){if(score<85)score-=30;else score+=4;}if(request.distancePreference==="easy-hop"&&score<68)score-=15;if(request.avoid==="long-travel"&&score<75)score-=18;if((o.includes("athen")||o.includes("αθην"))&&d.directFromAthens&&klass.includes("flight"))score+=6;score=score*.88+d.routeConfidence*12;return{score:clamp(score,20,100),klass}}
function travelerFit(request:TripRequest,d:V8Destination){const stored=Number(d.travelerFit?.[request.travelerType]);if(Number.isFinite(stored)&&Math.abs(stored-.8)>.001)return clamp(stored*100);if(request.travelerType==="family")return d.tags.includes("family")?98:d.tags.includes("nightlife")?62:78;if(request.travelerType==="couple")return d.tags.includes("romantic")?98:d.tags.includes("relax")?90:82;if(request.travelerType==="friends")return d.tags.includes("nightlife")||d.tags.includes("adventure")?96:d.tags.includes("city")?90:75;return d.tags.includes("city")||d.tags.includes("culture")||d.tags.includes("adventure")?94:82}
function crowdFit(request:TripRequest,d:V8Destination){if(request.avoid!=="crowds")return clamp(100-(d.crowdLevel-1)*5,75,100);return clamp(108-d.crowdLevel*16,28,100)}
function weatherImportance(request:TripRequest,intent:V8IntentProfile){const outdoor=Math.max(intent.weights.warmth,intent.weights.beach,intent.weights.nature,intent.weights.adventure);return outdoor>=.7?.16:outdoor>=.35?.11:.06}
function scoreWeights(request:TripRequest,intent:V8IntentProfile){const weather=weatherImportance(request,intent);return{intent:.38-(weather-.1)*.35,season:.20+(weather-.1)*.2,effort:.12,duration:.10,budget:.10,weather,traveler:.07,crowd:.03}}
function compute(request:TripRequest,intent:V8IntentProfile,d:V8Destination,weather?:WeatherEvidence|null):V8Ranked{
 const effort=effortForOrigin(request,d),breakdown:V8ScoreBreakdown={intent:Math.round(intentFit(intent,d)),season:Math.round(monthFit(request,d)),effort:Math.round(effort.score),duration:Math.round(durationFit(request,d)),budget:Math.round(budgetFit(request,d)),weather:Math.round(weather?.score??62),traveler:Math.round(travelerFit(request,d)),crowdFit:Math.round(crowdFit(request,d)),routeConfidence:Math.round(d.routeConfidence*100)};
 const w=scoreWeights(request,intent);let score=breakdown.intent*w.intent+breakdown.season*w.season+breakdown.effort*w.effort+breakdown.duration*w.duration+breakdown.budget*w.budget+breakdown.weather*w.weather+breakdown.traveler*w.traveler+breakdown.crowdFit*w.crowd;
 if(isOrigin(request,d))score=0;if(request.distancePreference==="island"&&!d.tags.includes("beach"))score-=10;if(request.moods.includes("warmth")&&!d.tags.includes("warmth"))score-=12;if(request.avoid==="crowds"&&d.crowdLevel>=5)score-=5;
 return{destination:d,score:clamp(score),preScore:clamp(score),breakdown,weather};
}

export function preRankV8(request:TripRequest,intent:V8IntentProfile,catalog:V8Destination[],limit=14):V8Ranked[]{return catalog.map(d=>compute(request,intent,d,null)).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,Math.max(8,limit))}
export function finalRankV8(request:TripRequest,intent:V8IntentProfile,pre:V8Ranked[],weather:Map<string,WeatherEvidence>):V8Ranked[]{return pre.map(x=>compute(request,intent,x.destination,weather.get(x.destination.slug)??null)).sort((a,b)=>b.score-a.score)}
function jaccard(a:string[],b:string[]){const A=new Set(a),B=new Set(b),inter=[...A].filter(x=>B.has(x)).length,union=new Set([...a,...b]).size;return union?inter/union:0}
export function diversifyV8(ranked:V8Ranked[],count=5):V8Ranked[]{const pool=[...ranked],selected:V8Ranked[]=[];while(pool.length&&selected.length<count){let bestIndex=0,best=-Infinity;for(let i=0;i<pool.length;i++){const c=pool[i],sameRegion=selected.filter(x=>x.destination.regionGroup===c.destination.regionGroup).length,similarity=selected.length?Math.max(...selected.map(x=>jaccard(x.destination.tags,c.destination.tags))):0,adjusted=c.score-sameRegion*7-similarity*8;if(adjusted>best){best=adjusted;bestIndex=i}}selected.push(pool.splice(bestIndex,1)[0]);}return selected}
function effortLabel(request:TripRequest,d:V8Destination){const {klass}=effortForOrigin(request,d);const el=request.language!=="en",map:Record<string,[string,string]>={local:["τοπικά","local"],"road-near":["κοντινή οδική απόδραση","nearby road trip"],"road-medium":["μεσαία οδική διαδρομή","medium road trip"],"road-long":["μεγαλύτερη οδική διαδρομή","longer road trip"],"ferry-easy":["εύκολη ακτοπλοϊκή απόδραση","easy ferry escape"],"ferry-long":["μεγαλύτερη ακτοπλοϊκή διαδρομή","longer ferry trip"],"domestic-flight":["σύντομη εσωτερική πτήση","short domestic flight"],"domestic-flight-plus-road":["πτήση + μικρή οδική συνέχεια","flight + road connection"],"short-flight":["σύντομη πτήση","short flight"],"medium-flight":["μεσαία πτήση","medium flight"],"long-flight":["μεγαλύτερη πτήση","longer flight"]};return map[klass]?.[el?0:1]??klass}
function budgetLabel(request:TripRequest,d:V8Destination){const el=request.language!=="en",tier=d.costTier;return el?(["","οικονομικό","καλή αξία","μεσαίο κόστος","premium","υψηλό κόστος"][tier]??"κόστος"):(["","budget","good value","mid-range","premium","high-cost"][tier]??"cost")}
function role(index:number,x:V8Ranked){if(index===0)return"BEST FIT";const b=x.breakdown;if(b.effort>=90)return"EASIEST";if(b.budget>=95&&x.destination.tags.includes("value"))return"SMART VALUE";if(b.season>=94)return"BEST THEN";if(x.destination.tags.includes("romantic"))return"ROMANTIC";return"ALTERNATIVE"}
function confidence(x:V8Ranked):Confidence{if(x.score>=82&&x.breakdown.intent>=75&&x.breakdown.season>=70&&x.destination.routeConfidence>=.75&&x.weather?.confidence!=="LOW")return"HIGH";if(x.score>=68&&x.breakdown.season>=55)return"MEDIUM";return"LOW"}
function reason(request:TripRequest,x:V8Ranked){const el=request.language!=="en",d=x.destination,b=x.breakdown,top=d.tags.filter(t=>["romantic","relax","food","culture","city","nature","beach","adventure","value","warmth","wellness"].includes(t)).slice(0,3).join(" · ");return el?`${d.nameEl}: δυνατό fit σε ${top||"το προφίλ σου"}, ${b.season}% για την εποχή και ${b.effort}% effort fit.`:`${d.nameEn}: strong fit for ${top||"your profile"}, ${b.season}% seasonal fit and ${b.effort}% effort fit.`}
function seasonNote(request:TripRequest,x:V8Ranked){const el=request.language!=="en",w=x.weather;if(w&&w.source!=="unavailable")return w.summary;return el?`Season fit ${x.breakdown.season}/100 από το Destination Knowledge Graph.`:`Season fit ${x.breakdown.season}/100 from the Destination Knowledge Graph.`}

export function toRecommendationsV8(request:TripRequest,ranked:V8Ranked[]):V8Recommendation[]{return ranked.slice(0,5).map((x,i)=>({slug:x.destination.slug,destination:request.language==="en"?x.destination.nameEn:x.destination.nameEl,destinationEn:x.destination.nameEn,country:request.language==="en"?x.destination.countryEn:x.destination.countryEl,countryCode:x.destination.countryCode,regionGroup:x.destination.regionGroup,role:role(i,x),score:Math.round(x.score),confidence:confidence(x),why:reason(request,x),seasonNote:seasonNote(request,x),effortLabel:effortLabel(request,x.destination),budgetLabel:budgetLabel(request,x.destination),tags:x.destination.tags.slice(0,6),latitude:x.destination.latitude,longitude:x.destination.longitude,directFromAthens:x.destination.directFromAthens,routeConfidence:x.destination.routeConfidence,breakdown:x.breakdown,weather:x.weather,verifier:{checked:false,passed:true,reason:null,model:null}}))}
