create table if not exists public.travel_missions (
  id uuid primary key default gen_random_uuid(),
  locale text not null default 'el' check (locale in ('el','en','de','fr','it','es')),
  status text not null default 'draft' check (status in ('draft','profiled','matched','destination_selected','researching','ready','shared','archived')),
  origin_text text,
  travel_window jsonb not null default '{}'::jsonb,
  travelers jsonb not null default '{}'::jsonb,
  budget_eur numeric(12,2),
  need_text text not null,
  escape_dna jsonb not null default '{}'::jsonb,
  chosen_destination_id text references public.destination_knowledge_v8(slug) on update cascade on delete set null,
  consent_email boolean not null default false,
  contact_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.travel_destination_matches (
  id uuid primary key default gen_random_uuid(),
  mission_id uuid not null references public.travel_missions(id) on delete cascade,
  destination_id text not null references public.destination_knowledge_v8(slug) on update cascade on delete restrict,
  role text not null check (role in ('winner','smart_value','wild_card','alternative','rejected_obvious')),
  rank smallint not null,
  fit_score numeric(5,2),
  confidence_score numeric(5,2),
  reasons jsonb not null default '[]'::jsonb,
  tradeoffs jsonb not null default '[]'::jsonb,
  evidence jsonb not null default '{}'::jsonb,
  selected boolean not null default false,
  created_at timestamptz not null default now(),
  unique(mission_id,destination_id)
);

create table if not exists public.travel_research_runs (
  id uuid primary key default gen_random_uuid(),
  mission_id uuid not null references public.travel_missions(id) on delete cascade,
  destination_id text not null references public.destination_knowledge_v8(slug) on update cascade on delete restrict,
  status text not null default 'queued' check (status in ('queued','running','ready','failed')),
  weather jsonb not null default '{}'::jsonb,
  places jsonb not null default '[]'::jsonb,
  restaurants jsonb not null default '[]'::jsonb,
  dont_miss jsonb not null default '[]'::jsonb,
  avoid jsonb not null default '[]'::jsonb,
  logistics jsonb not null default '{}'::jsonb,
  itinerary jsonb not null default '{}'::jsonb,
  media jsonb not null default '[]'::jsonb,
  sources jsonb not null default '[]'::jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.travel_escape_books (
  id uuid primary key default gen_random_uuid(),
  mission_id uuid not null unique references public.travel_missions(id) on delete cascade,
  status text not null default 'draft' check (status in ('draft','rendering','ready','failed')),
  pdf_url text,
  canva_url text,
  affiliate_tracking_url text,
  qr_payload text,
  emailed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.travel_mission_events (
  id bigint generated by default as identity primary key,
  mission_id uuid references public.travel_missions(id) on delete cascade,
  event_name text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists travel_missions_status_idx on public.travel_missions(status, created_at desc);
create index if not exists travel_destination_matches_mission_idx on public.travel_destination_matches(mission_id, rank);
create index if not exists travel_research_runs_mission_idx on public.travel_research_runs(mission_id, created_at desc);
create index if not exists travel_mission_events_mission_idx on public.travel_mission_events(mission_id, created_at desc);

alter table public.travel_missions enable row level security;
alter table public.travel_destination_matches enable row level security;
alter table public.travel_research_runs enable row level security;
alter table public.travel_escape_books enable row level security;
alter table public.travel_mission_events enable row level security;
