-- TravelAI V70: fully agentic backend foundation.
-- Final travel decisions are made by contextual agents over retrieved evidence.
-- SQL retrieval orders candidates for bounded context only; it is NOT a destination ranking/decision engine.

create table if not exists public.travel_agent_profiles_v70 (
  agent_id text primary key,
  title text not null,
  mission text not null,
  system_prompt text not null,
  allowed_tools text[] not null default '{}',
  evidence_policy jsonb not null default '{}'::jsonb,
  prompt_version integer not null default 1,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.travel_funnel_sessions_v70 (
  id uuid primary key default gen_random_uuid(),
  profile_key text null,
  auth_user_id uuid null,
  locale text not null default 'el' check (locale in ('el','en')),
  status text not null default 'discovering' check (status in ('discovering','clarifying','ready_top3','selected','journey','completed','abandoned')),
  current_context jsonb not null default '{}'::jsonb,
  context_confidence text not null default 'low' check (context_confidence in ('low','medium','high')),
  unresolved_questions jsonb not null default '[]'::jsonb,
  candidate_keys text[] not null default '{}',
  top3 jsonb not null default '[]'::jsonb,
  chosen_destination_key text null,
  chosen_stay_id text null,
  model_trace jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists travel_funnel_sessions_v70_profile_idx on public.travel_funnel_sessions_v70(profile_key,updated_at desc);
create index if not exists travel_funnel_sessions_v70_auth_idx on public.travel_funnel_sessions_v70(auth_user_id,updated_at desc) where auth_user_id is not null;

create table if not exists public.travel_funnel_turns_v70 (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.travel_funnel_sessions_v70(id) on delete cascade,
  role text not null check (role in ('user','assistant','system_event')),
  content text not null default '',
  stage text not null default 'discovering',
  structured_extract jsonb not null default '{}'::jsonb,
  evidence_refs jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists travel_funnel_turns_v70_session_idx on public.travel_funnel_turns_v70(session_id,id);

create table if not exists public.travel_discovery_snapshots_v70 (
  id uuid primary key default gen_random_uuid(),
  snapshot_date date not null,
  locale text not null default 'el' check (locale in ('el','en')),
  context_hash text not null default 'default-greece',
  context jsonb not null default '{}'::jsonb,
  picks jsonb not null default '[]'::jsonb,
  evidence_state jsonb not null default '{}'::jsonb,
  model_label text null,
  generated_at timestamptz not null default now(),
  expires_at timestamptz not null,
  unique(snapshot_date,locale,context_hash)
);

create index if not exists travel_discovery_snapshots_v70_expiry_idx on public.travel_discovery_snapshots_v70(expires_at desc);

create table if not exists public.travel_journeys_v70 (
  id uuid primary key default gen_random_uuid(),
  session_id uuid null references public.travel_funnel_sessions_v70(id) on delete set null,
  profile_key text null,
  auth_user_id uuid null,
  locale text not null default 'el' check (locale in ('el','en')),
  journey_slug text not null unique,
  destination_key text not null,
  destination_name text not null,
  stay_place_id text null,
  status text not null default 'draft' check (status in ('draft','ready','emailed','booked','travelling','completed')),
  trip_context jsonb not null default '{}'::jsonb,
  itinerary jsonb not null default '{}'::jsonb,
  evidence_refs jsonb not null default '[]'::jsonb,
  live_state jsonb not null default '{}'::jsonb,
  pdf_object_path text null,
  pdf_filename text null,
  email_status text not null default 'not_requested' check (email_status in ('not_requested','pending','sent','failed')),
  email_to text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists travel_journeys_v70_profile_idx on public.travel_journeys_v70(profile_key,updated_at desc);
create index if not exists travel_journeys_v70_auth_idx on public.travel_journeys_v70(auth_user_id,updated_at desc) where auth_user_id is not null;

create table if not exists public.travel_tracking_actions_v70 (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  journey_id uuid null references public.travel_journeys_v70(id) on delete set null,
  session_id uuid null references public.travel_funnel_sessions_v70(id) on delete set null,
  action_type text not null check (action_type in ('stay','activity','transport','restaurant','other')),
  subject_key text null,
  tracking_url text not null,
  metadata jsonb not null default '{}'::jsonb,
  click_count integer not null default 0,
  last_clicked_at timestamptz null,
  expires_at timestamptz null,
  created_at timestamptz not null default now()
);

create index if not exists travel_tracking_actions_v70_journey_idx on public.travel_tracking_actions_v70(journey_id,created_at desc);

insert into public.travel_agent_profiles_v70(agent_id,title,mission,system_prompt,allowed_tools,evidence_policy,prompt_version)
values
('context-interpreter','Traveler Context Interpreter','Reconstruct the traveller, companions, dates, origin, psychology, needs and uncertainty from the conversation.','You are the TravelAI context interpreter. Extract explicit facts, infer only reversible soft hypotheses, and ask exactly one high-information clarification when a missing fact can materially change the travel decision. Never use fixed destination weights or scorecards. Never fabricate facts. Return compact structured JSON, not private chain-of-thought.',array['traveler-memory','conversation-state'],jsonb_build_object('unknown_policy','preserve_unknown','clarification','one_at_a_time'),1),
('greece-explorer','Greece Experience Explorer','Explore the full Greece travel intelligence fabric and form multiple plausible trip hypotheses.','You are the TravelAI Greece explorer. Use retrieved destinations, micro-places, stays, activities, food, culture, nature and evidence to form diverse trip hypotheses. Retrieval relevance is only context; you must reason about the whole experience. Do not use fixed weighted scoring or deterministic destination ranking.',array['candidate-universe','knowledge-graph','evidence'],jsonb_build_object('must_ground_claims',true,'commercial_bias','forbidden'),1),
('time-weather','Time & Weather Reasoner','Interpret current date, season, forecast/climatology, daylight and operating periods as travel-experience context.','You reason about time and weather as lived travel conditions, not as a numeric ranking formula. Explain how conditions change the experience, uncertainty and alternatives. Facts constrain reality; they do not mechanically decide the destination.',array['weather','temporal-facts','events'],jsonb_build_object('freshness_required',true,'unknown_policy','state_uncertainty'),1),
('spatial-reasoner','Spatial & Friction Reasoner','Test geography, routes, transfers, realistic movement and daily spatial coherence.','You reason spatially over origin, route friction, ferry/flight/road dependencies, walking and realistic day sequencing. Reject impossible claims but do not apply a fixed travel-time score. Prefer coherent experiences over raw distance.',array['geo','routes','knowledge-graph'],jsonb_build_object('impossible_routes','reject_claim','unknown_route','state_uncertainty'),1),
('stay-curator','Contextual Stay Curator','Match accommodation to the selected trip experience and itinerary anchor.','You select stays contextually: location in the experience, traveller group, atmosphere, practical access, evidence and real tracking inventory. Never rank by affiliate commission. Never invent availability, rating or amenities.',array['stay-knowledge','stay-offers','tracking-validity'],jsonb_build_object('commercial_bias','forbidden','availability','truthful_only'),1),
('experience-composer','Experience Composer','Compose micro-places, food, culture, nature and activities into coherent candidate experiences.','You compose complete travel experiences with temporal, spatial and emotional pacing. Avoid checklist tourism. Every recommended stop must be grounded in retrieved evidence or clearly marked as needing verification.',array['knowledge-graph','evidence','food','culture','nature','activities'],jsonb_build_object('must_ground_claims',true),1),
('skeptical-critic','Skeptical Travel Critic','Attack each candidate, surface contradictions, hidden friction and missing evidence.','You are adversarial. Try to disprove each candidate using evidence, timing, weather, route, stay support and traveller context. Do not produce a score. Return objections, uncertainty and what would change the conclusion.',array['evidence','weather','routes','stay-offers'],jsonb_build_object('role','adversarial','fabrication','forbidden'),1),
('journey-synthesizer','Journey Synthesizer','Resolve the agent debate into a contextual Top 3 or one clarifying question, then later build the 360 journey.','You synthesize agent-grounded evidence into three distinct contextual choices only when the context is sufficient. Use qualitative confidence grounded in evidence quality, consistency, uncertainty and agent agreement. Never calculate a fixed weighted fit score. If uncertainty is material, ask one clarification instead of pretending precision.',array['agent-findings','evidence','journey-state'],jsonb_build_object('top3_only_when_ready',true,'fixed_weight_scoring',false),1)
on conflict(agent_id) do update set
  title=excluded.title,
  mission=excluded.mission,
  system_prompt=excluded.system_prompt,
  allowed_tools=excluded.allowed_tools,
  evidence_policy=excluded.evidence_policy,
  prompt_version=excluded.prompt_version,
  active=true,
  updated_at=now();

create or replace function public.get_agentic_candidate_universe_v70(
  p_limit integer default 220,
  p_locale text default 'el'
)
returns table(
  node_key text,
  canonical_slug text,
  display_name text,
  region_label text,
  latitude double precision,
  longitude double precision,
  property_count integer,
  offer_count integer,
  min_price numeric,
  max_price numeric,
  currency text,
  demand_signal numeric,
  semantic_text text,
  match_readiness real,
  content_status text,
  verified_fact_count bigint,
  evidence_count bigint,
  avg_confidence real,
  avg_evidence_strength real
)
language sql
stable
security definer
set search_path to 'public','extensions','pg_temp'
as $$
  select
    n.node_key,
    n.canonical_slug,
    case when lower(coalesce(p_locale,'el'))='en' then coalesce(n.name_en,n.name_el) else n.name_el end as display_name,
    n.region_label,
    n.latitude,
    n.longitude,
    n.property_count,
    n.offer_count,
    n.min_price,
    n.max_price,
    n.currency,
    n.demand_score,
    n.semantic_text,
    n.match_readiness,
    n.content_status,
    coalesce(ec.verified_fact_count,0)::bigint,
    coalesce(ec.evidence_count,0)::bigint,
    coalesce(ec.avg_confidence,0)::real,
    coalesce(ec.avg_evidence_strength,0)::real
  from public.travel_destination_nodes_v46 n
  left join public.travel_destination_evidence_coverage_v44 ec
    on ec.destination_slug=n.canonical_slug
  where n.active and n.country_code='GR'
  order by
    case when n.publication_gate='publish' then 0 else 1 end,
    n.match_readiness desc,
    coalesce(ec.verified_fact_count,0) desc,
    n.property_count desc,
    n.node_key
  limit greatest(1,least(coalesce(p_limit,220),574));
$$;

create or replace function public.get_agentic_destination_bundle_v70(
  p_node_keys text[],
  p_locale text default 'el',
  p_stay_limit integer default 6,
  p_entity_limit integer default 40
)
returns jsonb
language sql
stable
security definer
set search_path to 'public','extensions','pg_temp'
as $$
with selected as (
  select * from public.travel_destination_nodes_v46
  where active and country_code='GR' and node_key=any(coalesce(p_node_keys,'{}'::text[]))
), slugs as (
  select distinct canonical_slug from selected where canonical_slug is not null
), entities as (
  select e.*
  from public.travel_knowledge_entities_v44 e
  where e.active and e.destination_slug in (select canonical_slug from slugs)
  order by e.quality_score desc,e.freshness_score desc
  limit greatest(1,least(coalesce(p_entity_limit,40),120))
), facts as (
  select f.*
  from public.travel_knowledge_facts_v44 f
  join entities e on e.id=f.entity_id
  where f.status='verified'
  order by f.evidence_strength desc,f.confidence desc
  limit 240
), stays as (
  select s.*
  from public.stay_product_knowledge_v43 s
  where s.destination_slug in (select canonical_slug from slugs)
  order by s.evidence_score desc,s.offer_count desc,s.property_name
  limit greatest(1,least(coalesce(p_stay_limit,6),30)) * greatest(1,(select count(*) from slugs))
)
select jsonb_build_object(
  'destinations',coalesce((select jsonb_agg(jsonb_build_object(
    'nodeKey',d.node_key,
    'canonicalSlug',d.canonical_slug,
    'name',case when lower(coalesce(p_locale,'el'))='en' then coalesce(d.name_en,d.name_el) else d.name_el end,
    'region',d.region_label,
    'latitude',d.latitude,
    'longitude',d.longitude,
    'propertyCount',d.property_count,
    'offerCount',d.offer_count,
    'price',jsonb_build_object('min',d.min_price,'max',d.max_price,'currency',d.currency),
    'semanticText',d.semantic_text,
    'parentCanonicalSlug',d.parent_canonical_slug
  )) from selected d),'[]'::jsonb),
  'entities',coalesce((select jsonb_agg(jsonb_build_object(
    'id',e.id,'type',e.entity_type,'key',e.canonical_key,'name',e.canonical_name,
    'destinationSlug',e.destination_slug,'latitude',e.latitude,'longitude',e.longitude,
    'attributes',e.attributes,'quality',e.quality_score,'freshness',e.freshness_score
  )) from entities e),'[]'::jsonb),
  'facts',coalesce((select jsonb_agg(jsonb_build_object(
    'entityId',f.entity_id,'predicate',f.predicate,'value',f.value,'valueText',f.value_text,
    'confidence',f.confidence,'evidenceStrength',f.evidence_strength,'sourceKind',f.source_kind,
    'sourceName',f.source_name,'sourceRef',f.source_ref,'observedAt',f.observed_at,'validTo',f.valid_to
  )) from facts f),'[]'::jsonb),
  'stays',coalesce((select jsonb_agg(jsonb_build_object(
    'placeId',s.place_id,'propertyName',s.property_name,'destinationSlug',s.destination_slug,
    'locationLabel',s.location_label,'latitude',s.latitude,'longitude',s.longitude,
    'semanticText',s.semantic_text,'semanticTags',s.semantic_tags,'travelerFit',s.traveler_fit,
    'offerCount',s.offer_count,'minPrice',s.min_price,'maxPrice',s.max_price,'currency',s.currency,
    'heroImageUrl',s.hero_image_url,'evidenceScore',s.evidence_score
  )) from stays s),'[]'::jsonb)
);
$$;

alter table public.travel_agent_profiles_v70 enable row level security;
alter table public.travel_funnel_sessions_v70 enable row level security;
alter table public.travel_funnel_turns_v70 enable row level security;
alter table public.travel_discovery_snapshots_v70 enable row level security;
alter table public.travel_journeys_v70 enable row level security;
alter table public.travel_tracking_actions_v70 enable row level security;

revoke all on public.travel_agent_profiles_v70 from anon,authenticated;
revoke all on public.travel_funnel_sessions_v70 from anon,authenticated;
revoke all on public.travel_funnel_turns_v70 from anon,authenticated;
revoke all on public.travel_discovery_snapshots_v70 from anon,authenticated;
revoke all on public.travel_journeys_v70 from anon,authenticated;
revoke all on public.travel_tracking_actions_v70 from anon,authenticated;

revoke all on function public.get_agentic_candidate_universe_v70(integer,text) from public,anon,authenticated;
revoke all on function public.get_agentic_destination_bundle_v70(text[],text,integer,integer) from public,anon,authenticated;
grant execute on function public.get_agentic_candidate_universe_v70(integer,text) to service_role;
grant execute on function public.get_agentic_destination_bundle_v70(text[],text,integer,integer) to service_role;

comment on function public.get_agentic_candidate_universe_v70 is
'V70 bounded retrieval universe for agent context. Ordering is retrieval hygiene only and MUST NOT be presented as a final destination ranking.';
comment on table public.travel_funnel_turns_v70 is
'Conversation continuity and structured extracts only. Never store private chain-of-thought.';
